### ISSUE TITLE
[Feature Request] RAM Watch entry splitting

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#1024]
Too often I add a 4-byte region to my watchlist when only the second half is important, or something. It would be nice to have either the list controllable by Lua, allowing a script to split 4- and 2-bytes into multiple 1-bytes, or simply an option upon right-clicking that does the same.

**Comment by polytomous** [comment]
@YoshiRulz I added splitting to the ram watches. Current implementation on my fork leaves the split entry in the ram watch, and adds the two split values above. Splitting a value that cannot be split should do nothing, but for the moment it duplicates the split byte watch. Whatever. 

https://github.com/polytomous/BizHawk

The work on my fork is split into a few places. Two relevant commits: It's a messy diff tho.   
https://github.com/polytomous/BizHawk/commit/535ad79e77baf994157ef2df5e76917b684c4530
https://github.com/polytomous/BizHawk/commit/c30f1fde61c8b303c88f4bf5675533b6952cb53b

It's not a complete solution, and I haven't tested it enough to feel comfortable integrating it into mainline BizHawk, but if you needed something to start off of @YoshiRulz it would be sufficient. I would absolutely love it if you could test my work though. 😸 

Relevant splitting meme:

![ayo watch this.](https://i.imgur.com/TXjPf8Y.png)

**Comment by YoshiRulz** [comment]
Totally forgot about this. You'll forgive me for not trying to duplicate your changes, starting from scratch instead.
