### ISSUE TITLE
Kaizou Choujin Shubibinman Zero not working

### ISSUE THREAD

**Issue by lomaxgames** [TASEmulators/BizHawk#1086]
Just a black screen and no sound

From GoodSNES

Kaizou Chounin Shubibinman Zero (Japan) (BS)
SHA1:5B6A4D0740183703F35A349AFB6088A8603D8966
MD5:67FE189F30726C99AD1F5E9AC656F7FD

Core: Snes9x , Bizhawk developer build with commit 353fec4  . Changing core on BSNES also gives no effect

**Comment by synnae** [comment]
This is a Satellaview game, not a regular SNES one. Those tend to be problematic to work.

**Comment by YoshiRulz** [comment]
Can someone retest on the new BSNES core in 2.8 please?
