### ISSUE TITLE
bsnes - Watching / Searching SA-1 I-RAM memory possible?

### ISSUE THREAD

**Issue by gocha** [TASEmulators/BizHawk#1097]
Is watching / searching SA-1 I-RAM memory possible?

I think the I-RAM is not in the memory domains list. Also, I tried to watch it through the SNES System Bus 003000h-0037FFh, but the region is entirely filled by 0. I used Hoshi no Kirby Super Deluxe for the test.

Am I doing something wrong?

**Comment by NarryG** [comment]
Are you using SNES9X or BSNES?

**Comment by gocha** [comment]
I am using bsnes core.

2018年1月18日(木) 4:48 NarryG <notifications@github.com>:

**Comment by gocha** [comment]
Today I was working on this, but I don't have enough free time and motivation at the moment. Here's what I did.

[Abandoned attempt for adding SA\-1 IRAM memory domain · gocha/BizHawk@ff5b4ff](https://github.com/gocha/BizHawk/commit/ff5b4ff2b7e0a2dd648a3e518d41ce941219e67b)

Currently, BSNES core doesn't have a memory domain for SA-1 IRAM. Theorically it should be viewable from 003000h-0037FFh on the system bus, but it doesn't work either.

So why the system bus doesn't show SA-1 IRAM? It's because the system bus domain is allowing only accesses for WRAM/ROM regions, for the safe deterministic emulation (see SetupMemoryDomains function in LibsnesCore.IMemoryDomains.cs).

So I tried to add an individual domain for SA-1 IRAM to both the C# side (LibsnesApi) and C++ side (waterbox/libsnes), then update the fake bus code and allow read/write for IRAM.

However, I don't have enough free time and motivation at the moment. The most boring thing was updating CommStruct (marshalled struct used among C# side and C++ side). I guess it's mostly done though. I hope someone review it and complete the task. Thanks.

**Comment by vadosnaprimer** [comment]
I don't have time to test this but if the patch is completed I can apply it and upload the new core build.

**Comment by gocha** [comment]
It's not completed yet.

**Comment by nattthebear** [comment]
1711914

It's in faust, not bsnes, but that's what you get.

**Comment by ChutacoackoPlayz** [comment]
sorry but i still can't find sa1 i-ram

**Comment by nattthebear** [comment]
Are you using the faust core?

**Comment by ChutacoackoPlayz** [comment]
idk how to use the faust core

**Comment by nattthebear** [comment]
Try again with e798fb2b291a00128c5bf5289df7fab8b9b6611a

**Comment by ChutacoackoPlayz** [comment]
nope i don't see sa-1 i ram in memory domains list

**Comment by nattthebear** [comment]
:shrug:

![image](https://user-images.githubusercontent.com/1824709/83788623-7e59aa00-a663-11ea-84da-b165bb40c74c.png)

**Comment by ChutacoackoPlayz** [comment]
ok, when it's success, the faust core is shown

**Comment by ChutacoackoPlayz** [comment]
now i can see it in ram watch
you're a magician

**Comment by Masterjun3** [comment]
Can this be reopened until it is implemented for the bsnes core?
For TASing purposes, having access to relevant memory is important.

**Comment by adelikat** [comment]
Reopening, as a bsnes specific request

**Comment by Morilli** [comment]
Has been resolved for the BSNESv115+ core, which is now in released state as well. Not gonna bother for the "old" bsnes core, as the code is really ugly to work with, but this should be good enough for all use cases still.
