### ISSUE TITLE
N64 Body Harvest (U) Bizhawk problems

### ISSUE THREAD

**Issue by WMJ87** [TASEmulators/BizHawk#1173]
I have recently become interested in making a TAS for the N64 game Body Harvest. 

This game has bad collision detection problems with all of the video plugins except the latest release of the GLideN64 plugin. In the settings of that plugin you have to enable an option for frame buffer settings called "copy depth to RDRAM" to "use software render" because otherwise collision detection didn't work on most objects. That does completely fix the issue. 

Now, the problem is the game has enormous slowdown while using GLideN64 in Bizhawk while the Jabo plugin for instance doesn't have this (but no collision detection). 

In project64 the game was running fine for me before with the GLideN64 plugin. I went to check again and to my surprise on the latest release of Project64 it has very similar problems to what I experienced in Bizhawk. 

Checking for the differences there were a few settings that completely fix the slowdown problems. Notably the option AI count per byte. When set to 200 it's almost fixed but at 400 it's completely fixed and the game runs flawless (in Project64). 

Left image default settings in Project64 2.1.0.1 (the good one) and Project64 2.3.2.202 (with slowdown). Making the settings the same fixes the problem. 

https://i.imgur.com/ad9NNnG.png 

I couldn't find any equivalent settings in Bizhawk to change this so the problem of being unable to make a TAS remains. Is this something that's fixable or any other advice? 

Test video showing the problem: https://www.youtube.com/watch?v=KSrAbFn1kv4

BK2 movie file from Bizhawk 2.2.2. https://drive.google.com/open?id=1ugDWzs79ucg2sJFPQqk1bitsViTCQHqP

**Comment by vadosnaprimer** [comment]
Doesn't look like it's even a video plugin setting. It's in their core:
https://github.com/project64/project64/pull/881/commits/3335cfed8d27596d07e8795b7467dcaa32ef9c8a

**Comment by vadosnaprimer** [comment]
Does latest m64p suffer from this?

**Comment by vadosnaprimer** [comment]
@WMJ87 hello?

**Comment by YoshiRulz** [comment]
Movie result seems to be the same on 2.3.1.

**Comment by WMJ87** [comment]
That's funny I made this issue 10 months ago and got totally side tracked until this morning when I was testing it again... and here is a new post as well. My apologies for no replies.

@vadosnaprimer Yes, latest M64p has the same problem. I tried in bizhawk 2.3.1 as well just now and same problem. I am still interested in doing the TAS project for the game.

**Comment by vadosnaprimer** [comment]
Then there's no easy way to solve this. There's not even a patch for m64p that we could apply to fix it.

**Comment by WMJ87** [comment]
I tried various settins in the latest Bizhawk 2.6.1 but sadly the same issue is still there. Or, at least, I couldn't figure out how to get it to run properly.

Interestingly, in the mupen64plus next core for retro arch this is completely fixed. Would it be possible to implement this in a future bizhawk release?

Here's a video demonstrating it running perfectly with mupen64plux next: https://www.youtube.com/watch?v=dgp0KYehgYE

**Comment by YoshiRulz** [comment]
If it doesn't work in Mupen upstream, definitely not. If it does work in Mupen upstream too, probably not. Our fork of Mupen is very far behind and there are [a lot of problems](https://github.com/TASVideos/BizHawk/milestone/1) which can't feasibly be fixed because of that.
