### ISSUE TITLE
Megaman X3 - Zero Project v4.0 Beta doesn't work properly in Bizhawk.

### ISSUE THREAD

**Issue by SabinStargem** [TASEmulators/BizHawk#1198]
There are two issues that I am seeing so far:

1 - In the save menu, there are graphical glitches.  Probably related to why the next bit happens.

2 - You can't save the game.  The emulator doesn't write any SaveRAM.

The readme of this romhack mentioned that it is a Bizhawk-specific issue.  This seems the case, as vanilla SNES9x can save, nor does it have the graphical artifacts on the save menu.

**Comment by NarryG** [comment]
Are you using the Snes9X or the BSNES core? Bizhawk's snes9x integration has issues with various enhancement chips due to how it was implemented. Try with bsnes

**Comment by SabinStargem** [comment]
BSNES Core.    Trying with the SNES9x Core crashes the emulator.

Should the need to know about the workings of the romhack arise, the developer is Justin3009.  The changes are very extensive - the original game used a password system for saves, there is now a NG+ feature, Zero being fully playable, and so on. 

https://www.romhacking.net/forum/index.php?topic=11130.0

**Comment by SabinStargem** [comment]
The 0.96 version of BSNES apparently lacked native cheat functionality, and wasn't very friendly to use from what I recall.   Higan seems much of the same.

SNES9x is reliable and simple for my use case.  Unfortunately, the compatibility for XB1 gamepads is breaking down, so I will have to transition over to a modern SNES emulator at some point.  Bizhawk is at the top of the short list.

**Comment by nattthebear** [comment]
Right, sorry, I should have been more clear.  I'm not suggesting you use bsnes or higan for your regular gameplay, but I'm interested, for troubleshooting purposes, to know whether this romhack works in either of those.

If it doesn't, then it's a core problem and we probably can't do anything about it.
If it does, then it's a porting problem and I may be able to look at it.

**Comment by SabinStargem** [comment]
Fiddled around with Retroarch.  BSNES Mercury Accuracy v0.94 ran the ROM, but the Retroarch Higan core would fail to load.  I also tried to use the actual Higan emulator...but I couldn't figure out if I got things set up correctly.  :(

**Comment by SabinStargem** [comment]
Forgot to check if Retroarch BSNES Mercury-Accuracy v0.94 worked properly beyond booting.  No artifacts to be found, and saves can be created and loaded.

**Comment by nattthebear** [comment]
Great.  So if we can figure out what BSNES-mercury is doing differently, we can fix this.

**Comment by SabinStargem** [comment]
Zero Project 4.0 Final was released, so I gave it a spin in Bizhawk with the BSNES core.   As previous, it still has a save screen with artifacts when a save is created, followed by it vanishing if I select the slot again.

Bizhawk v3.1.0 was used.  Crashing with the SNES9x core still happens.

[Zero Project v4.0 Final - Patch](http://www.romhacking.net/hacks/4086/)

**Comment by nattthebear** [comment]
Does this work in our new snes faust core?

**Comment by YoshiRulz** [comment]
Romhack now has a supplementary file which tells BSNES which mapper to use. Can EmuHawk read it?

**Comment by Morilli** [comment]
Generally, yes, the rom will work in bizhawk with that file (needs current dev version though).
