### ISSUE TITLE
Drop Snes9x entirely in favour of BSNES

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#1204]
not a good idea

**Comment by jjfmz42015** [comment]
More bugs keep poping up. Not worth the time. Bsnes core for all is good these days anyway.

**Comment by vadosnaprimer** [comment]
inb4 it's reopened and reclosed 10 more times.

**Comment by jjfmz42015** [comment]
kept thinking the new snes9x core is good. truth is the latest updates to that emulator broke way too much compatibility now.

**Comment by YoshiRulz** [comment]
Relevant IRC logs from ~~ages ago~~ June 20th (felt like ages ago):
```
<adelikat> [... what] suggests we can't get rid of snes9x in favor of faust?
<natt> I have short IRC logs, but zeromus seemed pretty convinced
[...]
<zeromus> the reason to keep it is because of 1 or 2 high profile hacks that only work on snes9x
<adelikat> well, especially since it is very reasonably the hack's fault
[...]
<adelikat> and we've already been down this road
<adelikat> there's rom hacks that only work on pj64 or moopen
[...]
<zeromus> [...maybe we should] autoselect it when using a whitelisted rom known to need snes9x and tell people that need other roms to run in snes9x to post a bug or add the hash themselves.
<rootabaga> faust doesn't emulate the SPC7110, any of the ST* chips, OBC1, S-RTC, DSP3, nor DSP4
<natt> hmm, good point. well, i said i would like to see snes9x removed, but i usually don't get my wish anyway
<adelikat> so we are talking about having 3 snes cores then
```

**Comment by lightgod87** [comment]
>High profile hacks that only work in Snes9x

Sorry if I have to ask this, but... have you guys tested the hacks with the newest version of bsnes that has some features that emulate behaviors from older emulators (like ZSNES)? Would that help to get rid of Snes9x?

**Comment by nattthebear** [comment]
byuu added hackpatible features to bsnes?  Or is this one a bazillion bsnes forks?

**Comment by lightgod87** [comment]
> byuu added hackpatible features to bsnes? Or is this one a bazillion bsnes forks?

Yes, byuu / Near added some features to the main bsnes fork.

**Comment by vadosnaprimer** [comment]
Doesn't make sense to remove after it's just been updated.
