### ISSUE TITLE
SNES' 8 audio channels with SNES9X core not toggling correctly.

### ISSUE THREAD

**Issue by WDude** [TASEmulators/BizHawk#1208]
What's happening is that toggling channel 1's audio output is affecting *all* the channels instead of channel 1's own audio output. In addition, toggling channels 2 through 8 have zero effect on anything. Just a minor request, would it be possible to map keys to toggling the audio channels and the SNES gfx layers?

This is coming from BizHawk v2.2.2 on Windows 7 64-bit.

**Comment by jjfmz42015** [comment]
This is fixed if they update to 1.56 core.

**Comment by Testsr** [comment]
They should probably do something about that. By the way, what version of snes9x is Bizhawk using?

**Comment by jjfmz42015** [comment]
They are using 1.54 I believe.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
