### ISSUE TITLE
PS1 / PSX / Octoshock Additional Controls Support

### ISSUE THREAD

**Issue by Spikestuff** [TASEmulators/BizHawk#1225]
As the title says to both update the mednafen core in BizHawk and to provide the missing controls.

Mednafen's Last PS1 core update was in 0.9.44's update (April 19th 2017) whilst we are still using 2016's core.

As for the Missing Controllers that mednafen provides (and is within BizHawk's input section):
- LightGun / G-Con
- Justifier 
- Mouse (Covering all bases)

**Comment by Spikestuff** [comment]
Should update this by mentioning the latest that just came out today and has a few needed updates that have been brought up in the upstream which fixes some games.

So the most current core for it is now Dec 22nd 2018.

**Comment by Spikestuff** [comment]
As of the release of 2.4.1. The first half of this request has been completed. Thank you.

**Comment by CasualPokePlayer** [comment]
All controls from Mednafen are implemented in Nymashock.
