### ISSUE TITLE
Needing 4.6.1 on an older version?

### ISSUE THREAD

**Issue by ShadowMan44** [TASEmulators/BizHawk#1280]
Hi, I have been trying to run older versions of BizHawk on my Windows 32 bit OS.

The issue here is that I get an error stating that I need to have 4.6.1 Net Framework when it's not compatible with my OS, in fact every single version I have tried give me this error when those versions were created before the switch over.

The strange thing is though, if I open the EXE while it's in the zip folder, it will open and take roms. But when I extract it to a folder on my computer, it gives me the error.

**Comment by Asnivor** [comment]
So you are trying to run this version: https://github.com/TASVideos/BizHawk/releases/tag/1.13.2
and it is prompting you for .NET 4.6.1?

Are you sure that you have extracted the above version into a completely separate folder to any newer version? Any bizhawk version >= 2.x.x does require x64 OS.

**Comment by Asnivor** [comment]
@ShadowMan44 is this still a problem?

**Comment by zeromus** [comment]
Are we even supporting windows XP? If we switched to 4.6.1, I guess we aren't. If we aren't supporting windows XP then we don't need to waste anyone's time debugging why it works or doesnt work half the time.

**Comment by Asnivor** [comment]
@ShadowMan44 I think we will probably close this issue out soon (unless you speak up).

It seems like you were trying either to run a bizhawk v2 or greater on x86 windows, or you maybe had both v1.x and v2.x files in the same folder. Both of which are not supported and may cause the world to end.

:)
