### ISSUE TITLE
Inexplicable config file reset

### ISSUE THREAD

**Issue by negative-seven** [TASEmulators/BizHawk#1379]
On two separate occasions, for two different people, config.ini was suddenly wiped or overwritten with default settings, seemingly in between sessions. Maybe related to force-closing the emulator during PC shutdown/reboot. Minimal details known.

**Comment by Asnivor** [comment]
> Maybe related to force-closing the emulator during PC shutdown/reboot

iirc by default the config is saved when bizhawk is closed. If you interrupt this process then I guess there is a good chance that the json data in the config file can become corrupted (so defaults are loaded the next time bizhawk starts).

I'm not sure the best way to handle this though. I mean, windows does warn you about force closing stuff at shutdown/restart. 

Conceivably we could have bizhawk create a backup of the config file on disk pre-save (and hope this happens properly). Then have a popup on bizhawk start that fires when defaults are loaded.

"There was a problem loading settings from disk but a backup config was detected. Do you want to load the backup, or init defaults?"

Or something.

@zeromus @adelikat @vadosnaprimer you guys think this might actually be worth it?

**Comment by zeromus** [comment]
I don't think it's due to force-closing. Why would force closing make the ini file get written? It doesn't make sense. But if you want to look into it, find out how windows notifies a winforms app when rebooting and try tracing through that code

**Comment by YoshiRulz** [comment]
see also #1407

**Comment by ChutacoackoPlayz** [comment]
that happened to me too

**Comment by CasualPokePlayer** [comment]
I've had this occur sometimes developing things, only occuring with some cursed crash occuring on the unmanaged side. Seems that nowadays BizHawk does warn that the config file is corrupt and let's you back it up. I'll note last time I had this occur (which was only a week or so ago) the config file was just cut off in the middle of NesHawk settings.
