### ISSUE TITLE
Request: CHD file format support

### ISSUE THREAD

**Issue by psionx** [TASEmulators/BizHawk#1482]
que+bin is unreliable and fails to load if the que isn't formatted correctly. hopefully having the game data as a single file will resolve the issue. also CHD being a mame file format should make it easier to include then other formats.

specifically sega saturn games need this because depending on the emulator some games load perfectly while others are broken.

**Comment by hegyak** [comment]
My issue with this, personally is how do I turn my physical Disc into a CHD?  I know how to make Bin/Cue from a Physical Disc.

Another other issue is MAME's Code License compatible with BizHawk's?

**Comment by vadosnaprimer** [comment]
MAME is GPL now. BTW, potential use of this would be PCem whenever it's added as a core.

**Comment by Asnivor** [comment]
I'll take a look at this in a few weeks maybe if no-one else picks it up.

A .NET native implementation of [THIS](https://github.com/rtissera/libchdr) that feeds into DiscSystem is probably what we need.

**Comment by psionx** [comment]
> My issue with this, personally is how do I turn my physical Disc into a CHD?

as far as I know no easy way exists to directly rip a CD/DVD to CHD but you can convert bin+cue, toc, gdi, nrg and iso. http://wiki.batcom-it.netindex.php?title=Qt_CHDMAN_GUI< basic guide here

the only downside is that the QT gui is part of QMC2 mame launcher and not included with standard mame which is needed for chdman.exe.

**Comment by Sonia-7** [comment]
100% support this. Converting multiple files into a single chd is good to keep things neat and organized, not to mention the huge decrease in size after compression. Helps saving space in the HDD.

I've been converting PCECD and Sega CD bin/cue's to chd's as of late and they all work perfectly in RetroArch.

**Comment by soundyogi** [comment]
ping. no way to get .chd working in bizhawk?

**Comment by mightymo77** [comment]
CHD support will inevitably need to be supported. Any plans or insight on this?

**Comment by hegyak** [comment]
https://github.com/rtissera/libchdr
This appears to be what most Emulators are using.

To Convert to CHD, I recommend using CHDMan from any newer MAME release.  There are batch files that work for Windows users.  I don't know what Linux/OSX users would use for Bulk Conversion.

CHDs should be V5.  But V1-V4 are still "Valid"

**Comment by CasualPokePlayer** [comment]
> https://github.com/rtissera/libchdr This appears to be what most Emulators are using.

That was linked earlier in this thread.

> A .NET native implementation of [THIS](https://github.com/rtissera/libchdr) that feeds into DiscSystem is probably what we need...

**Comment by YoshiRulz** [comment]
Also https://github.com/SnowflakePowered/chd-rs

**Comment by HeatXD** [comment]
Today I worked on this https://github.com/HeatXD/chdr_cs 
I'm at the point where I can generate C# bindings for libchdr
I will make try to make examples and tests tomorrow.

**Comment by HeatXD** [comment]
Added a test it seems to have pretty much identical performance. I brought the benchmark from the libchdr repo over to c#
![image](https://user-images.githubusercontent.com/45072324/233867745-0a5ab23c-6010-425b-96f8-bcb493796fc5.png)

**Comment by HeatXD** [comment]
recreated the benchmark tool of libchdr in C#
benchmark done in release mode.
chdr_cs:
![image](https://user-images.githubusercontent.com/45072324/233868239-5f67fc73-4ddf-4ecd-9dc1-77f572438444.png)
libchdr:
![image](https://user-images.githubusercontent.com/45072324/233868328-d5e9060e-f7cd-41e9-be8c-1c87f2db875e.png)

Performance comes quite close using the C# bindings

**Comment by CasualPokePlayer** [comment]
Disc format support is not core specific at all, all cores get a format agnostic CD interface from BizHawk. If BizHawk's CD handling doesn't support CHD, then *no core* can use CHD CDs. If BizHawk's CD handling supports CHD, then *all cores* can use CHD CDs.

**Comment by CasualPokePlayer** [comment]
BizHawk does not have CD CHD support at all, regardless of the system. That's why this issue you are commenting on exists in the first place.

**Comment by CasualPokePlayer** [comment]
Resolved by 21b6bd331b1617b0a8dbfd4471787bb43b95814c
