### ISSUE TITLE
[Request] Make the emulator automatically reset ExtraPadding after stopping Lua script

### ISSUE THREAD

**Issue by ThunderAxe31** [TASEmulators/BizHawk#1509]
The functions `client.SetGameExtraPadding` and `client.SetClientExtraPadding` allow to enlarge the screen, which can be very useful in itself, however the effects remain after the Lua has stopped running, and even after closing the ROM. It's a bit silly and some people may get confused or frustrated after seeing the extra padding persisting beyond the execution of their Lua script.

In order to reset the extra padding, the user has to either re-launch BizHawk or run a Lua script that explicitly sets the padding to zero. Example:
```
client.SetGameExtraPadding(0, 0, 0, 0)
client.SetClientExtraPadding(0, 0, 0, 0)
```
Please make BizHawk automatically reset the extra padding, after that the Lua script which called it get its execution stopped.

**Comment by vadosnaprimer** [comment]
Forgot to address the logic behind the commit :/
Padding is used for lua drawings, and when we're not drawing anymore, it makes no sense to keep padding. Also there's no harm in resetting it here, because it's no drawn manually, scripts are doing it, therefore we're losing nothing.

**Comment by ThunderAxe31** [comment]
Now that I look at it again, this isn't exactly the solution that I was hoping for. The commit makes the padding resetted after closing the Lua window, not when the Lua script is stopped. I hope it would not be too much problematic to implement it that way.

**Comment by RetroEdit** [comment]
But what if you modify the padding through the Lua console instead of a script?

Not that I consider the Lua console super-functional for tweaky changes, but for general testing and understanding of BizHawk's functions, it's useful to be able to arbitrarily test functions at a whim. Of course, the Lua console isn't strictly necessary for this purpose, since you could always throw together a quick test script, but it's just a thought I had when reading this issue.

In some ways, I would be fine if the Lua console was completely removed from the Lua window, since I've found it to be inconsistent in comparison to the behavior of scripts, but that starts to get into the territory of a broader discussion that could be held in a different issue.

**Comment by ThunderAxe31** [comment]
I really like the Lua console, please don't remove it. Actually, I even opened an issue for a minor bug: https://github.com/TASVideos/BizHawk/issues/1967
By the way, in my opinion we could have BizHawk to automatically reset the padding depending on what changed it. If the padded was generated by a Lua script, reset it when that script stops execution. Instead, if the padded was generated by the Lua console, reset it when the Lua window is closed. We can have both behaviours, no?

**Comment by YoshiRulz** [comment]
That's a lot of work for something script authors can already do with a close or reset button in their form.

**Comment by ThunderAxe31** [comment]
Slapping the following at the beginning of my Lua script did the trick:
```
function reset_padding()
	client.SetGameExtraPadding(0, 0, 0, 0)
	client.SetClientExtraPadding(0, 0, 0, 0)
end
event.onexit(reset_padding)
```
I wonder it would make sense to make BizHawk silently execute these five lines at the beggining of any Lua script, or do something equivalent. If you think that it would be unnecessary, then just close this issue and forget about it.

**Comment by vadosnaprimer** [comment]
Script stopping execution isn't enough information, because there can be registered functions that mess with padding. IIRC when you have those in your script instead of a while true loop, the script stops immediately, but the functions keep running.

**Comment by YoshiRulz** [comment]
Removing (not disabling, see https://github.com/TASEmulators/BizHawk/issues/3014#issuecomment-1335385342) the *last* script now also resets the padding. If you have one long-running script and are loading and removing a second script which is messing with the padding, that script should include a reset as in the above comment. It doesn't really make sense for multiple scripts to set padding, maybe one on each canvas? This change won't affect that though.
