### ISSUE TITLE
TAStudio branch screenshot is low resolution if window size changed

### ISSUE THREAD

**Issue by Morilli** [TASEmulators/BizHawk#1513]
I am using a lua script while making a TAS, and loading a branch makes the screenshot on branch load be shrunken down to the size of the in-game-screen. So basically the entire window area is captured and squeezed together to fit into the actual game window, making it look like this:
![image](https://user-images.githubusercontent.com/35152647/54480388-32d19b00-4828-11e9-9ade-a763ffb83c25.png)
which renders the screenshot more or less useless.

**Comment by vadosnaprimer** [comment]
Is this on latest release?

**Comment by Morilli** [comment]
Yes, version 2.3.1

**Comment by vadosnaprimer** [comment]
As pointed out by another person, it's lowres when you load the branch, I thought it was lowres on hover.

**Comment by Morilli** [comment]
Yes sorry, I didn't even know a screenshot would show on branch hover when I made this issue.

**Comment by vadosnaprimer** [comment]
It works as 2 things at once, see if it's good now.

**Comment by Morilli** [comment]
I would like to, but it seems that debugging / building the program either does not work or crashes immediately, so I'll just not do that I guess. Stating "run the .bat file" in the readme is really not helpful when there are apparently other dependencies that are not mentioned.

**Comment by vadosnaprimer** [comment]
Just use the dev build https://github.com/TASVideos/BizHawk#testing

**Comment by Morilli** [comment]
I'm getting tons and tons of errors; I can absolutely not do anything productive with this build, sorry.

**Comment by vadosnaprimer** [comment]
That's what testing is for. What's the first error and how do you get it?

**Comment by Morilli** [comment]
Just trying to open a previously created .tasproj file gives me this:
![temp](https://user-images.githubusercontent.com/35152647/59163367-8b9b9180-8b00-11e9-897f-e364253a0125.PNG)
Although this happens on the version 2.3.1 as well now; I'm assuming the dev build just destroyed my .tasproj file.
After switching between branches I also got this: 
![temp2](https://user-images.githubusercontent.com/35152647/59163452-bb976480-8b01-11e9-9e5e-132839f7c705.PNG)

Other than that I could still reproduce the issue in that "interim" version I downloaded.

**Comment by vadosnaprimer** [comment]
It may be possible to fix the tasproject, see if it opens with 7zip. If it does, you can remove greenzone (if it's there) and upload it somewhere, I'll try fixing it.

To see if my commit was actually the cause of corruption, please to create a dummy tasproject with minimal data and a few dummy branches in 2.3.1, and try opening it in this build: https://ci.appveyor.com/api/buildjobs/umnso8p0ahhsy61l/artifacts/BizHawk_Developer-2019-06-02-233109-%230216359c1ffc9e3bc928ff10deb3c9a653c9db9b.zip

**Comment by Morilli** [comment]
Can confirm that this earlier version you linked does NOT crash when loading a savestate / branch in a tasproj I made earlier. About the broken tasproj, it seems that all branch info is gone, whereas the input log is still there, but I already have a .bk2 of it, so I don't really need that. I might have a backup somewhere, so I'll what I can do. So far I haven't been able to see corruptions in files from loading them or even getting those errors, so that was probably from my attempts of running current master in VS.

**Comment by Morilli** [comment]
Uhhh was this ever fixed? Every time I've TASed in recent times, this issue has been present, and even checking out the specific commit that supposedly fixed this issue did not resolve it.

Conversion was also sidetracked massively from my side and I never confirmed it working, so I'll assume this to need another look at it.

**Comment by Morilli** [comment]
@vadosnaprimer opinion on 541bf61a6f123c42132c9abbf8239ef507e45a9b?

**Comment by vadosnaprimer** [comment]
In that commit core framebuffer is the same for all branches.

**Comment by Morilli** [comment]
Okay, fixed with 91d6fab5c571b5033f7d02c36a25d5c348598038.

**Comment by vadosnaprimer** [comment]
That one seems to work ok.
