### ISSUE TITLE
[ATARI 2600 Hawk] List of games having bugs or crashing as of Bizhawk Dev 2019-11-09

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#1524]
LAST EDIT : NOVEMBER 11 2019

Theses lists excludes prototypes, demo and homebrew games that do not have a physical release for now

Sound related : 

- [x] Bowling : The bowling toss sound doesn't sounds like on a real Atari 2600 or Stella
- [x] Space Jockey : The sound when you shoot and a ship destroy doesn't sound like on a real Atari 2600 or Stella
- [x] Commando Raid : Helicopter sound are not the same on a real Atari 2600 or Stella
- [x] Ms Pac-Man : Minor sound issues 
- [x] Street Racer : Sounds do not sounds the same that if played on a real Atari 2600 or Stella

Bizhawk crashes with these games :

- [x] Maze Craze : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Lock 'n Chase : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Air Raiders : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Adventure of Tron : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Bump 'n Jump : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Kool-Aid Man : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Frogs and Flies : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Star Strike : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Acid Drop : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Tunnel Runner : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Chase The Chuck  Wagon : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Omega Race : Bizhawk crashes with "Unable to resolve Frame. Please Report." Impossible to test the booster grip controller
- [x] Video Chess : Bizhawk crashes as soon as the CPU is about to play its move
- [x] Haunted House Bizhawk crashes with "Unable to resolve Frame. Please Report."
- [x] Swordfight Bizhawk crashes with "Unable to resolve Frame. Please Report." However, it only happen if you want to replay the game after the first one ends.

Note : The "Unable to resolve Frame" also affected games like Burgertime and 3D Tic-Tac-Toe, but were fixed in a previous issue

Graphical glitches or weird behaviors 

- [x] Skeet Shoot : Game is glitched but boot (might be related to my rom)
- [x] Journey Escape : Game's background is glitched (it was not in 2.3.1)
- [x] Pitfall 2 : Broken in 2.3.2

Require Keyboard Controller

- [x] Basic Programming
- [x] Brain Games
- [x] Codebreaker
- [x] A Game of Concentration
- [x] Hunt & Score
- [x] Magicard (seems more like a tool than an actual game by CommaVid)

Require Kid's Controller

- [x] Alpha Beam with Ernie
- [x] Big Bird's Egg Catch
- [x] Cookie Monster Munch
- [x] Oscar's Trash Race

Other controllers requirement

- [x] Omega Race (Booster Grip)
- [x] Star Raiders (Video Touch Pad)
- [x] Track & Field (Track & Field Controller) (can be played with regular joystick)

~~Other note : 
When you load a save states at the moment a sound is playing, the sound continue to play and cause a long beep until another sound is played. So far, it does not affect the movie file or the video dump~~

This issues will be updated with more games if I find glitches, unsupported stuff or game crashing behaviors

**Comment by YoshiRulz** [comment]
Anyone looking to debug "Unable to resolve Frame", breakpoint [here](https://github.com/TASVideos/BizHawk/blob/c19c7cd5c39087027475a6eff6268c8aea8ce2e5/BizHawk.Emulation.Cores/Consoles/Atari/2600/Atari2600.IEmulator.cs#L60) (maybe the [gamedb fix](https://github.com/TASVideos/BizHawk/commit/62d1005ed9d764146d250f49a24096f8bbb6c035) for Burgertime is necessary).

@Glitcholog If you have homebrew please do try it.

**Comment by alyosha-tas** [comment]
@Glitcholog : I updated the game db for 'unable to resolve frame' error and added  boost grip controller, please retest.

**Comment by Glitcholog** [comment]
Thanks you, ill do the retest and update the first post.

**Comment by Glitcholog** [comment]
All "Unable to resolve Frame. Please Report." games except Maze Craze  for some reason violently crashes Bizhawk without showing an error now.

**Comment by alyosha-tas** [comment]
What specifically happens ?

**Comment by Glitcholog** [comment]
Bizhawk simply freeze at the moment I press the A2600 Reset button, and the "application is not responding" message appear, everything is white (like any application that freeze). My only option is to close it with the taskbar. This behavior is not present on the current bizhawk.

**Comment by alyosha-tas** [comment]
This happens because some game wait to end a frame until reset is RELEASED. If you start a frame by pressing reset, BizHawk holds reset until that frame ends. So since the game wait to end a frame until the button is  released, the frame never ends. This would properly be fixed with subframe inputs, but for now I fixx it just by releasing reset after a certain number of cycles for these game. 

Anyway game DB updated again, please test again hopefully they all work now.

**Comment by Glitcholog** [comment]
Will do the test tonight, thanks for looking at the issue.

**Comment by Glitcholog** [comment]
My apologies to not actually took the time to test that day. I am doing some test right now

Lock n Chase , Bump and Jump and Air Raiders plays without problem.

Acid Drop can be reseted (which was not possible before), but will crash the emulator without error (bizhawk is not responding) when you press the fire button to start the game.

Omega Race instantly crash the emulator, like in the older dev version

**Comment by Spikestuff** [comment]
I randomly decided to do a homebrew one out on the whim.

![image](https://user-images.githubusercontent.com/12412764/57979468-54861300-7a61-11e9-8134-899ffb263203.png)

This is created by johnnywc who made Mappy for the Atari 2600.
To point out the obvious, this does run on Stella.

Reason why it fails is unknowing to me, thought it was related to it being 32kb but I had other random 32kb games that ran fine.
I was thinking cause it's a .bin file and not .a26 but there are submissions on TASVideos that use .bin.

The last thing is probably a mapper error, but honestly don't know.

**Comment by alyosha-tas** [comment]
which game is it? I dont see the title

**Comment by Spikestuff** [comment]
> which game is it? I dont see the title

>This is created by johnnywc who made **Mappy for the Atari 2600**.

**Comment by alyosha-tas** [comment]
Looks like mappy uses the melody cart which isn’t implemented in BizHawk . This cart looks pretty high tech , using some ARM variant ? Probably won’t be implemented unless a dedicated person decides they want it.

**Comment by alyosha-tas** [comment]
@Glitcholog It turns out that audio wasn't part of the savestate in the core, so that is why you sometimes here beeping when loading states. I refactored the audio code so that I could add it to the state, please test to make sure it is good on your end now.

**Comment by alyosha-tas** [comment]
The game haunted House also seems to suffer the same 'unable to resolve frame' error.

**Comment by Glitcholog** [comment]
Ill do the test tonight!

**Comment by Spikestuff** [comment]
[Graphical Glitches: A2600 - Journey Escape](#1614)

**Comment by Glitcholog** [comment]
Just a quick update
The following game still crashes 
Tunnel Runner : Bizhawk crashes with "Unable to resolve Frame. Please Report."
Chase The Chuck  Wagon : Bizhawk crashes with "Unable to resolve Frame. Please Report."
Omega Race : Bizhawk crashes with "Unable to resolve Frame. Please Report." It is impossible to actually test the booster controller implementation
Haunted House
Journey Escape's background is now glitched (it was not in 2.3.1)

Acid Drop seems to work now well now.

**Comment by Glitcholog** [comment]
Just another quick update (AS OF NOVEMBER 9 2019)

- Bowling and Street Racer's sounds are fixed, they sound exactly like the true Atari 2600 or Stella
- Omega no longer crashes and the booster grip was tested and is working correctly.

The following game still crashes 
- Tunnel Runner : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- Chase The Chuck  Wagon : Bizhawk crashes with "Unable to resolve Frame. Please Report."
- Haunted House Bizhawk crashes with "Unable to resolve Frame. Please Report.
- Swordfight crashes with the frame error, but only after starting a second game (added  to list)

**Comment by alyosha-tas** [comment]
adding pitfall2 , see #1772

**Comment by alyosha-tas** [comment]
I moved lightgun to #1778 

The kid controller, video touch pad , and keyboard controller are all actually the same thing, I'm working on it currently.

**Comment by alyosha-tas** [comment]
Haunted House is fixed, this was interesting since it read from invalid TIA addresses and expected open bus, but was getting zero, apparently this case has never come up before.

**Comment by alyosha-tas** [comment]
Fixed pitfall 2, but it's only a temporary solution. The game is doing RESP during HMOVE and expects RESP to win. But, this is only true for missiles. Other games expect HMOVE to win for players, so need a more concrete solution on what exactly is happening at what time.

**Comment by Glitcholog** [comment]
Thanks you for those fixes and those of my other issues! Although on other project, ill eventually come back in video making and continue my quest of finding any problem with games

**Comment by alyosha-tas** [comment]
Keyboard controller has been added, so all such games should be playable now

**Comment by YoshiRulz** [comment]
Not an emulation problem: The rom `SHA1:982B8016B393A9AA7DD110295A53C4612ECF2141` which you added a hack for (in 7a799583e967353737c512f795268a46227d8072) isn't in the gamedb.

**Comment by alyosha-tas** [comment]
skeet shoot works fine with the correct ROM

gamedb entries added for chuck wagon and sword fight

Ms pacman added to #2676 

I'm ok with leaving that game of Kangaroo out of the DB for now, not sure where it came from.

Closing.

**Comment by YoshiRulz** [comment]
Karate (both NTSC `SHA1:C0DB7D295E2CE5E00E00B8A83075B1103688EA15` and PAL `SHA1:C8CD0A04EDEA449151E6349DB2455D48F23DC213`) crashes with "Unable to resolve Frame" ([thrown here](https://github.com/TASEmulators/BizHawk/blob/34d794b368a2943aa20a735f1045d63a69f094c3/src/BizHawk.Emulation.Cores/Consoles/Atari/2600/Atari2600.IEmulator.cs#L59)) when pushing Select or Reset as of https://github.com/TASEmulators/BizHawk/commit/79994070899581981005bc385170384167772c33. Adding gamedb overrides like in https://github.com/TASEmulators/BizHawk/commit/0d9f0d2af136628c297c60565c53a663606ffdc6 does not fix it, EmuHawk hangs instead.
Initially reported by @Chardcore on the TASVideos Discord.

**Comment by CasualPokePlayer** [comment]
Setting only SP_RESET to true seems to resolve the Reset crash (and does not hang, if SP_FRAME is set it hangs). However, even with that, pressing Select seems to still hang. Seems to be stuck in a similar reason to why Reset hanged with SP_FRAME set, it's waiting on Select to stop being pressed while it has the screen off.
