### ISSUE TITLE
Window is spontaneously moved/recreated during Yoshi's island's opening

### ISSUE THREAD

**Issue by henke37** [TASEmulators/BizHawk#1560]
The main emulator window suddenly teleports to the middle of the screen when Yoshi's island switches from the island scene back to the storybook scenes.

**Comment by YoshiRulz** [comment]
What display method are you using? Also please confirm that you're on version 2.3.1 and are using a known good rom (green checkmark in status bar).

**Comment by henke37** [comment]
A fresh download of the stable release of 2.3.1 and Direct3D9. And yes, it's a known good rom.

**Comment by YoshiRulz** [comment]
Reproduced on D3D and GDI+, OpenGL crashed as #1424. Testing that on a dev build now.

**Comment by YoshiRulz** [comment]
Still happening on 2.9.1. While you can set a fixed window size, it would be nice if the auto option could "smooth" resolution transitions. Maybe when the resolution changes outside of a core/rom load, it could keep the window the same size for a few seconds (real-time) with a countdown in the OSD, before jumping to the new size.
