### ISSUE TITLE
Master System Emulation Error : EccotheDolphin.sms

### ISSUE THREAD

**Issue by DelphineusCassandra** [TASEmulators/BizHawk#1611]
Ecco the Dolphin for Master System has a fatal glitch under BizHawk.

Game ending glitch occurs in level "the Machine." Drowning is intended to be disabled for this level. Instead, Ecco drowns as he would in a normal level. This leaves the player unable to progress.

Glitch is present in 1.12.0 as well as 2.3.2

I have confirmed that the same ROM works fine with FreezeSMS, using the same password. Also working as intended under Fusion.

I have not totally ruled out user error, but I've done a clean install of BizHawk, tried two different versions, and tried several different cores and configurations. Glitch is 100% reproduceable in all circumstances. Does not occur on any other emulator.

**Comment by DelphineusCassandra** [comment]
Example passwords for the level: EQPSC; MGPSK

I've also noticed that the sound quality is extremely poor under BizHawk. The dolphin sounds on the title screen are mangled - FreezeSMS sounds much better. The sound effect for eating a fish does not ever seem to play in BizHawk.

**Comment by DelphineusCassandra** [comment]
Additional discovery: the Undercaves "attract mode" auto demo does not play correctly in Bizhawk.

It also does not play correctly under FreezeSMS. It plays as intended under Fusion only so far.

(This particular game is the king of desynch. Get it even slightly wrong in your emulation and it seems you break the Undercaves autodemo.)

**Comment by alyosha-tas** [comment]
Thanks for all this info, this looks like a good case to improve accuracy with. I have a few other things to do first so this might take a bit to get to, but I’ll definitely look into it.

**Comment by DelphineusCassandra** [comment]
In a rather shock result, I have tested on real hardware and found that the [Undercaves demo desynch happens](https://cdn.discordapp.com/attachments/453649340565815326/598512215544561674/IMG_20190710_144813.jpg). My console is PAL running at 50Hz, which I suspect could be the cause. I don't have a non-PAL system to compare with.

The Machine level runs fine on real hardware, as expected. Or I would have been a very unhappy gamer all those years ago.

**Comment by DelphineusCassandra** [comment]
So in summary:

**The Machine:** Ecco should not be drowning on this level. Game cannot be completed without a fix.

**City of Forever Attract Demo:** Desynchs in Bizhawk. This is not accurate behaviour, at 50Hz or at 60Hz.

**Undercaves Attract Demo:** Desynch at 50Hz is actually console accurate. I have no 60Hz console to test. My intuition is that Fusion's behaviour is correct - Fusion desynchs at 50Hz but plays as intended at 60Hz. Confirmation needed from real hardware.

Good luck, Alyosha! I still hope to do a TAS of this game sometime. At present Bizhawk isn't useable.

**Comment by alyosha-tas** [comment]
This is another long standing bug that was tricky to fix. It turns out that the game stored some sprites off screen and the core was mistakenly processing collision for them. Eventually this led to extra code being run that decreasing the oxygen supply.

It is now fixed, and the City of Forever attract demo nowsyncs correctly as well.
