### ISSUE TITLE
Initial time settings needs work.

### ISSUE THREAD

**Issue by EZGames69** [TASEmulators/BizHawk#1622]
So first off let me point out that changing the system time for Saturn works as intended, but the issue comes from how to change it.

So normally when you open up core settings, you can see the Initial time here: https://i.imgur.com/VbAFGXu.png

now since it only shows the date and not the time, it would be assumed that you cant change the time here, but you actually can.  the easiest way to do this is to open the calander and select "today's date" twice.  The first time will change the date, and the 2nd time will add the time.  you are then left with this:
https://i.imgur.com/ad3blgB.png

now if you want to change Seconds, what you do is add them to the end of the time that just appeared, like this:
https://i.imgur.com/qntjiay.png

however, if you click out of the window, those seconds will not appear to you, **but it will still be saved in sync settings**. 
https://i.imgur.com/PymgOYE.png (this is a different time only because I'm stupid and didnt bother with continuity, but either way the seconds are in fact saved)

So the issue I have is how convoluted changing time should be, what would make this easier is if the Initial time setting showed not just the date, but also the time and seconds.  if this is done, then I wont have to check sync settings every time I have to change initial time by the second.

EDIT: turns out this is also an issue with other systems that use Inital time in their sync settings, it's not a Saturn exclusive thing.

**Comment by YoshiRulz** [comment]
I think this applies to GBA too.

**Comment by EZGames69** [comment]
I didnt realize GBA had an internal clock.

**Comment by YoshiRulz** [comment]
I was thinking of Pokémon Gold/Silver for GBC ([this Redditor](https://www.reddit.com/r/Gameboy/comments/3gd77s/looking_for_a_list_of_game_boy_and_gba_games_that/ctx9dqv/) lists some more), but the UI for that just uses a number.

**Comment by Spikestuff** [comment]
Relevant TAS?: [GBA Pokémon: Emerald Version (USA) in 2:12:33.24 by GoddessMaria](http://tasvideos.org/3287M.html) (Requires GMT-5).

**Comment by nattthebear** [comment]
So what do we want here, a different widget on the property grid that makes it obvious that seconds are a thing?

**Comment by EZGames69** [comment]
Yes

**Comment by CasualPokePlayer** [comment]
This was fixed since 2.7 (see https://github.com/TASEmulators/BizHawk/issues/2796, https://github.com/TASEmulators/BizHawk/commit/77916cfa2c8e6f10debfe32efa42e7e3aa2f5c40)
