### ISSUE TITLE
[Feature request] Option to use JPEG instead of PNG for screenshots

### ISSUE THREAD

**Issue by nlburgin** [TASEmulators/BizHawk#1666]
Of course lossy JPEG compression is probably not necessary or desirable for, e.g., NES or Game Boy screenshots. 

However on N64 (and possibly similar systems like PSX, etc.) the quantization artifacts might be less noticeable, and the space savings more substantial. (in tests using Mario Golf screenshots, converting to JPEG at 85% quality using ImageMagick achieved a roughly 80% file-size reduction, while keeping the potato-fication within acceptable limits).

And when running an automated bot that uses a folder filled with screenshots to log its results, these savings could start to add up.

**Comment by vadosnaprimer** [comment]
It should be noted that for jpeg, chroma should be 4:4:4 and DCT should be floating-point. Then it looks way better than usual jpegs without too much overhead in file size.

**Comment by nlburgin** [comment]
It just occurred to me that a workaround (sort of) might be possible by abusing the video output; using a custom ffmpeg command line that sets the codec as a jpeg sequence (not to be confused with MJPEG video) and then only recording for one frame.

However, IIRC the only lua functions dealing with that right now are `client.pause_av()` and `client.unpause_av()`. So the "recording" would have set up and started in advance before running the script, and lua would have no control over the output filenames.

If lua were given more control over the AV subsystem, then a more "complete" workaround could be possible, although spinning up a new "recording" for each screenshot might have some performance overhead...

**Comment by YoshiRulz** [comment]
You can try hacking your copy of EmuHawk a little to get JPEG encoding sooner. Just clone the repo, make the following change, and [build](https://github.com/TASVideos/BizHawk#windows-78110-1).

Replace:
https://github.com/TASVideos/BizHawk/blob/79c4b1e846569a1ef05662d231e393a9d7713e16/BizHawk.Client.EmuHawk/MainForm.cs#L965-L968
...with:
```csharp
using (var img = bb.ToSysdrawingBitmap())
{
	img.Save(fi.FullName.Substring(0, fi.FullName.Length - 3) + "jpg", ImageFormat.Jpeg);
}
```

**Comment by nlburgin** [comment]
While I don't have any intention of trying to set up visual studio just for that, I am pleased to hear that a solution would be so simple; that you're already using an image framework that supports JPEG and that and that this support could be extended to the application with minimal effort.

I was afraid I might be asking for something more complicated, like having to add a libjpeg dependency and call into its API directly :stuck_out_tongue_closed_eyes:

As a matter of fact, I've already come up with a workaround, though it's quite ugly and probably not applicable to most users since it only works if you're running Windows in a Virtualbox and are saving the screenshots to the Linux host using a shared folder:

```bash
#!/bin/sh

mkdir PNG
if [ ! -e PNG/MOUNTED ]
then
  sudo mount -t tmpfs tmpfs ./PNG
fi
IFS='
'
cd PNG
touch MOUNTED
while true
do
  for i in *.png
  do
    convert "$i" -quality 50 "../$i.jpg"
    rm "$i"
  done
  sleep 20
done
```

technically the tmpfs wasn't necessary, though it cuts the amount of disk writes in half.
