### ISSUE TITLE
Cheat device support issue

### ISSUE THREAD

**Issue by DarkLegend1987** [TASEmulators/BizHawk#1721]
In behalf of game fixer , ips patcher bug fixer rom community please support cheat device 3.0 or his correct name gameshark support 3.0

**Comment by YoshiRulz** [comment]
Which system is it for?

**Comment by DarkLegend1987** [comment]
Its psx core we play FF9 and create a patch that Fix some unbalanced tetra máster game but the cheat device dont support the memory address the code we using is this format
50006406 0001
3008324F 009C 
That Fix the card game issue but the cheat device dont support also the Joker command codes dont support to

**Comment by DarkLegend1987** [comment]
Yes its psx cheat device that not support 2.0 and 3.0 codes

**Comment by hegyak** [comment]
I am the Original Coder of the Gameshark Code Importer ..  If I remember right, the Unsupported Codes were not understood by me or I was not up for programming the handling of those code types or the Cheat system in BizHawk could not handle the cheats being put in due to it's own limitations.

**Comment by YoshiRulz** [comment]
PSX code parsing was overhauled in 4bfb4ab00 and the parser now runs without error. Does the code work as intended?
