### ISSUE TITLE
foreach loop in MemoryCallbackSystem.cs can cause enumeration exceptions

### ISSUE THREAD

**Issue by Trivial-Man** [TASEmulators/BizHawk#1823]
In commit 2b7cb1bb7d01c0acd29c955e80ef9e06c075a1e9 the Call function inside BizHawk.Emulation.Common/Base Implementations/MemoryCallbackSystem.cs was changed to use a foreach loop instead of a for loop. The problem is that the collection of memory callbacks can change itself when it is called, and thus crash Bizhawk with a System.InvalidOperationException. Can't modify a collection while iterating through it.

Reverting this specific change should remove the crash. If need be I can create a small sample script to demonstrate this behavior.

**Comment by Zinfidel** [comment]
Just as a data point for this one: I had a collection of scripts with callbacks for SNES Harvest Moon that would do exactly this kind of thing. Some of the callbacks would enable or disable other callbacks that were extremely expensive and only needed to be run on a couple frames.

**Comment by zeromus** [comment]
There were bugs in the original logic too. Please don't close this bug without addressing it more seriously, by actually accumulating edits to the callbacks list in a separated "added" and "removed" list and attempting to skip ones that have been removed. Don't do it with a dictionary unless you're absolutely sure you won't make the order the callbacks are run become chaotic.

**Comment by adelikat** [comment]
Well, I'm not going to do all that, I'll put it back to a for loop and unassign myself.  I at least fixed what I broke
