### ISSUE TITLE
non-VI lag frames doesn't work

### ISSUE THREAD

**Issue by 0xwas** [TASEmulators/BizHawk#1862]
I tested on this option on bizhawk 2.4.0 and kirby 64, which runs at 30 fps for most places. it worked correctly on 2.3.2 but it won't now. And lag counter doesn't seem to work during loadings either.

**Comment by 0xwas** [comment]
Sorry for bump.
I checked the option had been broken since 2.3.3. I didn't check dev versions so I don't know when exactly regression occurred.

**Comment by vadosnaprimer** [comment]
I see similar effect from that option in 2.3.2 and 2.4.
