### ISSUE TITLE
Add Support For Two N64 Plugins (Angrylion RDP Plus and rsp-cxd4) And Updating Plugins Manually.

### ISSUE THREAD

**Issue by Yersho** [TASEmulators/BizHawk#1872]
Sorry if this isn't the place to ask but I was wondering if these two plugins could get support for the N64 Core in Bizhawk. Angrylion RDP Plus is more graphically accurate than GLideN64 and rsp-cxd4 is a more accurate RSP plugin than the default one Mupen64Plus and Bizhawk are using right now. Their Github repositories are these (although you would probably already know this):
https://github.com/ata4/angrylion-rdp-plus (Angrylion RDP Plus)
https://github.com/cxd4/rsp (Original rsp-cxd4 repository)
https://github.com/mupen64plus/mupen64plus-rsp-cxd4 (Mupen64Plus fork of rsp-cxd4 which Mupen64Plus currently uses).
I would also like to request being able to update N64 plugins as they get updated whether it be new releases or compiling straight from the Github source code. I know the answer is probably going to be "it's impossible" since Bizhawk is not just Mupen64Plus so I don't mind if that idea gets rejected immediately.

**Comment by TiKevin83** [comment]
For a practical application to this, Pokemon Snap has only ever worked in an emulator by using dolphin to emulate the VC release or by using angrylion, as the picture scoring system fails to recognize what you took a picture of in less accurate emulators

**Comment by CasualPokePlayer** [comment]
I attempted to put angrylion plus into BizHawk, but it ended up just crashing the mupen emulation thread. The original angrylion works fine tho (implemented in 57c453ea682254553a6197d2f646d0a7f77eca1b, along with cxd4 when angrylion is being used).

You can just update plugins manually (you can just plop a new dll into the dll folder), of course brand new settings are not going to be accounted for and you can't just plop in entirely new plugins (as the list of possible plugins and their file names are hardcoded).
