### ISSUE TITLE
Add low-level support for the Nintendo GameCube Controller Adapter drivers (on host)

### ISSUE THREAD

**Issue by Yersho** [TASEmulators/BizHawk#1879]
Nothing to really add that isn't said in the title. It would just be a nice option to be able to use an official Nintendo Gamecube Adapter with a Gamecube Controller on Bizhawk.

**Comment by zeromus** [comment]
Set up your own input bindings and you can use your gamecube controller in bizhawk.

**Comment by Yersho** [comment]
I meant more of a support similar to how Dolphin handles it (install the WinUSB drivers with Zadig and it detecting and supporting that). Unless this is an option already and is either in a development build or I'm just dumb and if it's the latter sorry for opening a useless issue.

**Comment by YoshiRulz** [comment]
Does it show up in Devices and Printers as a controller icon? If so it'll work.

**Comment by zeromus** [comment]
We're not going to do it the way dolphin does it. Dolphin does this so it can emulate the gamecube with a high degree of fidelity. We don't emulate the gamecube AT ALL. There is no point.

**Comment by Yersho** [comment]
No it does not. On Windows 10 Settings Panel it does show up but not as a controller.
![Windows Devices](https://user-images.githubusercontent.com/56962651/76158661-95354280-60ee-11ea-8b21-d0c430cee44b.png)
And in Control Panel it shows up as well under unspecified.
![Windows Control Panel Devices](https://user-images.githubusercontent.com/56962651/76158675-da597480-60ee-11ea-9ff4-b91a9c85e097.png)
If you didn't know WUP-028 is the name of the official Gamecube Adapter (at least on Windows from what Zadig reports).
I am pretty sure Dolphin specifically detects this driver which is why it works. This driver cannot be detected by any standard controller detecting software (I've tried on multiple Steam games and emulators and if I recall correctly nothing detects it as a standard controller). I guess I should have been more specific in my original post.

**Comment by Yersho** [comment]
Oh I was typing my post before I saw the post saying you can't, sorry I know the answer is no.

**Comment by zeromus** [comment]
Dolphin does specifically detect that driver. Find a different driver and/or use an input mapper utility.

**Comment by Yersho** [comment]
Yea I'll just do that. Was just asking if support was possible, sorry for wasting your time.

**Comment by zeromus** [comment]
Actually, here's the way to proceed. 

Step 1. Paste the dolphin sources into a separate vcxproj which does nothing but expose a clean and simple API.. let's say, like what xinput is, but tailored to the needs of the GC controllers (it's possible it could be about 95% similar). You can find almost any programmer to help you with this, and it can include its own test program which has nothing to do with bizhawk.

Step 2. Any bizhawk programmer can use this by copying the xinput.cs which is already using pinvokes in that very same way

At this point it will work without having to change your driver. I should mention, I think zadig was made because having to change drivers constantly is a fact of life. But now you wouldn't need to.

**Comment by Yersho** [comment]
I don't have any programming experience and probably won't ever. I just have a Github account for whenever I need to report any issue I come across in the projects I use. So unless someone else can implement this I unfortunately can't do anything to help implement this.

**Comment by zeromus** [comment]
I told you to find someone to help you, not do it yourself.

**Comment by Yersho** [comment]
I know no one that can help me so it's probably never going to happen then unless someone else reading this decides to work on this issue.

**Comment by zeromus** [comment]
You could post a bounty somewhere; you could go to a local opensource or game developer meetup and see if you can get anyone interested (it's possible some maker or robots groups would be interested, insofar as it involves looking at how other people are interacting with peripherals); you could go scout out the dolphin developers and compliment their good work on their input handling and suggest other emulators and games might benefit from it if it was extracted as a separate module set up to work similar to xinput. Although this last idea is likely to irritate them, it isn't _very_ irritating and I think I put the most flattering spin on it possible. 

As a kind of composite of those ideas, you could find someone working on an opensource C++ game (or even a closedsource game that you have on steam and like -- look for games that have SDL dlls) and see if you can inspire them to make that project. 

You could also find some SDL developers forums and see they are interested in doing that as a kind of ancillary project.. I doubt they will want to jam huge chunks of dolphin in their source code. But if they could try opening wup028.dll and using a simple API from it, you might get them interested. 

Although all those people are likely to tell you just to use another driver. Good luck!

**Comment by Yersho** [comment]
I'm going to try posting this issue thread in the Dolphin Forums and see if anyone is interested there. I don't have much IRL social skills so I don't think going to real life meetups would be an option for me. Thanks for the advice though. If nothing comes of this than maybe someone reading this issue in the future might tackle it one day.
