### ISSUE TITLE
Can't use kana or other Unicode chars in Lua scripts, even w/ correct file encoding

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASEmulators/BizHawk#190]
```
What steps will reproduce the problem?
Can't use Japanese text.
It is not displayed.

What version of the product are you using? On what operating system?
Bizhawk 1.7.0
Windows 7 64bit

Please provide any additional information below.
Bizhawk Ver1.6.1 Ver1.6.0 Ver1.5.2 work.
```

Original issue reported on code.google.com by `mario...@gmail.com` on 10 Jun 2014 at 1:05

**Comment by tomzx** [comment]
From my current tests, it appears that the text sent to `lua.LoadString` (in `EmuLuaLibrary.SpawnCoroutine`) is properly encoded and readable. However, the string that is received by the `EmuLuaLibrary.Gui.DrawText` method is not recognizablt at that point.

Thus I'd be inclined to think that lua.LoadString/lua.DoString have issues with Japanese.

**Comment by vadosnaprimer** [comment]
The bitmap font that gui.text uses does not have any idea of Japanese letters, nor has it ever had. The only way it might have worked is someone hacked Japanese fonts in. But I can't see Japanese text using gui.drawText either.

**Comment by adelikat** [comment]
1) Does the move to NLua affect this by chance?

2) Can we consider vadosnaprimer's finding a reasonable solution and simply close this ticket?

**Comment by vadosnaprimer** [comment]
2. Nope.
