### ISSUE TITLE
Atari Jaguar

### ISSUE THREAD

**Issue by lucameat** [TASEmulators/BizHawk#1907]
Will the emulation of the Atari Jaguar be taken into account in the future?

**Comment by YoshiRulz** [comment]
No promises. But there's an obvious waterbox candidate should someone decide to contribute: [Virtual Jaguar](https://github.com/djipi/Virtual-Jaguar-Rx) (C/C++; GPLv3+).

There's only one other Jaguar emulator that I know of, the dormant and closed-source [Феникс](http://www.arts-union.ru/node/23) "Phoenix" (homepage only in Russian, claims [95% compatibility](http://www.arts-union.ru/node/66)).

edit 2025-06: Just coming back to note that BigPEmu, the proprietary emulator which seems to be the most accurate, is a ~15 MiB binary compiled from C++. So I would suggest that decompiling it is not worth the time.

**Comment by lucameat** [comment]
Ok, thanks.

**Comment by Spikestuff** [comment]
As a note there is also a dedicated [New Core Topic](http://tasvideos.org/forum/viewtopic.php?t=21526) on the TASVideos forums where you can ask about the Jaguar or another system (most if not all Hawk devs have an account there).

**Comment by nattthebear** [comment]
Reopening.  I don't know much about the cores in question, but there's no reason we couldn't do this.
