### ISSUE TITLE
Memory watches not protected against reading past end of domain

### ISSUE THREAD

**Issue by alyosha-tas** [TASEmulators/BizHawk#1924]
( Split from #1579 )

Repro: create a new 2 byte watch at the end of a domain, ex. for gameboy create a 2 byte watch in WRAM at 0x7FFF.

This will throw an out of bounds error.

Code is commented as such in several places:
https://github.com/TASEmulators/BizHawk/blob/b60bbba126cb5c49c0aa708800435f9dd865878f/BizHawk.Client.Common/tools/Watch/Watch.cs#L313

**Comment by adelikat** [comment]
I think there's a few things I would expect to see in the fix here:
1) get rid of the mod
2) do not attempt to "fix" any of this but rather prevent the watch from being created if it doesn't make sense, such has being fully or paritally out of range

**Comment by YoshiRulz** [comment]
TODO was resolved by https://github.com/TASEmulators/BizHawk/commit/1721e4f9eaf616d16f06b8b424b61832669df7ba. At a glance, ApiHawk/Lua seems to handle this properly as well. Closing.
