### ISSUE TITLE
Hang shortly after a popular minimal hook

### ISSUE THREAD

**Issue by whiteted-strats** [TASEmulators/BizHawk#1952]
### Summary
Bizhawk 2.4.0 hangs shortly after running a minimal hook on a popular function in the N64's Goldeneye 007.

### Repro

NTSC-U cart,
SHA256 = 2cdcec8a9f0cb6e36337f3ee39d8ad105dc8afa6ba1c02d466e8f5b771f9a162
SHA1 = abe01e4aeb033b6c0836819f549c791b26cfde83
MD5 = 70c525880240c1e838b8b1be35666c3b

Lua script:
```lua
local function callback()
 
end

event.onmemoryexecute(callback, 0x7f058258)
```

Most times it starts hanging in the iconic opening sequence of Bond. If not just start Dam and it should crash before you gain control. 

This hook address is the JR RA return for the matrix multiplication function, so presumably is called lots of times per frame.

### Output

Hangs.

### Host env.
- BizHawk 2.4.0 & 2.2.2;  Windows 10 Home 10.0.18362

**Comment by YoshiRulz** [comment]
(from https://github.com/TASVideos/BizHawk/issues/1920#issuecomment-613016216)

**Comment by YoshiRulz** [comment]
CNR on 2.8. Intro/title ran smoothly to frame 10000. Dam loaded fine.
