### ISSUE TITLE
[Lua] Implement memory functions for Fixed Point 20.12 and 16.16

### ISSUE THREAD

**Issue by ThunderAxe31** [TASEmulators/BizHawk#1970]
This thing bugged me for years. The RAM Watch tool allows to watch addresses as Fixed Point 20.12 and 16.16 values, yet there are no preinstalled Lua functions supporting that. In the end I was able to write my own workaround functions for converting to Fixed Point format, but I still think that it should be better to include such as a preinstalled feature, for user friendliness. Ideally, these would be the functions that I wish to be implemented:
```
mainmemory.read_fixedpoint_20_12(int addr, bool bigendian)
mainmemory.write_fixedpoint_20_12(int addr, bool bigendian)
mainmemory.read_fixedpoint_16_16(int addr, bool bigendian)
mainmemory.write_fixedpoint_16_16(int addr, bool bigendian)
memory.read_fixedpoint_20_12(int addr, bool bigendian, [string domain = null])
memory.write_fixedpoint_20_12(int addr, bool bigendian, [string domain = null])
memory.read_fixedpoint_16_16(int addr, bool bigendian, [string domain = null])
memory.write_fixedpoint_16_16(int addr, bool bigendian, [string domain = null])
```
Since these would be especially useful for systems like PSX, I think it would be a nice addition in conjunction with the update of Octoshock.

**Comment by nattthebear** [comment]
What type would this use on the lua side?

**Comment by zeromus** [comment]
I would prefer to see this be clear about whether there is a sign bit, and it could be expressed more succinctly: read_fx1x19x12 perhaps. Occasionally you will find fixed point values without sign bits. For instance in 8 and 16bit games you will commonly get pixels and subpixels as something like a fx8x8 or fx16x8. fx_1_19_12 is also clear enough, I suppose.

**Comment by ThunderAxe31** [comment]
Then there are more possibilities than what I thought, we can't have a billion of functions for every possible format possible. At this point I think it would make much more sense to make two functions that ask explicitly to declare the format, more or less like this:
```
mainmemory.read_fixedpoint(int sign_bits, int magnitude_bits, int fractional_bits, int addr, bool bigendian)
mainmemory.write_fixedpoint(int sign_bits, int magnitude_bits, int fractional_bits, int addr, bool bigendian)
memory.read_fixedpoint(int sign_bits, int magnitude_bits, int fractional_bits, int addr, bool bigendian, [string domain = null])
memory.write_fixedpoint(int sign_bits, int magnitude_bits, int fractional_bits, int addr, bool bigendian, [string domain = null])
```

**Comment by zeromus** [comment]
that's a decent idea, but we also have to support these formats in other tools (hex editor and such) so coming up with a name for them and having a finite set supported is still important. 

Now that you mention it, the functions you proposed here could be done in lua. The value could be built from ripping apart the raw integer values. Same as would be done in c#. Certainly it isn't super-easy, but why add an API function for something that can be done in lua? I don't know.. what's a good rule for when to stop?

**Comment by YoshiRulz** [comment]
Just use the s32 functions and scale by 2^12 or 2^16. Or don't, and pre-scale any hardcoded values.
