### ISSUE TITLE
Add Stella to Bizhawk for Atari 2600 emulation.

### ISSUE THREAD

**Issue by nattthebear** [TASEmulators/BizHawk#2001]
I'll be honest, I don't know much about this.  I've heard our 2600 isn't so great and theirs is.

@adelikat I think you've looked into this, could you give a short summary?

**Comment by endrift** [comment]
Modern Stella heavily depends on SDL2, for no good reason. You may need to figure out how to yank it out. Or use an ancient version of Stella like RetroArch does.

**Comment by nattthebear** [comment]
Excellent!  Wouldn't want it to be too easy 🤣

**Comment by alyosha-tas** [comment]
Our core is pretty good really, but I just no longer have the time to focus on all the in-house cores to keep them all up to speed. A2600 in particular has seen a lot of work on TIA emulation in the last couple of years that I am way behind on. It doesn't really effect commercial games, or even most demos, but accurately accounting for all the new info would require a major rewrite that I'm just not going to do. Also, a lot of modern homebrew require complex cartridge hardware that is not implemented at all (with internal ARM chips even.) Stella isn't totally up to date with all the new tests and info either, but at least they're working on it and have the homebrew stuff done.
