### ISSUE TITLE
[PSX core] Worlds scariest police chases unplayable

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#2095]
At the 9th mission, all you have to do is follow the bus and not lose sight of him. For some reason, the arrest bar goes up way too slow and you just end up losing the mission. The only way to beat it is by making the bus crash into lots of polls to slow him down. Which isn't normal as you can see from the rta record.

input file is here: http://tasvideos.org/userfiles/info/63810527013081129

Bios used: SCH1001.bin

NTSC version

**Comment by nattthebear** [comment]
Does this happen on upstream, or in other emulators?

**Comment by InfamousKnight** [comment]
I havent tried other emulators yet, but in some of the speedruns of this game it says its done on emulator. Ill have to ask them. I also haven't tried upstream yet.

**Comment by Spikestuff** [comment]
Latest builds match upstream so if you want to simplify your life convert your input to latest builds and remove/add frames where necessary.

**Comment by InfamousKnight** [comment]
Sorry for the late response, the build Im using is this: BizHawk_Developer-2020-05-20-153203-#8ef5c18fcbbc641099d4ce898de3a898c02789d2

Was the psx core updated since then?

**Comment by YoshiRulz** [comment]
nope 1d0dd4d25

**Comment by InfamousKnight** [comment]
Well, at least I dont have to restart the movie. Wheres the page for octoshock builds?

**Comment by YoshiRulz** [comment]
[upstream 1.24.2](https://github.com/mednafen/mednafen.github.io/raw/master/releases/files/mednafen-1.24.2-win64.zip)
