### ISSUE TITLE
Add TMSS to Genesis Core

### ISSUE THREAD

**Issue by hegyak** [TASEmulators/BizHawk#2230]
TMSS apparently was added to the ColecoVision Core as noted here:
https://github.com/TASVideos/BizHawk/issues/1116

Information on the TMSS can be see here:
https://segaretro.org/TradeMark_Security_System

More Information and discussion from GensPlus-GX can be seen here:
https://github.com/libretro/Genesis-Plus-GX/issues/44

I would like to note that doing this is a Sync Setting change, and also would require some DB changes for some Official and Beta games to work if this change is applied.  The change would be to tell the Genplus-GX Core to Skip/Bypass the TMSS for the game listed on SegaRetro's page.

**Comment by nattthebear** [comment]
What value does this provide?

**Comment by hegyak** [comment]
It does make the Genesis/Mega Drive Emulation more "Accurate."  Though, most likely, it has no real impact on Emulation.

**Comment by RetroEdit** [comment]
The general concept of this seems somewhat similar to the GBA bios screen with the Nintendo logo. While there is an option to skip the intro for GBA movies (separate from just using the bios; the bios can still be used even if the intro is skipped), submissions always retain the intro for accuracy purposes.

**Comment by alyosha-tas** [comment]
Since not all models have it, I don't think this is high priority. Game Gear also has a similar boot rom in some (but not all) systems that is likewise ignored.

**Comment by nattthebear** [comment]
So does gpgx actually implement this?  If so, it may be a low effort add.  If not, we should just close this because it's never going to happen.

**Comment by hegyak** [comment]
It does.  See the issue I linked to in the LibRetro GitHub for this.  Though, I am not sure if BizHawk's branch differs from LibRetro.

**Comment by nattthebear** [comment]
I see, so we'd need to figure out the status of https://github.com/ekeeke/Genesis-Plus-GX/commit/9310dcf92c958f5e5f2a04c17b2118565ee38640, and possibly some earlier commits?  (Since that is just wiring things up that already exist, mostly.)
