### ISSUE TITLE
Dobiestation broken

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#2269]
So I tested dobiestation, and found major bugs not found in dobiestation standalone. These games work fine in dobiestation(I tested ones before it was ported to bizhawk) and midnight club 2 for instance shows a black screen with this in the terminal:
Failed to satisfy allocation of 53248 bytes on sbrk like 17 times on the log.

And with kingdom hearts re chain of memories, on the first opening cutscene, it blacks out and somehow I can open the menu if I press start which normally wouldn't be possible. And it comes with a blank party screen. Creepy

**Comment by nattthebear** [comment]
> Failed to satisfy allocation of 53248 bytes on sbrk like 17 times on the log.

I upped the heap limit for sbrk, so maybe that will help.

Also remember to play around with the jit vs interpreter settings

**Comment by InfamousKnight** [comment]
Well, it got rid of the error message, but there's still a black screen. I tried ignoring it and pressing buttons that would progress, and I did notice a frame drop for a few seconds, and then it went back up and spammed the start button until I would supposedly go in game, but no luck. Either I didn't wait long or something but it ran at a high framerate because there was nothing to render

**Comment by InfamousKnight** [comment]
*bump* other dysfunctional games: kingdom hearts 1. Go past new game menus and it crashes. Oddly, it runs faster on bizhawk than standalone dobiestation. Ratchet deadlock crashes about 200 frames in on jit settings. If you make all options int, it would prevent the crash, but nothing rendered with occasional frame drops. With kingdom hearts 1, changing it to int on all settings doesn't prevent the crash.

About the speed problem, while I haven't managed to go in-game anywhere yet, I haven't noticed a major drop in frame rate. Maybe once these are fixed there will be. We don't know.

**Comment by nattthebear** [comment]
Uggg, what a mess.  I know I'm not handling `fenv` right now, hopefully that will fix some of this.  Other than that, I have no idea what would be causing behavioral differences; the integration is very simple and we haven't really modified core code.

**Comment by InfamousKnight** [comment]
Ok, I got some surprising news, I downloaded the latest dobiestation build
to compare speed, I tested kingdom hearts 1 for opening screens, newest
dobiestation runs at 19 frames a second. Bizhawk dobiestation runs at like
24 frames a second. I think you accidentally made it run faster with "fake"
threads.

**Comment by InfamousKnight** [comment]
Has anyone managed to go in-game?

**Comment by nattthebear** [comment]
Unfortunately I don't have a lot of time to work on this right now, and I am also stumped by these issues; we're compiling the same code so it should behave the same 😢.

In 9600bc2ce0add5fa8041a57b9fa8f53158403313 I did make a small tweak that might fix something, but probably won't

**Comment by InfamousKnight** [comment]
And just so you know, it didn't make any difference.. Although the frame rate on the opening screens of kingdom hearts 1 match more closely to dobiestation standalone. It must be because more things were implemented and so it has more to check and therefore a speed drop.

**Comment by CasualPokePlayer** [comment]
Dobie core was removed some time ago.
