### ISSUE TITLE
"Frame advance skips non-input frames" option also skips next polling frame

### ISSUE THREAD

**Issue by Zinfidel** [TASEmulators/BizHawk#2380]
### Summary
Setting BizHawk's profile to N64 Tool-Assisted Speedrunning causes frame advance to skip over input polling frames. The attached animated gif illustrates this issue.

What seems to be happening here is that the emulator is checking the same code that is responsible for the lua command `emu.islagged()` to see if the current frame should be skipped over for not polling input. *However*, the nature of checking whether a frame is a lag frame or not requires that the frame be rendered first. Thus, when checking if the frame is to be skipped, the emulator is actually acting on information about *the previous frame*.

TAStudio highlights this issue as TAStudio actually looks to the future and records lag vs. non lag frames, so it actually knows in advance whether the frame polls or not. **Please note that in the attached .gif that TAStudio's representation of lag frames is correct.**  This is probably a very difficult problem to deal with, because the nature of the checking whether a frame polls input or not necessitates moving past the frame. The N64 Speedrunning Profile is unfortunately affected by this problem as each frame advance while under this profile will skip over input frames (you can't land on them using TAStudio at all).

@YoshiRulz pointed out this line of code: https://github.com/TASVideos/BizHawk/blob/2a285af5aefc9014153801beb797c2e326189ed6/src/BizHawk.Client.EmuHawk/config/ProfileConfig.cs#L236 as being the particular setting that is responsible for this behavior.

### Repro
1. Open BizHawk
2. Config > Profiles > N64 Tool-Assisted Speedrunning
3. Load an N64 ROM (I have tested using Star Wars Episode 1 Racer and Glover)
4. Open TAStudio
5. Allow the game to be emulate long enough for input polling frames to appear in TAStudio.
6. Attempt to move TAStudio's current frame indicator to a polling frame. Observe that that the current frame indicator will skip over the frame to the next frame each time.
7. Advance the emulator one frame. Observe that each time this is done, a number of frames equal to the number of lag frames in front of the currently select frame is advanced, but always by 1 too much.

### Host env.
- BizHawk 2.4.0; Win10 Home, Intel
- BizHawk 2.5.0; Win10 Home, Intel

![JkSZyKT3jp](https://user-images.githubusercontent.com/1929934/92420690-b8868c00-f129-11ea-9e38-a1ea9c06b53e.gif)

**Comment by YoshiRulz** [comment]
To be clear, is this caused by `Config` > `Customize...` > `Advanced` > `Frame advance button skips non-input frames` specifically, or is it only in conjunction with the other settings from the N64 TAS profile?

**Comment by RetroEdit** [comment]
I know I previously said this is a problem, but looking at it further, I wonder if this might be the intended behavior?

The frame after the input is handled is the frame where the input takes effect. It doesn't change what you can do in TAStudio, it's just skipping past frames where your inputs would be ineffective.

To put it another way, what would be the benefit of this setting going to exactly the frame before an input would be processed?

----

The only way to "fix" this is to backtrack, which may be fine, but also I kind of don't see the point of doing so without a compelling reason.

**Comment by Zinfidel** [comment]
> To be clear: is this caused by `Config` > `Customize...` > `Advanced` > `Frame advance button skips non-input frames` specifically, or is it only in conjunction with the other settings from the N64 TAS profile?

It appears that turning on the N64 TAS profile automatically checks that box. Unchecking that box stop the behavior. This behavior exists with that checkbox checked regardless of the profile being used. So it appears to only be indirectly related to the N64 TAS profile. (I didn't even know about that checkbox!)

@RetroEdit :
I would not say that this is for sure a bug that needs to be "fixed" because it's a complicated situation. The behavior however *was* unintuitive enough to me when I first ran into it that I thought for sure that something was going wrong. If I had to make an argument for this being a bug, I would say that when TASing, conceptually I want to frame advance then observe the game's state to make a decision about what to do next. So I would do some input, advance a frame, then decide what kind of input to do next. This workflow assumes that at the end of a frame advance, the game is in a state that is ready for more input.

Another argument might be that without TAStudio open, this behavior makes it so that you can not do "precise" input. If you want to register an input for the next polling frame with this option turned on, you would need to hold a button down for all of the frames covered by the frame advance, such that when you land on the next frame, the frame before had the input held down. So you would get strings of holding the button down inside of non-polling frames, ending with one input frame. This is purely an aesthetic concern though.

**Comment by RetroEdit** [comment]
Yeah, maybe it shouldn't be packaged in with the N64 TASing profile.

**Comment by adelikat** [comment]
It's intentional, for reasons people have brought up.  It should be packed with the N64 profile due to .bk2 tasing.  Otherwise most every TAS is cumbersome to TAS since few games run at 60fps

**Comment by YoshiRulz** [comment]
Would ignoring "Frame advance skips non-input frames" while TAStudio is open be an acceptable fix? (Something like s/`Config.SkipLagFrame`/`Config.SkipLagFrame && !Tools.IsLoaded<TAStudio>()`/ [here](https://github.com/TASVideos/BizHawk/blob/766e2aa14dd6de1c8f285e4bf0df6013a17c31c4/src/BizHawk.Client.EmuHawk/MainForm.cs#L2895).)

**Comment by alyosha-tas** [comment]
I don't think disabling this for TAStudio is the best option here, as it can still work as intended in recording mode. (Or maybe someone actually uses this option on purpose.)

I think the only actionable thing here is to inform users about what is happening when they select the N64 profile, and let them know how to disable this setting if it is not desirable for them.
