### ISSUE TITLE
turning on "Auto-load Last state" breaks movie recording/playback

### ISSUE THREAD

**Issue by adelikat** [TASEmulators/BizHawk#2384]
1) Open a game
2) File -> LoadState -> Autoload last slot
3) Advance to some point in the game, and save a state
4) File -> Movie -> record movie, pick a filename and save
5) Notice the core will reboot but then the auto-load state will kick in, and movie recording will be recording from this state BUT this is not a savestate anchored movie!
6) turn off autoload loadstate, and replay movie, notice it will desync since it was recording from a not-power-on point, but is not anchored to it

**Comment by YoshiRulz** [comment]
Would it be enough to add `!MovieSession.NewMovieQueued && ` before the condition here? That's how a call to `LoadSaveRam` is guarded a few lines prior.
https://github.com/TASVideos/BizHawk/blob/c0b6bf61b1a06db2ce5287bfc74a7ab2fffbf4ef/src/BizHawk.Client.EmuHawk/MainForm.cs#L3810-L3813
