### ISSUE TITLE
Add option to disable savestate history in TAStudio backups

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#2426]
For users who have backups automatically saved frequently, this can quickly eat up too much hard drive space to be practical. This may be a result of the new backup mechanism, which saves multiple files instead of always replacing a single file (at least I remember it just replacing the same file previously). However, this does not mean saving multiple files is a bad thing; redundancy is good for backups.

One way to avoid taking up so much space would be to exclude the savestate history from backups. This could be a nice compromise: you could still keep markers and branches while reducing the size significantly. Replaying the whole movie to get back to the present is not too much of a problem, since it's a backup.

This should still be optional, since people who manually save backups may want to preserve the savestate history for a more limited set of backups.

**Comment by Morilli** [comment]
Was this fixed by #2416?

**Comment by RetroEdit** [comment]
Looks fixed to me.
