### ISSUE TITLE
[Feature Request] 64DD (.ndd) support

### ISSUE THREAD

**Issue by SamRohod** [TASEmulators/BizHawk#2454]
The 64 Disk Drive games and expansions in the .nnd format don't seem to work.
I tried to import my "64DD IPL ROM" but i couldn't find an option for it.
This effects games like the F-Zero X with the Expansion Kit disk & Super Mario 64 - Disk Version & few others.

**Comment by YoshiRulz** [comment]
Blocked by #1718.

**Comment by CasualPokePlayer** [comment]
This is implemented in the Ares64 core (mostly since upstream implemented so it was relatively easy to slap support in), although that's not great for casual playing at all.

**Comment by Varuuna** [comment]
Is there any news on this as I just ran into this issue myself? I'm aware that Ares64 is loaded when loading an N64DD game, but either I'm missing something or BizHawk doesn't support loading the .ndd together with the N64 file.

This affects F-Zero X + Expansion Kit as both the .z64/.n64 and the .ndd file needs to be loaded at the same time (loading only the .ndd results in an error message from the game asking the user to turn off the system and insert the cartridge) and I can't figure out a way of doing so in BizHawk so I've had to resort to using Project64 which allows loading 2 files as a "combo".

Thanks!

**Comment by CasualPokePlayer** [comment]
Use the multi-disk bundler, like every other BizHawk core which needs multiple "roms"

**Comment by Varuuna** [comment]
I see. I had never used it before, so wasn't aware of that this was what it was used for.

Unfortunately with that we arrive an an error message:
![image](https://github.com/TASEmulators/BizHawk/assets/8760858/c7e709e9-d1c5-432a-b005-0431ebe109fe)

Followed immediately by this message (might just be due to the first one):
![image](https://github.com/TASEmulators/BizHawk/assets/8760858/f893d129-5261-4190-9ee7-df55e029873d)

I am using BizHawk 2.9.1.

**Comment by YoshiRulz** [comment]
How does the performance compare to normal N64 games in Ares64?

**Comment by Varuuna** [comment]
The overall performance is mostly fine, though I tend to notice the occsasional "hiccup" from time to time.

Though loading the same game (F-Zero X in this case) in Ares64 results in a slightly smaller screen size and the vehicles and other objects are much more pixelated compared to Mupen64Plus's core.

Ares64:
![image](https://github.com/TASEmulators/BizHawk/assets/8760858/a5c3590e-c286-4abf-aa6a-6ef656ccd36e)

Mupen64Plus:
![image](https://github.com/TASEmulators/BizHawk/assets/8760858/61cea883-59f3-4038-b2d3-fca2ab20a0eb)

**Comment by CasualPokePlayer** [comment]
mupen64plus would give the same image if you use the "angrylion" plugin (i.e. the accuracy plugin).

**Comment by YoshiRulz** [comment]
My question wasn't about how it compares to Mupen. Though on second thought I realise the alternative is to not have N64DD emulation, so having functional emulation is better *a priori*. Closing.
