### ISSUE TITLE
Bizhawk Lua Function Addition (Emulation Display)

### ISSUE THREAD

**Issue by nymx-tas** [TASEmulators/BizHawk#2456]
### Summary
Bizhawks' lua library can benefit from a new function, under the **client** section to open access for lua scripts to have control over the display mechanism that exists in the GUI. I suggest the following enhancement:

client.emulationDisplay(0) *Full*
client.emulationDisplay(1) *Minimal*
client.emulationDisplay(2) *Absolute Zero*

**Comment by YoshiRulz** [comment]
`client.getconfig().DispSpeedupFeatures = 2`

Leaving this open because that's dumb. See also #2094.

**Comment by zeromus** [comment]
If someone hooked it up so you can change ANY CONFIG value from lua by reflection, then that's AMAZING, not dumb. It's all of the power and none of the maintenance cost as compared to adding a mass of code equal in size to the mass of configuration options.

**Comment by nymx-tas** [comment]
I never recognized that function. I will be giving that a try. Thanks.

**Comment by zeromus** [comment]
a refresh will not necessarily make it go black. those speedup functions speed up by not drawing ANYTHING, not even black. What you want is a function to draw black. You can already do that in lua with regular 2d drawing functions.

**Comment by YoshiRulz** [comment]
`gui.cleartext()` and `gui.text()` should do what you want.

**Comment by nymx-tas** [comment]
Ok. I'll give that a try. Thanks.
