### ISSUE TITLE
[enhancement] easier ffmpeg setup for Linux 

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#2457]
For now, users have to create a symlink pointing to a certain version. Its not as easy as it is on windows and was wondering if its possible to make it automatic like it is on windows?

I'm new to this kind of thing, and just am honestly really lost on what do with it. I dont want to go back to windows over this.

**Comment by YoshiRulz** [comment]
If you can find an FFmpeg binary that works on all distros, and you check that every combination of flags EmuHawk could possibly use are supported, I'll swap it out.

**Comment by zeromus** [comment]
You want to use linux, but you don't want to hand-configure and build your own software? That would be having your cake and eating it.

we could fork ffmpeg, branch on the needed commit, and modify the build scripts to produce and install an executable with the git revision in the filename. then people would only need to run a (very long-taking) one-liner to clone the ffmpeg fork and build&install it and put all their complaints about how they can't get it to build in one thread which we could ignore.

**Comment by InfamousKnight** [comment]
> If you can find an FFmpeg binary that works across distros, and you check that _every combination of flags EmuHawk could possibly use_ is supported, I'll swap it out.

Wait so the commits you linked to me gave other distros problems? This could be a mess unless we recommend 1 distro for bizhawk. That would be the easiest approach.

**Comment by YoshiRulz** [comment]
I don't have the time or patience to find portable FFmpeg binaries right now but I assure you, they exist.

**Comment by InfamousKnight** [comment]
I found them.. but I'm not sure if I made a symlink correctly. That or I have the wrong version. 


ln - s /home/sean/Downloads/ffmpeg-4.2-linux-64 /home/sean/Downloads/BizHawk_devbuild_master_24d07121/dll/ffmpeg

Doesn't it require a specific version? Or did I miss something in the command? I found binaries back from 2018.

**Comment by nattthebear** [comment]
Feel free to blame ffmpeg for some of this:  They're constantly changing parameters and have shipped releases with nonsense behavior (like requiring an index in a piped NUT file, why why why why why?).

**Comment by YoshiRulz** [comment]
It's `ln -s` not `ln - s` (or you can `mv` it, as long as `/dll/ffmpeg` resolves to the binary), and you will need to have the *exact* version for it to work. To disable the check, replace:
https://github.com/TASVideos/BizHawk/blob/bd64530ce581062c0b8477b756ff20f4be2f7c55/src/BizHawk.Common/FFmpegService.cs#L50
with:
```csharp
if (stdout.Contains("ffmpeg")) return true;
```

**Comment by InfamousKnight** [comment]
Thanks! I actually knew about the -s mistake its just I was copying the command by hand on my phone and the auto "correct" feature messed it up.

I found a portable binary that not only works, but also somehow removes the malformed video output experienced earlier. Tested on mgba so far.

**Comment by YoshiRulz** [comment]
I've automated building the correct version of FFmpeg: https://gitlab.com/TASVideos/testing/-/pipelines/241225958/builds. I have no idea which files are actually needed, a good start would be to drop the three binaries from `bin/*` and all the libraries from `lib/*` (don't bother with the links or `.a` files) into BizHawk's `dll` dir.

**Comment by InfamousKnight** [comment]
Sorry for the late response, but I tried putting those in like you said and it didn't make any difference. The dialog box still pops up. I don't know if just extracted them incorrectly, I extracted the folder into bizhawk and moved the files from within it. Using stable release. I tried deleting. a files too and not much luck.

Thanks for at least trying though.

**Comment by InfamousKnight** [comment]
*bump* after going back to linux, its pretty much feature-parity with windows now, except this is still not as straight-forward as windows is. I don't remember what ffmpeg version I used(should have noted it down) and back then I just downloaded one and hoped for the best.

Is there anything that can be done to make this easier?

**Comment by YoshiRulz** [comment]
I just need example use-cases. Movie file + FFmpeg flags + output video from Windows.
