### ISSUE TITLE
mGBA: Woody Woodpecker in Crazy Castle 5 desynchronization 

### ISSUE THREAD

**Issue by ozderya** [TASEmulators/BizHawk#2473]
I recorded this game and when I wanted to replay it desynchronized. I was using 2.4.2. Not sure if this problem exist in latest releases. 
Not sure if this is user mistake or real bug but I recorded more than 100 playthroughs in several systems. This one is my third desynchronized one.

**Comment by YoshiRulz** [comment]
Please try again on 8cc5488de (or 2.6.2 which is coming soon).

**Comment by ozderya** [comment]
Sure. It will take some time tho. Let you know if any desynchronization occur.

**Comment by alyosha-tas** [comment]
@ozderya reopen if this issue persists on current builds (2.6.3 and up) and attach a movie file if possible. Until then closing as this is too outdated to be useful.
