### ISSUE TITLE
MAMEHawk: playing movie under file>movie>play movie desynchronized for some games

### ISSUE THREAD

**Issue by ozderya** [TASEmulators/BizHawk#2496]
While title explanations the issue if you play the same movie under TASTudio it plays without any problem.
Example: Gradius and Aero Fighters 3

Saturn core also had same problem for Sonic Wings Special

**Comment by YoshiRulz** [comment]
Can you attach a `.tasproj` for the Saturn game which works only in TAStudio? Which version of EmuHawk are you using?

**Comment by ozderya** [comment]
Sorry to forgot to say version. The version is 2.4.2.
I deleted .tasproj but if it works I still have .bk2. 

I played it 2 months ago, if I'm not mistaken the problem was accrued in second loop just before final boss.
[[Saturn] Sonic Wings Special (Japan).zip](https://github.com/TASVideos/BizHawk/files/5610968/Saturn.Sonic.Wings.Special.Japan.zip)

**Comment by ozderya** [comment]
Sorry to mislead but I might be wrong about Sonic Wings Special. It was 2 months ago and did not remember exactly. I had some problem with one of the Aero Fighters games but most probably it was only Aero Fighters 3.

**Comment by ozderya** [comment]
I find another game have same issue. I played 2 stages. If you play under file>movie>play movie it will desynchronized during first stage boss. I hope .tasproj will helpfull.

[[Arcade] Darius Gaiden - Silver Hawk Extra Version (Ver 2.7J 1995+03+06) (Official Hack).tasproj.zip](https://github.com/TASVideos/BizHawk/files/5719587/Arcade.Darius.Gaiden.-.Silver.Hawk.Extra.Version.Ver.2.7J.1995%2B03%2B06.Official.Hack.tasproj.zip)

**Comment by vadosnaprimer** [comment]
Does this still happen in the latest dev build?

**Comment by CasualPokePlayer** [comment]
With the waterboxing (in 2.9 release) and lack of replies by the OP I'm going to assume these issues have been fixed.
