### ISSUE TITLE
Lua joypad.setfrommnemonicstr doesn't work without reinit'ing MovieSession

### ISSUE THREAD

**Issue by WilliamSzeto1** [TASEmulators/BizHawk#2525]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Running Lua programs for Pokemon Red, joypad.setfrommnemonicstr won't actually set the inputs for a frame until I open TASStudio. After closing TASStudio, the function will work properly.

### Repro
1. Open BizHawk, Load ROM, Open Lua Console
2. Run program in question, including joypad.setfrommnemonicstr. At this point, there is no input to the emulator.
3. Open TASStudio. The input begins working. 
4. Input keeps working after TASStudio is closed, even after Lua Console is closed and opened again, and even after ROM is closed and opened again.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.5.2; Win10 Pro 1909; not sure about other specifics

**Comment by YoshiRulz** [comment]
Working as intended. Changing this to a feature request.

**Comment by adelikat** [comment]
The intent is to only use this method with movies, maybe it would be better to move this to movie.setinputfrommnemonicstr() ?

**Comment by michael-simon** [comment]
I am trying to use this function in TASing/RNG Manipulating, and having to create and load a movie just to do this is weird given that this is the only compact data-driven format for doing controller input. If you want to put a list of controller inputs into a file (like bk2 does internally) and then use them, without a function like this you can't. For a scriptable toolkit, I would think you would want to support using some consistent input file format, and this is the one that's knocking around, right?

**Comment by YoshiRulz** [comment]
^ possibly a hack? @adelikat
