### ISSUE TITLE
PSX Movie Desyncs but syncs if you playback little earlier frame

### ISSUE THREAD

**Issue by ozderya** [TASEmulators/BizHawk#2540]
This is indeed weird bug and I don't know how to explain it. So I ended up screen record my computer to show it. Unfortunately it did not record TAStudio part but only emulator screen.

Game: Konami   Antiques: MSX Collection Vol. 1 - Gofer no Yabo Episode II
ver: 2.5.2

[PlayStation - Konami Antiques - MSX Collection Vol. 1 (Japan) - [PSX] Konami Antiques - MSX Collection Vol. 1 (Japan) - Gofer no Yabo Episode II.tasproj 2020-12-28 20-12-37.mp4.zip](https://github.com/TASVideos/BizHawk/files/5748243/PlayStation.-.Konami.Antiques.-.MSX.Collection.Vol.1.Japan.-.PSX.Konami.Antiques.-.MSX.Collection.Vol.1.Japan.-.Gofer.no.Yabo.Episode.II.tasproj.2020-12-28.20-12-37.mp4.zip)

**Comment by ThunderAxe31** [comment]
It may be the same as this one: https://github.com/TASVideos/BizHawk/issues/2214

**Comment by CasualPokePlayer** [comment]
Likely nonissue for Nymashock.
