### ISSUE TITLE
Hamtaro: Ham Ham Heartbreak - Game gets stuck after name entering screen

### ISSUE THREAD

**Issue by noddy360** [TASEmulators/BizHawk#2541]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
The GBA game Hamtaro: Ham Ham Heartbreak softlocks after pressing Yep-P on the name entering screen. The game should load a cutscene after that but it never does.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open BizHawk and load a ROM
2. Open the USA ROM of Hamtaro: Ham Ham Heartbreak
3. Skip the intro cutscene and select a New game with A/Start.
4. Press Down twice and select the "OK" option with A.
5. Select the "Yep-P" option with A.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.5.2; Win10 Pro; Intel
- BizHawk 2.6.3; Win10 Pro; Intel
- BizHawk 2.7.0; Win10 Pro; Intel
- BizHawk 2.8.0; Win10 Pro; Intel
- BizHawk dev build at 90c0214; Win10 Pro; Intel
- BizHawk dev build at bf5833a; Win10 Pro; Intel
- BizHawk dev build at 5e3e65a2; Win10 Pro; Intel
- BizHawk dev build at f8a688d47; Win10 Pro; Intel

This is where the game gets stuck:
![Hamtaro - Ham-Ham Heartbreak (USA) 2020-12-30 15 35 04](https://user-images.githubusercontent.com/31973588/103383132-398dd880-4ab7-11eb-93d3-6adae863cb6b.png)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by nattthebear** [comment]
Does this happen in standalone mgba?

**Comment by noddy360** [comment]
> Does this happen in standalone mgba?

It doesn't happen in 0.8.3.
But I haven't tested 0.8.4 yet.

**Comment by endrift** [comment]
Known regression in upstream.

This game is known to be very fragile and it just breaks here sometimes.

**Comment by YoshiRulz** [comment]
Please try again on 8cc5488de (or 2.6.2 which is coming soon).

**Comment by endrift** [comment]
This wasn't fixed upstream.

**Comment by noddy360** [comment]
Issue still persists in 2.6.3.

**Comment by noddy360** [comment]
Issue still persists in 2.7.0 and 5e3e65a2

**Comment by YoshiRulz** [comment]
Fix "delayed until 0.10.0" (https://github.com/mgba-emu/mgba/issues/2131#issuecomment-980455074), not that we've pulled 0.9.3 yet.

**Comment by CasualPokePlayer** [comment]
Fixed in upstream master, might be time to pull in as we're nearing 2.8 release.

**Comment by endrift** [comment]
You acted quickly.

But yes a pull soon is a good idea. A lot of things have changed.

**Comment by noddy360** [comment]
Issue still persists in bizhawk 2.8

**Comment by CasualPokePlayer** [comment]
BizHawk didn't pull.

**Comment by endrift** [comment]
...why didn't they pull?

**Comment by YoshiRulz** [comment]
They forgot, and by they I mean me. Sorry.

**Comment by vadosnaprimer** [comment]
Please test again on latest dev build.

**Comment by noddy360** [comment]
Issue is now fixed in f8a688d47
