### ISSUE TITLE
Waterbox:  Improve handling of reentrant guest calls

### ISSUE THREAD

**Issue by nattthebear** [TASEmulators/BizHawk#2585]
"Guest calls" is when code inside the waterbox is actually running; the emulation core itself.

"Reentrant guest calls" is when you are in host code (not guest code), that was _called back_ from guest code, for instance, a memory callback system, and you try to call more guest code.  An example would be having an input poll callback, and then trying to peek a system bus value while inside that callback, assuming peeking the system bus actually runs guest code.

As of 2.5.0, these all crash the emulator horribly with no possibility of recovery, and honestly not much possibility of debuggability:  I was faced with one of these crashes recently.  I knew what would happen on a reentrant call, but did not know that I was looking at a reentrant call, and I could not find out based on stacks, because everything was screwed++.

Bare minimum fix:  Kill the emulator with some more useful error message on a reentrant call attempt.
Better fix:  Support reentrant calls.  Usual caveat that the core probably doesn't support what you're trying to do with it, but in basic cases of reentrantly calling some memory domain access function, it may work out OK.

**Comment by nattthebear** [comment]
Here's an example crash case:

```lua
-- This script is for genesis.  It will crash the emulator horridly whenever
-- advancing through any non-lag frame (ie, oninputpoll is actually called).

-- If "M68K BUS" is replaced by "VRAM", then this will not crash.  This is because VRAM domain
-- reads do not require executing code in the waterbox, but M68K BUS reads do.

function handle_input_poll()
	local val = memory.readbyte(0, "M68K BUS")
	console.log("InputPoll happened and we read the value: ", val)
end
event.oninputpoll(handle_input_poll)
```

This exact script is obviously super contrived, but is reading a domain in a callback like this something we think "should" work?

**Comment by vadosnaprimer** [comment]
<natt> feos:  Does my demo script work in 2.4.2?

Yes. And dies since 2.5.

**Comment by nattthebear** [comment]
Besides things that you can trigger in lua, this also affects the GPGX tracelogger (and possibly some other traceloggers?) which work by using memory callbacks plus state queries inside the memory callback.
