### ISSUE TITLE
Unable to fully display two .lua scripts at the same time in 2.6

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#2600]
![1](https://user-images.githubusercontent.com/47687575/106359425-08513400-6313-11eb-8590-0f99a1774535.png)
![2](https://user-images.githubusercontent.com/47687575/106359428-0a1af780-6313-11eb-9503-7c121c28c2bf.png)

As shown in the screenshots, in 2.6 it seems i cant run these .lua scripts togheter: whichever i open first will show on screen. So as it is now i have to enable and disable each

No errors on the console, and it looks like part of 1 script, at least some text, shows up: it kinda looks like one overrides the other one, following a layer logic. Same windows sizes, it works without issues till 2.5.2

I'll also leave the lua scripts linked, just in case, idk if it might be useful

Game: CTR NTSC-U (PSX)
Lua Scripts: https://mega.nz/folder/r4lihSzA#u3C3sxXbE8hFsMJOrwgLOQ

**Comment by YoshiRulz** [comment]
I haven't tried, but looking at the code I think there's a simple fix for this. Is the old behaviour (drawing on the same surface, overwriting pixels) something we want to allow?

**Comment by YoshiRulz** [comment]
I think I accidentally fixed this with 8c8d7eab3, please test

**Comment by CasualPokePlayer** [comment]
This should be fixed in the latest dev build.
