### ISSUE TITLE
OSD not affected by system UI scale

### ISSUE THREAD

**Issue by ScHlAuChii** [TASEmulators/BizHawk#2605]
### Summary
Bizhawk messages are tiny on a 4K display to a point where its unreadable

### Repro
Run Bizhawk on a 4K display

### Host env.
Modern highend PC with a 5950X and a 3090 combined with a LG UltraGear 27GN950-B 4K monitor

![BH](https://user-images.githubusercontent.com/12144392/106646391-faf3ae00-658d-11eb-864f-bd8e512fb735.png)

see also #1930

**Comment by ScHlAuChii** [comment]
No Ok / Cancel buttons
![Movie](https://user-images.githubusercontent.com/12144392/205995431-17f667b2-4e5c-494f-ac19-ca9cd323c28c.png)

**Comment by YoshiRulz** [comment]
The Record Movie dialog and keybind dialogs were also broken under Mono. I manually fixed the Record Movie dialog (https://github.com/TASEmulators/BizHawk/commit/d32f7344ae52248defb3c94a5524c183047a35ee), but I guess they're just designed incorrectly?

**Comment by ScHlAuChii** [comment]
The casue of all this, is when the Windows Scaling factor is set to anything other than 100%.

![Display-Scale](https://user-images.githubusercontent.com/12144392/205999277-62aa599d-1386-4951-8a68-4244a7fa2fa7.png)
