### ISSUE TITLE
No Audio during FMV: PSX Blue's Clues - Blue's Big Musical

### ISSUE THREAD

**Issue by Meerkov** [TASEmulators/BizHawk#2639]
### Summary
The FMVs in Blue's Clues - Blue's Big Musical have no audio

### Repro
1. Start Blue's Clues the Big Musical
2. The FMV before the main menu has no audio.
3. After starting a new game, the FMV also has no audio.

### Host env.
- BizHawk 2.5.2; Win10

**Comment by zeromus** [comment]
test in mednafen

**Comment by Spikestuff** [comment]
upstream issue.

**Comment by Meerkov** [comment]
FWIW, does not reproduce in ePSXe.

**Comment by Spikestuff** [comment]
That's not worth anything considering that ePSXe is a closed source emulator, that is also heavily dependent on plugin usage and is also extremely out of date and is a hackjob in terms of accuracy.

"But it's the highest % in accuracy" cause it cheated the results.
ePSXe should be forgotten in a ditch for all that care about it these days.
