### ISSUE TITLE
 [Octoshock] neGcon controller is displaying lag frames when there shouldn't be any.

### ISSUE THREAD

**Issue by Spikestuff** [TASEmulators/BizHawk#2663]
(God if you can title that better, do it ause that's just a string of filth).

When selecting the neGcon controller, a poll of just lag when viewing with Frame Counter or using TAStudio to TAS with it.
Games used that have neGcon support: [Wipeout XL](https://youtu.be/_99zTjgx1Zo) & Ridge Racer.
Using 2.6.1, issue has been present since support was added for the controller (1.12.2) just that no one checked it.

Controller verification:
![image](https://user-images.githubusercontent.com/12412764/111055667-8a18ad80-84cc-11eb-83ad-f2f5f19a0509.png)

Wipeout XL (in menus, showing controller does respond):
![image](https://user-images.githubusercontent.com/12412764/111055678-a87ea900-84cc-11eb-98b8-2f371fd20896.png)

Ridge Racer (in menus, showing controller does respond):
![image](https://user-images.githubusercontent.com/12412764/111055972-53906200-84cf-11eb-9889-7d780666d48e.png)

**Comment by YoshiRulz** [comment]
Does this also affect Nymashock?

**Comment by Spikestuff** [comment]
No it doesn't. But simply saying "just use Nymashock" when an option is available in Octoshock isn't a solution.
Especially when in comparison by let's saying using the GunCon that has issues on Nymashock with aiming for instance.
(This is apparently a Nyma issue as this issue persists with Saturn as well)

**Comment by YoshiRulz** [comment]
Nymashock's light guns should be working properly in dev builds. Closing as #wontfix.
