### ISSUE TITLE
Lua socket communication truncates byte string on null byte

### ISSUE THREAD

**Issue by fusoyeahhh** [TASEmulators/BizHawk#2671]
### Summary

When using `comm.socketServerResponse` in lua, the retrieved byte string can be shorter than what is sent. Truncation seems to be reproducible when sending byte strings with `\0` in the non-final position. That byte and anything after it is truncated on the lua side. It's possible that the send counterpart `comm.socketServerSend` might exhibit the same behavior.

No ROM or core needs to be loaded, since this is all through the lua console.

### Repro

This is somewhat difficult to reproduce without an ability to send bytes from a remote (relative to the emulator) client. That said, if you have this ability:

- Start up the emulator with the port and ip arguments to ensure the socket is connected
- Open the lua console
- Send a byte string with a null character embedded within it to the correct ip/port, e.g. `test\0test`
- Call `comm.socketServerResponse()` from the console

You should find that the response is truncated and looks like `test`.

### Host env.

- BizHawk 2.6; Win10

**Comment by fusoyeahhh** [comment]
Though I'm dubious, this could be related to #2194 . If so, it might be fixed by fafa29a.

**Comment by zeromus** [comment]
you're right. the string receiving is dumb.
can you test buildbot builds? if so, I'm gonna try to fix it blind.

**Comment by YoshiRulz** [comment]
Isn't this a shortcoming of Lua, that it uses null-terminated strings like C? I don't think we can simply patch that.

**Comment by zeromus** [comment]
we should accumulate bytes until the datagram is done and then decode it with the firmly-known length in **one** GetString() call. That can handle embedded nulls. It should be really easy to do, once the test is setup. That's why I was "setting up the test" here

**Comment by fusoyeahhh** [comment]
If by the build bot builds, you mean the artifacts that appear [here](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts), then yes, I should be able to test them. Thanks for looking into it!

@YoshiRulz : It probably does under the hood, but I think one can make strings in the lua console with null bytes. For instance, I think this should work:

```lua
string.char(1) .. "test" .. string.char(0) .. "test" .. string.char(2)
```

Which should construct a string with 11 characters, with "test" appearing twice, null in the middle and flanked by two non-printing characters. C-style strings don't necessarily disallow the use of null characters in strings, they just make them difficult work with reliably in C, so any language which uses it as a substrate usually works around it.

**Comment by fusoyeahhh** [comment]
Sorry for the delay. Unfortunately, the bad news is that the receiver end in Lua no longer seems to receive bytes. That is, me pinging or sending any information from my side to the Lua side of the pipe (`comm.socketServerResponse`) returns no bytes. I tested [this version](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/38332882/artifacts) of the build. I checked to make sure that my connection was still okay by running the same ping through 2.6.1, and the bytes were received there. Let me know if there are further debugging steps or information you might need from me to help diagnose.

**Comment by zeromus** [comment]
ok, this is much worse than I thought. You can't just send an unformatted string over TCP. Some negotiation of how long it is, is required. I think Original committer's idea was to set a timeout of 5 to indicate that "the string's length is as many bytes as you get until you don't get anything else for 5ms". This is obviously absurd. 

The choice of how to format the string is kind of arbitrary but since the original intent was to send an unformatted string, I think (which is impossible) I decided to keep the format plaintext and design it so that you first send the length (in bytes) of the message as text, followed by space to terminate it, and then that many bytes.

However, I recognize this change of protocol may break many applications. I am ambivalent about that, but I'm not sure how easy it is to actually effect this protocol in lua. We should make sure the protocol can actually send and receive both ways in lua without it being impossible.

check b1602dae06c6f7446f2d9ca3e6b81860638aaca5 and see if it helps; but remember you will have to change your send protocol.

If this is awkward to work with in lua, then the only plan B I offer is to revise the specifications so that it sends a null-terminated string which MUST NOT contain nulls, and order you to use socketServerSendBytes() instead

**Comment by fusoyeahhh** [comment]
I'll check the new commit tonight, but for the record, if `SendBytes` and `ReceiveBytes` are available, that's all I need. I'm of the general opinion that this is all anyone should need, since sending "strings" implies an encoding, which the C# layer now implies on its own, and may not be what the receiver expects. Those issues are irrelevant with a byte string implementation. The general development theme in Lua seems to be "do it yourself", so encoding things and/or implementing protocol before they arrive in Lua may be counter to this anyway.

I *think* this aligns with your "trivial protocol" proposal with one exception. The socket implementation I'm working with implements [recv](https://man7.org/linux/man-pages/man2/recv.2.html), in [python](https://docs.python.org/3/library/socket.html). Those implementations require, at least, a specification of the length of the expected payload in bytes, though the actual payload may be shorter. So, I think the one disagreement we have with a send/receive bytes protocol is that blocking until the exact amount of bytes are received is not necessary, only anything up to the number of requested bytes is returned from the call, and returning zero bytes is allowed. The latter condition is important in tight loops, since otherwise we might end up blocking.

It is possible, however, that I have misunderstood something about TCP communication or some magic that's happening behind the scenes in python. Since you have access to a queue in the layer doing the actual work (e.g. in the C# layer), then buffering up received bytes hides blocking semantics from Lua, which I think is a positive. This is because Lua is 99.9% of the time being run *in* the emulator loop, so blocking invariably will lead to "lock ups" of the emulation process itself. While Lua adherents might look forward to writing a queue implementation in Lua, I am less enthusiastic, and would be thrilled to have that handled for me.

All of that said, these are only suggestions / ramblings, as I don't have the requisite experience to actual help develop this on the C# side (it's been years since I've written any C# code) and I definitely am not qualified to change the Lua interface. As long as there is a working implementation which can send and receive the full set of integers between 0-255, I'm satisfied. Bonus points for as little blocking on the Lua side as possible. Thanks again for the hacking.

**Comment by zeromus** [comment]
My choice to block until the given number is sent or received was arbitrary. That's the way I would prefer it, if I was making lua scripts. But the distinction between blocking and non-blocking is a classic one. But there are many cases where you would want the emulator to run until it receives something, and in that case you need the non-blocking version. So actually I think we should add both. It's not clear if SendBytes or ReceiveBytes are blocking or nonblocking so we should revise the API so the user has to decide. But if someone who's doing this work decides not to revise the API, I think SendBytes and ReceiveBytes should be blocking versions. From the POV of a casual user, a function that sometimes doesn't do what you tell it to do (as the nonblocking versions do) are not great at all.

**Comment by YoshiRulz** [comment]
Would your efforts be better spent on WebSockets? I believe the current impl. is blocking (it takes a timeout param), but the .NET API we're calling is async so a non-blocking option may be possible.

**Comment by zeromus** [comment]
No, we're not doing this with async. it either blocks or it doesnt. if it doesnt block, it returns the number of bytes read or written.

**Comment by fusoyeahhh** [comment]
Okay, so report on b1602 .

The socket server connects, and through the lua console I'm able to send bytes to the python receiver. As anticipated, I got three bytes on the python side, with the first corresponding to the length (1), a space, and the byte sent itself.

If I send the same back to the console, it's able to read the bytes with `comm.socketServerResponse`.

However, an attempt to load the lua script which is running the emulator loop and listening on the socket now causes the entire program to hang. I suppose this could be a glitch in the blocking logic, but I suspect something more serious, as sending bytes from python to the emulator doesn't seem to produce any output (I'd expect to see a printed response in the console from receiving bytes with the correct protocol even if `comm.socketServerResponse` blocked). Both the console and emulator window lock up and have to be hard killed.

**Comment by zeromus** [comment]
I'm sorry, I don't understand. Did you mean an attempt to UNLOAD the lua script? I don't think I care to guarantee what happens if you try to unload a script that's in a blocked socket read. but the basic functionality i checked myself.i sent messages and printed them. here's 100% of my test script
`print(comm.socketServerResponse())`

**Comment by fusoyeahhh** [comment]
No, I do mean loading the Lua script. E.g. through `Open Script` under the lua console. The choice is confirmed, the script shows up in the list, and then the entire program hangs and becomes unresponsive. You can find it [here](https://github.com/fusoyeahhh/BCFantasy/blob/game_dev/BCBridge.lua), but an extremely boiled down version looks like:

```lua
-- init a few variables here


-- main loop
while true do
    resp = comm.socketServerResponse()
    -- Do stuff including processing resp
     
     emu.frameadvance()
end
```

Perhaps I've misunderstood the impact of the recent changes?

**Comment by zeromus** [comment]
your script says to hang waiting for a message from the server. you will have to keep it continually fed with data in order for the user interface to work. if you want the script to just sit there, you can't do it this way. you would have to create a thread and receive commands that way or have me add the nonblocking IO commands. I know, you expect the GUI to work while your script is waiting for data. That's not how bizhawk works. The script is in control of the emulator, and you told it to hang.

**Comment by fusoyeahhh** [comment]
Okay, sounds like I need to investigate moving the socket reading to a coroutine.

**Comment by zeromus** [comment]
A coroutine doesnt run two things at once. You want the bizhawk gui and the socket blocking process to run at once. It won't work. you need a _thread_. Dunno if you can make a thread from lua via the bizhawk apis, someone else will have to chime in.

**Comment by fusoyeahhh** [comment]
Lua would seem to want to [conflate](https://www.lua.org/pil/9.1.html) the two concepts. That said it looks like lua has no concept of actual threading, so this approach is dead in the water.

**Comment by fusoyeahhh** [comment]
In any case, that isn't relevant to the current bug report, which I think is now resolved. Thanks for your help.

**Comment by zeromus** [comment]
Open a new bug for the async socket functions. someone else can do the lua setup and then ill evaluate the network code if needed. You're not going to be able to do what you want in lua without that (you could do it by c# extensions in bizhawk also)

**Comment by fusoyeahhh** [comment]
Will do.

**Comment by fusoyeahhh** [comment]
Just out of curiosity, is there a dev guide for the C# extension route?

**Comment by zeromus** [comment]
ExternalToolProjects examples

**Comment by YoshiRulz** [comment]
[ext. tool wiki](https://github.com/TASVideos/BizHawk-ExternalTools/wiki/Development-quickstart)

**Comment by fusoyeahhh** [comment]
Thanks!
