### ISSUE TITLE
Inaccurate Atari 2600 sound emulation

### ISSUE THREAD

**Issue by tildearrow** [TASEmulators/BizHawk#2676]
### Summary
Atari 2600 sound emulation still remains slightly inaccurate when compared to console.

### Repro
1. Load a ROM that sets AUDC0 or AUDC1 to `2`.
2. Compare with console.

### Output
Atari2600Hawk outputs audio color 2 in a slightly higher pitch than console.

### Host env.
- BizHawk 2.6.0; Arch Linux; Intel/AMD

**Comment by alyosha-tas** [comment]
Ms Pac Man also has audio issues on he level start music (high pitched tones that shouldn't be there.)

**Comment by tildearrow** [comment]
> Ms Pac Man also has audio issues on he level start music (high pitched tones that shouldn't be there.)

Pretty sure this is a different issue tho (maybe related to poor resampling algorithm).

**Comment by alyosha-tas** [comment]
> 
> 
> > Ms Pac Man also has audio issues on he level start music (high pitched tones that shouldn't be there.)
> 
> Pretty sure this is a different issue though (maybe related to poor resampling algorithm).

I just grouped them together since they are both audio issues, and i will (hopefully) fix them both at the same time. (I haven't actually managed to find the source of the problem yet though.)

**Comment by alyosha-tas** [comment]
Ms. PacMan purposely set audio to too high a frequency and expected silence as a result, so I made a test for this case.

@tildearrow can you provide a specific example of a game that uses AUDC = 2 that is very obvisouly wrong?

**Comment by tildearrow** [comment]
> Ms. PacMan purposely set audio to too high a frequency and expected silence as a result, so I made a test for this case.

Yup, resampling issue.

> @tildearrow can you provide a specific example of a game that uses AUDC = 2 that is very obvisouly wrong?

Dodge' Em. Sets AUDC to 2 for the engine sound. Plays F#1 on console, but G-1 on BizHawk.

**Comment by alyosha-tas** [comment]
Ok this is fixed now, this was actually a very simple bug that went unnoticed for a long time.
