### ISSUE TITLE
Waterbox breaks in debug mode with too many args

### ISSUE THREAD

**Issue by nattthebear** [TASEmulators/BizHawk#2735]
### Repro
1. Rebuild waterboxhost (the rust code) in debug mode.
  a. We always ship the release mode binary.
2. Create a function to call in a waterbox core that takes 5 or 6 args.
  a. At present, all actual waterbox cores have 4 or fewer args on all of these functions.
3. Call the function

### Output
CRASH.  `rax` was stomped over by the rust code in `depart5` / `depart6` before it could call it.

### Host env.
Windows only.

Want to fix this, can't think of an easy way right now so I'm dumping it here.

**Comment by CasualPokePlayer** [comment]
Perhaps the best way to fix this is to simply write asm in the C# side of the calling convention adapter, and scrap the Rust code doing calling convention adapting. Should be easy enough to just more or less copy paste the asm produced by rust in release mode in this case (probably don't need to differ here for debug mode?). The asm seems rather simple anyways: https://godbolt.org/z/aPhfPrP18

**Comment by nattthebear** [comment]
That's how it used to work.  The reason why I don't use pure ASM for these functions anymore is unwinding, see the writeup in https://github.com/TASEmulators/BizHawk/pull/2519

**Comment by CasualPokePlayer** [comment]
Shouldn't just directly using what rust does be sufficient (and be functionally identical?). Or does being in that specific location in the host's dll space matter?

**Comment by nattthebear** [comment]
In order for it to work in Windows, it either needs to be compiled as a regular dll and loaded by regular Windows dll loading, or we need to call `RtlAddFunctionTable` (which is also demonstrated in that PR).

So yes, there are many ways to go about this.  We could break out this code into a separate C, C++, or Rust dll that we always compiled with the needed optimize flags.  We could hand write assembly, hand write the unwind tables, and compile that into a dll.

**Comment by CasualPokePlayer** [comment]
I see. Some stuff needs to be registered with the kernel for this to properly work.

Perhaps just separating this into a new dll is the best solution, it really doesn't need to be in waterboxhost. Although perhaps there is some potential risk with some new hip compiler update deciding to trash rax as some optimization, which case maybe having inline assembly in the dll would be best (copying what we know works).

**Comment by nattthebear** [comment]
The thing I don't like about that is that it relies on the same sort of assumption:  The thunking code emitted by rustc won't touch xmm4 because there's no need to.  This is generally true in the current rustc, but it could easily change in the future.

With optimizations on, any valid register seems to work; as once you've said that you're going to use a reg with `asm!("", out("...") fp);`, the optimizer avoids reusing that register even where it would be legal because it would be an extra move step for it, as eventually it needs to get its junk out of that register.  But with optimizations off it seems too fragile.

Hand written asm directly to dll seems to be the best so long as someone can figure out all of the specifics of the unwind tables.
