### ISSUE TITLE
Using the MelonDs core

### ISSUE THREAD

**Issue by 1Codealot** [TASEmulators/BizHawk#2736]
Sometimes when loading a track (for mkds) it doesnt load whatsoever.

Another issue is that trying to use cheat codes, these do not work either.

**Comment by Spikestuff** [comment]
Now, I was going to say if you're using devbuild to make sure you have the bios.
Then I decided to check current version which I personally doesn't have the bios files for DS in that version.
I'm unable to replicated the "tracks don't load" issue with the USA version.

**Comment by 1Codealot** [comment]
I think what is going wrong is that my laptop is VERY bad.
