### ISSUE TITLE
"Record from Now" completely breaks movies on PSX and it carries over even switching ROMs (Repro)

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#2758]
### Summary
[//]: # 
Using the feature "Record from now" somehow breaks PSX games. Its easy to trigger when a cutscene/speech is loading, but as shown in the second game, it also happens in the main areas, just disabling music and keeping sfx for some reason.

In the second youtube video linked at the bottom of this message, it also caused the second rom i loaded to load the savestate with this issue, without needing to use the "record from now" feature once again. The game **Crashed** shortly after. Completely.

- Rom's Hashes taken from the bizhawk "hash disc" window
- Rom HASH 1: (CTR - NTSC- U) : 9A742438 CTR-NTSC-U.cue
- Rom HASH 2: (Bugs Bunny Lost in Time NTSC-U) : 54B8F5A3 BBLIT_USA.cue
- No running lua scripts

### Repro

1. Load any psx game (i tested this bug only on these two)
2. Get to an area where a cutscene is playing, or, as in the second rom, any point in the game.
3. Start the "Record from Now" feature

Following these steps always corrupts these games. 
It also occurred to me that this seems to be somehow connected to the movie being prone to desync. Apparently it's happening practically ALL the time on the second rom. The desyncs i get on Rom1 (CTR) seemed somewhat less frequent, and it so happens i rarely TASed that game using analog. Desyncs happened mostly after loading screens or when doing extremely precise manouvers with tasing manually analog inputs from my experience.
The way the desyncs happens are VERY similar to what happens in TAStudio aswell when tasing a game from BOOT, either after loading screens or when doing precise movement with analog and going back with savestates quite a few times when manually tasing. It's much less frequent (at least it seems) when the movie starts on boot, but its still there.

Also as shown at the end of the video, when using the turbo throttle mode.... the lag frames are somehow more than the total amount of frames since boot. Not sure what's going on with that.
Since i dont know if this turbo throttle aswell thing is connected to this issue, im not going to open a different thread 

### Host env.
- Tested on 2 machines, all running windows 10 21H1
- Tested on bizhawk 2.6.2 and 2.3.2, issue seem present in both, with the correct prereqisites installed

I will update this post with videos and screenshots of the issues, if i will encounter more specific bugs.
Feel free to ask for infos or tests in order to help. Thanks!

Recorded repro of the issue # 1: https://www.youtube.com/watch?v=5_xHA_WWkjY
Recorded repro of the issue # 2: https://www.youtube.com/watch?v=5vCxFYhvseE

**Comment by zeromus** [comment]
in CTR in the first video, I am not sure why you get to the character and then load a state again. Did you wait too long to do your experiment? And next time you did it earlier in his speech, and then noted the speech got cut off--without ever loading a state but merely by starting the movie recording?

**Comment by zeromus** [comment]
So in this last newest scenario, you're saying you didn't do anything with savestates, or anything special at all really, until the mask begins to speak, and then you 'record from now' and suddenly the mask breaks?

**Comment by AleMastroianni** [comment]
Correct, here's the video, i also removed savestates before reopening bizhawk: https://www.youtube.com/watch?v=_3pcjcfie54

**Comment by nattthebear** [comment]
That exact stack trace is simply running out of memory when trying to initialize a tasstudio state manager.

**Comment by AleMastroianni** [comment]
Yea i guess the last issue is unrelated to the "record from now" thing, same for the exponential increase in lag frames over total frames with turbo throttle. Feel free to split them into separate issues if thats the case and they do contribuite to instability

**Comment by nattthebear** [comment]
It looks like `BizHawk.Client.EmuHawk.PlayMovie.ScanFiles()` is loading up every movie file in a folder, creating full tasstate managers and buffers for each.  This is pretty certain to cause OOMs; anyone know what's going on there?

**Comment by zeromus** [comment]
It's supposed to load the movies, but do it through some abbreviated method. That kind of thing tends to break as people forget this use case and add more power to the movie objects. Maybe some OpenForEditing, OpenForPlaying, OpenForMetadata methods are needed

**Comment by TizianoMattei** [comment]
The issue triggers specifically with .XA audio files on PSX. Using "record from now" whenever one of these audio files is called softlocks any game; im not sure this can also affect TAStudio automatically creating savestates during these time frames and also bringing desyncs on .tasproj that start from boot

**Comment by TizianoMattei** [comment]
The "record from now" issue is completely absent using the Nymashock core. Also no .xa audio being interrupted using the feature, nor any other bug. Thanks for the new core!
