### ISSUE TITLE
Add 64DD Emulation Support

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#2770]
The upstream at http://emulation.gametechwiki.com/index.php/Nintendo_64_emulators says that 64DD is now emulated by Mupen64Plus, but BizHawk doesn't even care about it at all, and we get this instead:
![image](https://user-images.githubusercontent.com/39802077/120515316-7c3d3f00-c3ce-11eb-8000-252616e95289.png)

**Comment by YoshiRulz** [comment]
Blocked by #1718.

**Comment by vadosnaprimer** [comment]
> BizHawk doesn't even care about it at all

Citation needed.
