### ISSUE TITLE
Bizhawk interpret all frames as Lag Frames when there are 4 controllers enabled (PSX)

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#2778]
### Summary
I've started a number of tases with multitap enabled, (4 dual-analog controllers on port 1), and a memcard on slot1.
Both during normal gameplay and during TAStudio use all the frames are shown as lag frames.

TAStudio also mixes up what inputs to show/not show when prompted to do so on the setting of tastudio itself. 

### Repro
1. Open bizhawk
2. Open a psx rom
3. Open PSX-->Controller/Memcard Settings
4. Set 1 multitap on port 1, all 4 as dual analog controllers, and 1 memcard on port1
5. Open tastudio, start a tas from boot
6. All the frames will be shown as lag frames during gameplay

![image](https://user-images.githubusercontent.com/47687575/120918004-77200e80-c6b2-11eb-8cbd-f38934fdccf9.png)

Edit: tested on 2.6.2 and 2.6.1, forgot to mention that

**Comment by TizianoMattei** [comment]
This issue happens when there is multitap enabled on port 1. Multitap enabled on port 2 works, with all kinds of controllers.

**Comment by TizianoMattei** [comment]
This issue is gone aswell using Nymashock!
