### ISSUE TITLE
BizHawk Corrupts when loading a game from Libretro Core Again (Regression from #2176)

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#2786]
### Summary
BizHawk [corrupts](https://github.com/TASVideos/BizHawk/issues/2766) after loading from a Libretro core [again](https://github.com/TASVideos/BizHawk/issues/2176). This time this only happens when we load a core that makes WinForms windows pop up, for example, Genesis Plus GX Debugger Core. This bug only happens under specific circumstances within the ROM, like TiTAN Overdrive 2. This doesn't seem to happen in older versions like 2.4.2, as they can handle this just fine.
### Repro

1. Load any ROM that has similar circumstances as TiTAN Overdrive 2 using Genesis Plus GX Debugger core
2. BizHawk will throw an exception and corrupts in the similar way as #2766. This time we see that BizHawk believes that we are using NullHawk, which is even crazier.
### Output

```
System.ArgumentNullException: Wartość nie może być zerowa.
Nazwa parametru: source
   w System.Runtime.InteropServices.Marshal.CopyToManaged(IntPtr source, Object destination, Int32 startIndex, Int32 length)
   w BizHawk.Emulation.Cores.Libretro.LibretroCore.CloneSaveRam()
   w BizHawk.Client.EmuHawk.MainForm.LoadSaveRam()
   w BizHawk.Client.EmuHawk.MainForm.LoadRomInternal(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   w BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   w BizHawk.Client.EmuHawk.MainForm.LoadRomFromRecent(String rom)
   w System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   w System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   w System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   w System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   w System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   w System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   w System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ToolStrip.WndProc(Message& m)
   w System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

![image](https://user-images.githubusercontent.com/39802077/120988871-3e9a3680-c77f-11eb-8f86-48d9bb6d3c81.png)

### Host env.

BizHawk 2.3.2 Win 10
BizHawk 2.6.1 Win 10
BizHawk 2.6.2 Win 10

**Comment by YoshiRulz** [comment]
Is this a regression from 2.3.2, 2.4.2 (I assume you meant bc0849ad9 by "regression from #2176"), or a more recent version?

**Comment by getCursorsExe** [comment]
Yes, this time we get a different error message, and this occurs no matter if Always use recent path for ROMs in Config -> Paths is enabled or not.

**Comment by CasualPokePlayer** [comment]
Does this still occur in 2.9 dev?
