### ISSUE TITLE
Generic Sync Settings Has DateTime Display Get Truncated

### ISSUE THREAD

**Issue by Real96** [TASEmulators/BizHawk#2796]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end.
Whenever my cat sits on the left side of my keyboard, games run too fast for me to react to."

Sync Settings shows only Date in RTC Initial Time row

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open any GBA game
2. GBA -> Settings
3. Sync Settings -> RTC Initial Time

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
![image](https://user-images.githubusercontent.com/20956021/121792227-93600600-cbf2-11eb-9f03-831f432f3aef.png)

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6.2 Win10 Pro, commit #7c17f31cd

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by shenef** [comment]
Time is displayed after being entered manually but it instantly disappears when set to 00:00
![image](https://user-images.githubusercontent.com/20268890/121856173-7e6b9b80-ccf4-11eb-93ad-fce7ca987a38.png)

**Comment by Real96** [comment]
Also, if seconds are set different from 0 they disappear anyway.

**Comment by nattthebear** [comment]
Are you seeing bad behavior in games or is this just a display truncation bug in the settings UI?

**Comment by Real96** [comment]
> Are you seeing bad behavior in games or is this just a display truncation bug in the settings UI?

Just a display truncation
