### ISSUE TITLE
Bottom overscan border is wrong color in first stage of Space Harrier SMS

### ISSUE THREAD

**Issue by emu-hopeless** [TASEmulators/BizHawk#2816]
The overscan border is often, if not always, the same color as the background, in this case green. MAME, BlastEm, and video captures from real systems suggest that the lower border is supposed to be green here, but in SMSHawk, it is blue.

![border](https://user-images.githubusercontent.com/86317528/123008878-5679d900-d381-11eb-9860-a08d45c22866.png)

Recordings from actual Master Systems showing the correct color:
https://youtube.com/watch?v=Teo1fQE_Gm4&t=34s
https://youtube.com/watch?v=Kl38a92bV08&t=38s

**Comment by alyosha-tas** [comment]
Migrated to #2998 , closing this one
