### ISSUE TITLE
BizHawk is missing libretro core settings, even though it is present in the core itself

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#2852]
I know that a libretro core has some settings in it, but BizHawk does not load them in any categories.
If this would be intended, then Libretro would be an useless feature.

**Comment by zeromus** [comment]
reopen as feature request: "add libretro core settings" and leave out the description of how useful you think libretro cores are until it's done

**Comment by YoshiRulz** [comment]
Moved to #2854.
