### ISSUE TITLE
Sega CD fails to boot with 2.00 BIOS

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#2913]
edit 2022-02: In https://github.com/TASEmulators/BizHawk/issues/3147#issue-1138937379 it was noted that MAME marks this revision as a bad dump.
```cpp
/* this is reportedly a bad dump, it has many differences from the verified dump and does not boot in Kega */
/* ROMX_LOAD( "segacd_model2_bios_2_00_u.bin", 0x000000,  0x020000, CRC(340b4be4) SHA1(bd3ee0c8ab732468748bf98953603ce772612704), ROM_BIOS(1) ) */
```
([source](https://github.com/mamedev/mame/blob/21be925eb4746d3d8e126006402429eeb142dd37/src/mame/drivers/megadriv.cpp#L990) because GitHub doesn't want to embed it)

---

This one:
https://github.com/TASEmulators/BizHawk/blob/2f344f8ffd6b202c8293901dd2e429dcf64b5874/src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs#L184
Compare:
![sonic_cd_-_sega_cd_MK-4407_(redump)_hawked 2021-08-21 11 25 12](https://user-images.githubusercontent.com/13409956/130306167-4fc67f4e-694d-4475-9184-59c829b43ffd.png)
![sonic_cd_-_sega_cd_MK-4407_(redump)_hawked 2021-08-21 11 24 42](https://user-images.githubusercontent.com/13409956/130306169-36876af1-ed3d-4744-af31-023045aac934.png)

Is it supposed to work out-of-the-box?

**Comment by boktai1000** [comment]
Anecdotally, I've also tried this same firmware in the emulator Ares which has the same crash on the planet screen as well.

```
Name: SCD_us_9303.bin
Size: 131072 bytes (128 KiB)
CRC32: 340B4BE4
CRC64: B3B4B6A0837137A9
SHA256: 2c5358fcd8f2df22e14179426be6e30b466fb4134b6a397725a32f95a0b895d3
SHA1: bd3ee0c8ab732468748bf98953603ce772612704
BLAKE2sp: 6fc6cc17fb24be6bdd4c7b65cba8c6a1edd12f50bfb5fc1399420ea25155df72
```


![image](https://user-images.githubusercontent.com/9054563/154200386-a3b22419-34ba-4525-b73f-00269d3ed61f.png)
