### ISSUE TITLE
corrupted save data in DS emulator

### ISSUE THREAD

**Issue by TheCrockSnail** [TASEmulators/BizHawk#2914]
### Summary
For some reason saving my progress in one of the gen 4 pokemon games causes an error message leading to my file being wiped. this does not happen with any of the other emulators on Bizhawk,  I have tried different builds of Bizhawk, and I have not tested this with other DS games.

**Comment by zeromus** [comment]
"an error message"

**Comment by TheCrockSnail** [comment]
an in game error message if you where asking for clarity

**Comment by zeromus** [comment]
assume I'm asking for clarity. What do you think is the next question I'm gonna ask?

**Comment by Spikestuff** [comment]
@TheCrockSnail You need to provide the error you're being given, just saying "an error message" is not useful to anyone.

**Comment by TheCrockSnail** [comment]
![Untitled](https://user-images.githubusercontent.com/89330743/130661596-92f2f6d4-d946-41bf-8161-0fd064db2bcf.png)
this one, it appears when push start on the title screen

**Comment by zeromus** [comment]
yes, this happens in pokemon. someone needs to check it in the melonds upstream version we forked. if not it's a bug in our melonds wrapper.

**Comment by CasualPokePlayer** [comment]
> 
> 
> ![Untitled](https://user-images.githubusercontent.com/89330743/130661596-92f2f6d4-d946-41bf-8161-0fd064db2bcf.png)
> this one, it appears when push start on the title screen

This is an issue with upstream. Only workaround there is its DSi emulation afaik which BizHawk's melonDS is way before that was added in upstream.

**Comment by getCursorsExe** [comment]
Yeah, upstream issue.

**Comment by CasualPokePlayer** [comment]
Looked into this issue more, and it's not really an "issue" with the core but just an issue with firmware being bad. And the DSi "workaround" I mentioned was just coincidental since I used DSi firmware (which wasn't bad, unlike my DS firmware which was bad).

**Comment by CasualPokePlayer** [comment]
Fake firmware has valid wifi data and does not cause this error. Calling this fixed.
