### ISSUE TITLE
Crash issue - exception code 0xe0434352

### ISSUE THREAD

**Issue by ArmyofWon** [TASEmulators/BizHawk#2920]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."

Playing Metroid Fusion, have GBA bios installed in firmware, game crashes periodically. Not sure what causes it, but Windows Event Viewer does have the same exception code and Fault offset. Exception 0xe0434352 and Fault offset 0x0000000000034ed9

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
Damn Schroedinger.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
No error dialog, full crash
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6.2; Win10 build 19043.1165; AMD 5800x/NVIDIA

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by zeromus** [comment]
try playing a different game on a different system for a while; also change config > display > display method

**Comment by YoshiRulz** [comment]
Any update on this? I feel like we'd have gotten more reports if mGBA was crashing.

**Comment by ArmyofWon** [comment]
Oh sorry, I didn’t see this. I figured out that it was crashing because of controller connection issues, and how I configured the global input (off focus/click off window). Whenever the controller wire disconnected mGBA crashed. I figured a fix for it, but it’s been a long while since I’ve used mGBA so I don’t remember exactly how I fixed it.

Thank you for your time!
