### ISSUE TITLE
[Libretro] PPSSPP black screen

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#2924]
At last, ppsspp is somewhat functional under libretro player. The only problem is that it doesn't output anything.

Here is the log(linux):

core name: PPSSPP version 7120a97
extensions: elf|iso|cso|prx|pbp
NeedsRomAsPath: True
NeedsArchives: False
SupportsNoGame: False
ThreadManager::Init(compute threads: 8, all: 12)
[IO] Missing filesystem for lang/.ini
[G3D] Longest display side: -1 pixels. Choosing scale 1
[IO] Missing filesystem for 'langregion.ini'
[LOADER] Failed to read /controls.ini. Setting controller config to default.
FPS 59.940055847168 SPS 44100
[IO] Couldn't read data for 'ppge_atlas.zim'
[SCEGE] Failed to load ppge_atlas.zim.

Place it in the directory "assets" under your PPSSPP directory.

PPGe stuff will not be drawn

Don't really know what I'm doing with the whole assets thing.

**Comment by InfamousKnight** [comment]
To anyone who wants to know, i did read the guide on bizhawk libretro page and I read the guide on retroarch for ppsspp but didn't get anywhere. It might be linux exclusive. I tried playing around with it as well. Renaming, deleting etc.

Has anyone tried it on windows? Remember to use latest build.

**Comment by kage2051** [comment]
It also happens on Windows. Tried switching backends but no luck.

**Comment by InfamousKnight** [comment]
Oh well. Even if it did work, whether or not it will movies will sync is another question.

**Comment by InfamousKnight** [comment]
Revisiting this issue with the libretro rewrite and still just a black screen. Everything else functions but the display.

This is one of the cores that requires asset files for display. 

Don't get too excited if this does eventually work. Desync issues can still happen.

**Comment by CasualPokePlayer** [comment]
The libretro rewrite wouldn't do anything. This is just another core which requires hardware renderers which BizHawk's libretro impl doesn't provide, nor will it likely do so any time soon.

**Comment by InfamousKnight** [comment]
I see. Would be cool to see how well this works. I have no clue how sync stable this will be.
