### ISSUE TITLE
Desert Strike crash

### ISSUE THREAD

**Issue by I-Megaman-I** [TASEmulators/BizHawk#2925]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # 

Campaign 3: Embassy City | code: ILLBWBY

8 mission (embassy rescue) crashes when you land

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.1.1 x64; July 23 2017

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Oh, this game was ported to a bunch of platforms. Which version were you using? You can click the checkmark in the status bar to get the exact details.

**Comment by Spikestuff** [comment]
The passcode seems to be matching the Genesis version.
I don't know the game or how it works so I'm unable to go into playing and creating a movie file.

**Comment by getCursorsExe** [comment]
> ### Host env.
> * BizHawk 2.1.1 x64; July 23 2017

Nope, that's outdated version of BizHawk. Please use latest version.

**Comment by I-Megaman-I** [comment]
> 
> 
> > * BizHawk 2.1.1 x64; July 23 2017
> 
> Nope, that's outdated version of BizHawk. Please use latest version.

Ive tested different versions, all the same. I dont remember encountering such thing on other emulators. It could be a game bug also. Nevermind, I bypassed it by destroying vehicles around the landing zone first:-)
