### ISSUE TITLE
Two mGBA core issues

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#2949]
BizHawk 2.6.3 stable
1. Seems **RTC Use Real Time** is useless even it turned on, at least in _Pokemon FireRed_ hacks.
2. In _Pokemon Saiph_, Pokemon summary screen will occur glitch in mGBA core of BizHawk.
![mGBAinBizHawk](https://user-images.githubusercontent.com/54294476/135700627-f4bf8a41-a079-4455-a840-399709c8631c.png)
But won't occur in mGBA itself (0.9.2 stable).
![mGBAitself](https://user-images.githubusercontent.com/54294476/135700650-6fa0e913-4a98-44bd-af7d-ce68c6135078.png)

**Comment by CasualPokePlayer** [comment]
This is likely just due to these hacks relying on VBA bugs (which VBA bug compatibility mode upstream enabled by default for Pokemon ROM Hacks, mostly due to spamming of reports like this where it's the ROM relying on VBA inaccuracies rather than mGBA being inaccurate). This VBA bug compatibility is probably just being implicitly disabled.

**Comment by Yave-Yu** [comment]
I see, so the second is not an issue.

**Comment by CasualPokePlayer** [comment]
> 
> 
> I see, so the second is not an issue.

The first is also likely due to relying on VBA bugs, as Pokemon FireRed hacks are known to use an incorrect method to interface with RTC which does not work on real hardware (due to the tool they all use for RTC support doing it wrong).

**Comment by CasualPokePlayer** [comment]
That's not even what I meant by this. It's just due to the game not using the GPIO (what's used to interface with RTC data) correctly. Here's an explanation from endrift:
> the "correct" way to do GPIO code is to set the directions of the pins you want to write to output, then write the whole byte, which will only "update" the output pins
this is oversimplifying greatly of course
the buggy [romhack] code just doesn't bother with the direction bits

**Comment by Yave-Yu** [comment]
Since these are not issue, I close.
