### ISSUE TITLE
Genplus-gx Debugger crashes in debug builds on 2.6.3

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#2958]
In 2.6.2, we could use Genplus-gx debugger, but in 2.6.3 it throws an exception instead of opening, then crashes in most cases.

**Comment by zeromus** [comment]
it's useless for me, too. Just open the debugger and set an execute breakpoint on some code it was literally just on. It'll crash. Breakpoints can't make it out of GPGX core, or waterbox generally right now. Can't boot up visual studio in debug mode either, waterbox will hang it.

**Comment by getCursorsExe** [comment]
I did not set en execute breakpoint, so I don't know.

**Comment by getCursorsExe** [comment]
Here's the result when I opened BizHawk in Visual Studio 2019:

![image](https://user-images.githubusercontent.com/39802077/136453707-599bce49-e7eb-427f-adbc-1ca929f70214.png)
