### ISSUE TITLE
TAStudio scroll behavior bug when Follow Cursor is enabled

### ISSUE THREAD

**Issue by Masterjun3** [TASEmulators/BizHawk#2965]
### Summary
When Follow Cursor is enabled and TAStudio doesn't have every frame saved, it needs to rewind upward to the closest frame and catch up from there. The problem here is that it also scrolls the screen so that unexpected behavior happens.

https://user-images.githubusercontent.com/22375320/137001318-fec58807-f29c-490b-967a-b9805cbe78e7.mp4

Even worse: This chains if you move your cursor upwards so that you keep drawing inputs until the beginning of the movie.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Enable Follow Cursor.
2. Find a frame where a rewind takes up you several frames.
3. Draw input and see the screen scroll up and your input with it.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6.3; Win10;

**Comment by Masterjun3** [comment]
Yeah it's fixed. Now it doesn't seek until I let go of the mouse button and so it doesn't do the unwanted scroll up.

**Comment by Morilli** [comment]
Regressed in bb226f694aa9a3e2322c03dbdeb07f93e0774204. Really tempted to just throw a revert on that...

**Comment by Morilli** [comment]
Un-unfixed in 319455c2ea791c90af16a99806dea816d980d455.
