### ISSUE TITLE
[SMS] Japan version of Ys - The Vanished Omens is graphically glitched

### ISSUE THREAD

**Issue by Sonia-7** [TASEmulators/BizHawk#2984]
Graphical glitches appear in the status screen at the bottom:

![Ys - The Vanished Omens (J)](https://user-images.githubusercontent.com/24638400/139350899-f6a49cbe-3e3a-452e-971b-43dafc4dfaca.png)

International version is fine:

![Ys - The Vanished Omens (UE)](https://user-images.githubusercontent.com/24638400/139350923-47b0691a-def5-4cbf-a689-7c559364de38.png)

**Comment by alyosha-tas** [comment]
Migrated to #2998 , closing this one.
