### ISSUE TITLE
(FDS) Kikikai-kai: Dotou Hen hangs on the boss' room

### ISSUE THREAD

**Issue by ReyVGM** [TASEmulators/BizHawk#2986]
I'm using the latest Bizhawk version (2.6.3-win-x64).
Windows 7 64 bit
Intel CPU

Kikikai-kai: Dotou Hen (known as Pocky & Rocky) for the FDS doesn't work correctly on any emulator, except the old NNNesterJ.

The only no-intro dump is labeled as (b), which means it's probably a bad dump. The GoodFDS version has no label. So, I don't know if this hang is a result of the game being a bad dump for the past 15 years, of if it's just not emulated correctly on any emulator.

This game has been reported as broken on pretty much every emulator github page, and it has never been fixed. Hopefully one of you guys can finally fix it for Bizhawk.

If you want to get to the part in question, just follow these steps:
From the start point, walk straight up. Don't attack with your cards because you need all 50 of them. Keep following the path north until you get the first chance to travel east (you'll cross a few bridges just before that point.) Head east as soon as you are able, and then take the very next path south. This will lead you to the entrance of a cave. You need 50 cards to enter the cave (you can earn Ofuda cards by defeating enemies with your wand). Once inside, the path to the boss never branches. You travel north, then east, and the north. At the top of the second north path is the boss room. The expected result (and the one which NNNesterJ produces) is that the room scrolls into view, turns blue, and a large boss starts to attack you. The actual result in the rest of the emulators I've tried is that they hang before the room turns blue, stuck playing one note.

Or just can use this save state. Just walk up and the game will hang.
https://www.sendspace.com/file/9xu0et

And here you can find all the research people have done on this bug for the past 11 (!) years:
http://archive.nes.science/nesdev-forums/f3/t6504.xhtml

**Comment by Sonia-7** [comment]
No Intro now has good dumps for all official FDS games, and I think it's thanks to that Gigaleak that happened recently. You'll have to do more research to find the good dumps. Anyway, I tested both current dumps of the game on BizHawk 2.6.3 and everything worked fine. It didn't hang and the boss loaded successfully.

Here are a couple save states to send you straight to the boss (just walk north):
[Boss States.zip](https://github.com/TASEmulators/BizHawk/files/7462883/Boss.States.zip)

**ROMs**
Kiki Kaikai - Dotou Hen (Japan)
SHA1:B7B98DBC286366C9B024D93AB77FD599AA6B9E00
MD5:395309F36C8C739318BB695F5A5FE37E

Kiki Kaikai - Dotou Hen (Japan) (Rev 1) (Disk Writer)
SHA1:72EECE33428159B71951573EFBD5AAB7F9490235
MD5:50C982AFDFE889FD33792539A5E90451

**Comment by ReyVGM** [comment]
Thanks for the info. I haven't updated my FDS collection in a while.

So yeah, it was actually a problem with the game being a bad dump all the way to the GoodFDS dump.

The game works fine as you mentioned. This issue can be closed now.
