### ISSUE TITLE
(FDS) Kinnikuman: Kinnikusei Oui Soudatsusen - Game restarts

### ISSUE THREAD

**Issue by ReyVGM** [TASEmulators/BizHawk#2987]
I'm using the latest Bizhawk version (2.6.3-win-x64).
Windows 7 64 bit
Intel CPU

On every single emulator I've tried (Bizhawk, FCEUX, Nestopia), after beating the boss of stage 1-4, the game goes back to stage 1-1. I've checked walkthrough videos (using real hardware) and the game loads 2-1 right away. I've also seen there are no apparent special requirements one must fulfill in a stage to prevent the game from sending you back to the beginning.

So I'm wondering if maybe this is an emulation problem? I do know No-Intro's ROM is labeled as "(b)" which I think means bad dump? I also tried GoodFDS's ROM (which has no label) and the same problem happened.

Here are two saves, one at the 1-4 boss and one after he dies:
https://www.sendspace.com/file/8egihc

So, can anyone verify if it's an emulator problem or a ROM problem?

**Comment by ReyVGM** [comment]
Update: I tried No-Intro's good dump of the game, and the same thing happens.

**Comment by alyosha-tas** [comment]
@ReyVGM  did you try Mesen with the good dump?

**Comment by ReyVGM** [comment]
Same thing happened. Normally I would think I'm just missing some objective and this is the way the game tells me that I need to find something, but judging from the 3 playthrough videos I've seen using real hardware, there doesn't seem to be anything special you need to do other than collect some trinket and beat the boss.

After beating the boss the game is supposed to go into a now loading screen to load the next stage, but it instead goes back to stage 1-1.

Isn't there some way for a more knowledgeable person to use a debugger or some other tool to see the emulator performing internal tasks at that specific moment? Maybe it can show an error there, if it's indeed an error.

**Comment by ReyVGM** [comment]
I used a level select cheat to jump to stage 2-1, went all the way to 2-4 and when I defeated the boss I was dumped back in 2-1 again instead of loading the next stage. There's definitely something going on here.

**Comment by alyosha-tas** [comment]
I don't think this is a bug, I'm pretty sure you simply aren't meeting the requirements to advance.

The level advances only when 0x0153 reaches 4. This address increments when you collect some shiny objects that enemies occasionally drop.

I played for a bit but only got to 2 objects, maybe they are very rare or only dropped once per section.

**Comment by ReyVGM** [comment]
You figured it out! I thought that it probably was a requirement issue, but the game is so unfair that it's easier to just avoid all the enemies, that's why I wasn't collecting the shinny orbs.

I just tried it and was able to finish the level. Thank you very much alyosha!

I guess this issue can be closed now :)
