### ISSUE TITLE
Nondeterminism in A7800Hawk

### ISSUE THREAD

**Issue by coolkirby2000** [TASEmulators/BizHawk#2988]
### Summary
While recording a movie file in A7800 Choplifter, changing your original input after a savestate can permanently change the outcome when you attempt to press the original input again.

### Repro
1. Play [this userfile](http://tasvideos.org/userfiles/info/74969493952058015) until frame 4151.
2. Once there, save a state.
3. Continue playback for another second to see the glitched reset that's supposed to happen.
4. Load the state in Read+Write mode and hold Up+Right for at least five frames. This is the original input, and the reset will still occur. You can repeat this if you like, it will continue to work.
5. Load state again and don't press anything for the same amount of time.
6. Repeat step 4. Although the same input is pressed, you do not get the same outcome (reset). You can try again and again, it won't work.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6.3; Win10 Pro 21H1; Intel/Intel

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by alyosha-tas** [comment]
I fixed several bugs probably related to this, please test the dev build

**Comment by alyosha-tas** [comment]
@coolkirby2000 re-open with a new movie if there is still a problem, closing for now.

**Comment by coolkirby2000** [comment]
Just got around to [resyncing my movie](http://tasvideos.org/userfiles/info/75476910579162108) on the [latest dev build](https://github.com/TASEmulators/BizHawk/commit/47c5fcc39e83f18ef88062f44b798d616e48f05e), and the repro steps still result in a loss of determinism. I need to re-open this issue. Please follow the repro steps and see if you get the same result.

Thank you for those other fixes and the explanation of the second controller issue. This fixes the title screen "bug" I mentioned on the forum earlier. Can I still use only one controller for submitted runs, or would it be better to leave controller 2 plugged in all the time?

**Comment by alyosha-tas** [comment]
Nothing happens for me after the movie ends, the helicopter just goes to the right a bit and lands.

Using one controller is fine on dev builds now. Probably want to avoid submitting runs from 2.6.3 with only one controller.

**Comment by alyosha-tas** [comment]
@coolkirby2000 Ok I'm pretty sure I fixed it this time, I can no longer recreate any desyncs, please try the dev build.

**Comment by coolkirby2000** [comment]
That did the trick! Thanks very much, Alyosha. Closing, fixed by 92c60385f4e94949dde681d40ce4245803899b7d.
