### ISSUE TITLE
[SGB] SGB1 firmware is listed under Gameboy section even though it's supposedly not used by the emulator

### ISSUE THREAD

**Issue by Fortranm** [TASEmulators/BizHawk#2991]
As the Gamebatte SGB core only uses the SGB2 firmware.

**Comment by YoshiRulz** [comment]
It doesn't hurt, plus if you happen to have just the SGB1 version then EmuHawk is able to patch it.

**Comment by CasualPokePlayer** [comment]
BSNESv115+ supports using it.
