### ISSUE TITLE
[SGB] Open ROM starts in the SNES folder when the SGB mode is running

### ISSUE THREAD

**Issue by Fortranm** [TASEmulators/BizHawk#2992]
This applies to all SGB cores

**Comment by getCursorsExe** [comment]
Well, this allows original GB and GBC to be loaded in SGB mode, crashing BizHawk with Savestate buffer size mismatch! message.

**Comment by CasualPokePlayer** [comment]
You would get different savestate sizes from GB/SGB vs GBC (which GB vs GBC was already a thing https://github.com/TASEmulators/BizHawk/issues/2090). GB and SGB should be the same savestate size, although you get screwed over by the SGB audio not being correctly initialized.

**Comment by YoshiRulz** [comment]
Savestate headers should be more like movie headers IMO.
