### ISSUE TITLE
[NDS] Touch input not working

### ISSUE THREAD

**Issue by medigi** [TASEmulators/BizHawk#2993]
Works fine on Bizhawk 2.6.3

Mouse clicking (touching the screen using mouse) doesn't give effect. Video is attached for easier reproduce (i clicked there on the はじめる button to begin a new game)

Affects last dev build with commit 946e088

https://user-images.githubusercontent.com/21311432/140451864-dd55e6b9-4d1a-40da-a0c5-efab94f2e367.mp4

**Comment by CasualPokePlayer** [comment]
Did you copy paste your config.

**Comment by medigi** [comment]
It looks like something went wrong. Just created new folder and copied last dev build, touching now worked

**Comment by CasualPokePlayer** [comment]
> 
> 
> It looks like something went wrong. Just created new folder and copied last dev build, touching now worked

So I am assuming that's a yes. Copying configs from 2.6.3 will unbind the Touch axises as they were re-named from TouchX/TouchY to Touch X/Touch Y.
