### ISSUE TITLE
Old BizHawk versions on the "Releases" page 

### ISSUE THREAD

**Issue by anewuser** [TASEmulators/BizHawk#2994]
People are unknowingly downloading old versions because they're being displayed at the top of the Releases page: https://github.com/TASEmulators/BizHawk/releases

**Comment by CasualPokePlayer** [comment]
This is just GitHub being dumb. We can't do anything about it besides a new release (which should happen soon anyways).

**Comment by zeromus** [comment]
I just marked them as prereleased, so latest is marked as latest automatically. hope that will help.
