### ISSUE TITLE
SMS / GG Graphics Issues

### ISSUE THREAD

**Issue by alyosha-tas** [TASEmulators/BizHawk#2998]
Hub Issue for remaining SMS / GG graphics issues

~~From Sonia7:~~

~~Japan version of Ys - The Vanished Omens~~

~~Graphical glitches appear in the status screen at the bottom:~~ Resolved with proper emulation of VDP masking bit on JPN consoles.

From emu-hopeless:

The overscan border is often, if not always, the same color as the background, in this case green. MAME, BlastEm, and video captures from real systems suggest that the lower border is supposed to be green here, but in SMSHawk, it is blue.

![border](https://user-images.githubusercontent.com/86317528/123008878-5679d900-d381-11eb-9860-a08d45c22866.png)

Recordings from actual Master Systems showing the correct color:
https://youtube.com/watch?v=Teo1fQE_Gm4&t=34s
https://youtube.com/watch?v=Kl38a92bV08&t=38s

~~From Ghost:~~

~~Fray: Shugyouhen (minor graphic glitches on the right side of the playfield)~~ resolved by using one less column of tiles when vert lcok enabled in GG mode

**Comment by Sonia-7** [comment]
About Ys, I loaded the game in BizHawk through the GenesisPlusGX libretro core and it works correctly there:

![Ys](https://user-images.githubusercontent.com/24638400/141604043-a26f718a-fd1b-44c6-98d5-1fd870e61122.png)

Maybe looking into what GenesisPlusGX does could give some idea on what needs to be fixed. Not sure how helpful that would be, it's just a thought.

**Comment by alyosha-tas** [comment]
Fixing Ys required emulating a VDP masking bit only applicable to older (presumably JPN) SMS consoles. more info under register 2 here: https://www.smspower.org/Development/VDPRegisters

That one is fixed now.

**Comment by alyosha-tas** [comment]
Space harrier is fixed. That's everything here, closing.
