### ISSUE TITLE
Gambatte: Last byte missing in HRAM Domain

### ISSUE THREAD

**Issue by alyosha-tas** [TASEmulators/BizHawk#3003]
As the titles says, loading up the HRAM domain in hex editor does not display the last byte.

**Comment by CasualPokePlayer** [comment]
Intended change, that's not HRAM, that's I/O.

**Comment by alyosha-tas** [comment]
Oh, ok makes sense.

**Comment by getCursorsExe** [comment]
The very last byte is actually the interrupt switch, which is why this is intended.
