### ISSUE TITLE
When load a ROM from Recent ROM, if a core rejects the file, BizHawk marks that file as "not found"

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3006]
For whatever reason if a core rejects the file that was opened in Recent ROM, BizHawk will then mark that file as not found, even though it still exists.

**Comment by InfamousKnight** [comment]
Anyway to reproduce? If it didn't reject it in first place then why is it rejecting a second time? I never had any issue with that

**Comment by YoshiRulz** [comment]
I could have sworn this as fixed already... maybe I'm confusing it w/ #2880.

> If it didn't reject it in first place then why is it rejecting a second time?

I think this will happen if you set up a core like GBHawk to use firmware, then change the firmware path to an empty folder.
