### ISSUE TITLE
Bk2InputDisplayGenerator.Generate() is too slow

### ISSUE THREAD

**Issue by Morilli** [TASEmulators/BizHawk#3011]
The [Generate()](https://github.com/TASEmulators/BizHawk/blob/34ec13635b914e1dd74e62b7e6e9f140a260c771/src/BizHawk.Client.Common/display/IInputDisplayGenerator.cs#L30) method of the `Bk2InputDisplayGenerator` class is called every frame and performs way too slowly for that. It iterates through all inputs and performs super slow C# operations to get a list of valid controls and displays them on screen if pressed (all this only happens if the `Display Input` option is checked, though).

I did a profile run on a snes game with rewind and throttling disabled over 50,000 frames using the `Payload` controller, which has ~35 virtual inputs and got a result of all `ControlsOrdered` calls combined (150k) taking around 19% of total running time, with the rest of the `Generate()` method taking another 11%. That is 30% of total running time spent in code that does nothing, because no buttons were pressed.

Caching at least the return of the `ControlsOrdered` function should provide a substantial speedup already.

**Comment by YoshiRulz** [comment]
In total, how much of an improvement was that PR?

**Comment by Morilli** [comment]
In my testing configuration and running release configuration without any overhead, I measured a speedup of around 5% (50k frames in 184 seconds vs. 192 seconds). This is arguably much less than what I was expecting, considering I got a speedup of 30% (going from 320 seconds to 245 seconds) while running with a profiler attached.

welp, still an improvement so that's nice.
