### ISSUE TITLE
Lua drawings aren't cleared from screen after you stop a script

### ISSUE THREAD

**Issue by ThunderAxe31** [TASEmulators/BizHawk#3014]
Version: from 2.6 to latest devbuild

Repro:
1. Open any game
2. Launch Input_Display.lua
3. Stop execution of Input_Display.lua without closing the Lua window
4. The graphics drawn by Input_Display.lua are stuck on screen.

**Comment by YoshiRulz** [comment]
Pretty sure this is intentional?

Workaround:
```lua
event.onexit(function() gui.clearGraphics() end);
```

**Comment by ThunderAxe31** [comment]
If this is intentional, why did drawings used disappear right after stopping script execution in previous versions? Also, why does drawing anything on screen automatically make disappear anything that was drawn before? It's pretty clear to me that any drawing is supposed to disappear after that the next frame is emulated.

**Comment by YoshiRulz** [comment]
#2501

**Comment by ThunderAxe31** [comment]
Look, in previous BizHawk versions, the same Lua scrpits didn't leave any trace on screen after getting execution stopped. This is a regression.

**Comment by ThunderAxe31** [comment]
I know that I shouldn't be making wild guesses without actually debugging, but I'm pretty sure that this regression was caused because the Lua drawing surface isn't being updated unless there is at least one script executing, probably for saving CPU usage. If that's the case, then the issue could be easily fixed by having the Lua drawing surface being updated just once, when all scripts are paused.

**Comment by YoshiRulz** [comment]
Under the assumption that multiple scripts should be able to draw at once (#2600), I thought about when autoclearing would be necessary and when it would be annoying, and came to the conclusion that *removing* a script should trigger a clear, but not *disabling/stopping* a script.
