### ISSUE TITLE
PSX - Movie syncs and desyncs randomly

### ISSUE THREAD

**Issue by TizianoMattei** [TASEmulators/BizHawk#3016]
### Summary
Yet another desync, unfortunately, hopefully this one might give some clues as why this happens

### Repro (Wish it was that easy!)
I replayed this tas many times during development, at this point im used to constantly have backups and use a cloud storage aswell. But it didnt desync at all where it does now, until i reached point past what the greenzone covered. This is what makes these desyncs nasty, they happen on an early section, that even if you checked and it was fine, its gonna desync sometime later with further tas development, unrelated to the initial section that desyncs.

I havent used branches, controller inputs, record mode, anything fancy really.
I recorded a clip of the desync happening, and to my surprise, it stopped desyncing the 3rd time i played back the tas, from the SAME frame. As you can see from the video, it desyncs 2 times, one near the start, the last near the end, just as i try to play back from an even further zone, making tastudio Seek to the nearest savestate to resume playback.
I havent changed any header savestates settings, either.

So, here's what ive noticed in this instance:
- TAS would desync from the same frame, resuming playback both instances (desync and not) from the "Start" marker you can see.
I could simply play the tas, resuming from double clicking the marker, and it wouldnt sync. Double click again on the same marker, then it did sync. Then it didnt. At some point it stopped desyncing from using that marker. But now even a single frame behind that marker, triggers TAStudio seek, replaying the tas from frame 0, in which case, at least for the time being, it is desyncing. 
One time i clicked on frame 0, and it didnt desync anymore. Now, as im writing, it went back to not-sync. 

Im not doing anything different between each attempt, literally, not even using turbo seek, slowing or increasing speed, etc. Simply replaying the TAS from such frames.

Will include a short clip as i stumbled across this, and the .tasproj
Game is CTR-NTSCJ (90743D27 CTR_NTSC_J.cue)

I also have a bunch of backups of this tasproj, with development way beyond the point of desync, but not as up-to-date with the tasproj i was working on. Let me know if those are needed, i can upload those aswell
Thanks in any case anyone tries to figure this out

Tasproj: https://mega.nz/file/3xcXWayD#8awzTkwBQR3Hosag4pM3fmquT3fClLhpkyB98ecPE1U
Video: https://www.youtube.com/watch?v=CyNC2hPEujY

Edit nr.1: as of now, it ONLY syncs from exactly where my single marker is, and anything past that. 
Anything before that, desyncs. It has sort of "stabilized" itself.

### Host env.
- Bizhawk 2.7.1 dev build
- Windows 11, AMD System, Nvidia GPU, 16GB Ram, 1TB Ssd drive

**Comment by YoshiRulz** [comment]
It probably isn't important, but could you grab the commit from the about window?

**Comment by TizianoMattei** [comment]
Sure thing, #4f71df99a, just after colorblind mode and the HASH thing fix were implemented

**Comment by alyosha-tas** [comment]
What are the results if you run State history Integrity Check? (In the edit menu.)

**Comment by TizianoMattei** [comment]
Here are the results:
- state history integrity check (run1): bad data between frames 1415 and 1416
- state history integrity check (run2): bad data between frames 1409 and 1416
- state history integrity check (run3): bad data between frames 1415 and 1416
- state history integrity check (run4): bad data between frames 1409 and 1416
- state history integrity check (run5): bad data between frames 1409 and 1416

and so on. I'll attach both of run1 and 2 outputs of raw save data given me by the state integrity check:

State Integrity check output1: https://mega.nz/file/DxMDwYjB#SOwsXd-mXaIBs3NzMQJ917PKA2cLSRBnH5PlGvvnsjQ
State Integrity check output2: https://mega.nz/file/3pNBSY6D#pIA5AvTJ6HwOPrQa89JulenuNsIc8LR4klZig2Ruk2U

Which is interesting, because its after my race restart, so the very first loading of the track was already done from the game, and no more cd seeking is usually done by psx in these instances. (On actual hardware, after the first loading, one can remove the disc from the console and keep restarting the race) Dont know if that helps narrowing it down, wont hurt saying it i guess

But most importantly, its basically right before my marker (frame 1417); now, as i stated at the start, initially the sync/desync delimitated area wasnt as clear as before and after that marker, in the video i uploaded aswell, the first desync with TAStudio Seek, happens when i try to playback a frame way beyond 1417, but once i replayed it again from the marker, that disappeared, effectively "fixing" the desync part after the frame 1417. The desync before that, stayed

**Comment by zeromus** [comment]
just a reminder, I really think we need to backtrack on my octoshock edits substantially, and in the case of the savestate code, entirely. we need to make the existing mednafen savestate code work verbatim (one way or another) for no other reason than to outsource the responsibility for making sure it works

**Comment by CasualPokePlayer** [comment]
Likely nonissue for Nymashock.
