### ISSUE TITLE
PCEHawk is literally unusable (corrupts execution engine)

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3018]
PCEHawk is completely unusable. ANY ATTEMPT to change resolution to 512x240 almost ALWAYS crashes BizHawk. We cannot get past it at all even with savestates. If it doesn't, attempting to reboot core will ALSO crash BizHawk. There was also one point where it corrupts the rewind config.
According to Visual Studio 2019, this is due to a fatal error in the execution engine (FatalExecutionEngineError). This possibly suggests that PCEHawk attempts to execute code that is not in the core itself. I don't think this core is recommended. Use TurboNyma or HyperNyma instead.
![image](https://user-images.githubusercontent.com/39802077/144756490-425af58a-f9ae-4f9d-8921-a35fcb9a1cf3.png)

First tested in 2.6.2, then in 2.7.

**Comment by Morilli** [comment]
How are you changing the resolution to `512x240`?

**Comment by getCursorsExe** [comment]
This is possible with Artemio's 240p Test Suite ROM for PC Engine.

**Comment by Morilli** [comment]
Using that, I was getting an `IndexOutOfBounds` exception which did crash bizhawk, but not corrupt it in any way.

**Comment by zeromus** [comment]
completely unusable? exaggerate much? 
the core uses pointers internally for some rendering. someone should change it not to do that. it's probably the culprit.

**Comment by YoshiRulz** [comment]
Or... we could remove PCEHawk. Does the testrom work in TurboNyma?

**Comment by zeromus** [comment]
do not remove pcehawk.

**Comment by adelikat** [comment]
PCEHawk implement more debug related services such as memory hooks.  Until a Nyma core has those, PCEHawk still has value

**Comment by nattthebear** [comment]
> completely unusable? exaggerate much? the core uses pointers internally for some rendering. someone should change it not to do that. it's probably the culprit.

Or just fix whatever bounds check is broken?  That rendering refactor doubled the speed of the core.

**Comment by Morilli** [comment]
As far as I can see the screen height (or width or whatever it is) is changed by the rom, but hardcoded in the core.

**Comment by zeromus** [comment]
the screen size is certainly not hardcoded in the core. the PCE has a zany variety of screen sizes. the problem is probably just that there's a mistake in handling one of them.

**Comment by nattthebear** [comment]
Anyone have an example of a game that selects the 512 wide mode?

**Comment by alyosha-tas** [comment]
There are a lot of moving parts here, but safe to say that PCEHawk is not handling this case correctly at all. I fixed it in so far as it does not crash, but obviously it's not supposed to be rendering 512 full pixels. 

I think incorrect display is better then crashing at least. I don't see a point rewriting everything to make it look correct since there is too much else wrong with the core as it is.

I hope Nyma can be brought to feature parity so we can finally kill off this core.

**Comment by getCursorsExe** [comment]
I saw that that this bug does not happen if you have Visual Studio 2020 installed. **So this means that PCEHawk is not compatible with Visual Studio 2019!**

**Comment by getCursorsExe** [comment]
There is also an issue with savestates. Loading a savestate with 512 pixels width crashes BizHawk.

**Comment by nattthebear** [comment]
Can you reproduce the savestate issue with new savestates (created after the fix)?

**Comment by getCursorsExe** [comment]
PCEHawk improperly handles 512 width savestates with Delta compression enabled. If this is disabled, then it is okay.

**Comment by zeromus** [comment]
It's not clear whether you answered natt's question
