### ISSUE TITLE
Psx games acting weird-- sometimes wont recognize my inputs but then suddenly will

### ISSUE THREAD

**Issue by DatBo76** [TASEmulators/BizHawk#3019]
So this issue has happened maybe 2 or 3 weeks ago. Before this time frame my controller worked fine with ps1 games. Anyway, there are points when the game's don't recognize my inputs. So I unplug my controller then plug it back in, nothing; I play a non psx game, the controller works for it even if I didn't previously unplug it and replug it. Weirder too is the fact it occurs when I load a savefile of the moment my controller disconnected. After like 30 minutes though of closing the app and re opening it, it works. I have no Idea why this is happening and it's made me less enthusiastic about playing ps1 games on biz currently

**Comment by zeromus** [comment]
wasn't there a bug template that asked you to write the bizhawk version and what game's youre playing?
do you know the difference between savefiles and savestates?

**Comment by YoshiRulz** [comment]
As I said on Discord, if you're getting the gamepad disconnected sound, it must be a driver or hardware problem. (We don't control Windows' notification sounds nor play our own.)

**Comment by zeromus** [comment]
Delete your ini file and you will observe the inconsistency between psx and the other platforms disappear. it may fix psx or break all the rest. You must have bound the PSX buttons differently. When your device connects differently, it behaves differently
