### ISSUE TITLE
Cannot import Snes9x movies into Bizhawk with Snes9x core

### ISSUE THREAD

**Issue by despoa** [TASEmulators/BizHawk#3022]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
When importing an SMV movie into Bizhawk while using the snes9x core, a prompt shows up that tells you that the SMV would sync better if you switch your core preference to bsnes and gives you option to switch or not. The problem here is that clicking "No" will have the prompt repeatedly pop up until you click "Yes", making it impossible to import SMV movies into the Snes9x core of Bizhawk.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Select Snes9x core
2. Import SMV movie
3. Click "No"

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.7; Win10 Home 19043; Intel/Nvidia

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Hardcoding BSNES was changed to prompting the user in https://github.com/TASEmulators/BizHawk/commit/3b8f08b1b089bb51f6b5915efe6e3da1c690e85c. Unfortunately, due to an oversight in https://github.com/TASEmulators/BizHawk/commit/641c3e9f82d027969dc5358f4254cb352fd573eb, the check ran for each frame in the movie file.
