### ISSUE TITLE
Dump Status Report misreporting game status since 2.7

### ISSUE THREAD

**Issue by TalicZealot** [TASEmulators/BizHawk#3027]
### Summary
```0DDCBC3D	G	Castlevania - Symphony of the Night (USA)	PSX		dh=ACF987E8```
was previously reported as **known good**, but since 2.7 Game.Status is RomStatus.NotInDatabase , aka UI shows **Warning: Unknown ROM**.
The entry is still present in gamedb_psx and the full hash through PSX Disc Hasher matches redump.org and the gamedb.

Found this while updating an external tool to support 2.7. Had to disable the following line, which should still work:
```
[ExternalToolApplicability.SingleRom(CoreSystem.Playstation, "0DDCBC3D")]
```

**Comment by YoshiRulz** [comment]
Fixed by https://github.com/TASEmulators/BizHawk/commit/8849134d50e428ea223951ac74ec0999650f5d45?

**Comment by TalicZealot** [comment]
Thanks. Will compile and check later today.

**Comment by TalicZealot** [comment]
Confirmed fixed, thank you.
![screenshot](https://user-images.githubusercontent.com/18632109/145725053-3f56d440-8718-44b2-a790-9d0790e77faa.png)
