### ISSUE TITLE
ROM Bank and SRAM Bank in Gambatte's Debugger registers are useless

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3028]
You cannot edit ROM Bank and SRAM Bank in Debugger at all, because you will only get this:
```
System.ArgumentException: Nie można znaleźć żądanej wartości 'SRAM Bank'.
   w System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   w System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   w BizHawk.Emulation.Cores.Nintendo.Gameboy.Gameboy.SetCpuRegister(String register, Int32 value)
   w BizHawk.Client.EmuHawk.RegisterBoxControl.<>c__DisplayClass17_0.<GenerateUI>b__4(Object o, EventArgs e)
   w System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   w System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
   w System.Windows.Forms.TextBox.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by CasualPokePlayer** [comment]
There is no API for setting them, they're read only. You can still go set them anyways with memory writes.

**Comment by Morilli** [comment]
> There is no API for setting them, they're read only. 

But... you can, in here:
![image](https://user-images.githubusercontent.com/35152647/145722813-215a2d5e-0575-47b4-abc3-5e7f74cc6f10.png)
That causes the mentioned exception though.

**Comment by CasualPokePlayer** [comment]
There's no API for those cases. No idea if there's some way to mark those cases as not working (maybe hardcode them to return immediately, at least until someone wants to hook something up for changing them).

**Comment by zeromus** [comment]
are you actually able to productively use the debugger in bizhawk? for what platforms?
