### ISSUE TITLE
PathConfig doesn't work correctly on 2.7

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3029]
1. Entries are alphabetised, both Global and system-specific
2. Unreleased systems are included in the dropdown
3. Unreleased systems do not have associated tabs, so the indices of the dropdown and tabs do not match
4. Due to 3., choosing a system near the end of the list causes a crash
5. Clicking the browse button on any entry causes a crash

Good news: I was not able to reproduce these on d979a09f5 when hardcoding `DeveloperBuild = false`. My earlier refactors seem to have fixed whatever the bug was.

Initially reported by @Fortranm via Discord. I'm going to assume that almost no-one uses the Path config, based on the lack of reports of it being *completely broken* until a month after release.

**Comment by TizianoMattei** [comment]
Actually i use that path config, i reported the issue when 2.6.3 release candidate went out on discord, but it must have been mixed up with other messages. I can still repro on 2.7.1 dev tho

**Comment by YoshiRulz** [comment]
Which commit are you using, and which behaviour(s) are still broken?

**Comment by TizianoMattei** [comment]
@YoshiRulz nevermind, i had opened another version of bizhawk, as i keep different versions on my machine, it is indeed fixed, apologies (and thanks!)
