### ISSUE TITLE
NDS load error

### ISSUE THREAD

**Issue by EonLeader** [TASEmulators/BizHawk#3030]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/70076374/145863004-d8f288a1-5b33-4adf-b6b8-1ba7c9c86581.png">

Happening when attempting to load all DS games currently. Please advise.

**Comment by YoshiRulz** [comment]
Which version are you using?

**Comment by EonLeader** [comment]
2.7.0, latest version.

**Comment by CasualPokePlayer** [comment]
Does this happen with a completely fresh config too?

**Comment by EonLeader** [comment]
Fresh config fixes it.
Changing the config back to as it had been makes the error reappear, and amending it back it seems as though the issue lied with leaving the firmware message blank. Adding anything to it at all makes it fine.

**Comment by InfamousKnight** [comment]
> Fresh config fixes it. Changing the config back to as it had been makes the error reappear, and amending it back it seems as though the issue lied with leaving the firmware message blank. Adding anything to it at all makes it fine.

?????

Why touch the config files in the first place?

**Comment by CasualPokePlayer** [comment]
Seems like firmware username and firmware message have this problem if they're blank. Firmware username being blank isn't valid anyways, although firmware message can legitimately be blank. The fix seems to just check if length is 0 then give it a 1 byte array with 0
