### ISSUE TITLE
Lua: Question about the size unit of the forms library

### ISSUE THREAD

**Issue by gocha** [TASEmulators/BizHawk#3034]
### Summary
I tried to use Lua's forms library to display a button that filled the screen, but the size of the button did not fit the window size as expected.

### Repro
```lua
function onclick()
    gui.addmessage("Lua button clicked")
end

form = forms.newform(800, 450, "800x450");
btn1 = forms.button(form, "Size (800/2, 450/2)", onclick, 0, 0, 800/2, 450/2);
btn2 = forms.button(form, "Size (800/2, 450/2)", onclick, 800/2, 0, 800/2, 450/2);
btn3 = forms.button(form, "Size (800/2, 450/2)", onclick, 0, 450/2, 800/2, 450/2);
btn4 = forms.button(form, "Size (800/2, 450/2)", onclick, 800/2, 450/2, 800/2, 450/2);
```

### Output
What I expect to see is:
* A window with a client area of 16:9 aspect ratio is displayed
* 4 buttons of the same size in the window

Actual result:
![forms_sizing](https://user-images.githubusercontent.com/332500/146106311-8974dccf-d686-4146-b061-bd2fe489499b.png)
Note: The button caption "Size (800, 450)" should correctly be "Size (800/2, 450/2)". Please don't mind about it...

Also, I tried changing the display scale of Windows 10, but it was the same whether I used 100%, 125%, or 150%.

### Host env.
- BizHawk 2.7; Win10 Pro 20H2 (Japanese); Intel/NVIDIA

### Feature request
I would like to see an explanation of this behavior in the Lua reference.

Ideally, I would like to see the size strategy of forms modified to achieve the expected results.

**Comment by gocha** [comment]
I'm also wondering why there is a slight gap between the buttons.

**Comment by Invariel** [comment]
Weird that what you have posted here doesn't match the e-mail notification that went out.  Anyhow, as far as I recall, based on my using the forms library, the vertical height includes the height of the menu bar, which is frustrating, but it is what it is.  If you try making your form 500 pixels vertically, you should see some whitespace at the bottom of the form where your 400 x 225 buttons end.  As for the space between them, I think that's a function of C# enforcing space between objects.

**Comment by gocha** [comment]
Thanks for the quick reply.

> the vertical height includes the height of the menu bar

I see. Is there any possibility to improve this by using [Form.ClientSize](https://docs.microsoft.com/ja-jp/dotnet/api/system.windows.forms.form.clientsize) instead of [Form.Size](https://docs.microsoft.com/ja-jp/dotnet/api/system.windows.forms.form.size)?

For reference: [FormsLuaLibrary.cs](https://github.com/TASEmulators/BizHawk/blob/38f3cdb687a42e26b6b58cf5649eaf272108919f/src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/FormsLuaLibrary.cs)

> As for the space between them, I think that's a function of C# enforcing space between objects.

I'm not very sensitive about this, but I suspect that the rounding done by UIHelper may have something to do with it.

For reference: [UIHelper.cs](https://github.com/TASEmulators/BizHawk/blob/84e195659c47fdf8b617777a1504efe5cffb169e/src/BizHawk.Client.EmuHawk/UIHelper.cs)

**Comment by YoshiRulz** [comment]
`UIHelper` rounds to a whole number of pixels, nothing wrong with that. Everything else is just how WinForms works unfortunately. You might be able to use a bunch of `forms.setproperty` calls to work around it.

**Comment by gocha** [comment]
I see. If you don't plan to work on it, you can close this issue. I am currently looking into working on my own project with ExternalTools.
