### ISSUE TITLE
Lua: Replacing the implementation of a library function will affect other scripts (Global variables are shared across scripts)

### ISSUE THREAD

**Issue by gocha** [TASEmulators/BizHawk#3036]
### Summary
Replacing the implementation of a library function will affect other scripts.

### Repro
1. Open the first script 'print_hijacking.lua'
   ```lua
   unaltered_print = print
   print = function(...)
       unaltered_print("Goodbye")
   end
   ```
2. Open the second script 'hello.lua'
   ```lua
   print("Hello world")
   ```

### Output
Expected output of 'hello.lua':
```
Hello world
```

Actual output:
```
Goodbye
```

### Host env.
- BizHawk 2.7; Win10 Pro 20H2; Intel/NVIDIA

**Comment by gocha** [comment]
I was expecting the two scripts to be running in different Lua VMs, is that not correct?

**Comment by CasualPokePlayer** [comment]
Does doing `local print` instead of `print` for the `print` redefinition also have the same result.

**Comment by gocha** [comment]
a.lua:
```lua
name = "Alice_Rabbit"
```

b.lua:
```lua
print(name)
```

Output of b.lua:
```
Alice_Rabbit
```

It seems that scripts can manipulate each others global variables.

**Comment by gocha** [comment]
> I think that's intended?

Hmm... Even so, I don't think this is the way to go.

In my opinion, a script should not change the behavior of another script. If scripts need to communicate with each other, I think they should use another method that is not a global variable.

As an example of other emulators, DeSmuME, for example, does not share global variables between scripts.

**Comment by YoshiRulz** [comment]
Tempted to call this a "feature" because we won't be changing the sandboxing (or lack thereof) anytime soon, and fixing this within the current system would suck...

**Comment by nattthebear** [comment]
I assume someone has written a collection of scripts that rely on this data passing
