### ISSUE TITLE
[Lua request] User-friendly `tostring(a_table)` output

### ISSUE THREAD

**Issue by gocha** [TASEmulators/BizHawk#3037]
For Lua tables, `tostring()` returns an unhelpful string.

```lua
local t = {name="gocha"; age=4}
print(tostring(t))
```

```
table: 000001F4BEC4ED20
```

In fact, this is the original behavior of lua's `tostring()` itself, so it's not that BizHawk is particularly bad. However, I would like to have a `tostring()` function that can display the entire contents of a table.

For debugging purpose, it seems that I can use the `print()` function without `tostring()`.

```lua
local t = {name="gocha"; age=4}
print(t)
```

```
"age": "4"
"name": "gocha"
```

It's good. However, if possible I would like to use this style outside of the lua console window. Also, the print function does not expand the contents of nested tables, so I would like to have a version that supports nested tables. When dealing with nested tables, you have to worry about circular references, which can be a bit costly.

The solution does not necessarily have to be to replace the behavior of `tostring()`. For example, in Ruby, there are two separate functions: `to_s()`, which provides normal string conversion operations, and `inspect()`, which is especially for debugging.

For what it's worth, DeSmuME seems to have achieved my ideal, and the following script displays some very cute output.

```lua
local t = {name="gocha"; age=4, arr={10,20,30}}
t.circular=t
print(tostring(t))
```

```
{circular=table:parent, arr={10, 20, 30}, name='gocha', age=4}
```

I am using BizHawk 2.7.

Thanks for reading.

**Comment by YoshiRulz** [comment]
This is a shortcoming of Lua's standard library. Pick your favourite implementation from [TableSerialization](http://lua-users.org/wiki/TableSerialization) on the Lua wiki and bundle that with your script.
