### ISSUE TITLE
Need more precision when tweaking axis sensitivity/deadzone

### ISSUE THREAD

**Issue by Nicholas-Steel** [TASEmulators/BizHawk#3038]
![image](https://user-images.githubusercontent.com/11567846/146634344-4931d45a-f516-45c7-b489-f256fee989b0.png)

Hi, it would be fantastic if the granularity was improved to 5% adjustments instead of 10% and for the keyboard arrow keys to increase/decrease by 5% with each arrow key press for the Sensitivity slider (currently seems to adjust by +/- 100% per key press).

Thanks.

Windows 10 21H2

**Comment by Meerkov** [comment]
Is it just me, or is the N64 sensitivity *waaaaay* high? I feel like in some games I have to drop it to 10% to get anything resembling reasonable.

**Comment by YoshiRulz** [comment]
IIRC games expect -80..80 but we send -128..127

**Comment by Meerkov** [comment]
161/256 is roughly 62.5%. Hmm.

**Comment by Nicholas-Steel** [comment]
> IIRC games expect -80..80 but we send -128..127

Why?
