### ISSUE TITLE
Vivian Land: 6 Shadow Stars - Game doesn't boot

### ISSUE THREAD

**Issue by noddy360** [TASEmulators/BizHawk#3040]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Vivian Land: 6 Shadow Stars is a ROM Hack for the Gameboy game Super Mario Land 2: 6 Golden Coins, made by Skelux.
![bgb00002](https://user-images.githubusercontent.com/31973588/146661007-4f869f10-83c3-4ba0-a4c0-c7004e2366b4.png)

The hack works in most emulators I tried, including BGB, Sameboy, KiGB, mGBA and VBA. All of these worked for me and the game was playable. When I tried to play the hack on BizHawk however, it wouldn't go past the GB/GBC BIOS screen and wouldn't start the game. This happened for both GB, GBC and GBA modes for both the Gambatte and GBHawk cores of BizHawk.
I then discovered that you need to set the "Use official Nintendo BootROM" option as "False" in the Sync Settings so that the game could start. I didn't have the official BIOS enabled for all the other emulators I tried.
![Sin título](https://user-images.githubusercontent.com/31973588/146661276-82725308-09be-4e01-bb1d-39ec2eec0092.png)

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open BizHawk and load a ROM
2. Open the ROM of Vivian Land - 6 Shadow Stars.gb
3. Make sure that you set the "Use official Nintendo BootROM" option as "True" in the Sync Settings.
4. Let the Gameboy/GBC BIOS screen run.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
![Sin título](https://user-images.githubusercontent.com/31973588/146661331-d1447821-8b60-4e9b-8b5a-c9c25cbb2195.png)

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.7.0; Win10 Pro; Intel
- BizHawk dev build at 5e3e65a2; Win10 Pro; Intel

Now, the game does boot on the emulator bgb, however, it throws me this warning when I open the ROM:
![Sin título](https://user-images.githubusercontent.com/31973588/146660711-61d596af-2615-4cf2-9ee0-44fa6cdcbfef.png)
I then opened the game with the GB BIOS enabled, and naturally, the game didn't start.
I'm very aware that this is an issue with the ROM hack itself and not the emulator, I wish I didn't have to toggle settings like that just to play one single Gameboy ROM Hack.

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
To be clear, by default using the real BIOS is disabled. With default settings this hack would be fine. Enabling the official BIOS will not work with that game due to having an incorrect header checksum (which the official BIOS will not boot).

**Comment by zeromus** [comment]
maybe we should fix the checksum. if that's objectionable in the unlikely case someone wants to test what the bios does for the wrong checksum or is otherwise let-down by the emulator ignoring their wrong checksum (that's how these hacks get made with wrong checksums in the first place) then we can add a sync setting to disable the checksum auto-fixing

**Comment by CasualPokePlayer** [comment]
If it makes it any better https://github.com/TASEmulators/BizHawk/commit/c33d2cfbe5fb69951e68d9846b0d5865fc4d102c will pop up a message warning the user if BIOS is enabled and the header checksum is bad.
