### ISSUE TITLE
Multi-disk bundler stops working after second disc

### ISSUE THREAD

**Issue by Reinc01** [TASEmulators/BizHawk#3047]
I used the multi-disk bundler to record Panzer Dragoon Saga for Sega Saturn, but the "next disc" button on virtual pad does not do anything when I try to switch from disk 2 to disk 3 when prompted. Switching from disk 1 to disk 2 worked normally previously. Strangely, pressing the "previous disc" button still works, but not "next disc", at least not until the Saturn BIOS menu appears. Meaning, I still can switch to disk 3 from disk 2 by pressing "previous disc">"next disc">"next disc".

In the attachment, there is a save file with the end of disk 2. You need to save the game, and then you will be prompted to insert disk 3.
[save.zip](https://github.com/TASEmulators/BizHawk/files/7784639/save.zip)

**Comment by CasualPokePlayer** [comment]
Should be fixed in 58c28aefbaaa74e1c3a2a5b9bae4b1d5724a365d
