### ISSUE TITLE
BSNESv115+ crashes BizHawk when rendering out-of-bounds colors (above 0x7FFF)

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3050]
Did you know that it is possible to crash BizHawk by rendering an out-of-bounds color like 0x8014 or 0x8050?
```
System.IndexOutOfRangeException: Indeks wykraczał poza granice tablicy.
   w BizHawk.Emulation.Cores.Nintendo.BSNES.BsnesCore.snes_video_refresh(UInt16* data, Int32 width, Int32 height, Int32 pitch)
   w Bizhawk.BizInvokeProxyBsnesCoreImpl.snes_run()
   w BizHawk.Emulation.Cores.Nintendo.BSNES.BsnesCore.FrameAdvance(IController controller, Boolean render, Boolean renderSound)
   w BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   w BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   w BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```
You can also see that these colors are interpreted weirdly (colors do not go from black to white, they instead change randomly). No idea if hardware outputs the same. Interestingly, on old BSNES, they are interpreted as mirror of valid colors (0x0000 to 0x7FFF), effectively avoiding the crash. Faust does the same. Snes9x does not have CGRAM memory domain, so getting out-of-bounds color manually here is impossible.

**Comment by YoshiRulz** [comment]
Can this happen when playing a licensed game or testrom, or did it require poking virtual memory?

**Comment by getCursorsExe** [comment]
It may happen when a GPU Corruption Crash occurs, but it is not controlled by client.

**Comment by CasualPokePlayer** [comment]
> You can also see that these colors are interpreted incorrectly (colors do not go from black to white, they instead change randomly). No idea if hardware outputs the same.

SNES Hardware is RGB15, not RGB16.

**Comment by getCursorsExe** [comment]
For example, if displaying color 0xFC1F, which would appear as magenta if valid colors are mirrored, it is displayed as yellow/gold.

**Comment by YoshiRulz** [comment]
Can we have repro instructions? Did this happen after poking virtual memory, or were you playing a rom normally?

**Comment by getCursorsExe** [comment]
After poking virtual memory (editing CGRAM).
