### ISSUE TITLE
Disabling Window Menu in Display Configuration - No Easy Way To Re-Enable

### ISSUE THREAD

**Issue by boktai1000** [TASEmulators/BizHawk#3051]
Consider this maybe a nitpick if you will, or a problem - but I couldn't for the life of me figure out how to re-enable the Menu without completely re-installing BizHawk to a fresh folder and re-setting up the entire thing.

There's a bit more context to this - I stream via Discord and when doing so, the game plus the Menu shows up. I went through and tried to disable everything under view, but the "Menu" was still showing up. So I ended up finding the option tucked away here, but I sort of figured that by pressing a key like Alt, Ctrl, Shift, any of the F1-F12 keys, etc - basically every key on my keyboard, something would get the Menu to show momentarily so I could get back in there but I couldn't figure it out.

I searched around documentation and couldn't find anything on this either, so I wanted to write to you to let you know about this "small" gripe - you could consider the usability of re-enabling I suppose, as well as when the program is streaming and having the Menu show (maybe some want this by default - but it's probably on a case by case basis)

Thanks!

![image](https://user-images.githubusercontent.com/9054563/147802586-18da543a-9c0c-432c-90d1-3a8f1b799283.png)

**Comment by zeromus** [comment]
config.ini - DispChromeMenuWindowed

**Comment by YoshiRulz** [comment]
Right-click > `Show Menu`

(though, under Mono at least, it doesn't hide unless you re-enable and re-disable the setting)

**Comment by boktai1000** [comment]
@YoshiRulz Excellent! It wasn't so obvious, but this works a treat. Thank you!
