### ISSUE TITLE
VectrexHawk doesn't support bank-switched ROMs

### ISSUE THREAD

**Issue by tildearrow** [TASEmulators/BizHawk#3057]
### Summary
Apparently the VectrexHawk emulation core lacks support for bank-switched ROMs.
Even though none of the officially released (and possibly homebrew games) use bank switching, two demos are known to use it: "EigenVectrex" and "Where Have All The Pixels Gone?".

### Repro
1. Load EigenVectrex. It will not play the music and begin in the first half (possibly because BizHawk only loads the first 32K bank, and the demo should start on the last bank?).
2. Alternatively cut EigenVectrex in half (remove the first 32K bank from the ROM, e.g. by doing `dd if=demo2019-party.bin of=cut.bin bs=32768 skip=1 count=1`), then load it. After a while the demo will error with "THIS IS BANK1" displayed on the screen (see screenshot below).

### Host env.
- BizHawk 2.7.0; Arch Linux; Intel/AMD

![demo2019-party 1 2022-01-03 21 57 53](https://user-images.githubusercontent.com/13842506/148003992-9db96395-9b14-4191-b3e4-c40e351b911e.png)

The demos in question that trigger the bug can be found here:
- https://www.pouet.net/prod.php?which=59227 (Where Have All The Pixels Gone?)
- https://www.pouet.net/prod.php?which=81485 (EigenVectrex)

**Comment by alyosha-tas** [comment]
Neat demos. I don't recall ever coming across bank switching games or demos when I was developing the Vectrex core, but looking around now I do see a couple different mentions of ways people develop bank switching carts. I'll try to look into fixing this soon.

**Comment by alyosha-tas** [comment]
ok these are implemented now. There are some graphical errors, but that is common to the Vectrex core, not particular to these demos.
