### ISSUE TITLE
Unreferenced pixels being rendered on screen (possibly caused by out-of-bounds read)

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3058]
![image](https://user-images.githubusercontent.com/39802077/148046929-1dbfad1d-b53e-4c4c-919c-c76f3a9ca923.png)

These pixels can change colors. They also change within savestates, emulator pause and when we open any menu. This is possibly due to an out-of-bounds read bug found inside of screen rendering engine in BizHawk.
Suprisingly it does not cause any [CWE-125](https://cwe.mitre.org/data/definitions/125.html) type vulnerabilities, but still, use it at your own risk.

**Comment by Morilli** [comment]
Any context? Rom used? Reproduction scenario? How are you sure that whatever you are seeing is not correct?

**Comment by getCursorsExe** [comment]
DebugYellow
SHA1:ECE578EE1642A7AA9A3C9DE9F647E7599ABF0231
MD5:E7B6D8EC4BB227B1E9E2E3A0C6219D41

It's done by using the "DEBUG" item, then using Predef 0x40 in Misc.

**Comment by Morilli** [comment]
Can confirm that graphics look corrupted, although the question remains: How are you sure that what you're seeing is not supposed to be there? I couldn't find any documentation about the miscellaneous section, and this looks like normal-ish behavior to me; nothing in the emulator seems to be broken.

**Comment by getCursorsExe** [comment]
If you take this scenario and record it:

https://user-images.githubusercontent.com/39802077/148086325-51e150fe-58a5-4515-a1ca-4ed0fabf33e2.mp4

you'll then see, that the SGB border is now overwritten by BizHawk's internal textbox and window buffer, possibly causing an out-of-bounds read bug.

**Comment by CasualPokePlayer** [comment]
This happens for completely unrelated emulators and even BSNESv115, these corrupted graphics look like they should be there, as the game ends up transferring junk data to the border.

Some investigation into the savestates/etc changing border seems to point reading uninitialized data in the stack, probably nothing particularly harmful anyways. A one-liner fixes it: https://github.com/pokemon-speedrunning/gambatte-core/commit/54d7286e1619452fa5f088f7bbcaf59865a8cedf

**Comment by getCursorsExe** [comment]
We somehow arrive at the [simillar issue](https://github.com/TASEmulators/BizHawk/issues/2898#issuecomment-908640131).

**Comment by CasualPokePlayer** [comment]
How is that even similar lol. It's not even savestates in particular it's just uninitialized memory being read, and this would not affect official games, and can't even cause a desync for a movie.
