### ISSUE TITLE
GuiApi some methods stop working after core reboot

### ISSUE THREAD

**Issue by TalicZealot** [TASEmulators/BizHawk#3059]
### Summary
GuiApi drawing methods can stop outputting elements once a core is reboot.

### Reproducing
1. Load a game
2. Draw a box or text using GuiApi.DrawBox / GuiApi.DrawString
3. Reboot Core
4. Draws don't work, due to reaching
 https://github.com/TASEmulators/BizHawk/blob/c7403e7fe77729084b0038f69e04e18280b4718b/src/BizHawk.Client.Common/Api/Classes/GuiApi.cs#L529
and
https://github.com/TASEmulators/BizHawk/blob/c7403e7fe77729084b0038f69e04e18280b4718b/src/BizHawk.Client.Common/Api/Classes/GuiApi.cs#L276

Exception caught is from System.Drawing with message "parameter is not valid".

Note: DrawImage doesn't seem to have issues. Potentially the issue is due to not disposing of everything properly.

### Host environment
- BizHawk 2.7; Win10;  Intel/NVIDIA

**Comment by TalicZealot** [comment]
After further investigation it seems like the methods in question are not finding a Brush and a Pen to draw with through GetBrush or GetPen. Will create a pull request if I can figure this out.

**Comment by YoshiRulz** [comment]
Are you using `IGuiApi.WithSurface`? Without it, nothing is drawn.

**Comment by TalicZealot** [comment]
Here is a short video showcasing the issue. Initially the drawn elements behaving correctly, then only images being drawn after rebooting the core, then I go in debug mode and catch the exception. [video](https://www.youtube.com/watch?v=KWsBJwtTDrc)

**Comment by TalicZealot** [comment]
The problem was due to me not handling restarting the tool properly, so the reference of the GuiApi I was using was outdated.
