### ISSUE TITLE
BSNESv115+ hex editor: viewing bytes at location hex:xx2130 causes graphical bugs

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3060]
xx is the bank (set of 0xFFFF bytes)

**Comment by Morilli** [comment]
Judging from a comment in the disassembler part of the code
```
    //$00-3f,80-bf:2000-5fff: do not attempt to read I/O registers from the disassembler:
    //this is because such reads are much more likely to have side effects to emulation.
```
, it seem that certain system bus reads may have emulation side effects.
I'm not entirely sure why those exist or how to prevent them.

**Comment by CasualPokePlayer** [comment]
> Judging from a comment in the disassembler part of the code
> 
> ```
>     //$00-3f,80-bf:2000-5fff: do not attempt to read I/O registers from the disassembler:
>     //this is because such reads are much more likely to have side effects to emulation.
> ```
> 
> , it seem that certain system bus reads may have emulation side effects. I'm not entirely sure why those exist or how to prevent them.

In general having something like "peek at system bus the same way as the CPU" can have side-effects if it causes the state of various components to be updated (common for lazy evaluation emulation etc). You need to either have them not be updated and try to return whatever is present (which granted may be "wrong") or just block the reads.

**Comment by getCursorsExe** [comment]
I think the culprit is the address xx213C and xx213D, which is the location of the scanning beam.
