### ISSUE TITLE
Genesis Game Demons of Asteborg Not Emulated Properly (SRAM Fails to Load)

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASEmulators/BizHawk#3073]
Demons of Asteborg (https://www.demonsofasteborg.com/) does not load the SRAM properly.  This is fixed in the genesis plus gx according to the link below.  I have tested the current build of Bizhawk alongside 2.6.2 and 2.7.0. Older Bizhawks like 2.3.2 just displays graphical garbage on loading the game.

https://github.com/ekeeke/Genesis-Plus-GX/issues/381

I think what is needed is to update using Waterbox for the genesis plus gx core?  

The way to tell the game is not loading properly is to run the game and when you start a new game no difficulty or save slot is selectable and no files can be saved. 

https://youtu.be/3lPBlLZvgXk?t=335

I have not tested Retroarch, but Blastem does load the rom and SRAM as long as you do a hex edit where you replace "SEGA DOA" with "SEGA SSF" in the header. https://www.reddit.com/r/SEGAGENESIS/comments/p1x3hh/demons_of_asteborg_review/

Rom Info
DemonsOfAsterborg v1.1
SHA1:3274194684FE28DA04F6E57981CA7B00E10835D2
MD5:7EF77BBB609124BCFC18FA400DE99BF3

PM me CoolHandMike#0352 on Discord if necessary.
![image](https://user-images.githubusercontent.com/34147391/149338481-9eab5e5e-9ddb-4ac5-bf8a-d99c4c365113.png)

![image](https://user-images.githubusercontent.com/34147391/149338396-4e99b860-42bd-4c05-aeb0-41736fcc1b17.png)

**Comment by CasualPokePlayer** [comment]
Fixed by https://github.com/TASEmulators/BizHawk/pull/3139
