### ISSUE TITLE
Unnecessary file in win x64 release Tools\.gitempty

### ISSUE THREAD

**Issue by meshuggahtas** [TASEmulators/BizHawk#3075]
Version: 2.7
Link: https://github.com/TASEmulators/BizHawk/releases/tag/2.7  BizHawk-2.7-win-x64.zip

There is an empty .gitempty file in Tools directory. 
Thought I should report it.

**Comment by YoshiRulz** [comment]
This is a common method of checking-in an empty (or nearly empty) directory to a Git repo. See these popular StackOverflow answers: https://stackoverflow.com/a/8418403 https://stackoverflow.com/a/7229996

**Comment by meshuggahtas** [comment]
Yes I understood the meaning of the file, but its not used for the end-user. Thought I report it maybe because the file was intended to place somewhere else. Thanks for infos nonetheless!
