### ISSUE TITLE
BizHawk does not handle movies made from other emulators

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3076]
I have tried to load the TAS movie of Kaeru no Tame ni Kane wa Naru, made by Ryuto, unfortunately, this ends up putting BizHawk in a glitched state, where all files from Recent will be marked as "not found", and you cannot open any ROMs. The only way to get out of this is to restart BizHawk instance completely.

**Comment by YoshiRulz** [comment]
Not sure what this means. EmuHawk is able to read several other emulators' movie formats via `File` > `Movie` > `Import Movies...`.

**Comment by getCursorsExe** [comment]
I was trying to do so, but it results in no core specified message, and putting BizHawk in a glitched state.

**Comment by YoshiRulz** [comment]
Could you share the movie?

**Comment by getCursorsExe** [comment]
https://tasvideos.org/1367M?handler=Download

**Comment by YoshiRulz** [comment]
I reproduced some weirdness and then was able to fix it. Comment if there are any more problems.
