### ISSUE TITLE
DiscoHawk comparison listview double buffer

### ISSUE THREAD

**Issue by Aurumaker72** [TASEmulators/BizHawk#3079]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
The "comparison" listbox in DiscoHawk is not double buffered and flickers.
Reproduce by clicking on it, the selection box will flicker while changing elements or by dragging the selection tool.
*Should multiselect be allowed in this listbox?*

**Comment by zeromus** [comment]
this does nothing by design, just ignore it.
