### ISSUE TITLE
[Feature Request] Bizhawk Saving gamepad profil

### ISSUE THREAD

**Issue by PegHorse** [TASEmulators/BizHawk#3080]
Hi !

This is not critical but i'd like this to be thinked to add the Feature of Gamepad profil
See here on the contextual menu, we can "Save Defaults, Load Defaults"
I'd like to **Save custom profile and name it as i wish,** so i can plug differents controllers without setting the keys again over and over.

![image](https://user-images.githubusercontent.com/7678316/150272009-8744b0e3-17d4-4498-9262-521b754246af.png)

Thanks :)

**Comment by YoshiRulz** [comment]
Duplicate of #1636.

**Comment by PegHorse** [comment]
Any ETA of this feature ?
