### ISSUE TITLE
TURBO and HYPERnyma updates.

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#3081]
Please update Turbonyma and Hypernyma to 1.29 stable.

taken from changelog

PCE: Fixed a memory initialization bug that could cause graphics glitches after the explosion of the first boss in "R-Type".
PCE, PCE-Fast: Fixed unreadable black letters in "Order of the Griffon"'s password entry screen.

**Comment by Eggo-dotcom** [comment]
these bugs canthese bugs can be reproduced in bizhawk so when possible the update will be nice.

**Comment by Shinobi-1987** [comment]
Bump? Will fix rtype and order of the geyphon

**Comment by Shinobi-1987** [comment]
Is this something that will eventually happen? Curious

**Comment by CasualPokePlayer** [comment]
Done in e6d74c3167ad8ffb6ce7b90d84bd609028016d53
