### ISSUE TITLE
tool savefile paths doesn't track current rom

### ISSUE THREAD

**Issue by zeromus** [TASEmulators/BizHawk#3085]
1. Load a NES rom
2. open the cheat window
3. add a cheat
4. save it
5. load a different NES rom
6. note the watch window still shows "old game.cht saved". Not great, but ok...
7. note that the cheats list is now empty
8. click save. it's going to save to "old game.cht"
9. use file > save as -- its going to suggest "old game.cht"
10. close everything and reopen it with old rom. you old rom's cheats are lost because you clicked save while you had the 2nd rom open

I know there's a certain amount of logic to this and that's why things got the way they are. I'm not really sure what to do about it. It's just not a great user experience. I am encouraged to expect the associations between tool save files and rom selections to be much stronger. That you can save multiple cheat files with different names than the rom you're on is an advanced feature and a rare use case.

**Comment by kalimag** [comment]
If "Autosave cheats" is enabled (by default), this happens without any user interaction once you reboot core/close rom/etc. after step 7
