### ISSUE TITLE
Hotkeys trigger when typing values in the Virtual Pad input fields.

### ISSUE THREAD

**Issue by MrCheeze** [TASEmulators/BizHawk#3087]
### Summary
There is a usability issue where hotkeys are not disabled when typing in the input fields of the Virtual Pad window. This means that unless you reconfigure the number and "-" keys to do nothing, typing an exact joystick value will trigger them, which seems like a small inconvenience but adds up a lot over time.

As far as I can tell, this problem is unique to the Virtual Pad window, every other popup window seems to disable input to the main window entirely (both controller and hotkeys). Not sure if this issue stems from a deliberate design difference or is a pure bug, but I can think of three possible behaviours that would all be better than the current one:

* Make the virtual pad window work like all other popup windows, and totally disable input to the main window when focused on it.
* Disable input to the main window, but only when specifically focused on the text input fields.
* Same as the first option, but with a setting in the virtual pad that lets you revert to the old behaviour if you wanted to for some reason.

### Repro
1. Have the hotkeys configured with their default values.
2. Open a game for a console with analog input (e.g. N64)
3. Type e.g. "-1" as the X stick input value.

The "-" hotkey and "1" hotkeys trigger, slowing down emulation and selecting save slot #1.

### Host env.
- BizHawk 2.7.0; Windows

**Comment by MrCheeze** [comment]
Behaviour is the same in 2.8, the fix doesn't seem to have fixed it.

**Comment by YoshiRulz** [comment]
Reopening *again* because it turns out people need hotkeys like frame advance while TASing, which often also involves the Virtual Pad...

edit from the future: Fixed for TAStudio (axis editing mode) in https://github.com/TASEmulators/BizHawk/commit/a5b631c9e7984edc7cff2b30dd7128cb0bdaf000.
