### ISSUE TITLE
[melonDS] Firmware Language always stays in English even if you change it to another Language

### ISSUE THREAD

**Issue by danylopez123** [TASEmulators/BizHawk#3088]
### Summary

Going to the melonDS settings in Sync Settings (Located from the NDS Tab) and then switching the Firmware Language to something else will not affect to a NDS game that haves different languages and will always stay in English.

### Repro

1. Have a NDS game running that supports different languages.
2. Go to NDS tab then Settings.
3. Go to Sync Settings and change "Firmware Language" to something else other than English.
4. Reboot, Language still English.

### Host env.
- BizHawk 2.7; Win10; NVIDIA

**Comment by CasualPokePlayer** [comment]
1. What game? Not all games have to abide by firmware settings.
2. Are you using a real firmware file? If so have to enabled Firmware Override?

**Comment by CasualPokePlayer** [comment]
[This commit](https://github.com/TASEmulators/BizHawk/commit/7ac2e97cb7612b731ff35fe22312e99e68371f23) should make firmware always use user settings if firmware file is not provided, calling this fixed.
