### ISSUE TITLE
PSX - How to trigger a desync every single time, step by step

### ISSUE THREAD

**Issue by TizianoMattei** [TASEmulators/BizHawk#3090]
### Repro
1. Open the .tasproj i uploaded here: https://mega.nz/file/uhF10S4C#VvTMq-9JCL2fqYEVU-8gLW3vDJ0R-FWOSFBVdKHwZl8
2. Go to the section i show in the video, after the loading screen
3. Put the 2 l1 inputs at the earliest possible time (just above the 2 lag frames, as shown in the video)
4. Clear greenzone and play from boot or proceed much further in the tas till that section isnt covered by an active greenzone anymore
5. Notice the desync after the loading screen

Video with step by step repro: https://www.youtube.com/watch?v=y-jam4whZMM
Game: Bugs Bunny Lost in Time - NTSC U, HASH from Bizhawk: 54B8F5A3 BBLIT_USA.cue
Firmware:: 524288	sha1:0555C6FAE8906F3F09BAF5988F00E55F88E9F30B	PSX_3.0(A).bin	PSX BIOS 

NB: tastudio didnt just add frames. thats a backup i have of a tas that proceeds till 40k frames with the desync happening there, around the 20k mark. Just used the backup in the video and uploaded .tasproj so its easier to see without getting confused, anyway, here's the main .tasproj with the desync happening there, despite being able to jump after the desync with branches and markers with active greenzones: https://www.youtube.com/watch?v=lX4oOZfl-nY

### Host env.

Bizhawk 2.7.1, commit 4f71df99a (2.7 has the HASH bug which breaks my lua scripts, older versions have desyncs caused by autofire and other causes, and this one has colorblind mode on top of the updated octoshock core, so thats why im using this commit, not that it matters anyway)
Win11, Nvidia gpu, Amd cpu, 16gb ram

Same kind of desync thats always been there for psx, unless one clears greenzone and replays the tas every single time, the desync is noticed much later when the greenzone isnt there anymore, as usual
If other files or anything else is needed to help fix the issue, feel free to ask, thanks in any case

**Comment by TizianoMattei** [comment]
Yea, i couldnt just wait for full release so i kept using nymashock A LOT all these days, im 50k re records in a tas with no issue whatsoever. Even fully ran a savestate integrity check, all fine. Shall i close these open octoshock isues since they arent a problem anymore with nyma?

**Comment by YoshiRulz** [comment]
We'll wait until after release, so you have more time to play with it.
