### ISSUE TITLE
Saturn BIOS files matching good firmwares in DB are marked unknown by icon

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASEmulators/BizHawk#3095]
Repro:

Get a good saturn BIOS.
Put it in right slot.
? icon instead of checkmark. Interestingly the "Resolved With" field has the correct info, indicating it did get a match but the icon doesn't see that.

Test on 2.7 with fresh config, originally found it in dev builds

**Comment by Eggo-dotcom** [comment]
looks perfect here.? or?
![Capture](https://user-images.githubusercontent.com/84027465/151083033-548e07bb-4fbc-4e4b-9c36-b311f8056c72.PNG)

**Comment by nattthebear** [comment]
> Get a good saturn BIOS.

Please be more specific than this.  What are the exact hashes?

**Comment by CasualPokePlayer** [comment]
> > Get a good saturn BIOS.
> 
> Please be more specific than this. What are the exact hashes?

Any one which matches the firmware DB. e.g. `SHA1: FAA8EA183A6D7BBE5D4E03BB1332519800D3FBC3` for US bios, which matches the entry in the firmware DB.

**Comment by CasualPokePlayer** [comment]
I think I found the issue
https://github.com/TASEmulators/BizHawk/blob/e38726db50186caa52aaac3b4e5b2cf7bf0be826/src/BizHawk.Client.Common/fwmanager/FirmwareManager.cs#L211-L215
This code seems innocent enough, but what if the we decide to put a firmware file in multiple options?
https://github.com/TASEmulators/BizHawk/blob/1c4c390e8fa55c30884f58bb7978b93cacdb0cdd/src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs#L164-L184
... which we decide to do for saturn, so the above code misbehaves.

Not sure the correct way here, either we have to merge U and E into a single option and don't do what was being done before, or we nuke the above code (which is sure to run into bugs) :/
