### ISSUE TITLE
Q Boy (NES bootleg) worked fine in 2.6.2, does not run in 2.7.0

### ISSUE THREAD

**Issue by mooware** [TASEmulators/BizHawk#3099]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."

I tried to run the game Q Boy in BizHawk 2.7.0, but the screen simply stays black, or green for subneshawk. I distinctly remembered playing it in BizHawk, so I checked an older version I had on disk, 2.6.2, and it worked fine there.

On the old version, both NesHawk and SubNesHawk work, and QuickNes seem to fall back to NesHawk, I assume that's intentional behavior. On the new version, QuickNes also falls back to NesHawk, and the other two stay on a black or green screen.

I looked at the log window for both versions, see below. It seems that BizHawk comes up with different hashes for the rom, and that's why it doesn't find it in the gamedb file. I checked the gamedb file for both versions, and they have an identical line for Q Boy.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."

Load the NES rom "Q Boy (Asia) (Unl).nes" (sha1:ed559a03d03b6c8812e359600979c1ae173d86df)

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."

Log from BizHawk 2.6.2:
```
ROM was not a multiple of 1024 bytes, and not a recognized header size: 16. Assume it's purely ROM data.
------
BEGIN NES rom analysis:
Found iNES header:
pr=256,ch=0,wr=8,vr=8,ba=0,pa=0|1,brd=MAPPER191,sys=
Since this is iNES we can (somewhat) confidently parse PRG/CHR banks to hash.
headerless rom hash: sha1:568BF236FB3085B8BD522FBD2C18C7831E3A2DD1
headerless rom hash:  md5:6843BAE61D53B0EC08EA2962C3933C74
DB: hash md5:6843BAE61D53B0EC08EA2962C3933C74 not in game database.
Chose board from bizhawk gamedb: SACHEN-8259A
Final game detection results:
pr=256,ch=0,wr=0,vr=8,ba=0,pa=0|0,brd=SACHEN-8259A,sys=
""
Implemented by: class Sachen8259ABC
END NES rom analysis
------
Rom is of unknown NES region!
Using NES system region of NTSC
Core reported BoardID: "Sachen8259ABC"
Active Firmwares:
  NES+Bios_FDS : 57FE1BDEE955BB48D357E463CCBF129496930B62
```

Log from BizHawk 2.7.0:
```
ROM was not a multiple of 1024 bytes, and not a recognized header size: 16. Assume it's purely ROM data.
------
BEGIN NES rom analysis:
Found iNES header:
pr=256,ch=0,wr=8,vr=8,ba=0,pa=0|1,brd=MAPPER191,sys=
Since this is iNES we can (somewhat) confidently parse PRG/CHR banks to hash.
headerless rom hash: SHA1:82DF6C92D76D1487556F52BAFC16F4660B16B585
headerless rom hash:  MD5:5A1BB914687C8567F27F3FE4935EE099
DB: hash MD5:5A1BB914687C8567F27F3FE4935EE099 not in game database.
DB: hash SHA1:82DF6C92D76D1487556F52BAFC16F4660B16B585 not in game database.
Could not locate game in bizhawk gamedb
Could not locate game in nescartdb
Attempting inference from iNES header
Chose board from iNES heuristics:
pr=256,ch=0,wr=8,vr=2,ba=0,pa=0|1,brd=MAPPER191,sys=
Final game detection results:
pr=256,ch=0,wr=8,vr=2,ba=0,pa=0|1,brd=MAPPER191,sys=
""
Implemented by: class Mapper191
END NES rom analysis
------
Rom is of unknown NES region!
Using NES system region of NTSC
Core reported BoardID: "Mapper191"
Active Firmwares:
  NES+Bios_FDS : 57FE1BDEE955BB48D357E463CCBF129496930B62
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6.2; Win10 Pro 21H2 (works)
- BizHawk 2.7.0; Win10 Pro 21H2 (does not work)

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Looks like #3027. Please try 2.8 RC1.

**Comment by mooware** [comment]
Works in 2.8 RC1.
