### ISSUE TITLE
GLideN64: Texture wildcard support

### ISSUE THREAD

**Issue by GhostlyDark** [TASEmulators/BizHawk#3104]
As BizHawk is stuck with an older GLideN64 version it lacks wildcard support. Wildcards are a very useful feature for texture artists to easily retexture infinitely dumping duplicates of Ocarina of Time's skyboxes or infinite dumps of green and red shells in Mario Kart 64.

More info on what it is:
https://github.com/gonetz/GLideN64/pull/2441

Cherrypicking this commit will work without conflicts:
https://github.com/gonetz/GLideN64/commit/31b38a7a2bdf4d9cfbe9dc928e3a385866f2c32f

Changes don't negatively affect any texture packs or cache files.

**Comment by vadosnaprimer** [comment]
Does that commit fix it?

**Comment by GhostlyDark** [comment]
Yup. Wildcarded skybox loads after generating the cache using current master. Works as intended.
![image](https://user-images.githubusercontent.com/31742919/151659497-98ea32ec-3d5f-4824-ae0d-472ec1b921b0.png)
