### ISSUE TITLE
Gambatte: LCD Display Disabled causes static color 0xFFFFFF to be displayed, no matter the palette (such as BGB (lcd green))

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3106]

**Comment by CasualPokePlayer** [comment]
This is intended.

**Comment by getCursorsExe** [comment]
Did you compare this with BGB?

![image](https://user-images.githubusercontent.com/39802077/151672436-cb7e3aba-86aa-4fe8-962f-42192ecd86d4.png)

**Comment by getCursorsExe** [comment]
BGB actually gets this right! On hardware the LCD does not completely disappear, but only graphics.

**Comment by CasualPokePlayer** [comment]
A "whiter than white" color should appear (so it's intentionally set to the whitest color available). And as far as Gambatte sees, using a DMG palette other than grayscale is custom and does not have to have any semblance to reality.

**Comment by getCursorsExe** [comment]
Now there is a mismatch between SameBoy and Gambatte.

**Comment by CasualPokePlayer** [comment]
They're different cores.
