### ISSUE TITLE
Readd SameBoy as SGB core (due to movie backwards compability issues)

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3107]
I noticed that SameBoy SGB movies are not compatible with current version of BizHawk. As soon as I try to load them, BizHawk just switches to NullHawk. Even if this would not happen, the movie will be desynced. Is this due to absence of SameBoy SGB core?

**Comment by nattthebear** [comment]
There's no promise of forward compatibility of movies ever, and especially not when a core is removed outright.  Reading a movie as being for a core that it wasn't made for would mean we'd have to discard syncsettings entirely, and it has about a 0% chance of syncing directly.  As always, if you want to forward import movies, you have to resync them and resettings them.
