### ISSUE TITLE
Hard-crash at OAM DMA Bus Conflict test ROM in SameBoy

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3108]
Do you remember #2709? Well, now something is wrong with SameBoy core. Viewing the hell1 test ROM does not show anything (unlike GBHawk and Gambatte). Now we don't know if SameBoy get's this right or not.

**Comment by CasualPokePlayer** [comment]
Go to upstream to complain about this. DMAs in general are still under todos and currently being worked on there.
