### ISSUE TITLE
Savestates (and branches in TAStudio) are 0-indexed

### ISSUE THREAD

**Issue by Morilli** [TASEmulators/BizHawk#3112]
Not sure whether it's just me or I am missing something, but I feel like it would make more sense if savestates and branches were 1-indexed instead of 0-indexed, aka the first savestate/branch is 1, the second 2, and so forth.

Main reasoning for me personally is that I like to make and load TAStudio branches via the savestate hotkeys (F1-F10 to load and Shift+F1-F10 to save), and I can either not save branch 0 comfortably, or I offset my hotkeys by 1 (aka F1 loads branch 0, F2 loads branch 1, etc.), which is also weird to keep in mind all the time.

Idk, maybe you're supposed to treat branch 0 as something special or something, but in my workflow at least it is just the first branch to me.

**Comment by YoshiRulz** [comment]
see also #2023

**Comment by TizianoMattei** [comment]
Personally i use the save/load state/branch nr.0 to be exclusively assigned to controller keybinds, whenever im testing something before, or even during the works of a TAS, depending on the situation

That said it wouldnt be that big of a problem if that ends up being changed

**Comment by Morilli** [comment]
> Personally i use the save/load state/branch nr.0 to be exclusively assigned to controller keybinds (which leaves f1 to f10 the rest of states)

You mean F1-F9 for the remaining states, right? Considering that there are only 10 savestates hotkeyable. In that case just using the 10th savestate instead of the 0th should work for you, although that is perhaps a little less "separated" logically.

**Comment by TizianoMattei** [comment]
> You mean F1-F9 for the remaining states, right? Considering that there are only 10 savestates hotkeyable. In that case just using the 10th savestate instead of the 0th should work for you, although that is perhaps a little less "separated" logically.

Yes, apologies, i meant that.
Yea that would work, just shared to give a perspective on how some of the userbase might have used the save/load state 0

**Comment by Morilli** [comment]
![image](https://user-images.githubusercontent.com/35152647/153225980-df9ceb81-de68-4653-b31d-f0630c9226ae.png)
Branch numbers on the left side in TAStudio are still 0-indexed, otherwise this looked good.
