### ISSUE TITLE
MelonDS throws OutOfRangeException if FirmwareMessage is set to empty string

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3120]
### Repro
0. (Not sure if necessary) Use the actual NDS firmware files.
1. Set Firmware Override to on
2. Set Firmware Message to blank (no characters)
3. Try to run ROM
![image](https://user-images.githubusercontent.com/83939/152574739-308e90f9-9c26-4b88-967d-723d6b3eab57.png)

### Host env.
- BizHawk 2.7; Win8.1; AMD

**Comment by CasualPokePlayer** [comment]
This was already fixed in 2.8 dev.
