### ISSUE TITLE
[melonDS] Autofire Controls don't work

### ISSUE THREAD

**Issue by Real96** [TASEmulators/BizHawk#3127]
### Summary
Pressing autofire controls in game doesn't work.
I tryed enabling "Display Input" option and it seems that the keys are being pressed every frame, but in game they don't do nothing. I tryed this on GB/GBA and they work correctly instead.

### Repro
1. `Config` > `Controllers` > `Autofire Controls` > Set A and B keys
2. Run any DS game
3. Press in game the keyboard keys you set above

### Output
Nothing happens in game

### Host env.
- BizHawk 2.8 Win10 Pro, commit f4b4c60

**Comment by CasualPokePlayer** [comment]
They work, although some games might need tweaking to account for invisible lag. Go to Config->Autofire and change your pattern to a 30 FPS turbo instead of a 60 FPS turbo. (1/1 on/off to 2/2 on/off).
