### ISSUE TITLE
[Nymashock] multiple encode files caused by changing resolution too much

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#3129]
To reproduce, open any psx game(i.e destruction derby raw)
start ffmpeg encode
Let it play until like the main menu
Notice multple video files made

The first one would be the bios screen.
Second is just some short static nothingness.
Another one is a trade mark
And another is a fmv video
and so on so forth.

This means you have to stitch everything in some other encoding software.

Is there anyway to make it so that you have 1 encode file?

**Comment by vadosnaprimer** [comment]
https://tasvideos.org/Bizhawk/FAQ#HowToPreventSplittingOnResolutionChanges
