### ISSUE TITLE
Actually implement CoreForce flag in gamedb

### ISSUE THREAD

**Issue by ThunderAxe31** [TASEmulators/BizHawk#3131]
There are many games that only work properly if used with a specific emulation core. We want to have BizHawk forcing to use the preferred core for that. We may ignore this for cores that are being actively updated, like Gambatte and GBHawk. Good examples of where this would be needed, is for cases like NES games that use the MMC3_Jncota mapper, for which the graphics are processed only in NESHawk.

Note that there is already a CoreForce flag mentioned in the `gamedb_nes.txt` file, but it does nothing, as there is no logic coded in BizHawk for it.

**Comment by YoshiRulz** [comment]
There is no CoreForce option or flag in the gamedb.

**Comment by Eggo-dotcom** [comment]
If memory serves years ago we had for core override and it was removed

**Comment by YoshiRulz** [comment]
So I don't think this is a good idea. If a core can't load a game, its constructor should throw (see QuickNes for an example of a blocklist). If a core can't run a game properly, it should warn the user, and let them decide whether to change preferred core or not. Any circumstance in which you'd want to control cores via customising the gamedb could instead be done by changing preferred core.
