### ISSUE TITLE
BizHawk shouldn't just crash if game.db or /gamedb is deleted, right?

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3137]
GameDB seems like a relatively inessential part of the program, so deleting files from the gamedb directory (which I've been trying to do because I don't like the way it forces SaveRAM filenames to conform to the DB names) shouldn't cause the whole thing to not launch at all.

**Comment by YoshiRulz** [comment]
Duplicate of #2939.
