### ISSUE TITLE
[Glitch] Unstable movie import ( Snex9X 1.6.0 --> Bizhawk 1.7.0) 

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3143]
Unstable movie import ( Snex9X 1.6.0 --> Bizhawk 1.7.0) 
Snes9X Play's Movie without Deaths.
Mario in Bizhawk movie dies at ~3 minutes.
P.S I can record a video if needed.

**Comment by CasualPokePlayer** [comment]
There is no guarantee at sync with a movie import. Different emulators have different levels of accuracy and thus may lag differently, have different rng, etc. You are expected to manually resync a movie you import.
