### ISSUE TITLE
Update, Remove or at least make SNES9X not the default SNES emulator.

### ISSUE THREAD

**Issue by nameless01234567** [TASEmulators/BizHawk#3144]
Self explanatory, the current version is a old and not very accurate version that glitches some games like Megaman X.
The emulator has newer more accurate versions, but if that isn't a possibilty consider removing or at least making the default option for future releases BSNES or Faust. That would make BizHawk more practical to use.

**Comment by nattthebear** [comment]
A new SNES core is unlikely, so making it not the default is the most likely.  Would Faust be a good default?

**Comment by nameless01234567** [comment]
As long as it is a good, stable version instead of focused on compatibility like SNES9X, it would be fine.

**Comment by nattthebear** [comment]
> As long as it is a good, stable version instead of focused on compatibility like SNES9X, it would be fine.

Well that's what I'm asking; is Faust good and stable?  I don't actually use any of these cores much at all.

**Comment by nameless01234567** [comment]
I use bsnes and got no issues, so there is my recomendation.

**Comment by nattthebear** [comment]
Hmm, likely too slow for potato computers, although maybe times have changed there.

**Comment by Shinobi-1987** [comment]
I would use snes9x 1.61 for a potato. More compatible and lighter than faust. Ide use benes 115 on real computer

**Comment by nattthebear** [comment]
We don't currently have a snes9x 1.61 port, and it's not likely worth the dev effort just for potatoes

**Comment by Shinobi-1987** [comment]
> We don't currently have a snes9x 1.61 port, and it's not likely worth the dev effort just for potatoes

Ide just leave current snes9x for potato lol

**Comment by YoshiRulz** [comment]
I'd like to reiterate that we are not considering whether to *remove* Snes9x. We are considering changing the *default* to Faust.

**Comment by Shinobi-1987** [comment]
> I'd like to reiterate that we are not considering whether to _remove_ Snes9x. We are considering changing the _default_ to Faust.

Faust is slow and even compared to 1.54 has issues with compatibility.

**Comment by nameless01234567** [comment]
There are currently two versions of bsnes, if the need of snes9x is for potato computers maybe do that with a new snes9x version?

**Comment by Shinobi-1987** [comment]
> There are currently two versions of bsnes, if the need of snes9x is for potato computers maybe do that with a new snes9x version?

I guess you didnt read the whole thread

**Comment by nameless01234567** [comment]
I read the whole thread, all I'm saying is that if snes9x is the best for potato computers, as said by yourself, then to CONSIDER that going forward, because the current version of snes9x has severe compatibility issues, but if you guys prefer to leave the one that is already there, that is beyond me.

**Comment by Shinobi-1987** [comment]
> I read the whole thread, all I'm saying is that if snes9x is the best for potato computers, as said by yourself, then to CONSIDER that going forward, because the current version of snes9x has severe compatibility issues, but if you guys prefer to leave the one that is already there, that is beyond me.

1.61 ram would be nice-but i dont think they want to

**Comment by nameless01234567** [comment]
Doesn't mean it shouldn't be suggested.

**Comment by Shinobi-1987** [comment]
> Doesn't mean it shouldn't be suggested.

Good point

**Comment by YoshiRulz** [comment]
It's recently come up that Faust does not have a "System Bus" domain, preventing cheats from working (see also #3486). It also does not implement `IDebuggable` or `IDisassemblable`.
![2022-12-10T05:36:17](https://user-images.githubusercontent.com/13409956/206783196-3b3aa4a1-d3d9-4f94-b7c4-cf3cca34c54f.png)

**Comment by vadosnaprimer** [comment]
Updated.
