### ISSUE TITLE
Mega CD / Sega CD Firmware Not Shown in Firmwares Window

### ISSUE THREAD

**Issue by boktai1000** [TASEmulators/BizHawk#3145]
### Summary
The Mega CD firmware does not show up in the Firmwares list in BizHawk 2.7.0 x64

### Repro

1. Open Firmwares from Config>Firmwares
2. Scroll and view through the options and you will not see Mega CD (or Sega CD) listed in the GUI window.

### Host env.

- BizHawk 2.7.0; Win10 Pro 21H1 Intel

![image](https://user-images.githubusercontent.com/9054563/153997288-16ec06ab-e8f8-4b87-a309-971f77a1ff46.png)
![image](https://user-images.githubusercontent.com/9054563/153997327-311b377a-6e20-442f-b34d-953383421ba7.png)

**Comment by YoshiRulz** [comment]
It's literally in the second screenshot you posted, under Genesis.
