### ISSUE TITLE
Ares64-Peformance renders image with resolution 1x1 (or maybe 0x0) when starting a ROM if Vulkan is enabled

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3151]
This allows BizHawk to become this mess:
![image](https://user-images.githubusercontent.com/39802077/154267060-7d5d0bd9-e383-4415-9eda-ebdedf70029d.png)

**Comment by CasualPokePlayer** [comment]
This shouldn't be an issue as virtual width is hardcoded to be 640x480, is there some setting overriding that?
