### ISSUE TITLE
Linux files in windows version? (BizHawk-2.8-win-x64.zip)

### ISSUE THREAD

**Issue by poesdelal** [TASEmulators/BizHawk#3163]
Are these linux files (.so and .gz) in /dll need to be there in windows version?

**Comment by YoshiRulz** [comment]
The `.so` files probably don't *need* to be there. I'll leave this open as a reminder.

**Comment by CasualPokePlayer** [comment]
the .gz files are waterbox cores and used in both the Windows and Linux versions (effectively cross platform in a way).

**Comment by nattthebear** [comment]
How did you come to the conclusion that a file whose name ends in `.gz` is for Linux? 😕

**Comment by poesdelal** [comment]
I opened in with 7-zip and check .wbx file inside - it's ELF.

"Gzip is a popular data compression program originally written for the GNU project.

ELF that abbreviates Executable and Linkable Format. It is widely used for executable files, relocatable object files, shared libraries, and core dumps.

Twenty years ago – in 1999 – the 86open project has chosen ELF as the standard binary file format for Unix and Unix-like systems on x86 processors.

Since then, the ELF format is in use by several different operating systems. Among others, this includes Linux, Solaris/Illumos, Free-, Net- and OpenBSD, QNX, BeOS/Haiku, and Fuchsia OS [2]. Furthermore, you will find it on mobile devices running Android, Maemo or Meego OS/Sailfish OS as well as on game consoles like the PlayStation Portable, Dreamcast, and Wii."

**Comment by nattthebear** [comment]
Interesting!  Didn't think anyone would go to that level of effort.  Yes, it is an ELF, but as explained this particular ELF is loaded by our custom Waterbox ELF loader and is actually multiplatform.

**Comment by CasualPokePlayer** [comment]
I think this is "fixed" with https://github.com/TASEmulators/BizHawk/commit/e0e5a68c5058195d5a25798d7a88d5fcb7893bf1
