### ISSUE TITLE
[NDS] SaveRAM does not automatically flush when rebooting core

### ISSUE THREAD

**Issue by InfoManiac742** [TASEmulators/BizHawk#3165]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Saves for DS games are reverted when using the Ctrl-R command to refresh the core.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load any DS game with a save feature
2. Save the game
3. Use Ctrl-R to reset the core
4. The save data will have reverted to what it was before you saved

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8; Windows 10

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by vadosnaprimer** [comment]
For the reference https://github.com/TASEmulators/BizHawk#in-game-saves

**Comment by CasualPokePlayer** [comment]
Rebooting the core completely throws it out and creates a brand new core. If the SaveRAM was not flushed either automatically or manually you will lose save data.

**Comment by InfoManiac742** [comment]
So if I'm interpreting everything right that means that means that automatic flushing isn't working properly for the MelonDS core

**Comment by nattthebear** [comment]
Saveram should autoflush on rebooting a core, this works for every other core

**Comment by Xelrog** [comment]
I am on 2.9.1 and still having what seems to be this issue. Save files are in my BizHawk NDS saves folder, but they are not recognized. Tested with Animal Crossing Wild World and Pokemon Diamond - both games start every time as if no save data exists, and only have new game options.

**Comment by CasualPokePlayer** [comment]
> Save files are being created in my BizHawk NDS saves folder

This itself means this is not the same issue.

I cannot reproduce the issue you are reporting either. Save game, reboot core, save appears to be recognized just fine.
