### ISSUE TITLE
[PS1] Screenshots are completely transparent

### ISSUE THREAD

**Issue by InfoManiac742** [TASEmulators/BizHawk#3166]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Screenshots are entirely transparent when using a PS1 core (the proper RGB channels are still present, and the image can be fixed if the alpha channel is manually changed). This issue occurs on both Octoshock and Nymashock. (Note: I've only tested this on Castlevania: Symphony of the Night since that's the only PS1 game I have)

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load a PS1 game (Core doesn't matter)
2. Make sure File > Screenshot > Capture OSD is unchecked
3. Press F12 to take a screenshot (or using File > Screenshot > Screenshot As)
4. The screenshot file will be completely transparent

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8; Windows 10

Broken screenshot:
<img width="280" alt="transparent_screenshot" src="https://user-images.githubusercontent.com/26778801/155242143-151b2696-bfa4-4011-a81f-33d96f0a730c.png">
Screenshot with OSD (not broken):
<img width="1280" alt="screenshot_with_osd" src="https://user-images.githubusercontent.com/26778801/155242129-25e1690d-4dd3-41e2-ab20-e1d0b35c1877.png">

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by nattthebear** [comment]
Does it makes sense for the FE to always fill in alpha here when composing a screenshot?

**Comment by mooware** [comment]
I had this issue with the BSNESv115+ core, for some reason it's fine with the regular BSNES core. Was about to report it, but then I tried it with the most recent source and found it already fixed.
