### ISSUE TITLE
Loading savestate after reset is broken on bsnesv115+

### ISSUE THREAD

**Issue by 0xwas** [TASEmulators/BizHawk#3173]
### Emulator
Bizhawk 2.8

### Repro
1. Load any snes games with said core.
2. Hard reset at any point.
3. Try to load savestate.

That process leads crashing emu without warning, making emu stuck loading state for good or open state normally. That didn't occur in 2.7.

**Comment by nattthebear** [comment]
Your repro steps don't include saving a savestate... where are you getting a savestate from?

**Comment by CasualPokePlayer** [comment]
Can not reproduce (using Super Puyo Puyo (Japan)). What games exhibit this behavior? When are you actually creating the savestate?

**Comment by CasualPokePlayer** [comment]
Able to reproduce. I would suspect it's due to the changes to reduce state size (yes natt you can say "I told you so").

**Comment by nattthebear** [comment]
> Able to reproduce.

Could you answer my question then, what state are you saving?

**Comment by CasualPokePlayer** [comment]
Saved some state before the hard reset (or soft reset, either break it), loaded after reset.

**Comment by Morilli** [comment]
Easiest possible fix (plus the required *HeapSizeKB changes in `BsnesApi.cs`):
```diff
diff --git a/waterbox/bsnescore/bsnes/sfc/memory/memory.cpp b/waterbox/bsnescore/bsnes/sfc/memory/memory.cpp
index c9174e7ee..0e54571ae 100644
--- a/waterbox/bsnescore/bsnes/sfc/memory/memory.cpp
+++ b/waterbox/bsnescore/bsnes/sfc/memory/memory.cpp
@@ -25,8 +25,8 @@ auto Bus::reset() -> void {
   //lookup = new uint8 [16 * 1024 * 1024]();
   //target = new uint32[16 * 1024 * 1024]();

-  if (!lookup) lookup = alloc_invisible<uint8> (16 * 1024 * 1024);
-  if (!target) target = alloc_invisible<uint32>(16 * 1024 * 1024);
+  if (!lookup) lookup = alloc_plain<uint8> (16 * 1024 * 1024);
+  if (!target) target = alloc_plain<uint32>(16 * 1024 * 1024);

   reader[0] = [](uint, uint8 data) -> uint8 { return data; };
   writer[0] = [](uint, uint8) -> void {};
```

However, this brings the issue of state size exploding on reset again...

what I think is happening is that `lookup` (or `target`, not sure tbh) contains function pointers to specific functions that should be called to read or write values. The idea behind not savestating this memory would be that these functions stay the same for a loaded game, therefor it's not necessary to re-initialize or store the state of those arrays; they will stay the same.
I'm actually not quite sure why those function pointers (or maybe something else?) seem to no longer be valid after a reset + loading of the savestate; knowing why that happens would certainly help here.

In any case, here's an example `backtrace` of the `SIGSEGV` that gets thrown on a frameadvance after loading a savestate:
```
nall::function<unsigned char (unsigned int, unsigned char)>::operator()(unsigned int, unsigned char) const (this=0x36f00313dd8 <SuperFamicom::bus+88>, p#0=504, p#1=122 '<error reading variable>) at ./bsnes/nall/function.hpp:29
29        auto operator()(P... p) const -> R { return (*callback)(forward<P>(p)...); }
(gdb) bt
#0  nall::function<unsigned char (unsigned int, unsigned char)>::operator()(unsigned int, unsigned char) const (
    this=0x36f00313dd8 <SuperFamicom::bus+88>, p#0=504, p#1=122 '<error reading variable>)
    at ./bsnes/nall/function.hpp:29
#1  0x0000036f001086bb in SuperFamicom::Bus::read (data=122 '<error reading variable>, addr=504, this=<optimized out>)
    at ./bsnes/sfc/memory/memory-inline.hpp:31
#2  SuperFamicom::CPU::read (this=0x36f00315360 <SuperFamicom::cpu>, address=504) at bsnes/sfc/cpu/memory.cpp:43
#3  0x0000036f000225f1 in Processor::WDC65816::pull (this=0x36f00315360 <SuperFamicom::cpu>)
    at bsnes/processor/wdc65816/memory.cpp:36
#4  Processor::WDC65816::instructionPull16 (this=0x36f00315360 <SuperFamicom::cpu>, T=...)
    at bsnes/processor/wdc65816/instructions-other.cpp:189
#5  0x0000036f0002930c in Processor::WDC65816::instruction (this=0x36f00315360 <SuperFamicom::cpu>)
    at bsnes/processor/wdc65816/instruction.hpp:124
#6  0x0000036f0010f01e in SuperFamicom::CPU::main (this=0x36f00315360 <SuperFamicom::cpu>) at bsnes/sfc/cpu/cpu.cpp:46
#7  0x0000036f0010ec04 in SuperFamicom::CPU::Enter () at bsnes/sfc/cpu/cpu.cpp:30
#8  0x0000036f0026227a in alloc_thread (size=3775442534384) at amd64.c:72
Backtrace stopped: Cannot access memory at address 0x36f09e94000
```
