### ISSUE TITLE
[import Movie] .smv import on BSNES Core, when Snes9X core selected.

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3177]
.smv import on BSNES Core, when Snes9X core selected.
There was also a notice that was fixed, about the core too, but still the movie has a BSNES core, not SNES9X.
PS It is necessary to check the operation of the movie from the SNES9x emulator on SNES9x and BSNES cores.

**Comment by YoshiRulz** [comment]
see also #3022
