### ISSUE TITLE
[Recording Codec Problem] Xvid Status Won't work on BizHawk 2.8

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3178]
[Recording Codec Problem] Xvid Status Won't work on BizHawk 2.8
When Xvid Degub enabled, xvid status won't work, On Snes9x work's good.
![image](https://user-images.githubusercontent.com/38865696/158018135-ed704183-bb91-45bd-bb28-6190e0431573.png)

**Comment by YoshiRulz** [comment]
What are the steps you did to cause this? To my knowledge, Xvid is not part of our A/V recording feature.

**Comment by Danik2343** [comment]
Yes, officially Xvid is not included in the Emulator, I installed this codec, it records video, but does not show Xvid status per frame, there is such a function, show Xvid status, it works in Snes9x, but does not work on BizHawk.
Reason: The Show Xvid Status feature is enabled

**Comment by YoshiRulz** [comment]
Right, well we're not going to look into bugs in external programs and change EmuHawk to suit them. Use FFmpeg or one of the other A/V options then transcode afterwards.
