### ISSUE TITLE
SameBoy's GB detection when running GBC is broken

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3185]
White areas in the middle of the game, affects literally anything.

![image](https://user-images.githubusercontent.com/39802077/159116505-f3300747-255d-42b8-bb0d-08df5227e682.png)

This is due to VRAM memory domain addresses 0x38A0 through 0x39CF being set to 0xFF instead of 0x00. The Bank 2 (CGB exclusive) is also corrupted (addresses 0x2000 through 0x240F).

**Comment by CasualPokePlayer** [comment]
Oh right, this is mostly due to a bug in SameBoy's built in bootroms. It ended up working in SameBoy due to inaccuracies, although SameBoy updates ended up fixing those inaccuracies and making this bug surface. Use real bootroms to get around this for now.
