### ISSUE TITLE
Order of the Griffon (USA) password screen

### ISSUE THREAD

**Issue by Shinobi-1987** [TASEmulators/BizHawk#3188]
Order of the Griffon (USA)

password screen missing letters. Happens in Bizhawk all builds in Turbonyma, Hypernyma and PCEHawk

Fixed in Mednafen 1.29

screenshots attached

Bizhawk render

![bizhawk](https://user-images.githubusercontent.com/99974890/159695870-8059a2c6-175d-4020-a3c5-035531260efd.JPG)

And latest mednafen 1.29 stable with fix render

![Order of the Griffon (USA)-0000-mednafen1 29](https://user-images.githubusercontent.com/99974890/159695939-9c7b3e3a-aba3-4ac1-950a-6bcef383ab5e.png)

**Comment by Shinobi-1987** [comment]
Is the update to upstream a possibility?

**Comment by CasualPokePlayer** [comment]
e6d74c3167ad8ffb6ce7b90d84bd609028016d53 updated to 1.29.0, is it fixed here?

**Comment by Shinobi-1987** [comment]
> [e6d74c3](https://github.com/TASEmulators/BizHawk/commit/e6d74c3167ad8ffb6ce7b90d84bd609028016d53) updated to 1.29.0, is it fixed here?

Yes thanks!! fixed.

This also fixes some minor r-type glitches!! Thanks so much for doing this.

On a side note the about section still lists core as 1.27.1
