### ISSUE TITLE
(Regression) screenshot works pcehawk fails nyma core

### ISSUE THREAD

**Issue by Shinobi-1987** [TASEmulators/BizHawk#3189]
Taking a screenshot works in PCEHawk, fails in Turbo And Hyper Nyma.

JUst run a PCE game in Turbo Or Hypernyma, take a screenshot and you get a black picture.

**Comment by CasualPokePlayer** [comment]
Possibly just this https://github.com/TASEmulators/BizHawk/issues/3166

**Comment by nattthebear** [comment]
Yes, this is definitely that issue.
