### ISSUE TITLE
AVI/WAV stop function after Movie Finished

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3191]
Add AVI/WAV recording auto-completion function after Movie finishes playing, it will be very helpful to leave PC at night and not delete unnecessary frames that were recorded after MOVIE finished.

**Comment by nattthebear** [comment]
Can you use pause movie when playback is finished to approximate this behavior?

**Comment by YoshiRulz** [comment]
IIRC A/V recodring via the command-line will also cause EmuHawk to close when it's finished.

**Comment by Danik2343** [comment]
Yes, thanks for the answer, but I would like it to end automatically, because 9 hours of longplay, set for the night, and in the morning the recording will be stopped.

**Comment by nattthebear** [comment]
Yes, and both workarounds mentioned handle exactly that scenario.  In either case, there will be no extra frames that need to be removed.
