### ISSUE TITLE
Window size 4x 5x works as 3x?

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#3193]
2.8 stable, 1x 2x 3x are works fine, but 4x 5x are works as 3x.
![QQ20220329120348](https://user-images.githubusercontent.com/54294476/160531094-7ad6b449-7012-417f-a928-f7deb3d69605.png)

**Comment by CasualPokePlayer** [comment]
Your screen isn't big enough for 4x/5x so they don't do anything.

**Comment by Yave-Yu** [comment]
> Your screen isn't big enough for 4x/5x so they don't do anything.

I think 1920x1080 enough to contain 4x but it doesn't...

**Comment by CasualPokePlayer** [comment]
Space status bar and such take is accounted for in calculation, along with Window's bar on the bottom (or top, wherever you have it). The latter might be more problematic if you're on Windows 11.
