### ISSUE TITLE
Win10 version check can fail sometimes

### ISSUE THREAD

**Issue by ayunami2000** [TASEmulators/BizHawk#3194]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
BizHawk fails with no sound devices.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. have NO sound devices (at all)
2. see image:
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/24785136/160607872-ee94d5f8-b203-42dc-a647-9a9549bfb84c.gif)

### Output

[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BizHawk.Common.OSTailoredCode.<.cctor>g__GetRegValue|18_3(String key)
   at BizHawk.Common.OSTailoredCode.<>c.<.cctor>b__18_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at BizHawk.Client.EmuHawk.MainForm..ctor(ParsedCLIFlags cliFlags, IGL gl, Func`1 getConfigPath, Func`1 getGlobalConfig, Action`1 updateGlobalSound, String[] args, IMovieSession& movieSession, Boolean& exitEarly)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk [latest development build](https://gitlab.com/TASVideos/BizHawk/-/commit/15270adebebea26c1cde4333355f5e4bdda038bd); Windows 10 Education 10.0.19043; Intel
- BizHawk 2.8; Windows 10 Education 10.0.19043; Intel

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

### Expected behavior

Allow BizHawk to not initialize sound if there are no sound devices.

**Comment by YoshiRulz** [comment]
This isn't related to audio. The error that appears is part of a failsafe:
https://github.com/TASEmulators/BizHawk/blob/15270adebebea26c1cde4333355f5e4bdda038bd/src/BizHawk.Client.EmuHawk/MainForm.cs#L470-L482

The stacktrace points to the Windows version detection, which admittedly I haven't tested on Win11. Could you try writing `{"SkipOutdatedOsCheck":true}` to `config.ini`?

**Comment by ayunami2000** [comment]
Well guess that worked! I'll close this since the title is wrong, but it definitely needs to be clearer or fixed still.

**Comment by Morilli** [comment]
`10.0.19043` is not a windows 11 version though?

**Comment by ayunami2000** [comment]
I think it's to do with it being Windows 10 Education, all values are intact:

CurrentVersion: 6.3
ProductName: Windows 10 Education
ReleaseId: 2009

**Comment by Morilli** [comment]
Does anything special happen when running the corresponding `REG` commands from a shell prompt, like `cmd` or `powershell`?
e.g. `REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /V ReleaseId`?

**Comment by ayunami2000** [comment]
I think we have the issue: "Registry editing has been disabled by your administrator." I know for a fact you can still edit registry values (I use a third party program for it and it works fine) but I guess the method BizHawk uses won't work. Maybe try making it use native Windows APIs if it doesn't already do that?

**Comment by Morilli** [comment]
BizHawk is using the `REG` command to retrieve these values, which is why I asked you to try them as is. I'm pretty sure this is a very native way of retrieving registry values.

**Comment by ayunami2000** [comment]
I mean like an API version rather than a command (which is calling a separate program every time it wants to mess with the registry...)

**Comment by ayunami2000** [comment]
I think this is the right thing: https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registry.setvalue?view=net-6.0

**Comment by YoshiRulz** [comment]
Should probably switch to that if it's available in .NET Framework and .NET Core. I want to say I tried it and Mono's `msbuild` complained, but I can't remember.
