### ISSUE TITLE
MelonDS Rewinds at very low speed

### ISSUE THREAD

**Issue by dennisrijsdijk** [TASEmulators/BizHawk#3198]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
MelonDS rewinds at 4-5 fps, compared to running at ~60 fps

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. launch bizhawk 2.8
2. launch any NDS game
3. View > enable Display FPS
4. press and hold Shift + R

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8; Win11 Home 22H2; Intel/NVIDIA

**Comment by YoshiRulz** [comment]
Not entirely sure this is a bug; how does melonDS compare to other Waterboxed cores, such as BSNES?

**Comment by CasualPokePlayer** [comment]
Could be related to melonDS' rather big states and how that typically ends up with "gaps" between stated frames.

**Comment by dennisrijsdijk** [comment]
> Not entirely sure this is a bug; how does melonDS compare to other Waterboxed cores, such as BSNES?

On BSNESv115+ and BSNES I get a rewind at 50 FPS (PAL game)

**Comment by dennisrijsdijk** [comment]
> Could be related to melonDS' rather big states and how that typically ends up with "gaps" between stated frames.

there doesn't appear to be any "gaps" between the frames on my end. I'll make a quick tool so I can see the frame count though because I could be wrong

**Comment by CasualPokePlayer** [comment]
Checked out rewind, and it's exactly as I thought. The FPS counter tanks to "3" FPS, although there's around 17 frames in between each state (the "gaps" I was referencing"), so in reality it's operating closer to "60" FPS.

The best "fix" for this really is to turn on the delta compressor, as that will shrink states down to ~100KB. It may however tank performance to below 60 FPS (for me it hovers around 50 FPS).

**Comment by dennisrijsdijk** [comment]
Gotcha, I'll give this a shot on 2.8, as well as on 2.8-dev to see if performance increases any on that

**Comment by CasualPokePlayer** [comment]
Any update on this?

**Comment by dennisrijsdijk** [comment]
I haven't had an opportunity yet due to some issues arising with my machine. Will update when I have a chance.
