### ISSUE TITLE
SM64 crashes bizhawk RTC 5.0.6 on start

### ISSUE THREAD

**Issue by Milopk11** [TASEmulators/BizHawk#3204]
Hello, today after not using my pc for weeks i got on and decided to corrupt sm64 because it was my favorite thing to do, when for some reason bizhawk froze and about 5-15 seconds later it closed. I was using GLideN64 on Direct3D9. I switched to rice core and it didnt crash, but the textures were destroyed. I have a picture below of mario who was only one of the many things that got destroyed.
![glitch](https://user-images.githubusercontent.com/86530003/161448743-7fd32a27-21a3-4a0a-a91d-a71685ca5a19.png)
Theres this too. I have no idea what it is, but i assume mario is falling through the ground and into a special area.
![Super Mario 64 (USA) 2022-04-03 17 37 13](https://user-images.githubusercontent.com/86530003/161449750-98b3deb9-3480-4cb9-97e1-15263db39ffa.png)
Does anyone now how to fix this? I use windows 10.

**Comment by Milopk11** [comment]
Duplicate of #)_!)%*_)@)#)+!_____((((((((((((((

**Comment by Milopk11** [comment]
the video broke

**Comment by Milopk11** [comment]
![Super Mario 64 (USA) 2022-04-03 17 40 38](https://user-images.githubusercontent.com/86530003/161449898-c55d3f8c-b248-4b65-b808-5b03b5e0ba0c.png)
Somethings happening. The press start button is still flashing so its not frozen, but mario just got.. turned into whatever that is. And RTC is not open.

**Comment by YoshiRulz** [comment]
This is the issue tracker for BizHawk. For help with RTC Vanguard, join [their Discord](https://redscientist.com/discord).

**Comment by Milopk11** [comment]
> This is the issue tracker for BizHawk. For help with RTC Vanguard, join [their Discord](https://redscientist.com/discord).

Its not about rtc. Its with bizhawk itself. The problem persists even without rtc open.

**Comment by YoshiRulz** [comment]
Can you grab a fresh copy of 2.8 and confirm it's not rendering properly?

**Comment by getCursorsExe** [comment]
The RTC uses 2.3.2, an old version of BizHawk.
