### ISSUE TITLE
 [Feature Request] Nyma Cores Selecting the Disk and Nubmer the Disk

### ISSUE THREAD

**Issue by Spikestuff** [TASEmulators/BizHawk#3206]
Currently the Nyma cores only have "previous disk" and "next disk" as its options but it doesn't state which disk you're currently using.

It also doesn't allow the freedom for instance when you need to go from Disk 1 to Disk 4 where instead you're forced to skim over Disk 2 and 3.

**Comment by CasualPokePlayer** [comment]
Fixed in 58c28aefbaaa74e1c3a2a5b9bae4b1d5724a365d
