### ISSUE TITLE
Add video resolution options

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3209]
Now BizHawk can make videos for the SNES and not only in 1920x1080, but it stretches the entire video, but the quality is better, but it's better to give a choice, stretch the video, or just insert the video in 1920x1080 leaving black bars on the sides, because this is the standard for the SNES

**Comment by YoshiRulz** [comment]
Do it in post? You can pass whatever flags you want to FFmpeg if you choose that option, saving an extra re-encode.

**Comment by Danik2343** [comment]
Yes, but I'm using an AVI Writer (VFW) and the resolution change option is in the AVI/WAV config and recording, I used to add the change resolution type selection feature:
1. Expand the video in full screen
2. Change the resolution, but leave the video size, leaving black bars
P.S. FFMPEG works worse with AVI than VFW, due to the performance increase with the X264VFW codec, performance degradation is more common on FFMPEG, but the size with FFMPEG compression is larger than X264VFW, the function that is now implemented in the emulator itself works the same as on VFW/NUT/FFMPEG etc
Screenshot of video with original resoultion  (FFMPEG (AVI): https://imgur.com/a/VrAPRNX
Video screenshot with  original resoultion (VFW):https://imgur.com/kgC0wWq
Screenshot of video with Resize Video Enabled (FFMPEG (AVI): https://imgur.com/UHWfAVQ
Video screenshot with  Resize Video Enabled (VFW): https://imgur.com/9lUHSXy
Screenshot of the function itself in activated (current):
![image](https://user-images.githubusercontent.com/38865696/162467573-17f83bca-09b7-499f-a7a5-cc9f2fd158fb.png)
Here is a 1920x1080 video with black bars:
![image](https://user-images.githubusercontent.com/38865696/162468030-bc641cb0-d6c5-43b9-93b6-30175564f62f.png)

**Comment by Spikestuff** [comment]
> Resize Video
> **1920**x1080

You should be using **1440**x1080 as that's the 4:3 ratio.
