### ISSUE TITLE
N64 Crashing

### ISSUE THREAD

**Issue by hotaruikamusume** [TASEmulators/BizHawk#3210]
So basically I wanted to TAS Dairantou Smash Brothers (JP) but when i dragged the ROM to EmuHawk it stopped working and then crashed.

~~When i checked the Firmware thing the Nintendo 64 was missing, I checked the dll folder and the cores were there, but they weren't detected.~~ edit: there is meant to be no N64 entries in the firmware config --yoshi

### System Specificacions (If it helps)

OS: Windows 8.1 Pro (using an old notebook)
CPU: Intel(R) Pentium(R) CPU 987 @ 1.50GHZ 1.50GHz
GPU: Intel(R) HD Graphics
BizHawk Version: 2.8

**Comment by CasualPokePlayer** [comment]
That setup looks really old. In particular, reportedly that GPU only supports up to OpenGL 3.1, which might be too old for Mupen. Do all games exhibit this issue? If so, does changing the video plugin make it not crash? If all fail, check out the latest dev builds too and see if Angrylion crashes (that plugin doesn't interact with GPU at all, so in theory if it is a GPU problem it should be immune).

**Comment by hotaruikamusume** [comment]
> That setup looks really old. In particular, reportedly that GPU only supports up to OpenGL 3.1, which might be too old for Mupen. Do all games exhibit this issue? If so, does changing the video plugin make it not crash? If all fail, check out the latest dev builds too and see if the recently added plugin Angrylion crashes (that plugin doesn't interact with GPU at all, so in theory if it is a GPU problem it should be immune).

I changed it to Rice and now it's working ^^
