### ISSUE TITLE
[Request] Add Genesis Plus GX's SMS core

### ISSUE THREAD

**Issue by Sonia-7** [TASEmulators/BizHawk#3214]
Genesis Plus GX's SMS core probably has the best emulation available for the system. The emulator claims 100% compatibility on all platforms it supports, which is probably true as I've never ran into any SMS bugs while using it.

The reason I'm requesting this is that SMSHawk is problematic. Until recently several games were bugged, those got fixed but it broke some stuff elsewhere. An example is issue #3187, which gives the impression the core is some sort of house of cards similar to PCEHawk. Another problem is that audio emulation is kind of bad. Originally it was too quiet before the #2814 fix, but that ended up making the FM a little too grating. Now there are some nasty popping sounds in some games (examples are Phantasy Star's town or dungeon themes). Those sound much more clean on GPGX.

By the way, that SMS core already works through libretro. I even made a test movie with one game (Shinobi) and it synced perfectly, so save states seem stable. Since the hawk already has all components necessary to run it, maybe it'd not be that hard to integrate it properly? (SMSHawk doesn't need to be deleted, we could have two options similar to Nyma/PCEHawk.)

**Comment by CasualPokePlayer** [comment]
Savestates are non-consideration as our gpgx core is waterboxed.

Note too our gpgx core is rather old (with various cherry picked commits), so it may be a bit less accurate than you expect.

**Comment by CasualPokePlayer** [comment]
The genesis emulation from meda is already just a genesis gx fork, and the sms core is some fork off "SMS Plus" which is a mystery in terms of accuracy (and very low priority for meda's maintenance).

**Comment by Shinobi-1987** [comment]
> The genesis emulation from meda is already just a genesis gx fork, and the sms core is some fork off "SMS Plus" which is a mystery in terms of accuracy (and very low priority for meda's maintenance, so it isn't going to be getting better).

Gotcha, i was just thinking hey this is probably easy considering all the nyma going on, mind you if it made sense and was that easy you prob would be doing it already. Was just a thought from someone who doesnt know enough lol

**Comment by getCursorsExe** [comment]
> our gpgx core is waterboxed

Doesn't need to be waterboxed anymore, the latest upstream release doesn't have any savestate (including desync) issues.

**Comment by Sonia-7** [comment]
Why not simply add the GPGX core as it is? From what I've seen, even outdated GPGX is more accurate than the current SMSHawk. At least it doesn't fail on basic tasks like displaying games without visual glitches, and the audio is much better. It doesn't need to be updated since it's already fine.

**Comment by CasualPokePlayer** [comment]
Main thing blocking it being added is just someone having the motivation to hook it all up.

**Comment by Sonia-7** [comment]
I was wondering... just how hard it is to update GPGX? It's been around 7 years now. Latest GPGX is very different from what we currently have. Even if it's hard I think the update would be worth it at this point. Any chances of it being added in 2.9? It'd certainly be nice even if it means waiting longer (we've already waited a lot anyway).
