### ISSUE TITLE
it shows white screen for encyrepted nds games

### ISSUE THREAD

**Issue by dananothername** [TASEmulators/BizHawk#3217]
is the problem in bois 7 /9 or frimware?

**Comment by YoshiRulz** [comment]
Which game(s) aren't working? CPP already confirmed *Castle of Magic* works, at least in dev builds:
![screencap](https://cdn.discordapp.com/attachments/280813077853765632/964332091540135997/unknown.png)

**Comment by CasualPokePlayer** [comment]
The issue is definitely not "encrypted nds games" (melonDS handles those internally just fine). You reported on discord the problematic game was Castle of Magic, as DSiWare game, Is it white screening after you select the icon in the DSi menu?

**Comment by dananothername** [comment]
how to open dsi menu

**Comment by CasualPokePlayer** [comment]
Sounds like that confirms my suspicion, you opened the game up in DS mode, but since it's a DSiWare game that doesn't work and will crash. Go to settings and change DSi Mode from False to True.

**Comment by dananothername** [comment]
done now it says you are missing the needed firmware files to load this rom
i dont know the right bios for bizhawk

**Comment by dananothername** [comment]
if you cant provide bios it ok 
just tell me where to put it

**Comment by CasualPokePlayer** [comment]
We cannot provide the firmware files as they are copyrighted (just like game roms).

Go to Config->Firmwares, right click the firmware you wish to set and click "Set Customization" and you can then select the firmware to bind.

**Comment by dananothername** [comment]
why did you ban my tasvideos account i did nothing there

**Comment by CasualPokePlayer** [comment]
![image](https://user-images.githubusercontent.com/50538166/163661935-a415c658-924b-481c-a590-0c9c0f704eb9.png)
This was not your first time asking for ROMs and the like. You had 1 chance left and you blew it.
