### ISSUE TITLE
is it ok

### ISSUE THREAD

**Issue by dananothername** [TASEmulators/BizHawk#3219]
![Screenshot 2022-04-16 051418](https://user-images.githubusercontent.com/101902085/163662659-538ef016-d554-45fd-b4f1-751ad598197a.png)

**Comment by YoshiRulz** [comment]
It's optional.

**Comment by dananothername** [comment]
iam still having issues

**Comment by dananothername** [comment]
![Screenshot 2022-04-16 163651](https://user-images.githubusercontent.com/101902085/163687518-f829c201-ce45-4a90-959f-ca0da1fc0308.png)
here biz hawk cant run castle of magic or soul of darkness
bios is loaded successfuly
![Screenshot 2022-04-16 165112](https://user-images.githubusercontent.com/101902085/163687552-b5c649de-0c54-4cb5-8ce8-40a626967061.png)
here melon ds runned soul of darkness but show this error on castle of magic

**Comment by CasualPokePlayer** [comment]
It works fine for me on 2.8. You NAND is probably a bad dump, go get a better one.

**Comment by dananothername** [comment]
it worked thanks you may see my other issue about seeking
