### ISSUE TITLE
Possible Bug With Lag Log / Follow Cursor / TASProj Loading

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASEmulators/BizHawk#3220]
Originally posted on the [tasvideos forum]( https://tasvideos.org/Forum/Topics/13505?CurrentPage=34&Highlight=513610#513610).

User reported some exception occurred on opening their tasproj, and this rendered the input editor unusable (shows a big red X lol). This exception seemed to occur if opening the file with Follow Cursor enabled. Looking into the file they PM'd me indicated the Lag Log was reporting lag status for frames past the end of the input log. Removing these frames in the lag log stops the exception.

Note however if you load the file up without Follow Cursor enabled, and enable it once it's done loading, it does not throw an exception. Not sure why exactly. Maybe some loading step is being done later and it needs to happen sooner to prevent this exception?

I'm not sure how a tasproj would come to a state it has the lag log reporting frames past its end, maybe something with branches would cause that? In any case it probably should not cause some exception that renders the current session unusable upon load.

**Comment by vadosnaprimer** [comment]
Can you send the crashing file to me too?

**Comment by CasualPokePlayer** [comment]
https://drive.google.com/file/d/1IHnwoCXLffMjHctbW0YKaRyCWubhfjdq/view?usp=sharing

**Comment by CasualPokePlayer** [comment]
It is relatively standard to Join() a thread in Dispose(), in order to wait for it to properly end (effectively acting like a Dispose() for it). The next two lines have events which can only be safely disposed once the frame thread ends execution.

Could probably end up just having some loop checking for .IsAlive and sleeping to "replace" Join? melonDS should be the only core affected by something like this anyways.

**Comment by Morilli** [comment]
Looks like rare and unexpected bugs from calling `Thread.Join()` from the UI thread are not new, see the answer from <https://stackoverflow.com/questions/38911758/why-thread-join-does-not-hang-my-application-when-called-on-ui-thread>. Is there any way to not use a thread here and do this differently somehow?

**Comment by CasualPokePlayer** [comment]
"Any way to not use a thread for the multithreaded renderer" No, not really other than trying to launch the thread without the CLR (which might have other issues perhaps). Doing some while loop checking .IsAlive and sleeping for like 1ms also just works as a join without using Join() (could maybe be made an extension method?).
