### ISSUE TITLE
please disable seeking /saving

### ISSUE THREAD

**Issue by dananothername** [TASEmulators/BizHawk#3222]
i click rewind 
and the game go back like one minte and start playing till it reach the rewindid frame

**Comment by CasualPokePlayer** [comment]
You're complaining that TAStudio is seeking to the frame you selected from the last savestate it has. Go increase the memory given for savestates in state history settings, sounds like the default isn't high enough for your case.

**Comment by dananothername** [comment]
can i increase it randomly
it crashed last time
