### ISSUE TITLE
Exporting Raw Core Save States

### ISSUE THREAD

**Issue by SergioMartin86** [TASEmulators/BizHawk#3223]
Would be desirable to have a way to export/import save and load the emulator core's raw internal savestate.

To be more specific, to be able to export what is now "Core.bin" inside the BizHawk savestate, without modifications (e.g., signatures, byte prefixes or suffixes) and uncompressed.

This feature will help greatly passing savestates around between BizHawk and my TASing bot.

Thanks.

**Comment by nattthebear** [comment]
Just take a savestate, unzip it, and extract the core.bin if that's what you want.  You could even program your bot to do that operation automatically if you'd like.

> without modifications (e.g., signatures, byte prefixes or suffixes)

Unless what you want is something more complex?  What exactly are you passing this state to if not another copy of bizhawk?

**Comment by SergioMartin86** [comment]
> Just take a savestate, unzip it, and extract the core.bin if that's what you want. 
This is exactly what I've been doing so far. But additionally I have to manually remove the 4 bytes that BizHawk adds at the beginning with a binary editor.

> You could even program your bot to do that operation automatically if you'd like
I guess I could create a batch script to do this, but being able to directly export the core would make things less complicated from the get go.

> What exactly are you passing this state to if not another copy of bizhawk?
I have a TAS bot that does breadth-first exploration using QuickNES as emulation core. I need to pass savestates (e.g., the start of a level) from EmuHawk to the bot to begin the exploration. Every time I need a new savestate, I need to do this whole process. I do this process many times during the creation of a TAS, so having a 'Export Emulation Core State' hotkey would make my life way easier.

**Comment by nattthebear** [comment]
> manually remove the 4 bytes

> QuickNES

Thanks, that helps a bit.  But I'm not understanding what these extra bytes are.  I looked at the [code in emuhawk](https://github.com/TASVideos/BizHawk/blob/f05fc1aa086e07097f7fbe617f12e5ec642929a6/src/BizHawk.Client.Common/savestates/SavestateFile.cs#L63) and it's just exactly copying what the core gives it.  I tried saving and loading a few QuickNES states and they all worked fine.

I feel there's still a fundamental disconnect here and I'm not understanding your request at all:  If there were any extra bytes being written on state create that weren't appropriately read back or skipped on state load, then the core would not function and states would not work at all.  Everything would be a few bytes off and the core would read random garbage in.

**Comment by CasualPokePlayer** [comment]
They might be referring to the "extra" variables appended by the c# side of the core (frame count, lag count, is lagged, maybe more?)

**Comment by SergioMartin86** [comment]
> They might be referring to the "extra" variables appended by the c# side of the core (frame count, lag count, is lagged, maybe more?)

That's right. This is what I mean:

![image](https://user-images.githubusercontent.com/12969989/164281946-8a7784a6-daf7-4671-baa1-78b0578063ea.png)

On the left is the unaltered Core.bin as given by EmuHawk, and on the right is the same but after I removed the first 4 bytes.

- The flie on right works on loading it into the QuickNES core I took from [libretro's github](https://github.com/libretro/QuickNES_Core).
- The file on the left has these additional variables that seem to reflect what @CasualPokePlayer referred to, and fails catastrophically when I load it into my bot.

This is consistent to what @nattthebear predicted:

> If there were any extra bytes being written on state create that weren't appropriately read back or skipped on state load, then the core would not function and states would not work at all.

**Comment by nattthebear** [comment]
Thanks for explaining.  As a minor note:  There are extra bytes at the end as well, but the native core probably ignores those.

We really can't field requests like this.  Each and every core in Bizhawk consists of a C# `IEmulator` implementation, and some C# code to handle that.  When a core additionally includes some other code, be it native C/C++ compiled into a dynamic library or the "mini-linux" executables for waterbox cores, then that code is a part of the implementation detail of the core and is not a separate productized thing.

We've built our entire core philosophy around this decision.  We port in the core in the manner most convenient to us, and the unified interface we support is the C# one.  Upstream relationships can be complicated and we need to have some place where we can have the needed logic to make everything cleanly interoperate with Bizhawk.  If the core is separately packaged for other use cases, then we can't possibly stay perfectly in sync with that packaging.

This request additionally gets into low level savestate behavior requests that we don't, and never have, supported.  Savestates are never guaranteed across versions, and they're never guaranteed across different but related emulator products.  Maintaining canonically specified savestate formats is just too much effort for too little gain, and is very much at odds with our goals to make savestates as deterministic as possible.

At the same time, this is a problem you can easily fix yourself with no manual effort.  In and amongst whatever spaghetti of scripts and programs compromises your bespoke bot, there must be some place that you can trivially add a "slice 4 bytes off the file" operation.

**Comment by YoshiRulz** [comment]
I assume you're using ApiHawk? Use `IMemorySaveStateApi` for less overhead:
```csharp
var handle = APIs.MemorySaveState.SaveCoreStateToMemory();
APIs.MemorySaveState.LoadCoreStateFromMemory(handle);
```
To get the savestate byte array without the leading 4 bytes:
```csharp
[RequiredService]
public IStatable? _maybeStatableCore { get; set; }
private IStatable StatableCore => _maybeStatableCore!;
// ...
StatableCore.CloneSavestate.AsSpan(4);
```
