### ISSUE TITLE
BS F-Zero Grand Prix 2 ROM Issue

### ISSUE THREAD

**Issue by nymx-tas** [TASEmulators/BizHawk#3225]
I'm trying to get ready for TASing the 2nd game, in the F-Zero series for the SNES. The issue is a problem with the HASH codes used in bizhawk. So, this makes me think that I can potentially receive a rejection, after doing a lot of work.

BS F-ZERO Grand Prix 2 (J) [h1].smc shows a **correct hash**; however, it **doesn't work** at all.
BS F-ZERO Grand Prix 2 (J) [h1C].smc shows an **incorrect hash**, yet **works** fine.
BS F-ZERO Grand Prix 2 (J).smc shows an **incorrect hash** and **doesn't work**.
F-Zero Grand Prix 2 - Practice (Japan) (12-6) (1).bs, which is a weird verison that I have no idea about. **Doesn't work**.

There is no [!] version, which I imagine is a problem...since I believe this was a download from a satellite system used in 1997. So I don't think a cartridge exists.

Can you please advise on this situation? Thanks.

**Comment by CasualPokePlayer** [comment]
Does this apply for ALL SNES cores (Snes9x, Faust, BSNES, and BSNESv115) or only some/one of them?

**Comment by nymx-tas** [comment]
Ok. There was something that I didn't think about. After switching the core, I needed to perform a "Reboot Core". 

So the new information is:

BSNESv115, and Faust are the only ones that work on the "recognized" HASH.



I'm not sure why I ddn't see this before, but "Faust" works for the "Recognized" HASH.

I think this resolves my question. So the only thing remaining is...will submissions be accepted on BSNES v115+, since it is not the default selection on BizHawk 2.8

**Comment by CasualPokePlayer** [comment]
TASVideos only rejects cores which are "Experimental" (i.e. not "officially" released). All the SNES cores are released and are allowed to be submitted (although obviously the less accurate cores are less preferable, but not inherently disallowed)

**Comment by nymx-tas** [comment]
Thank you.
