### ISSUE TITLE
Savestate issue with Gambatte

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3227]
There is a savestate issue in Gambatte core that causes OAM output on the emulation screen to glitch out after loading a savestate. This is not an issue in any other core.
First you load jmla09.gb. https://www.pouet.net/prod.php?which=53578 (this isn't copyrighted now)

https://user-images.githubusercontent.com/39802077/164975478-3b8ab974-f9ff-4c6d-aabd-9117db785eeb.mp4

**Comment by CasualPokePlayer** [comment]
I can't repro the issue using latest master, also you have multiple cheats active in your little video. Not considering this valid until you can provide better repro steps and without cheats active.
