### ISSUE TITLE
(Enchancement) POKEMON STADIUM Lua TAS file

### ISSUE THREAD

**Issue by juanroman74454811** [TASEmulators/BizHawk#3228]
Can you make one? im trying to make a PKMN STADIUM speedrun

**Comment by YoshiRulz** [comment]
The point of Lua is that you can do it yourself. [Start here](https://tasvideos.org/MemorySearch). Failing that, maybe the authors of the published TAS or someone else in [the Pokémon Stadium thread](https://tasvideos.org/Forum/Topics/4752) have scripts they can share.
