### ISSUE TITLE
GB in GBC emulation in Gambatte is inaccurate.

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3232]
The left mole should NOT be seen. 
![image](https://user-images.githubusercontent.com/39802077/166101583-a0c3a582-15fa-46c0-95c2-6318e658407e.png)
SameBoy and GBHawk is devoid of this bug.

**Comment by YoshiRulz** [comment]
This testrom is included in our automated tests. It's already marked as failing.
https://github.com/TASEmulators/BizHawk/blob/46a426a2446028cefc973b35f1814c23420f73e8/src/BizHawk.Tests.Testroms.GB/GB_GBC/AcidTestroms.cs#L82

**Comment by CasualPokePlayer** [comment]
fixed in https://github.com/TASEmulators/BizHawk/commit/ebb028286091564f7734ee68817ac4e2aaa5be81
