### ISSUE TITLE
Shape characters in Nymashock are not correctly marshalled through in Lua

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASEmulators/BizHawk#3235]
joypad.get() (and co.) use raw input names so the internal shape names get shown. Lua marshalling doesn't like this so they get merged together as a single ?. This is *not* fixed by https://github.com/TASEmulators/BizHawk/pull/3119 to note

**Comment by nattthebear** [comment]
We probably wanted some overrides in src/BizHawk.Emulation.Cores/Waterbox/NymaCore.Controller.ButtonNameOverrides.cs

**Comment by YoshiRulz** [comment]
#3119 didn't fix this because I assumed those functions would only ever deal with ASCII strings and skipped them. Pushed https://github.com/TASEmulators/BizHawk/pull/3119/commits/45941fda159ffd7a00d6932aba70a31c6b07a18f.

**Comment by CasualPokePlayer** [comment]
> We probably wanted some overrides in src/BizHawk.Emulation.Cores/Waterbox/NymaCore.Controller.ButtonNameOverrides.cs

The main reason I didn't actually do that is due to being unable to make X be Cross without fucking up any other Nyma core having an X button, so they would end up being inconsistent compared to Octoshock, so I just kept the shape names and made sure the mnemonics were the same from Octoshock.

**Comment by nattthebear** [comment]
Fair enough, I was never big on button name policing.
