### ISSUE TITLE
(Feature request) Compatibility with playstation mouse

### ISSUE THREAD

**Issue by RoddieCat** [TASEmulators/BizHawk#3243]
Everything is in the title. It would be awsome to have compatibility with the "Playstation mouse", in particular in TAStudio.

Thanks for the good work

**Comment by CasualPokePlayer** [comment]
Are you asking about emulation of the PSX Mouse for games? Nymashock has support for that.

**Comment by RoddieCat** [comment]
Yes, this is what I am asking. I did not know Nymashock supported it, but still I cannot find it in the controller configuration.

**Comment by RoddieCat** [comment]
Indeed, I did not know that. Sorry for the request, I close the topic.
