### ISSUE TITLE
Homebrew ROMs instantly switch to SameBoy

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3244]
sierpinskiboy.smol.cgb (https://files.scene.org/get/parties/2021/revision21/oldskool-intro/sierpinskiboy.zip) not copyrighted for now.
This ROM somehow forces BizHawk to switch to SameBoy. There is no explaination why does this happen.
The file is also in CGB extension, which BizHawk does not recognize at all despite it being GBC ROM. DMG file extension is also not recognized, although it is GB ROM.

**Comment by CasualPokePlayer** [comment]
Gambatte only accepts ROMs that are at least 0x150 bytes (size up to the complete ROM header). This is upstream policy. The ROM is only 0x14E bytes big.

**Comment by getCursorsExe** [comment]
I've patched the ROM to make it 0x150 bytes, and it still switches to SameBoy, no matter what.

**Comment by CasualPokePlayer** [comment]
Patch better, making it 0x150 works for me.
