### ISSUE TITLE
[GPGX bug report] MD CART writing via M68K BUS

### ISSUE THREAD

**Issue by dennisrijsdijk** [TASEmulators/BizHawk#3246]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
On the GPGX core on any GEN game, writing to $000000-$3FFFFF via the M68K BUS doesn't reflect a change, while it does when you write on the MD CART domain. 

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open BizHawk 2.8 (release)
2. Open any Genesis game
3. Open the RAM Watch
4. Create a watch for an address in the above mentioned range on M68K BUS
5. Create another watch for the same address on MD CART
6. Poke the address on M68K BUS, see that it does not write
7. Poke the address on MD CART, see that it does write.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8; Win11 Home 22H2; Intel/Nvidia

**Comment by CasualPokePlayer** [comment]
ROM is normally read only, and you are writing to the bus as if you are the game writing to the bus. Writing to the specific ROM domain rather directly writes to the ROM array, bypassing any sort of restrictions a game would have. This is intended behavior.

**Comment by getCursorsExe** [comment]
This leaves an issue with cheat codes. All Game Genie codes pointing to ROM will be unusable, and **you have to manually locate the address in MD CART memory domain to make it actually work. EVERY. SINGLE. TIME.**
