### ISSUE TITLE
Genesis SetCpuRegister() not implemented please implement

### ISSUE THREAD

**Issue by Cokie1** [TASEmulators/BizHawk#3248]
[FeatureNotImplemented]
		public void SetCpuRegister(string register, int value)
		{
			throw new NotImplementedException();
		}

**Comment by YoshiRulz** [comment]
Duplicate of #3043. (Sorry for implying you needed to make this; my searches were for "Lua" so I missed the existing one.)

**Comment by Cokie1** [comment]
No worries 😉
