### ISSUE TITLE
Some inputs stopped working on the bottom screen

### ISSUE THREAD

**Issue by Devidkzxyx** [TASEmulators/BizHawk#3249]
i've been playing Pokemon Black and after some time, the A button stopped working, even tho it works in the upper screen perfectly, not sure if i activated some setting because i sometimes use clicks instead of A buttons to do attacks in Pokemon Battles, this bug doesn't only apply on Pokemon but in Megaman ZX and other roms, any fix to this?

**Comment by CasualPokePlayer** [comment]
The only inputs that correspond to the "bottom screen" are touch coordinates and is touching button, as far as the emulator can see. Anything else is a game construct. What are you talking about with the "A button."
