### ISSUE TITLE
Debugger- breakpoint breaks at wrong address (execute)

### ISSUE THREAD

**Issue by Cokie1** [TASEmulators/BizHawk#3253]
### Summary 

Loaded Core Gen-Plus GX
Open Tools The debugger (Tools->Debugger)

Sonic The Hedgehog Rom ( normal one you would get - rev 0 )

Using the debugger, I set a breakpoint to break at the instruction at address 0x3AE2. The debugger breaks at the address the Program Counter points to
before the specified address. It breaks at 0x3B4A. This instructions is beq 0x3AE2. It branches to the specified address we set if conditon is true
(which in this codes case is true - Z flag is set ). Is this a pre fetch issue?

Another example, break at 0xD33E breaks at address of previous instruction, 0xD33C.

### Repro 

1. Open Bizhawk
2. Open Sonic The Hedghog 1 Rom
3. Start the first level on sonic.
4. Let the level play for a second so it isn't the first time calling level loop subroutine. If it is first time called, it will still have bug, but from a different address)
5. Go to Tools -> Debugger
6. Add break point with address 3AE2. Set Execute setting. Make sure break point is toggled
7. The address it breaks at will be 0x3B4A, not  0x3AE2.

### Host Env.

Windows 10 
Bizhawk 2.8 x64

Havent tried it on anything else

![image](https://user-images.githubusercontent.com/93406911/169730844-15bc9ca1-8041-4574-8588-3bcae84e7179.jpg)
![image](https://user-images.githubusercontent.com/93406911/169731000-92f8827c-ffa2-4f0b-8f8e-708d8d805d2e.jpg)

**Comment by Cokie1** [comment]
Obote that this applies with other games , I just used sonic 1 as an example

**Comment by YoshiRulz** [comment]
Possibly fixed with GPGX update. Please [grab a dev build](https://github.com/TASEmulators/BizHawk#development-builds) and test again.

**Comment by danbolt** [comment]
I was having this issue, and switching from `2.9.1` to devbuild `3a8b3913` fixed it for me. (Linux)

Thanks! Much appreciated!
