### ISSUE TITLE
Watebox peformance loss in dev builds.

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3256]
Dev build 8ca1e4a0
This also makes Genplus-gx framerate go below 1 FPS, making it unusable.

**Comment by CasualPokePlayer** [comment]
You're probably building in Debug mode and that will slow things down. That is expected.

**Comment by getCursorsExe** [comment]
This breaks waterboxed cores, if you open Hex editor, the emulation speed will go below 1 FPS, effectively making waterboxed cores unusable for debugging.

**Comment by CasualPokePlayer** [comment]
Debug buiids are not for debugging games, they are for debugging BizHawk itself. This is entirely expected behavior.
