### ISSUE TITLE
core settings

### ISSUE THREAD

**Issue by Shinobi-1987** [TASEmulators/BizHawk#3264]
gambette core is listed under console and handheld for core settings.

This is wrong I believe?

On a side not could a controller tab be added to the core settings to allow controller config without core load?

another approach would of been allow load core without rom?

**Comment by YoshiRulz** [comment]
There are 3 questions here, so:
1. Gambatte emulates SGB so it's not a mistake to put it in the "Consoles" submenu.
2. This isn't a *bad* idea, but it wouldn't really have any benefit considering keybinds don't require a core restart to take effect.
3. I plan to do something like this, not for users but for automated testing. It's not trivial so I didn't consider it when working on the settings anywhere feature.

**Comment by Shinobi-1987** [comment]
Was just some thoughts thanks for the details.


As a user bizhawk is already very very nice. The only thing I think its truly lacking but seems to be somonething no one really cares for is the ability to set output screen resolution rather than matching the desktop. Very useful in many setups out there.

**Comment by YoshiRulz** [comment]
That would be blocked by #825, unfortunately.
