### ISSUE TITLE
SameBoy BGP and OBP manual change (with Hex Editor) won't be applied until you load a savestate

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3267]

**Comment by CasualPokePlayer** [comment]
BGP/OBP domains represent the internal 15 bit colors the GBC uses, although the 32 bit colors used in the frame buffer are separate. Poking BGP/OBP is just directly writing to that internal buffer. You can force a refresh by changing some color setting, poking 0xFF69/0xFF6A in System Bus, or just loading a state.

**Comment by getCursorsExe** [comment]
This will soon lead to an inconsistency involving GPU viewer. It's better to make it changes apply every time we manually write to BGP and OBP domains.
