### ISSUE TITLE
error with windows version detection on build _90220b65

### ISSUE THREAD

**Issue by Shinobi-87** [TASEmulators/BizHawk#3272]
error pop up
![Capture](https://user-images.githubusercontent.com/107374811/173260351-cb777297-fe1b-4601-a7d6-ec8905013e60.PNG)

and windows version (newer)
![Capture2](https://user-images.githubusercontent.com/107374811/173260388-a2ee823c-7931-4d0a-946e-b5a0f29386aa.PNG)

Doesnt effect anything just the pop up. Reporting to be helpful. If there is a command to log this and it could help let me know.

**Comment by CasualPokePlayer** [comment]
I can repro this on my own machine (which is also on 21H2).

**Comment by YoshiRulz** [comment]
Goddamn it Microsoft.

**Comment by Shinobi-87** [comment]
Its thinking 19041 when the build is 19044.

i wonder if the decimal has anything to do with it?

real shot in the dark

**Comment by Morilli** [comment]
Looks like this on my windows 10 VM:
![image](https://user-images.githubusercontent.com/35152647/173261978-33603420-ee48-4772-985f-406ed56380e7.png)

**Comment by YoshiRulz** [comment]
I'll just do an allowlist on `REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /V DisplayName`.

**Comment by Shinobi-87** [comment]
> Looks like this on my windows 10 VM:
> ![image](https://user-images.githubusercontent.com/35152647/173261978-33603420-ee48-4772-985f-406ed56380e7.png)

Interesting. So what is being checked is kernal file signed version and not the os build i think

**Comment by Morilli** [comment]
> REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /V DisplayName

Does that exist for you? Because it doesn't for me. What seems to be consistent with the windows version on both win11 and win10 for me looks to be the `CurrentBuild` / `CurrentBuildNumber` value (optionally with the `UBR` for more precision if you can be bothered).

**Comment by Shinobi-87** [comment]
> I'll just do an allowlist on `REG QUERY "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /V DisplayName`.

DisplayName not good.


see attached
![Capture3](https://user-images.githubusercontent.com/107374811/173262698-99ba5221-692d-4d07-b14b-6f6d76179ce7.PNG)

**Comment by YoshiRulz** [comment]
I meant `DisplayVersion`. But I'll use `CurrentBuild` because that will be a smaller diff.
