### ISSUE TITLE
Nymashock PSX Lua joypad.get() missing Triangle, Circle, and Square buttons.

### ISSUE THREAD

**Issue by ak505188** [TASEmulators/BizHawk#3275]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
With Nymashock core, the table from running `joypad.get()` does not contain entries for Circle, Triangle, or Square buttons. There is an entry for `"P1 ?"` as well. Running joypad.get() while holding Circle has `"P1 ?"` set to `True`, other face buttons have `"P1 ?"` set to `False`.
Running `input.get()` does detect buttons properly, and buttons behave properly in game.
My best guess to the issue is that in `Config > Controllers` the names for the Circle, Triangle, and Square use Unicode symbols, which doesn't play nice with Lua.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Set PSX core to Nymashock
2. Open a game
3. Open Lua console, run `print(joypad.get())`

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
"Next Disk": "False"
"P1 ?": "False"
"P1 Analog": "False"
"P1 D-Pad Down": "False"
"P1 D-Pad Left": "False"
"P1 D-Pad Right": "False"
"P1 D-Pad Up": "False"
"P1 L1": "False"
"P1 L2": "False"
"P1 Left Stick Left / Right": "32768"
"P1 Left Stick Up / Down": "32768"
"P1 Left Stick, Button": "False"
"P1 R1": "False"
"P1 R2": "False"
"P1 Right Stick Left / Right": "32768"
"P1 Right Stick Up / Down": "32768"
"P1 Right Stick, Button": "False"
"P1 Select": "False"
"P1 Start": "False"
"P1 X": "False"
"Power": "False"
"Previous Disk": "False"
"Reset": "False"
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8.0; Win10 Home 21H1; Intel/NVIDIA

[//]: # "(screenshots, if applicable)"
![image](https://user-images.githubusercontent.com/7521432/174030526-aa0f53b1-2e79-410a-ac36-b7ff3d9c0507.png)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
Already fixed in 2.9 dev (see https://github.com/TASEmulators/BizHawk/issues/3235 https://github.com/TASEmulators/BizHawk/commit/09061843f41c501813186d1c708898829d6069aa)
