### ISSUE TITLE
melonDS - Lag frames aren't being properly counted

### ISSUE THREAD

**Issue by noddy360** [TASEmulators/BizHawk#3278]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
The melonDS core isn't properly counting lag frames, compared to DeSmuME which properly counts them. This is specially evident in 30 fps games like Super Mario 64 DS. I have the "Threaded 3D Rendering", "Use Real BIOS", "Skip Firmware" and "Firmware Override" sync settings set to "True". DSi Mode is set to false.
### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open BizHawk.
2. Load a Nintendo DS ROM.
3. Make sure the "Display Lag Frame Count" option is turned on in the View options.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
This game in particular runs at 30 fps when playing any level, yet BizHawk only counts 7 lag frames.
![Sin título](https://user-images.githubusercontent.com/31973588/174194297-2e257b1e-8d7f-4ed3-9adb-966a67882c52.png)

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8; Win10 Pro; Intel
- BizHawk dev build at aa099e0; Win10 Pro; Intel

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
I believe it's due to melonDS counting frames which the touchpad is polled as nonlag frames, while DeSmuMe does not. I've been meaning to make it a setting here since it doesn't seem particularly useful for lag indication (although I've had a case where it did matter, so it's not completely useless).
