### ISSUE TITLE
[Debugger] It should be checking to see if a breakpoint set at the given address exists, to prevent it from crashing when attempting to remove said breakpoint

### ISSUE THREAD

**Issue by tommai78101** [TASEmulators/BizHawk#3287]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
Bizhawk Debugger cannot remove a single breakpoint where the address is pointing to the same address of another breakpoint. This also prevents the user from closing Bizhawk windows because the Debugger attempts to remove all of the breakpoints and fails.

Below included the error exception. However, the error exception stack trace is misleading, because the actual cause is a code logic error from this source file here:  
https://github.com/TASEmulators/BizHawk/blob/79994070899581981005bc385170384167772c33/src/BizHawk.Client.Common/BreakpointList.cs#L12-L15

The issue is the lack of breakpoint validations before adding the new breakpoint object into the Breakpoint List. It should be checking to see if a breakpoint with the same address exists in the `BreakpointList` class, before adding the new breakpoint. If an existing breakpoint whose address matches in the list, it should either tell the user the breakpoint already exists, or skip adding the breakpoint.

That way, when the time comes for the user to attempt to remove the breakpoint, it will not crash, because the delegate LINQ function assumes there exists only a breakpoint whose address is unique among the list of breakpoints. (The `_callbacks.SingleOrDefault()` on line 136.)

https://github.com/TASEmulators/BizHawk/blob/79994070899581981005bc385170384167772c33/src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAMemoryCallbackSystem.cs#L134-L142

### Repro
1. Download the open-source GBA rom here:  ( https://github.com/Hpmason/gba-dvd/releases/tag/v0.1.1 )
2. In Bizhawk, open the gba_dvd.rom, making sure it is running on mGBA v0.9.1 Core.
3. Open TAStudio.
4. Open Debugger.
5. At the bottom of the Debugger tool, click on the green [+] icon to add a new breakpoint.
6. In the pop-up, in the Address field, enter 0x08000286.
7. In the Mask field, leave 0xFFFFFFFF as the default.
8. In the Scope field, select the radio button next to Execute.
9. Click on the Add button.
10. Repeat Steps 5 through 9, then go to Step 11.
11. Attempt to remove one of the breakpoints.
12. Encounter error exception.

### Output

```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at BizHawk.Emulation.Cores.Nintendo.GBA.MGBAMemoryCallbackSystem.Remove(MemoryCallbackDelegate action)
   at BizHawk.Client.Common.Breakpoint.set_Active(Boolean value)
   at BizHawk.Client.Common.BreakpointList.Remove(Breakpoint b)
   at BizHawk.Client.EmuHawk.BreakpointControl.RemoveBreakpointButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Host env.
- BizHawk 2.8.0; Win10 Pro 21H1 Build 19043; Intel/NVIDIA

**Comment by YoshiRulz** [comment]
This code has changed a lot since 2.8, could you try a dev build to see if it's fixed?

**Comment by CasualPokePlayer** [comment]
The issue isn't necessarily that there's two breakpoints with the same address, but rather there's two breakpoints which use the same callback. In fact, it seems every Breakpoint sent over uses the same callback here, regardless of address, so there shouldn't be a reason the same address is needed?
