### ISSUE TITLE
Joypad.get/getimmediate doesn't get input correctly

### ISSUE THREAD

**Issue by IsaGoodFriend** [TASEmulators/BizHawk#3289]
### Summary
Immediately passing `joypad.get()` or `.getimmediate()` into `joypad.set()` disables all inputs to the game.

### Repro
```
while true do
    
    gamepadinput = joypad.getimmediate()
    
    joypad.set(gamepadinput)
    
end
```
Run this lua script.  I would expect the game to run just as before, but all inputs are now eaten up by this script.

### Host env.
- BizHawk 2.8; Win10

**Comment by Gikkman** [comment]
Input manipulation isn't trivial. I'm not super sure on the internal workings, but I've learnt with some help from the bizhawk devs that you have to poll and set input in the `onframestart` and `onframeend` event handlers.

I had problems with joypad manipulation a while back and submitted this script as reference for future. You could have a look at it for inspiration, and see if it works for you: https://github.com/TASEmulators/BizHawk/blob/master/Assets/Lua/JoypadIntersection.lua

**Comment by YoshiRulz** [comment]
Script as given is an infinite loop. The following script works correctly, i.e. reads all-`false` and writes it.
```lua
while true do
	joypad.set(joypad.getimmediate());
	emu.frameadvance();
end
```
`joypad.set` will override a button if its value in the table is `true` or `false`, and will not override if its value is `nil`/omitted.
