### ISSUE TITLE
[Genesis Plus GX] Z80 RAM memory domain

### ISSUE THREAD

**Issue by Ralakimus** [TASEmulators/BizHawk#3290]
Genesis Plus GX does not swap bytes in Z80 RAM like it does with 68000 memory, and thus should not use MemoryDomainIntPtrSwap16Monitor. A friend was using the hex editor to poke at bytes in Z80 RAM for a game, and they were byteswapped.

**Comment by Shinobi-87** [comment]
Does this happen only in bizhawk or is it directly a genesis plus gx issue? Could it have been done on purpose at some point?

**Comment by nattthebear** [comment]
Probably a Bizhawk specific issue.  I didn't validate the low level details of how the memory was mapped before making all of these domains.  It should be easily fixable.

**Comment by Ralakimus** [comment]
It's specifically a BizHawk thing with the hex viewer.
