### ISSUE TITLE
arrows won't work while TAStudio is on

### ISSUE THREAD

**Issue by dananothername** [TASEmulators/BizHawk#3291]
this happens in linux version

**Comment by CasualPokePlayer** [comment]
What "arrows" are you talking about?

**Comment by dananothername** [comment]
![Screenshot_2022-06-24-22-47-55-894_com android chrome](https://user-images.githubusercontent.com/101902085/175697310-6f88145d-3ae4-42d9-a5f4-2fd87e9668a7.png)

**Comment by CasualPokePlayer** [comment]
They work completely fine for me.

**Comment by YoshiRulz** [comment]
If there is an edge case under Mono where the arrow keys don't trigger hotkey/gamepad keybinds, I'm not fixing it. But I suspect you just had recording mode off.

**Comment by dananothername** [comment]
if it's off then why only B A Y X LR only work
