### ISSUE TITLE
Access violation while trying to print "TRACE" 68k error message

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3297]
In Predisposition by Team Evanesco (Sonic hack at SHC2012) running with Genplus-gx, trying to play sound ID 0x3C would cause BizHawk to crash immediately, with output 0xc0000005 "Access violation". 

This crash does not occur on PicoDrive core, as it prints "TRACE" on screen (suggests that Genplus-gx throws up on "TRACE")

**Comment by nattthebear** [comment]
svp was special cart hardware for one cart, and this isn't it.  Likely just a bug in the cart hitting non existent mmio addresses.

**Comment by getCursorsExe** [comment]
So svp emulation is not a thing in placeholder PicoDrive32x core.
