### ISSUE TITLE
(a question) about dsi cia rom

### ISSUE THREAD

**Issue by dananothername** [TASEmulators/BizHawk#3298]
is cia and  title app supported on dsi

**Comment by CasualPokePlayer** [comment]
CIA: No
Title app: I assume you are talking about title metadata, which are already bundled into BizHawk (that is required for DSiWare to work)

**Comment by dananothername** [comment]
how to increase memory given to  dsi emulator 
it lag every sec 
and seek 7 to 12 fps
those lags cause the movie to mismatch after restart the emuhawk
