### ISSUE TITLE
[GENPLUS-GX] NHL 96 crashes at the team selection screen

### ISSUE THREAD

**Issue by Glitcholog** [TASEmulators/BizHawk#3300]
Description
When you start NHL 96 for Sega Genesis, the player chooses the option and then proceed to the team selection screen. As soon as the game brings the player there, the game crashes to a black screen. Every other NHL games (NHL Hockey, NHLPA 93, 94, 95, 97 and 98) do not crash and a full game can be played. This issue is similar (if not the same) as the closed #1041 but for NHL 96 instead of NHL 98 and Madden 98 and was fixed for those two.

Steps
Load NHL 96 for the Sega Genesis
Proceed to the team selection screen, the game crashes. 
If somehow the game bring the player to the team selection screen by itself, the game will crash if the player press starts.

Output
No output (game crash to a black screen). Bizhawk runs correctly and its possible to switch game without problem.

Host environment
BizHawk 2.8; Win10 Pro 21H2 Intel/Nvidia

**Comment by hegyak** [comment]
In the File:
gamedb_sega_md.txt
Change this line:
89E7E0FBE8DB82B1F2DD7BEAFCC4E7FB		NHL 96 (UE) [!]	GEN	

To
89E7E0FBE8DB82B1F2DD7BEAFCC4E7FB		NHL 96 (UE) [!]	GEN		sram=1

That appears to fix this issue.  The game Loaded into a match

**Comment by Glitcholog** [comment]
I did the test and at first it didn't work until i've put a big space like the NHL 98 entry had. Did a full CPU VS CPU match and everything seems to be working! Tested with my personnal backup (Bizhawk saw it as NHL 96 (UE) [!]).

Thank you! Seems like it was a simple DB fix
