### ISSUE TITLE
Shift doesn't work for control

### ISSUE THREAD

**Issue by Lini1804** [TASEmulators/BizHawk#3302]
I mapped my shift key as the B-button on the NES and when I just push B it works but when I push another button together with B and release it, Bizhawk thnks that I also released shift although I didn't do that.

User "TheMetroid7998" described it on https://github.com/TASEmulators/BizHawk/issues/3184 and didn't got an answer.

I'm using version 2.8 on Windows 11.

![Bild_2022-07-03_172819200](https://user-images.githubusercontent.com/108622484/177046482-c7eb74ad-fcc6-4b73-9adf-afe84892ba70.png)

**Comment by YoshiRulz** [comment]
I did answer: https://github.com/TASEmulators/BizHawk/issues/3184#issuecomment-1116892773
If something isn't working *in dev builds* then by all means let me know.
