### ISSUE TITLE
Black Screen on Pokemon Black (NDSi Enhanced)

### ISSUE THREAD

**Issue by barthotymous** [TASEmulators/BizHawk#3319]
I pressed the trade button on accident in pokemon black for the NDS on bizhawk and now its stuck on a black screen. Nothing happens when I press buttons, rewind doesn't take me anywhere, and I have tried the other display options and nothing fixed it. Please help

**Comment by YoshiRulz** [comment]
Probably because Wi-Fi isn't implemented.

**Comment by barthotymous** [comment]
> Probably because Wi-Fi isn't implemented.

how should I fix this?

**Comment by CasualPokePlayer** [comment]
You can't. The game crashed here so you can't recover it, you just have to hard reset and proceed with the last save.

Wi-fi is implemented upstream, but not here for obvious reasons (also, because waterbox). All the frontend<->core wifi stuff is just stubs here returning 0s.

**Comment by YoshiRulz** [comment]
[melonDS](https://melonds.kuribo64.net/)
