### ISSUE TITLE
TAStudio unstable in StarCraft 64

### ISSUE THREAD

**Issue by thekovic** [TASEmulators/BizHawk#3328]
### Summary
The game has a problem rolling back state via the piano roll. Basically, you need to simulate the whole run from power on in order to successfully pass through the mission briefing screens, if you try to go back by a bit (say, to adjust an input), the whole screen turns to black and you can't control the game anymore. Furthermore, when I tried to save the .tasproj in this state, BizHawk crashed.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Launch StarCraft 64 (specifically, tested on USA ROM; SHA-1: A36D91B5AAC7BB95DF0D7DE5F9814F5270E25C2B)
2. Launch TAStudio
3. Let the game run.
4. On the first frame of the FMV, input A to skip it.
5. On the first frame of the main menu, input A to go to Single Player.
6. On the first frame of the next menu, input D-pad down, followed by empty frame, D-pad down, and A to select the first mission.
7. On the second frame of the mission title, input A to go to mission briefing.
8. Input A on, for example, the 8th frame of the mission briefing, then attempt to go back and input A on the 3rd frame. Game should now display a black screen.

### Output
None; BizHawk crashed without any error message. If there's a log file that I should look for, let me know.

### Host env.
- BizHawk 2.8; Win10 21H2; Intel/Nvidia

[//]: # "(screenshots, if applicable)"
![image](https://user-images.githubusercontent.com/72971433/180600966-6f8b5bd4-413f-49c9-884f-cf20e5e6dfb6.png)

**Comment by CasualPokePlayer** [comment]
Does enabling the Expansion Pack change anything here?

**Comment by CasualPokePlayer** [comment]
I believe https://github.com/TASEmulators/BizHawk/commit/5e34dc61660207856da7949ebe0136db51ffa47d should resolve this.

**Comment by CasualPokePlayer** [comment]
Another user on Discord encountered similar issues and they are fixed at least in 2.9-rc2, calling this fixed.
