### ISSUE TITLE
API Hawk: MemoryDomains specified with attribute [RequiredService] will throw NullReferenceException when loading external tool DLL with EmuHawk using argument `--open-ext-tool-dll` .

### ISSUE THREAD

**Issue by tommai78101** [TASEmulators/BizHawk#3329]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."

When developing a DLL external tool project for BizHawk, if the tool needs to use MemoryDomains, it will throw a null pointer reference exception when the DLL is loaded by passing the argument `--open-ext-tool-dll` to EmuHawk.exe.

I did make sure to include this in my WinForm class:

```csharp
		[RequiredService]
		public IEmulator Emulator { get; set; }

		[RequiredService]
		public IMemoryDomains MemoryDomains { get; set; }
```

And I also added this in the `this.Load` event from `MainForm` to bind a `System.EventHandler` delegate to this method:

```csharp
		public void OnBotLoad(object sender, EventArgs eventArgs) {
			if (!CurrentMovie.IsActive() && !Tools.IsLoaded<TAStudio>()) {
				DialogController.ShowMessageBox("In order to proceed to use this tool, TAStudio is required to be opened.");
				this.Close();
				DialogResult = DialogResult.Cancel;
				return;
			}

			if (Config!.OpposingDirPolicy is not OpposingDirPolicy.Allow) {
				DialogController.ShowMessageBox("In order to proceed to use this tool, please check if the U+D/L+R controller binds policy is set to 'Allow'.");
				this.Close();
				DialogResult = DialogResult.Cancel;
				return;
			}

			if (OSTailoredCode.IsUnixHost) {
				ClientSize = new(707, 587);
			}

			_previousInvisibleEmulation = InvisibleEmulationCheckBox.Checked = Settings.InvisibleEmulation;
			_previousDisplayMessage = Config.DisplayMessages;
		}
```

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."

1. Either pull down the commit [here](https://github.com/tommai78101/Bizhawk-GeneticAlgorithmBot/commit/23f8f660dce2e1bb7569247119870683dbb3fa3a) (commit ID: 23f8f660), or download the attachment below.

[tool_src.zip](https://github.com/TASEmulators/BizHawk/files/9174695/tool_src.zip)
 
2. Build the DLL.
3. Follow the instructions from the Quick Development guide ([here](https://github.com/TASEmulators/BizHawk-ExternalTools/wiki/Development-quickstart#setup)) to load the DLL via EmuHawk.
4. You should be able to see an exception thrown mentioning the MemoryDomains encountering a null pointer reference.

If not, you can try "Debugging a DLL using external application" and attaching the debugger to the application, by following this instruction from Microsoft:

https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-from-a-dll-project?view=vs-2022#specify-a-calling-app-in-a-c-dll-project-net-core-net-5

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."

These exceptions all point to the same thing.

Pictures are only here to help:

![image](https://user-images.githubusercontent.com/6444116/180623350-84755003-c9b2-4acd-a91d-ebac5435bdb4.png)
![image](https://user-images.githubusercontent.com/6444116/180623344-b7540af7-d496-4a3f-be9d-116aecc40c25.png)

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=GeneticAlgorithmBot
  StackTrace:
   at GeneticAlgorithmBot.GeneticAlgorithmBot.Restart() in E:\LargeGithubProjects\Bizhawk-GeneticAlgorithmBot\src\GeneticAlgorithmBot.cs:line 266
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeneticAlgorithmBot.GeneticAlgorithmBot.Restart()
   at BizHawk.Client.EmuHawk.ToolManager.LoadExternalToolForm(String toolPath, String customFormTypeName, Boolean focus, Boolean skipExtToolWarning)
   at BizHawk.Client.EmuHawk.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at BizHawk.Client.EmuHawk.FormBase.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at BizHawk.Client.EmuHawk.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk dev build at 84886b7395; Win10 Pro 21H1; Intel/NVIDIA

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
`IToolForm.Restart` is called from two places; on init, and when restarting all tools. Only the latter checks services are available.
