### ISSUE TITLE
Waterbox support for Mupen64Plus core

### ISSUE THREAD

**Issue by TempleOfHorus** [TASEmulators/BizHawk#3334]
For some reason HUD in Mario 64 Speedrunning rom stays even when I load state that was saved without HUD.
Bizhawk: https://youtu.be/0q8yH_Zgpc8
Just to compare how it should works (ares v129): https://youtu.be/ZXwD6M_HM78

**Comment by TempleOfHorus** [comment]
Just an addition: Sometime game freezes when I load save state: https://youtu.be/WQwX2MD7mds
When I restarted bizhawk, the save state suddenly worked.

**Comment by CasualPokePlayer** [comment]
The MupenPlus here is an ancient version (circa 2013) and its savestates just suck and plugins are not helping on that. Not much that can be done here really. You'll have stable savestates with the ares core (as it's waterboxed) but otherwise this probably won't be fixed any time soon.

**Comment by TempleOfHorus** [comment]
Good to know, I thought all cores in Bizhawk are waterboxed. Do we have list of waterboxed cores ? 
I change title of this issue to "Waterbox support for Mupen64Plus core" and keep issue open.

**Comment by CasualPokePlayer** [comment]
Waterboxing our mupen core is "get rid of plugins, yoink out all the crap like SDL, somehow make not rely on threads, and god knows what else." This is not easy at all.

**Comment by CasualPokePlayer** [comment]
See if the affected games are fixed with 5e34dc61660207856da7949ebe0136db51ffa47d

**Comment by CasualPokePlayer** [comment]
Closing due to lack of user response (also going to assume the original state issue was fixed with that commit).
