### ISSUE TITLE
[Gambatte request] Add volume slider

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#3338]
Gambatte in BizHawk is too quiet with 100% volume of BizHawk.

**Comment by CasualPokePlayer** [comment]
https://github.com/TASEmulators/BizHawk/blob/ea5e8b70d35820dd46eb02ff952ff0566cafde9d/src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.ISoundProvider.cs#L70
https://github.com/TASEmulators/BizHawk/blob/ea5e8b70d35820dd46eb02ff952ff0566cafde9d/src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.ISoundProvider.cs#L79

These weird shift right 2 might be why it's "too quiet" (it's effectively at 25% volume). Not sure why exactly this is needed, git blame says @nattthebear?

**Comment by nattthebear** [comment]
https://github.com/TASEmulators/BizHawk/commit/13c3dafd8a6af0a7ecf7a16e8ed2dc1fa6eb58af is exactly what it looks like -- the core sounded too loud, so I kicked it down 12dB.  There wasn't deep scientific research involved.

Much about the core has changed since then, so feel free to tune that number.

**Comment by CasualPokePlayer** [comment]
I took a look at some wav dumps here:
![image](https://user-images.githubusercontent.com/50538166/181653819-d5d3f2c6-1e18-4ca9-832f-9002a35bd79c.png)
The top one is SameBoy, the middle one is Gambatte with the >> 2, and the lower one is Gambatte without the >> 2.

Gambatte's raw output seems to be very very loud indeed, although the >> 2 makes it much quieter than SameBoy. A >> 1 seems to be around the same ball park as SameBoy though, perhaps that is enough to resolve this issue.
