### ISSUE TITLE
Use better compression for savestates and project files

### ISSUE THREAD

**Issue by Morilli** [TASEmulators/BizHawk#3344]
As discussed on discord, the zip compression currently used is far inferior to more modern methods, and would do good being replaced with a better and faster method, for example zstd.

This could benefit both savestates and .bk2 and .tasproj files, resulting in smaller project files and faster savestates.

**Comment by getCursorsExe** [comment]
Seems to be a good idea, but this does NOT MEAN dolphin and citra will appear.

**Comment by nattthebear** [comment]
What, zip file with zstd compressed entries?  Not until all major zip software supports it.

**Comment by Morilli** [comment]
> Not until all major zip software supports it.

Well in that case, let's wait another 20 years, or potentially till the end of time. If you consider this path problematic, perhaps just compressing specific binary files (inside of the zip) additionally could work as well.

**Comment by nattthebear** [comment]
No, we don't need every last random zip program, but certainly the major ones on Windows, which would include the Windows file explorer.  One of the major design goals of the current line of formats is for end users to be able to open them and manipulate them without programming knowledge or special programs.

**Comment by Morilli** [comment]
> One of the major design goals of the current line of formats is for end users to be able to open them and manipulate them without programming knowledge or special programs.

Right, which is why I think this "double-compression" could work fine, aka keep zips as they are, and just compress and decompress specific files an additional time internally. Especially the greenzone file can become quite large (500MB for me), which takes a long time to compress using deflate and is not really editable for an end-user anyway.

**Comment by nattthebear** [comment]
I'm interested to see the real world gains that we'll get with 2c56da5

**Comment by vadosnaprimer** [comment]
Greenzone indeed takes way too long to save to file.

The previous implementation was able to only save every 16th state (user adjustable iirc), because you don't need all the immediate states from the previous session, only some basic anchors. And if saving is quick, it feels transparent and doesn't interrupt the workflow.

Since to work comfortably you need to have a decent number of immediate states, now they take several seconds to save every time. So autosaving is now a problem, unless one forces saving to a backup file, but then autosaving as regular tasproj is kinda pointless...

**Comment by CasualPokePlayer** [comment]
Started a separate go here: https://github.com/CasualPokePlayer/BizHawk/commit/aae12f3c1f847cc58fa15bd3217950a16092f847

Doesn't rely on ZstdNet, instead rolling out my own wrapper around LibZstd. Has some minor speed advantages (able to use BizInvoker, able to tweak the implementation according to how savestates are used, etc), and of course no need to have another NuGet dependency.
