### ISSUE TITLE
[Enhancement] Estimated accumulated timestamp

### ISSUE THREAD

**Issue by tommai78101** [TASEmulators/BizHawk#3346]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."

In TAStudio, we have a known quantity of input frames available for us, and we can add, insert, remove, and do frame advances. Another thing in TAStudio is our ability to keep track of how many average frames per second in the current run, as we are playing back our inputs.

With this information, I believed it might be possible to estimate the total time from Frame 0 (Powered On) up to the current frame the user is currently on.

As a feature request, I would like to ask for a total estimated timestamp, either be displayed in TAStudio, or be displayed somewhere within EmuHawk's emulator's viewport (like how we display the recorded inputs and FPS overlay). All it needs is to show an overlay of the current overall timestamp since Frame 0 (in TAStudio) on the emulator window (EmuHawk).

[//]: # "(screenshots, if applicable)"
### Mockup

![image](https://user-images.githubusercontent.com/6444116/182759389-2e9912d8-bbdd-477c-a0d8-723b9dd2152d.png)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by tommai78101** [comment]
Now that I think about it, it should be called "Total Elapsed Timestamp". It will display the total elapsed timestamp since Frame 0 (or from "Powered On" to the current frame in TAStudio) in EmuHawk.

**Comment by YoshiRulz** [comment]
Isn't this just... `FrameCount / PlatformFramerates[SystemId]` (or `ClockCycles / ClockRate` for variable-length frames)?

**Comment by CasualPokePlayer** [comment]
Is movieclock.lua what you're looking for?

**Comment by tommai78101** [comment]
@YoshiRulz  Yes, it is. I wasn't sure what the C# API would be, thank you for the clues.

@CasualPokePlayer Yes, indeed! This is what I am looking for.
 
Closing issue because it's already included with BizHawk.
