### ISSUE TITLE
Add a waterboxed version of Libretro

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3350]
Requries LLVMpipe mentioned [before](https://github.com/TASEmulators/BizHawk/issues/3247), because we cannot store GPU state easily, possibly making the emulator crash as soon as the emulator attempts to save a single savestate. And this should NOT be changeable.

**Comment by CasualPokePlayer** [comment]
Sure you can waterbox libretro cores, but that means BizHawk folks are actually building libretro cores instead of them provided by the actual libretro folks. Which no

**Comment by getCursorsExe** [comment]
If we could change the libretro API to not use stuff incompitable with waterbox, it might work. Unfortunately it's not possible.

**Comment by CasualPokePlayer** [comment]
That's not the issue. The issue is that waterbox cores have to be compiled in a special way, which means the work of compiling the cores is on BizHawk developers instead of libretro developers. Which is not going to happen.
