### ISSUE TITLE
Sonic 1 Colors Edition is playable on BlastEm and upstream Genplus-gx, but not BizHawk

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3352]
```
Sonic 1 Colors Edition
SHA1:ADC7A5C9ED3EC1E3FB6B658459415746BF16E239
MD5:A5A8EBA79FB8856F019B8BB7638A7F17
```
Game crashes when attempting to display level select. Definetly not present in upstream.

romhack available from [this terrible website](https://shc.zone/vault/) under the '17 competition --yoshi

**Comment by CasualPokePlayer** [comment]
This does actually occur in upstream when using more accurate settings to emulate lockups. This hack writes to an illegal address and would not work on actual hardware.

(And as a fun bonus, Retroarch (what I used to check) is bugged and inverts the setting, so "enabling" system lockups actually disables them and "disabling" them enables them).

**Comment by getCursorsExe** [comment]
> (And as a fun bonus, Retroarch (what I used to check) is bugged and inverts the setting, so "enabling" system lockups actually disables them and "disabling" them enables them).

This doesn't happen in debugger fork of that core.
