### ISSUE TITLE
Nyma core light gun issue

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3359]
from https://github.com/TASEmulators/BizHawk/issues/2663#issuecomment-1118308127

@Spikestuff and/or @CasualPokePlayer can provide details

I'm putting my foot down—this is blocking release. Not even fixing it necessarily, just documenting it.

**Comment by CasualPokePlayer** [comment]
I think the issue is just the midpoint is improperly defined. The core sees 0, 0 as "top left", yet that's seen in hawk as "middle of the screen"

**Comment by CasualPokePlayer** [comment]
"Fixing" that seems to work more or less correctly in Saturn. However, for PSX, there seems to be inconsistencies. 0, 16 is actually "top" left there it seems, and the maximum Y value (240) does not reach the end of the screen...

**Comment by CasualPokePlayer** [comment]
I think the issue for that was just the end range was improperly defined. Seems PointerOffset is the beginning of the range, and PointerOffset + PointerScale is the end of the range?

**Comment by CasualPokePlayer** [comment]
re: https://github.com/TASVideos/tasvideos/issues/1402#issuecomment-1221313742, that is actually a separate issue from this. The issue is deadzone is being applied for mouse controls (although that doesn't make sense, deadzone should be ignored for mouse controls), and applies for any analog control binded to the mouse.

**Comment by YoshiRulz** [comment]
~~Oh, so user error then.~~ I suppose we could set the deadzone to 0 when binding to the mouse, or something like that. I can't think of any scenario in which having a deadzone for it would be useful.

**Comment by nattthebear** [comment]
Deadzone makes sense when binding a real mouse to an emulated delta controller.
