### ISSUE TITLE
[Request] Add libretro's retropad to Input_Display.lua

### ISSUE THREAD

**Issue by Sonia-7** [TASEmulators/BizHawk#3360]
This would be a helpful thing to have when you're running games through libretro, since input display doesn't work there at all and it's a feature I use a lot. There's no need to bother with the RetroKeyboard since it has too many inputs and I don't think a lot of games use them. But retropad has only 12 buttons (just like a SNES controller), and being able to display their P1 and P2 inputs would certainly be useful.

**Comment by YoshiRulz** [comment]
I think the request as you've written it is an XY problem; input display doesn't work for Libretro so you want this other thing to work for Libretro. I've fixed the input display and I'm going to close this as wontfix.
