### ISSUE TITLE
Savestate issue with Genplus-gx

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3363]
When mode 4 is enabled, VRAM is actually only 0x4000 bytes. However, this is ignored for savestates, so the mirrored VRAM writes disappear instantly.

**Comment by CasualPokePlayer** [comment]
Do you have a game where this can be reproduced?

**Comment by getCursorsExe** [comment]
We can set the address 0x0A23 to 0x60 in Dr. Robotnik's Mean Bean Machine. This sets the VDP 0x01 to 0x60.

**Comment by CasualPokePlayer** [comment]
What do you mean by "writes" disappear with savestating? Do you have to savestate and load a state at a particular point? VRAM is being correctly savestated as far as I can see.

**Comment by nattthebear** [comment]
This needs proper reproduction steps

**Comment by getCursorsExe** [comment]
> VRAM is being correctly savestated as far as I can see.

Perhaps it depends on your device?
The core ITSELF does this. I think you need to make sure you find a point where a lot of VRAM writes appear. I will place a video here. The mirrored writes disappear when I rewind.

https://user-images.githubusercontent.com/39802077/186667063-9486ffe4-08cc-4b11-895b-65163e08d878.mp4

**Comment by nattthebear** [comment]
Proper reproduction steps means a step-by-step from starting the core with rom, and everything you did in sequence, and what you observed, what you expected to observe, and why you expected to observe it.

There is an invis mapped memory mirror that might not be regenerating correctly.  Or it might be nothing; if it's only visible in the VDP tool then the VDP tool may be exposing things that aren't supposed to be exposed.  We don't support Master System with this core, so if you're somehow tricking the thing into Master System mode with a hacked Mega Drive rom, it might not matter.

**Comment by CasualPokePlayer** [comment]
The Core.gpgx_invalidate_pattern_cache() seems to be the "culprit" to this behavior. It's not restricted to the VDP viewer. You can do the "poke 0x60 at 0x0A23 for this specific game" and then you can see saving a state and loading a state will change the image produced.

It's probably harmless overall, as this is just the rendered image having some sort of wonkiness with the cache fully invalidated. Maybe the invalidation is being done wrong? Not sure.
