### ISSUE TITLE
mGBA (Bizhawk 2.8) Freezes during loading screens when using TAStudio

### ISSUE THREAD

**Issue by hndfhng** [TASEmulators/BizHawk#3369]
Issue: Emulation in mGBA can freeze when loading screens are involved. There are 2 ways I was getting this bug. Both involve using TAStudio.
Game used to trigger this bug was Rayman - Raving Rabbids (Europe). I only had this bug in mGBA core, multiple times with this game. Haven't tested other GBA games. Never had this bug with PSX core on Bizhawk 2.8. Haven't used any other cores on this version.

Method 1: Recording Mode is off. Seek until the screen is black and game is loading stuff (for example, frame 828). Then place an input when the game was fading out a few frames earlier (for example, frame 802). This will cause the emulation to freeze and you'll get a white screen of death, sometimes black screen of death too. It's very consistent, but involves doing this on the "wrong" frames 💀 
Method 2: Recording Mode is on. Make a savestate when game is loading (on an "unfortunate" frame), then proceed to load that savestate. The emulation will also freeze on a white/black screen.

Repro: (method 1)
1. Use Bizhawk 2.8 emulator
2. Use valid BIOS sha1: 300C20DF6731A33952DED8C436F7F186D25D3492
3. Config->Profiles is set to Tool-Assisted Speedruns.
4. All other settings are default
5. I'm using legit and clean Windows 10 Pro 64-bit
6. Use game "Rayman - Raving Rabbids (Europe) (En,Fr,De,Es,It,Nl)" CRC-32: 9914DA23 (clean rom, No-Intro verified)
7. Open TAStudio, keep playback paused
8. Place "A" button press on frames: 424 and 584 (to progress the menus)
9. Let the movie scroll to frame 828, then pause the emulation. Make sure frame 828 is the last "greenzoned" frame. If you go further than that, clear greenzone and pause it when it gets to 828.
10. Place any button press on frame 802. Also works if you place any button press on frame 801 (lag frame).
11. ???
12. Screen goes white and emulation is frozen. Only way to fix it is to clear greenzone before this happened, for example by placing and removing a button press on frame 800.

I won't post repro steps for method 2, because you just have to find the "wrong" frame to savestate on during loading screens by trial-and-error, and then loadstate.

Anyway, both methods work in many other moments during the game. The common conditions are to let the game seek until a "wrong" moment during loading screen, and then either place an input before that "unfortunate" frame, or make a savestate on the "unfortunate" frame and re-load it later.

**Comment by CasualPokePlayer** [comment]
Partially related to https://github.com/TASEmulators/BizHawk/issues/2938 possibly, there were some savestate fixes after 2.8. Does the latest dev build still have issues?

**Comment by YoshiRulz** [comment]
Reproduced as stated on 2.8, but not dev build. Closing.
