### ISSUE TITLE
Sonic Rush (U) language issue (not present in upstream)

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3377]
```
Sonic Rush (USA) (En,Ja,Fr,De,Es,It)
SHA1:BC617530BB9B6E4179F2E54D7816C38676812DDE
MD5:BD4DCF6AD27DE0E3212B8C67864DF0EC
```
On BizHawk 2.8, every single string in the game is in Japanese (although this is suppossed to appear in a different game release made for Japan only).
This issue doesn't exist in upstream at all.

**Comment by CasualPokePlayer** [comment]
The `Ja,` means Japanese. This just means the language set in the firmware is Japanese. Note the `Firmware Language` sync setting so not take effect unless `Firmware Override` is true.
