### ISSUE TITLE
[Win] Sound Output Device setting is erased after Output Device missing error

### ISSUE THREAD

**Issue by Meerkov** [TASEmulators/BizHawk#3379]
### Summary

Load BizHawk while your normal sound device isn't plugged in, resulting in 0 sound devices.
Open Bizhawk, try loading a game, and doing a FFMPeg recording.
You'll see an error saying something like "This is probably not gonna work!!!"
Close BizHawk.
Fix your sound device issue.
Reopen Bizhawk.
Bizhawk no longer has any sound output...
Open the Sound Configuration menu
Notice the Output Method radio button has no selection.
Set it to Direct Sound and select the correct audio device again.

Result:
Now it works.

Expected Result:
Bizhawk, upon loading with no Output Method, would try to fix itself by choosing the only sound device available.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8 windows 10
![image](https://user-images.githubusercontent.com/8139496/188331339-3d09ec01-004c-4948-a599-77e8ecc531c4.png)

E.g. when you click "Direct Sound" here, then the correct output device will appear. The expected result is that when the desired output device is re-plugged in, you don't have to re-do this setting.

**Comment by YoshiRulz** [comment]
Let me know if that did what you wanted. I don't have a Windows machine with 0 sound devices so I couldn't repro.
