### ISSUE TITLE
Ares64-Accuracy doesn't allow major ROM Hacks to be played

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3380]
Ares64-Accuracy doesn't allow any major ROM Hacks like [B3313](https://drive.google.com/file/d/1Z2K2NjEsaAFZTPi2fRF0b-i9CthKSQu4/view) to be played, but it does allow minor ROM hacks such as Visible Parallel Universes Mod.

This is not an issue in Ares64-Peformance.

**Comment by CasualPokePlayer** [comment]
Check back in the latest dev build, performance/accuracy cores were scrapped, only 1 ares core remains.

**Comment by YoshiRulz** [comment]
In a previous thread I reported that B3313 specifically was playable, for a very loose definition of playable.
