### ISSUE TITLE
Add Pointer Offset Support on Hex Editor and RAM watch? + Merge CasualPokePlayer's GC/Wii Core in BizHawk's official github repo?

### ISSUE THREAD

**Issue by TheAmazingAladdin** [TASEmulators/BizHawk#3381]
Could you add Pointer Offset Support on Hex Editor and RAM watch so i can see the values of Momentums in Bizhawk?
```
003CB4A0 without pointer offset = Wrong Value
003CB4A0 with pointer offset = Value of Momentum
"baseIndex": 0,
                    "label": "Momentum X",
                    "pointerOffsets": [
                        "0"
                    ],
                    "typeIndex": 3,
                    "unsigned": false
```
![image](https://user-images.githubusercontent.com/108961061/188729040-3f20c579-8209-4c0f-a060-3b58a9a96553.png)
![image](https://user-images.githubusercontent.com/108961061/188729850-ad90fb20-b6cb-4959-b70d-ef8c7e1268a3.png)
For Core port request: If possible, could you also merge [CasualPokePlayer's GC/Wii Core](https://github.com/CasualPokePlayer/BizHawk) in BizHawk's official github repo?

**Comment by tommai78101** [comment]
Referencing this one, since it's an older issue.

https://github.com/TASEmulators/BizHawk/issues/377

**Comment by YoshiRulz** [comment]
I was going to rename this Issue to be only about Dolphin, but I'm going to close it instead. Any discussion of CPP's work would be more useful as comments on a PR. ("Work" meaning "code", there's a forum thread if you have usability concerns.) My understanding is that to merge it now would mean adding edge cases for Dolphin (similar to melonDS and Mupen64Plus), which isn't *ideal*, but ultimately that decision is his.
