### ISSUE TITLE
No support for .BIN file of the type "MODE2/2336"?

### ISSUE THREAD

**Issue by calp5k** [TASEmulators/BizHawk#3387]
### Summary
In BizHawk 2.8, when I attempt to load a .cue file for a PS1 .bin where the type is listed as `MODE2/2336`, an exception is thrown by the core and the file will not load successfully.

FYI, all of the files I have previously gotten to work in BizHawk are listed as `MODE2/2352`. I'm also not aware of a method to convert a `MODE2/2336` file to a `MODE2/2352` file.

Here is the content of the specific .cue file I attempted to load:
```
FILE "biso-bmm.bin" BINARY
  TRACK 01 MODE2/2336
    INDEX 01 00:00:00
```

### Repro
1. File > Open ROM
2. Navigate to the .cue file for the .bin, select it, then click Open.
3. An exception is thrown regardless of whether the core is Octoshock or Nymashock.

### Output
![EmuHawk_2022-09-15_17h36m28s](https://user-images.githubusercontent.com/113653748/190546667-68eec558-5dc0-4cc6-9bea-4357fd79e405.png)
thrown here:
https://github.com/TASEmulators/BizHawk/blob/2b59cfc1c49b7e1a90181ef8485f6c43db7fd5e8/src/BizHawk.Emulation.DiscSystem/DiscFormats/CUE/CUE_Load.cs#L315

### Host env.
- BizHawk 2.8; Windows 10 Home 19043.2006; Intel core i7

**Comment by CasualPokePlayer** [comment]
What game exactly is this? Googling that file name does not give any helpful results.

**Comment by calp5k** [comment]
> What game exactly is this? Googling that file name does not give any helpful results.

It's an earlier prototype version of Beatmania (Europe). There are significant differences between it and the widely released version.

For background, I'm able to get it running on Retroarch using the Beetle PSX core, but I would highly prefer to use BizHawk's features so that I can help document the differences between the versions.

**Comment by Spikestuff** [comment]
Just noting that upstream is fine, this issue is exclusive to Hawk.

A temporary solution is to use [CDMage](https://www.romhacking.net/utilities/1435/) and save it as such and it'll work again:
![image](https://user-images.githubusercontent.com/12412764/190673529-d68d64f8-cba2-47bf-888d-538e15a3d58a.png)

**Comment by calp5k** [comment]
> A temporary solution is to use [CDMage](https://www.romhacking.net/utilities/1435/) and save it as such and it'll work again: > ![image](https://user-images.githubusercontent.com/12412764/190673529-d68d64f8-cba2-47bf-888d-538e15a3d58a.png)

I used CDMage to convert the image's tracks to `MODE2/2352` and can now successfully run the game in BizHawk 2.8. Thank you!

I don't know if support for non-`MODE2/2352` tracks will be implemented in a future release, but for now this solution works for my needs.

**Comment by YoshiRulz** [comment]
Changing to DiscoHawk feature request. CDMage doesn't appear to have source code available and there are [no FOSS alternatives](https://alternativeto.net/software/cdmage/), so we could be the first.

**Comment by Spikestuff** [comment]
> Changing to DiscoHawk feature request.

It's still an issue in Hawk due to upstream running MODE2/2336 just fine.
Probably split the two features?

**Comment by YoshiRulz** [comment]
Something something `UserData2048Mode` set in RomLoader
https://github.com/TASEmulators/BizHawk/blob/3e79e68d1da61e7cf020053a2e0a7d34f3629cba/src/BizHawk.Emulation.DiscSystem/DiscIdentifier.cs#L179-L184
https://github.com/TASEmulators/BizHawk/blob/3e79e68d1da61e7cf020053a2e0a7d34f3629cba/src/BizHawk.Emulation.DiscSystem/DiscStream.cs#L72-L79
Not respected by Nymashock
https://github.com/TASEmulators/BizHawk/blob/3e79e68d1da61e7cf020053a2e0a7d34f3629cba/src/BizHawk.Emulation.Cores/Waterbox/NymaCore.cs#L103
https://github.com/TASEmulators/BizHawk/blob/3e79e68d1da61e7cf020053a2e0a7d34f3629cba/src/BizHawk.Emulation.Cores/Waterbox/NymaCore.Cd.cs#L11-L14

**Comment by CasualPokePlayer** [comment]
DiscStream is not used by Nymashock here, so that is irrelevant.
