### ISSUE TITLE
Genplus-gx: Layers issue when loading a save state

### ISSUE THREAD

**Issue by ReyVGM** [TASEmulators/BizHawk#3388]
### Summary
[//]: # Using Genplus-gx, when loading a save state after disabling graphic layers, the layers revert back to normal in-game but the layer options stay in the "false" position. The correct behavior should be for the layers to stay visually disabled until I manually turn them back on.

### Repro
[//]: # 
1. Make a save state
2. Disable any layers
3. Load the save state

### Host env.
[//]: # 
- BizHawk 2.8; Win7 64bit; Intel/NVIDIA

**Comment by YoshiRulz** [comment]
Can you try a dev build? A similar bug #3363 was recently fixed.
