### ISSUE TITLE
[Request] Auto-disable cheats when playing a movie

### ISSUE THREAD

**Issue by ReyVGM** [TASEmulators/BizHawk#3389]
When playing a movie, any cheats you have stay active and usually desynchronize the movie.

I would like to request for either an auto-disable, or a prompt asking if you want to disable cheats when loading a movie. Something similar to what FCEUX already does.

![Capture](https://user-images.githubusercontent.com/7338867/191084341-b7acfa02-15ca-48e7-9f25-45241d654908.PNG)

**Comment by ReyVGM** [comment]
What does 2.9 milestone mean?

**Comment by YoshiRulz** [comment]
This is blocking release. Which is because this is necessary for our frontend determinism goal and I believe the fix will be simple.

**Comment by vadosnaprimer** [comment]
I think a prompt is the best possible idea. You should not be able to disable it, and you should be able to actually record with cheats. It should always explicitly give you the option.

**Comment by ReyVGM** [comment]
> This is blocking release. Which is because this is necessary for our frontend determinism goal and I believe the fix will be simple.

I see. Thanks.

Any chance this old #3091 can be included in that milestone?
