### ISSUE TITLE
[Core Port Req.] (DuckStation, PSX)

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3392]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for duplicate core requests, both on the issue tracker and on this Wiki page: https://github.com/TASEmulators/BizHawk/wiki/Core-Requests"

### Upstream info
- [Website](https://www.duckstation.org)
- Target platforms: Win10+ and Linux, x64 and arm64
- [Source repo](https://github.com/stenzek/duckstation)
- Language(s): C++
- License: GPLv3

### Merits
[//]: # "Briefly explain why this emulator is worth including in BizHawk. If it emulates the same system as an existing core, compare them."
The emulator emulates PSX very well, even replaced ePSXe

### Technical details
[//]: # "Non-exhaustive list of things to consider:"
- (able to build .dll/.so for P/Invoke?) unknown
- (frontend/backend separation--for example, can backend be built without SDL?) No, SDL required
- (can force single-threaded?) unknown
- (has I/O abstraction accepting byte array, or only accepts file paths? for disc-based consoles, can swap out implementation for BizHawk's?) unknown
- (savestate quality) "Good"

Alternatives:
- https://github.com/BluestormDNA/ProjectPSX

**Comment by CasualPokePlayer** [comment]
What's the point of this when we have Nymashock.

**Comment by Spikestuff** [comment]
> What's the point of this when we have Nymashock (i.e. waterboxed mednafen PSX core). 

There's no point, especially when some of the stuff within DuckStation is based on mednafen.

DuckStation also has a heavy addition of selectable hacks, which is better to prevent anyone from asking for such features, and goodsizers, that have never been only part of two PlayStation encodes for the site itself, before being promptly ditched and ignored for software rendering.

What's the point of doing more work to avoid implementing where less work is actually better (mednafen)?

> The emulator emulates PSX very well, even replaced ePSXe

Not worth a point of comparison when ePSXe is a closed source emulator full of hacks and junk.
It would've been more fair to compare it to PCSX-R[-PGXP].

**Comment by CasualPokePlayer** [comment]
Duckstation recently has switched their licensed to CC No-Derivatives Non-Commercial, so it's effectively just source available, disallowing someone like us making a core out of their emulator. We technically have an option of using the last GPLv3 version, but such usage would forever be stuck with effectively a "dead" upstream, and not much point since again Nymashock exists.
