### ISSUE TITLE
SGB BSNESv115+ lag frames are from the GB component, not from actual SNES

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3394]
Lag frames in SGB BSNESv115+ are from the GB component instead of base SNES. As such, it's possible to open the SGB Menu with L and R buttons (not the D-Pad) while BizHawk interprets these lag frames are present, which defies lag frames (because the controller input for the GB component of SGB is actually from base SNES, not GB itself).
Proper lag frames are present in original BSNES core.

**Comment by CasualPokePlayer** [comment]
This was intentional.

**Comment by getCursorsExe** [comment]
SNES lag frames here determine if the input is accessible by the GB component (this is how SGB works, SNES input is actually used to transfer input to GB component). It's actually possible for GB component to execute any code SNES-side, which usually leads to a SNES crash. Should we combine both SNES and SGB lag frames for this? But if you want it like it is currently, then okay.

**Comment by YoshiRulz** [comment]
A partial-poll indicator would be ideal, but I certainly don't want to try writing that.

**Comment by CasualPokePlayer** [comment]
> SNES lag frames here determine if the input is accessible by the GB component and the SGB menu

In practice this is essentially every frame, as the SNES side will constantly poll the physical controllers. This doesn't give you useful lag info at all.

> It's actually possible for GB component to execute any code SNES-side, _which usually leads to a SNES crash._

What the fuck are you even talking about? This is used by 1 commerial game and that's not a crash, that's just executing an SNES game transferred from the GB cart. Of course this does give some merit to using SNES lag frames, but as it's used in only  1 commerial game (and that's Space Invaders lol) I wouldn't bother.

**Comment by getCursorsExe** [comment]
> Wtf are you even talking about?

https://www.youtube.com/watch?v=4A1Wrff-6Xw

**Comment by getCursorsExe** [comment]
Also, every 162 frames, a random lag frame appears out of nowhere.

**Comment by CasualPokePlayer** [comment]
> see https://www.youtube.com/watch?v=4A1Wrff-6Xw

That's not a crash that's someone running some homebrew that specifically just screws around with the screen, like the description says.

> Also, every 162 frames, a random lag frame appears out of nowhere.

Yes, this is more due to the SNES and GB not running at the same "framerate." This is expected behavior and this is in fact what occurs on an actual console. This is one thing you could not see if you simply marked SNES polls as not lag.

**Comment by getCursorsExe** [comment]
If we input the SGB credits code (L L L R R R L L L R R R R R R R) on BSNES and BSNESv115+, we can see the difference without memory editing.
