### ISSUE TITLE
System.IndexOutOfRangeException at BSNESv115 graphics debugger

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3399]
This issue can be reproduced with World Class Service Super Nintendo Tester after reaching "Look for many Service Marios" screen in Character test. Opening the graphics debugger at that point might sometimes cause System.IndexOutOfRangeException when the output screen cuts to black. Visual Studio Breakpoints say that this is located at line 338 in BizHawk.Emulation.Cores.Nintendo.SNES.SNESGraphicsDecoder, which is just at the very end of `RenderMode7TilesToScreen`.

**Comment by YoshiRulz** [comment]
Do you mean here?
https://github.com/TASEmulators/BizHawk/blob/9fa38b8d78aef698f29b09bda77889fc1f21a9b2/src/BizHawk.Emulation.Cores/Consoles/Nintendo/BSNES/SNESGraphicsDecoder.cs#L337-L338
If you could copy the stacktrace, that might be more helpful than a line number.

**Comment by Morilli** [comment]
Stacktrace I got: 
```csharp
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei BizHawk.Emulation.Cores.Nintendo.BSNES.SNESGraphicsDecoder.RenderMode7TilesToScreen(Int32* screen, Int32 stride, Boolean ext, Boolean directColor, Int32 tilesWide, Int32 startTile, Int32 numTiles) in D:\GitHub\BizHawk\src\BizHawk.Emulation.Cores\Consoles\Nintendo\BSNES\SNESGraphicsDecoder.cs:Zeile 330.
   bei BizHawk.Client.EmuHawk.SNESGraphicsDebugger.RenderTileView()
   bei BizHawk.Client.EmuHawk.SNESGraphicsDebugger.InternalUpdateValues()
   bei BizHawk.Client.EmuHawk.SNESGraphicsDebugger.UpdateAfter()
   ```
![image](https://user-images.githubusercontent.com/35152647/192630919-040b1883-e60d-4183-8d8e-074216b4ff74.png)
Can't investigate right now, but here it is for now.
