### ISSUE TITLE
.DMG and .CGB file extensions

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3408]

**Comment by CasualPokePlayer** [comment]
Those are not actually used for games.

**Comment by getCursorsExe** [comment]
I believe this now leads to an inconsistency with other emulators such as BGB. These file extensions reference Gameboy/Gameboy Color games. I think we should add these file extensions at least.

**Comment by YoshiRulz** [comment]
Switch to the "All Files" filter in the file picker for these, or drag-and-drop, or rename the rom(s) in question. File extensions are meaningless anyway.

**Comment by endrift** [comment]
They don't "normally" reference games at all since nothing uses them. The standard is .gb for GB games and .gbc for GBC games.

**Comment by Testsr** [comment]
BGB can load anything as a rom, so that source is not valid.
