### ISSUE TITLE
Something with Display configuration in Nymashock isnt quite right

### ISSUE THREAD

**Issue by TizianoMattei** [TASEmulators/BizHawk#3409]
### Summary
During usage of the new core, i've come across some weirdness regarding display settings, however this was mostly reported to me by other users as we were collaborating on stuff on other PSX games, as i dont usually try anything different than "Use system's recommendation"

### Repro
1. Open a PSX game in nymashock
2. Config
3. Display
4. Use display settings that arent "system recommendation", like 1:1 pixel size, unchecking "mantain aspect ratio", or "expand pixels by integers".

### Output

The following are side to side comparisons of the same settings, on a fresh bizhawk config.ini file, between octoshock and nymashock

![1](https://user-images.githubusercontent.com/87330697/194722831-72117724-02dc-47fe-8a6e-87580cf9ed8b.png)
![2](https://user-images.githubusercontent.com/87330697/194722901-2024f8cd-0b6e-4ba2-ae0d-3f55658228ce.png)
![3](https://user-images.githubusercontent.com/87330697/194722964-18646801-7cee-49fe-8416-fe6c47772d39.png)

There's also stretching whenever one tries to dump footage from the emulator, if one doesnt check first "capture OSD" option.
For example, following any guide here: https://tasvideos.org/Forum/Topics/22681, like using this ```-vcodec libx264 -pix_fmt yuv420p -crf 20 -acodec aac``` as custom command on ffmpeg in bizhawk, depending on wether or not the user has checked the capture OSD option, gives these 2 different results (with the same display settings as shown):
![4](https://user-images.githubusercontent.com/87330697/194723539-a27884a3-9c3a-4b00-8ed4-e77dde59af47.png)

### Host env.
Bizhawk 2.8, Win10 22H2, AMD Cpu, Nvidia GPU

**Comment by CasualPokePlayer** [comment]
This is expected behavior. Disabling aspect ratio correction will make the core output something similar to "hardcore debug mode" of Octoshock, which won't look pretty but that is what the core is outputting.

**Comment by TizianoMattei** [comment]
I see. But is the avi dump supposed to be that stretched when recording movies without the "capture OSD" thicked? That's with default settings, i've seen quite a few users outside TAS usage that have no idea why only their footage out of bizhawk looks so distorted and have no idea how to solve it

**Comment by CasualPokePlayer** [comment]
Yes, if you don't tick capture OSD the AVI dumper goes to the raw video buffer instead of what's output by the DisplayManager (which does aspect ratio correction here).

Expand pixels by integer only would probably cause distortion. It would be fine if square pixels were actually outputed on console, but that is not the case.

**Comment by TizianoMattei** [comment]
That makes sense, thanks for the explanation, if anything i would at least suggest to make default "capture osd", then
