### ISSUE TITLE
NES [Enhancement] Does it possible to make option for sound...

### ISSUE THREAD

**Issue by WhiteMagicRaven** [TASEmulators/BizHawk#3422]
Just look that great video, explaining on how sound can be enhanced highly
https://www.youtube.com/watch?v=8RrQrATnXXY&t=68s&ab_channel=KYLXBN

**Comment by CasualPokePlayer** [comment]
No

**Comment by YoshiRulz** [comment]
Though see #3164 re: accuracy and #3306 re: control over mixing.
