### ISSUE TITLE
ffmpeg not working in linux

### ISSUE THREAD

**Issue by dananothername** [TASEmulators/BizHawk#3430]
![Screenshot_2022-10-23_10-28-19](https://user-images.githubusercontent.com/101902085/197397853-5a1a394a-9e9c-45b9-a934-85b3c7f608ca.png)
in this screenshot it tried 
1-download ,but FAILED 
2-download the binary manly with symlink for both win64 and linux binary one each time

**Comment by YoshiRulz** [comment]
Please try a [dev build](https://github.com/TASEmulators/BizHawk#development-builds), which will have the option to automatically download FFmpeg like you can on Windows.

**Comment by dananothername** [comment]
![Screenshot_2022-10-23_12-39-36](https://user-images.githubusercontent.com/101902085/197404451-d9bea2c8-73e0-49f6-8a0a-1149e35de6d1.png)
thanks 
any further advice

**Comment by YoshiRulz** [comment]
No because I don't use the A/V feature :P Ask in the TASVideos Discord server's #encoding channel.

**Comment by dananothername** [comment]
![Screenshot_2022-10-27_05-54-15](https://user-images.githubusercontent.com/101902085/198840422-a277e2ce-988e-4412-b021-fadb2a37693d.png)
how can i increase the memory given for dsi core
