### ISSUE TITLE
How do I use Bizhawk on MacOS Big Sur

### ISSUE THREAD

**Issue by Gamemaker182** [TASEmulators/BizHawk#3433]

**Comment by Gamemaker182** [comment]
Hello, I want to use Bizhawk but I am on macos big sur. How can I do it?

**Comment by YoshiRulz** [comment]
As the [readme](https://github.com/TASEmulators/BizHawk#macos-legacy-bizhawk) says, BizHawk is not currently built for macOS, so you have the option of
1. using Sappharad's builds; or
2. launching a Windows or Linux VM.

**Comment by Gamemaker182** [comment]
What's Sappharad's build?

Le ven. 28 oct. 2022 à 09:07, James Groom ***@***.***> a
écrit :

**Comment by YoshiRulz** [comment]
[TASVideos forum post](https://tasvideos.org/Forum/Topics/12659?CurrentPage=9&Highlight=481258#481258)

**Comment by Sappharad** [comment]
My old builds stopped working starting with macOS 11, for unknown reasons.
As far as I'm aware, there are currently no builds of BizHawk that work on the latest macOS versions.
