### ISSUE TITLE
PAL Nintendo 64 video output is smushed

### ISSUE THREAD

**Issue by alkamaass** [TASEmulators/BizHawk#3434]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # 
![image](https://user-images.githubusercontent.com/77021109/198699213-eb6f09a1-772c-495d-9fe4-ba171f2bded7.png)
The graphics on Perfect Dark n64 PAL are smushed and it makes it unclear to read decimals at times despite it being clear on console https://www.youtube.com/watch?v=7YZZ7tjniEM. I am using ARES core

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load Perfect dark EU/PAL with the Ares core
2. turn on the timer decimal ingame with options - display -show mission timer

### Host env.
Windows 11, Bizhawk 2.9 Dev build

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
This game seems to be interlaced, was this screenshot with Weave deinterlacing or Bob deinterlacing?

**Comment by alkamaass** [comment]
I wouldn't worry about this post it isn't even ares lmao
