### ISSUE TITLE
Genesis Plus GX crashes after completing Night Striker

### ISSUE THREAD

**Issue by despoa** [TASEmulators/BizHawk#3439]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
After completing a game of Night Striker, BizHawk crashes right after the high score screen and during the opening splash credits. There's no log or error screen, the emulator hard crashes and closes.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Play through the game using a Redump verified BIN/CUE combo. [This replay movie](https://tasvideos.org/7700S) can be used.
2. Continue to let the emulator run after beating the game or after the movie ends until it gets to the opening screens.
3. The emulator will crash.
### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8; Win10 Home 19044; Intel/Nvidia

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
Debugging shows this
```
Thread 1 received signal SIGFPE, Arithmetic exception.
[Switching to Thread 22008.0x59cc]
0x0000036f000fb2b6 in gfx_update (cycles=1752) at core/cd_hw/gfx.c:629
```
https://github.com/TASEmulators/BizHawk/blob/948084a97e4bfc9e5c9132cf5123430d9b39f339/waterbox/gpgx/core/cd_hw/gfx.c#L629
Debugging also seems to show gfx.cyclesPerLine is 0 in this case, somehow...

**Comment by YoshiRulz** [comment]
Please try [a dev build](https://github.com/TASEmulators/BizHawk#development-builds).
