### ISSUE TITLE
[F.Rq.] Expose GPGX' "disable sprite limit" setting

### ISSUE THREAD

**Issue by Sonia-7** [TASEmulators/BizHawk#3440]
It's an enhancement feature that's nice to have for casual playing and such. We already have it for other cores like NES/SMS/PCE, so why not.

Standalone bsnes v115 can already do it natively, so it's just a matter of importing over.

**Comment by Morilli** [comment]
I'm not actually sure what this option does exactly, is it just visual or does it actually affect emulation?
In any case this would be easy to implement; it's one of the configuration options not currently exposed anywhere in the frontend: https://github.com/TASEmulators/BizHawk/blob/f1f0f1695c3dbd18ff939d06a8f718733ee2a957/waterbox/bsnescore/bsnes/sfc/interface/configuration.hpp#L40

**Comment by Sonia-7** [comment]
It's just a visual setting. In the case of SNES it makes possible to display more than 32 sprites per scanline, bypassing the original PPU's limitation.

Such options can be toggled on/off whenever in a core and it's a non-sync setting.

**Comment by getCursorsExe** [comment]
To my surprise, this is also an issue in Genplus-gx, the upstream frontend has this option present, while BizHawk doesn't.

**Comment by Morilli** [comment]
Do you perhaps know a specific game or test rom that could be used to test this functionality?

**Comment by Sonia-7** [comment]
> Do you perhaps know a specific game or test rom that could be used to test this functionality?

Yes. On Alttp's Helmasaur King battle, after you kill him the explosions will normally flicker a little, but with limit disabled they won't.

There's a practice rom of the game floating on the web that's pretty easy to find. Just google "alttp practice rom". It will let you skip straight to that battle through the in-game menu (accessible by pressing R+Start).

**Comment by Morilli** [comment]
Hm, I couldn't figure out how to get the actual boss fight to work, and from a 100% TAS playthrough I also couldn't spot the flickering in the encode (it looked pretty normal to me).

**Comment by Sonia-7** [comment]
I made a save state on e7e587d6, using the vanilla USA rom:
[helma.zip](https://github.com/TASEmulators/BizHawk/files/9981607/helma.zip)

This will send you straight to the boss dying. Play it with the limiter enabled, then disabled so you can see the difference. Basically, some of the explosions aren't fully rendered (parts of the graphics are missing).

**Comment by Morilli** [comment]
Have resolved the bsnes part of this with c21fedc76a1008df83e31d3278a888a904986a98. Wanna keep this open for genplus-gx specifically @YoshiRulz ?

**Comment by Sonia-7** [comment]
GPGX is currently the only major older system missing this feature. Do you think you can expose for it as well, @Morilli?
