### ISSUE TITLE
The debugger is greyed out and can not be used at all

### ISSUE THREAD

**Issue by buruto** [TASEmulators/BizHawk#3446]
At the end of #3445 @CasualPokePlayer said:

> Change the core to Octoshock (Config -> Cores -> PSX) if you want to use the debugger.

I did it but the debugger is still greyed out and can not be used at all.

Why the debugger is not simply always available for use?

I already know that @CasualPokePlayer said that the debugger is garbage and barely works so at least warn the user about this when he or she wants to try the debugger but this is pretty annoying that the debugger is always initially greyed out and the user always must enable it.

Please at least let all the users the option to try the debugger and report any bugs and issues that they will find.

If the debugger is so bad and all the users will find the debugger completely useless according to @CasualPokePlayer then why not simply remove the debugger from the Tools menu and that's it?

**Comment by CasualPokePlayer** [comment]
Did you reboot the core like it tells you to do?

**Comment by buruto** [comment]
> > I did it but the debugger is still greyed out and can not be used at all.
> 
> Did you reboot the core like it tells you to do? That is what makes the actual switch over to Octoshock.
> 
> > Why the debugger is not simply always available for use?
> 
> If a core doesn't implement debugging services, then the debugger cannot work in any respect.
> 
> > why not simply remove the debugger from the Tools menu and that's it?
> 
> The debugger is garbage but not completely useless. It's workable if that is literally your only option.

You answered all of my questions.
I switched from nymashock to octoshock but I was **not** told to reboot the core.
I rebooted the core and now the debugger is available for use but it is very limited.

Is there a website where I can download more cores to be used with BizHawk?

**Comment by YoshiRulz** [comment]
> Is there a website where I can download more cores to be used with BizHawk?

EmuHawk can use Libretro (RetroArch) cores, but not all of them will work, and they will be missing even more debugging features. RetroArch's Beetle core is the same as Nymashock anyway.

**Comment by buruto** [comment]
> > Is there a website where I can download more cores to be used with BizHawk?
> 
> EmuHawk can use Libretro (RetroArch) cores, but not all of them will work, and they will be missing even more debugging features. RetroArch's Beetle core is the same as Nymashock anyway.

I understand. Looks like I must find another emulator with a better debugger than BizHawk then.
