### ISSUE TITLE
Mute hotkey

### ISSUE THREAD

**Issue by anewuser** [TASEmulators/BizHawk#3450]
Could you add a hotkey for muting/unmuting Bizhawk?

![ad](https://user-images.githubusercontent.com/6733770/201679770-cb39b21c-0c3d-437a-a5df-7abd41d3e555.png)

**Comment by YoshiRulz** [comment]
![2022-11-15T11:53:58](https://user-images.githubusercontent.com/13409956/201807292-16aee928-2366-4b47-8088-ccb522b60756.png)

**Comment by anewuser** [comment]
Could you move it next to the `Volume Up` and `Volume Down` options?
