### ISSUE TITLE
socketServerScreenShot consistency with other socket methods

### ISSUE THREAD

**Issue by victorsevero** [TASEmulators/BizHawk#3461]
Hello! I implemented a socket server to interact with BizHawk's socket and everything was going pretty well until I decided to send image bytes instead of simple numeric variables. Here's what is happening: `comm.socketServerSend(string sendstring)` send that first integer representing total number of bytes in sent message, which is great! This is my first experience with sockets, but it seems like a good practice. But the problem is: `socketServerScreenShot` does not use it and it seems important specially for images, which don't usually fit in the ideal buffer sizes (1k to 4k, if I'm not mistaken).

So... could we get something like that for all socket send methods? Also, wouldn't it be better if that "len number" had a fixed size? That also seems like a good practice, as it would allow people to receive, for example, the first 4 bytes to determine message length, and then receive only the following N bytes as seem in first message.

**Comment by YoshiRulz** [comment]
Not going to change to fixed-width integer for length.

**Comment by victorsevero** [comment]
@YoshiRulz one more question: I manually resized BizHawk window (like dragging that arrow in one of its corners) to make its window be 640x480. When I screenshot through UI, the resolution is exactly that, but when using `socketServerScreenShot`, the PNG is 240x350 (which I think is equivalent to setting Window > View Size > 1x in UI). Is this intentional?
