### ISSUE TITLE
questions support 

### ISSUE THREAD

**Issue by dananothername** [TASEmulators/BizHawk#3465]
how to save the game progress into the rom
and i am not talking about save states 
or
- start input recording without restarting the game from the beginning

**Comment by YoshiRulz** [comment]
`File` > `Movie` > `Record Movie...` then set this dropdown to "SaveRam".
![2022-12-02T03:32:49](https://user-images.githubusercontent.com/13409956/205121467-3f267110-2736-4317-8003-870eb27a27a4.png)
You can then immediately save the movie and open it in TAStudio if you'd prefer.
