### ISSUE TITLE
VBA Gameboy sound output request

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3470]
VBA is very popular even though it is very inaccurate. With that emulator being popular I'm thinking about simulating VBA sound output (false by default, during movie recording gets immediately set to false). It shoudn't affect the sound registers behavior, this only changes how the audio is processed, not the console's sound controller, because it would cause all sound test ROMs to fail (VBA already fails all of them).

**Comment by CasualPokePlayer** [comment]
No

**Comment by getCursorsExe** [comment]
Well, if you didn't know, some people prefer to have VBA output for sound, while some prefer the hardware output. But if you don't want this, then okay.
