### ISSUE TITLE
Gambatte audio distortion caused by this savestate

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3473]
[DebugYellow.Gambatte.QuickSave2.zip](https://github.com/TASEmulators/BizHawk/files/10149358/DebugYellow.Gambatte.QuickSave2.zip)
this savestate causes the audio to be distorted that stays forever until you reload the core (not even hard resetting fixes this).
Interestingly, the corrupted audio IS saved by the savestates, meaning you can load a savestate without corruption to fix these ear-deafening noises (and vice versa). Only Gambatte is affected by this issue.

This video demonstrates this (TURN DOWN THE VOLUME AS LOW AS YOU CAN):
https://user-images.githubusercontent.com/39802077/205513223-359f89d8-b2c0-4d36-8b5b-918c5421e778.mp4
```
DebugYellow
SHA1:ECE578EE1642A7AA9A3C9DE9F647E7599ABF0231
MD5:E7B6D8EC4BB227B1E9E2E3A0C6219D41

Core reported Header Name: POKEMON YELLOW

**Comment by getCursorsExe** [comment]
Imagine if TheZZAZZGlitch sees this...

**Comment by YoshiRulz** [comment]
The version metadata just reads "GIT #". Which version are you using?

**Comment by getCursorsExe** [comment]
Dev Build [683aa263](https://github.com/TASEmulators/BizHawk/commit/683aa263).

**Comment by nattthebear** [comment]
What are the repro steps?

**Comment by getCursorsExe** [comment]
This didn't actually happen in this case, I've just looked at sound registers and I didn't see anything wrong there.

**Comment by getCursorsExe** [comment]
So I believe either a core bug or something to do with Gambatte's sound emulation.

**Comment by getCursorsExe** [comment]
Also what MMIO register causes this?

**Comment by getCursorsExe** [comment]
> From what I can tell, hard reset does clear out this problem if skipping the bios isn't done (the state was made with skip bios setting enabled, not hard to force it back on).

Unfortunately, this did not clear out this issue for me. The distortion still persists. And the issue doesn't happen always, this actually depends on timing.
