### ISSUE TITLE
[Ares] black screen on any rom

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#3477]
On bizhawk pre-release 2.9, I tested games that used to work like buck bumble and now its a black screen.

Running ubuntu.

**Comment by CasualPokePlayer** [comment]
![image](https://user-images.githubusercontent.com/50538166/206080736-0a1a629e-7f01-4470-9c3f-9e460f1f26e4.png)
It seems to work fine for me? (using Windows here)

**Comment by InfamousKnight** [comment]
I don't know. Are you using the prerelease? I don't know how to take screenshots, but I swear its not working on my end. I even waited like 2k frames. And the frames are all lag frames(colored red)

**Comment by CasualPokePlayer** [comment]
What is the hash of the rom file?

**Comment by InfamousKnight** [comment]
How do you find hash?

**Comment by CasualPokePlayer** [comment]
`md5sum path/to/file`, and by click the bottom left checkmark (or ?/other symbol if that's there instead).

(rom file here being buck bumble).

**Comment by InfamousKnight** [comment]
2bd134f866af753ab46767fac3144e2e

**Comment by CasualPokePlayer** [comment]
That would match a byteswapped dump (I'm using a native big endian dump). The internal rom fixing code might be faulty then?
