### ISSUE TITLE
[TAStudio] Max Undo Level keeps resetting to 100

### ISSUE THREAD

**Issue by WarHippy-1** [TASEmulators/BizHawk#3478]
### Summary

In TAStudio ribbon go to Config>Set max Undo Level. It reverts back to 100 every time you close tastudio.

BizHawk 2.9
Mupen64Plus
Star Fox 64 (U) (V1.0) [!].z64

**Comment by YoshiRulz** [comment]
This is stored in `TasMovie.ChangeLog` and so does not get written to disk.

**Comment by vadosnaprimer** [comment]
Sounds like a good thing to request to make it persist across all sessions. Probably poor initial implementation.
