### ISSUE TITLE
Cannot alter N64 video plugin settings when TAStudio is open

### ISSUE THREAD

**Issue by WarHippy-1** [TASEmulators/BizHawk#3479]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
With an N64 rom loaded I can freely change video plugin settings, but when tastudio is opened it prevents the Plugins and Controller settings... option from being selected. It doesn't matter if there's a movie loaded into tastudio or not.

BizHawk 2.9
Mupen64Plus

[//]: # "(screenshots, if applicable)"
![Capture](https://user-images.githubusercontent.com/107928747/206264220-5e8bf6b0-a0b8-4821-a1d7-6555cea25d02.PNG)

**Comment by YoshiRulz** [comment]
This is not a bug, no core's sync settings may be changed while a movie is loaded. TAStudio does not have a "no movie loaded" state.
