### ISSUE TITLE
[Feature request] Option to force static screen size

### ISSUE THREAD

**Issue by WarHippy-1** [TASEmulators/BizHawk#3480]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
When loading a rom the screen reverts to the default resolution, and I have to resize it every time. I would like an option to force the screen to always be the same size it currently is.

**Comment by vadosnaprimer** [comment]
It's there in display config.
