### ISSUE TITLE
[Feature request] Hotkey to accept background input

### ISSUE THREAD

**Issue by WarHippy-1** [TASEmulators/BizHawk#3481]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

In the Bizhawk window go to Config>Customize... There's an option to accept background input. I find myself frequently using this option for re-syncing work where I'm always comparing side-by-side with another tas. I would really like a hotkey to be able to toggle this on and off.

**Comment by YoshiRulz** [comment]
How is the hotkey going to work if background input is on? In two instances as well?

**Comment by WarHippy-1** [comment]
So yah, I will have the original run in the 1st instance of bizhawk and the file I'm re-syncing in the 2nd instance.  When I press the hotkey it will cause the first window to stop accepting input (assuming I had it turned on) and the current window to start accepting input. And since the current window has focus I simply have to press the hotkey a second time to turn it off.
