### ISSUE TITLE
Background loading of gamedb isn't blocking when autoloading rom, leading to miss

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3489]
I'm sure this is only a problem because my HDD is so slow.
![2022-12-10T14:22:08](https://user-images.githubusercontent.com/13409956/206828925-5ecbdbf1-24ad-4fa0-991e-65e3ab64504c.png)

**Comment by CasualPokePlayer** [comment]
There's normally `ManualResetEvent`s that would block however, are they not working or init in the wrong spot?

**Comment by YoshiRulz** [comment]
¯\\\_(ツ)\_/¯ but I was going to rewrite w/ `async`/`await` for #2939 anyway
