### ISSUE TITLE
ZX Spectrum +2A +3 Missing firmware

### ISSUE THREAD

**Issue by Mad-Matty** [TASEmulators/BizHawk#3494]
Opening a ZX Spectrum Tape or Disk with the ZX Spectrum core set to +2A or +3 results in a core exception window detailing missing firmware. 

These firmware's are embedded and not detailed in the firmware window.

Another possible issue is that Loading a savestate takes a second or so where the expected behaviour is to be instant like every other core.

This is happening in current dev builds of Bizhawk.

**Comment by YoshiRulz** [comment]
Need to double-check the rest of 5be8b0aab @CasualPokePlayer

I'll leave the poor loadstate performance for @Asnivor, and if he doesn't comment for a while then I'll open a separate Issue for it.
