### ISSUE TITLE
TAStudio recording mode may get toggled on erroneously

### ISSUE THREAD

**Issue by Morilli** [TASEmulators/BizHawk#3500]
I've found myself using recording mode more recently and I've stumbled upon a potentially dangerous bug:
There is a way to get recording mode to turn on (by itself), even though it was just turned off. This combined with the fact that recorded input is very hard to undo could possibly lead to losing input.

How to reproduce:
1. Open TAStudio with any ROM, in my case I'm using Super Mario World with the new BSNESv115 core
2. Toggle recording mode and enter any inputs for a couple of frames, let's say holding `R` for 10 frames.
3. Remove the `R` input in frame 9 by clicking on it. Then add a `L` input in that frame (or any other), again by clicking in TAStudio and still having recording mode toggled on.
4. Toggle recording mode off by using the "Toggle read-only" hotkey (Q by default)
5. jump to any other frame, like frame 2.

Recording mode gets turned back on now, even though there is no reason for that to happen.

**Comment by YoshiRulz** [comment]
May be related to #2619 or #2641.

**Comment by vadosnaprimer** [comment]
Is there an old release where it still works correctly?

**Comment by Morilli** [comment]
> Is there an old release where it still works correctly?

Tested as far back as 2.3 and 1.13.2 and all of them are bugged.

**Comment by Morilli** [comment]
I did have a look at the code and I'm pretty sure the issue lies here: https://github.com/TASEmulators/BizHawk/blob/05ff3ab40cd64bef4440564be91191760e6db89b/src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs#L111-L115

**Comment by vadosnaprimer** [comment]
CNR on latest master.

**Comment by Morilli** [comment]
> CNR on latest master. Can you make a video?

Sure:

https://github.com/TASEmulators/BizHawk/assets/35152647/d8c6fc88-37fb-4bb0-8c4c-4d0ff9256eab

**Comment by vadosnaprimer** [comment]
Ah. It doesn't happen when using the actual Rec mode checkbox, which is why I never knew about this bug (since I never use the hotkey).

**Comment by vadosnaprimer** [comment]
@Morilli check if ^ helps.

**Comment by Morilli** [comment]
> @Morilli check if ^ helps.

This does indeed fix this issue, although with your followup commit b4a6b06fba12b3fa86de0d5f604df3ee51c68fd0 this scenario cannot happen anymore anyway.
Which is probably fair, as the only reason the reproduction steps came to be in practice was because of the scenario mentioned in #2144, where you usually don't want recording mode checked after manually editing anyway.

**Comment by vadosnaprimer** [comment]
Lol right.
