### ISSUE TITLE
Bizhawk taking 30+ seconds to launch when Vive Pro 2 connected to PC

### ISSUE THREAD

**Issue by mycenotaph** [TASEmulators/BizHawk#3503]
### Summary
When I have my HTC Vive Pro 2 connected to the PC and I launch Bizhawk, there is a strange 30-40+ second delay before it launches, but then it just launches normally. Occasionally I'll have a 30+ second freezeup during gameplay (has happened in different cores, so I don't think it's got anything to do with that) where Bizhawk just stops responding completely, and then resumes as if nothing has happened. There is no spike in CPU usage, memory usage, network usage, or disk usage. It feels like it's waiting for something to happen and times out and moves on.

### Repro
1.) Plug in my Vive Pro 2 (turning the breakout box that it is connected to physically works) - do not open SteamVR, just have the Vive powered, connected, and off.
2.) Start Bizhawk
3.) ??? [confusingly long wait for the application to open]
4.) Things work fine from there 

[note that I have seen the cursed 30 second freezeup happen during gameplay as well on occasion, usually when switching focus to another window -- generally, OBS on my second display. However, the easiest way to duplicate the issue is to just start Bizhawk with the Vive Pro 2 connected. If I disconnect it, it's fine.

### Host env.
Bizhawk 2.8.0: Win10 Pro, AMD/NVIDIA
Have tried this on a few older builds as well, doesn't seem to matter which build, they all do it on this machine.

I know this isn't exactly common hardware, if you need me to try test builds out to generate debug info or whatever feel free to ask

**Comment by CasualPokePlayer** [comment]
Does this still happen on the latest dev build?
