### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by deft20** [TASEmulators/BizHawk#3515]
when i try to run my cue file it gives me this error 
![loading error](https://user-images.githubusercontent.com/122054346/210873043-b2617185-5f25-47c3-ac9c-9d2cbcdca3c9.JPG)

What can I do to fix this

**Comment by YoshiRulz** [comment]
Open DiscoHawk, then select the `.bin`+`.cue` in the File Explorer and drag+drop into the top-right "HAWK" box.
