### ISSUE TITLE
Slot 10 is still Slot 0 it seems

### ISSUE THREAD

**Issue by Sonia-7** [TASEmulators/BizHawk#3521]
If you select slot 10 and save there, it still saves to slot 0 anyway. Either slot 10 needs to go back to being 0 as in 2.8, or the new changes should be reflected properly upon saving.

**Comment by YoshiRulz** [comment]
??? Do you mean the filename? I left it as a single char on purpose.

**Comment by Sonia-7** [comment]
There are 10 save slots total. It used to be 1,2,3,4,5,6,7,8,9,0 in that order until 2.8. Saving to slot 0 would save to 0 as intended. Now that 0 became 10, but if you save there it still says you saved to 0 instead of 10 as one would expect. This number mismatch is causing confusion now. Am I saving to 0 or 10 after all? I don't know anymore.

If this is still not clear enough I could make a video showing the issue in action.

**Comment by YoshiRulz** [comment]
It says "Saved to QuickSave0" and writes `*.QuickSave0.State`.

**Comment by Sonia-7** [comment]
Then what's the point of changing the name to "State 10" in the hotkeys window and others?

**Comment by YoshiRulz** [comment]
Because we have 10 slots starting from number 1, matching most keyboard layouts. See #3112.
