### ISSUE TITLE
Docs for `value` param of `CallMemoryCallbacks` are incomplete/wrong

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3522]
https://github.com/TASEmulators/BizHawk/blob/15056f11f2ac1f1b186e9144a259cc35d9bd633e/src/BizHawk.Emulation.Common/Interfaces/IMemoryCallbackSystem.cs#L71

Seems the convention is to pass `value: 0` for exec *and also write*, making this doc comment incorrect.

Also I don't think this is mentioned anywhere in user-facing docs.

edit: This is just wrong (writes are before and r/x are before by convention, though again, that doesn't seem to be documented):
https://github.com/TASEmulators/BizHawk/blob/15056f11f2ac1f1b186e9144a259cc35d9bd633e/src/BizHawk.Client.Common/lua/LuaHelperLibs/EventsLuaLibrary.cs#L113

**Comment by CasualPokePlayer** [comment]
Passing value 0 is actually more a stub implementation when the core doesn't actually provide the value with its implementation. We do have quite a few cores which do pass the value to be written. I believe Octoshock is actually the only core that does pass the value to be executed in its implementation.
