### ISSUE TITLE
Cheat serialisation is borked

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3523]
...since introduction in 6616a75cf. First reported by @mcw4v3-x on Discord.
Value is written as decimal or hex or ???:
https://github.com/TASEmulators/BizHawk/blob/15056f11f2ac1f1b186e9144a259cc35d9bd633e/src/BizHawk.Client.Common/tools/CheatList.cs#L296
https://github.com/TASEmulators/BizHawk/blob/15056f11f2ac1f1b186e9144a259cc35d9bd633e/src/BizHawk.Client.Common/tools/Cheat.cs#L93-L95
https://github.com/TASEmulators/BizHawk/blob/15056f11f2ac1f1b186e9144a259cc35d9bd633e/src/BizHawk.Client.Common/tools/Watch/ByteWatch.cs#L132-L135
But read as hex:
https://github.com/TASEmulators/BizHawk/blob/15056f11f2ac1f1b186e9144a259cc35d9bd633e/src/BizHawk.Client.Common/tools/CheatList.cs#L368
Compare is written as decimal:
https://github.com/TASEmulators/BizHawk/blob/15056f11f2ac1f1b186e9144a259cc35d9bd633e/src/BizHawk.Client.Common/tools/CheatList.cs#L297
https://github.com/TASEmulators/BizHawk/blob/15056f11f2ac1f1b186e9144a259cc35d9bd633e/src/BizHawk.Client.Common/tools/Cheat.cs#L74
But read as hex:
https://github.com/TASEmulators/BizHawk/blob/15056f11f2ac1f1b186e9144a259cc35d9bd633e/src/BizHawk.Client.Common/tools/CheatList.cs#L376
(There is a `Cheat.CompareStr` but it's not used for serialisation, and it's just the same `FormatValue` calls as the value.)
I'm guessing there are more bugs in this.

**Comment by Morilli** [comment]
For future reference: The following code sets the cheat type to hex for saving, so specifying `NumberStyles.HexNumber` in the loading code is correct.
https://github.com/TASEmulators/BizHawk/blob/ad1f4f40b562424ea0281aac11cf880344efcb0f/src/BizHawk.Client.Common/tools/CheatList.cs#L284
