### ISSUE TITLE
mGBA PSG channels not captured by savestates

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3531]
see also https://github.com/mgba-emu/mgba/issues/2793
If this doesn't get fixed, the only way to fix it is to ~~waterbox~~ mGBA core, which is something you don't want to do that now.

**Comment by YoshiRulz** [comment]
Did you open that upstream issue, comment it on #2749, then delete the comment and open a new issue? Please don't do that.

> the only way to fix it is to waterbox mGBA core

And please stop saying this about every core; it's tired and rarely, if ever, true.

**Comment by getCursorsExe** [comment]
It was an accident, but I won't do it at all.
