### ISSUE TITLE
"IOException: The device is not ready" when loading `.cue`

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#3532]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."

When I try to an error message box appears instead of booting the game.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."

Just click File => Open ROM... or simpy press Ctrl+O and then open "Sonic 3D Blast.cue" and then this error message box appears on screen.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
A core accepted the rom, but threw an exception while loading it:
System.IO.IOException: The device is not ready.
  at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
  at System.IO.FileSystemEnumerableIterator`1.CommonInit()
  at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
  at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
  at BizHawk.Emulation.DiscSystem.CUE.CueFileResolver.Resolve(String path)
  at BizHawk.Emulation.DiscSystem.CUE.CompileCueJob.OpenFile(FILE f)
  at BizHawk.Emulation.DiscSystem.CUE.CompileCueJob.Run()
  at BizHawk.Emulation.DiscSystem.DiscMountJob.<RunBizHawk>g__LoadCue|15_0(String cueDirPath, String cueContent)
  at BizHawk.Emulation.DiscSystem.DiscMountJob.RunBizHawk()
  at BizHawk.Emulation.DiscSystem.DiscMountJob.Run()
  at BizHawk.Emulation.DiscSystem.DiscExtensions.CreateImpl(Nullable`1 type, String path, Action`1 errorCallback)
  at BizHawk.Client.Common.RomLoader.LoadDisc(String path, CoreComm nextComm, HawkFile file, String ext, String forcedCoreName, IEmulator& nextEmulator, GameInfo& game)
  at BizHawk.Client.Common.RomLoader.LoadRom(String path, CoreComm nextComm, String launchLibretroCore, String forcedCoreName, Int32 recursiveCount)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8, Win10 *Enterprise* 21H2, Intel x64

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
The nature of the error would imply this is not at all related to the actual game per se, as it ends up erroring in internal Windows when trying to resolve the .cue files. Could you post the exact .cue file? Also, where exactly did you place this .cue file?

**Comment by buruto** [comment]
> The nature of the error would imply this is not at all related to the actual game per se, as it ends up erroring in internal OS code when trying to resolve the .cue files. Could you post the exact .cue file? Also, where exactly did you place this .cue file?

I placed the .cue file in a directory where I place all the games that I want to play in the future and content of the .cue file is:

> FILE "F:\SEGA SATURN\101-150\125 SONIC 3D BLAST (U).BIN" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 06:17:21
  TRACK 03 AUDIO
    INDEX 01 07:10:24
  TRACK 04 AUDIO
    INDEX 01 07:21:30
  TRACK 05 AUDIO
    INDEX 01 09:52:22
  TRACK 06 AUDIO
    INDEX 01 13:03:13
  TRACK 07 AUDIO
    INDEX 01 16:21:55
  TRACK 08 AUDIO
    INDEX 01 19:47:42
  TRACK 09 AUDIO
    INDEX 01 22:58:06
  TRACK 10 AUDIO
    INDEX 01 25:45:42
  TRACK 11 AUDIO
    INDEX 01 29:18:05
  TRACK 12 AUDIO
    INDEX 01 31:52:44
  TRACK 13 AUDIO
    INDEX 01 35:03:12
  TRACK 14 AUDIO
    INDEX 01 37:57:03
  TRACK 15 AUDIO
    INDEX 01 41:04:34
  TRACK 16 AUDIO
    INDEX 01 44:00:39
  TRACK 17 AUDIO
    INDEX 01 46:49:56
  TRACK 18 AUDIO
    INDEX 01 49:43:31
  TRACK 19 AUDIO
    INDEX 01 52:32:54
  TRACK 20 AUDIO
    INDEX 01 55:01:21
  TRACK 21 AUDIO
    INDEX 01 57:53:46
  TRACK 22 AUDIO
    INDEX 01 58:21:17
  TRACK 23 AUDIO
    INDEX 01 58:48:14
  TRACK 24 AUDIO
    INDEX 01 58:55:71
  TRACK 25 AUDIO
    INDEX 01 59:16:11

**Comment by nattthebear** [comment]
> in a directory where I place all the games that I want to play

Is that directory `F:\SEGA SATURN\101-150`?  Probably not.  The `.cue` references an absolute location that doesn't exist.

**Comment by CasualPokePlayer** [comment]
Remove the `"F:\SEGA SATURN\101-150\` and make sure the `125 SONIC 3D BLAST (U).BIN` file is next to the .cue file.

**Comment by buruto** [comment]
> Remove the `F:\SEGA SATURN\101-150\` and make sure the `125 SONIC 3D BLAST (U).BIN` file is next to the .cue file.

Why BizHawk doesn't show me a clear error message box?

**Comment by nattthebear** [comment]
It does.  Drive F: is not ready, and you'd get the same if you tried to access it in Windows Explorer.

**Comment by CasualPokePlayer** [comment]
BizHawk is not a human, it doesn't understand that you're "asking" to access drive F because you got your dump from some shady site and doesn't understand the exact solution.

**Comment by YoshiRulz** [comment]
I agree that "The device is not ready" is not a helpful message for the end-user. We should encapsulate directory enumeration and throw "file not found" in that case. (And then handle missing files in `.cue` parsing better.)

**Comment by buruto** [comment]
I corrected the .cue file and now BizHawk plays the game fine. Looks like that I made a mistake while dumping this game. I am not so good at dumping my games. With a proper error message box I wouldn't open this issue in first place.

**Comment by Morilli** [comment]
> We should encapsulate directory enumeration and throw "file not found" in that case. (And then handle missing files in .cue parsing better.)

fwiw the core does usually throw a `DirectoryNotFoundException` when using an invalid path, and the error message is helpful. This specific `IOException` only happens when the path specified links to an existing, but not accessable device (for example a physical disk slot that has nothing inserted).

**Comment by buruto** [comment]
> > We should encapsulate directory enumeration and throw "file not found" in that case. (And then handle missing files in .cue parsing better.)
> 
> fwiw the core does usually throw a `DirectoryNotFoundException` when using an invalid path, and the error message is helpful. This specific `IOException` only happens when the path specified links to an existing, but not accessable device (for example a physical disk slot that has nothing inserted).

This puts me in blackout to see a so detailed error message box if "directory not found" is the only problem here.

I think that this must still must be improved.

**Comment by nattthebear** [comment]
> I agree that "The device is not ready" is not a helpful message for the end-user.

I disagree strongly.  That is the canonical message that MS Windows gives end users if, for instance, you try to access a floppy drive with no disk in it.  It's distinct from path or file not found; more like "Drive not found" but a bit more complex because the drive might exist but just isn't ready.  Boiling down all IOExceptions to just a generic "not found" hurts user debugging.

**Comment by nattthebear** [comment]
It would be nice to have the full pathname of the faulting file here.

**Comment by buruto** [comment]
> > I agree that "The device is not ready" is not a helpful message for the end-user.
> 
> I disagree strongly. That is the canonical message that MS Windows gives end users if, for instance, you try to access a floppy drive with no disk in it. It's distinct from path or file not found; more like "Drive not found" but a bit more complex because the drive might exist but just isn't ready. Boiling down all IOExceptions to just a generic "not found" hurts user debugging.

I am a windows user for many years and with windows applications and programs that I was using over years every time that a file or folder or directory or path was not found I saw an error message box that explicitly state it.

I don't remember that I was seeing the word "device".

**Comment by nattthebear** [comment]
> I don't remember that I was seeing the words "device" or "ready" at all.

As google shows, it's quite common even now that floppies are dead due to removable USB media:  https://letmegooglethat.com/?q=device+not+ready

**Comment by YoshiRulz** [comment]
🤏 This close to clicking the lock button.

Malformed `.cue`s are a common problem for our users and it's apparent that the UX could do with a rework. Debating exactly which text is shown in the error dialog is missing the point; the app shouldn't give up and slap a "this is your problem now" in the user's face when it could recover and analyse, maybe list some *options*. So I'd ask everyone to save their comments unless it's to suggest an improved UX design.

**Comment by buruto** [comment]
> > I don't remember that I was seeing the words "device" or "ready" at all.
> 
> As google shows, it's quite common even now that floppies are dead due to removable USB media: https://letmegooglethat.com/?q=device+not+ready

I am not dealing with floppies.
