### ISSUE TITLE
BizHawk 2.9RC2 - Display Configuration error

### ISSUE THREAD

**Issue by ImSpecial** [TASEmulators/BizHawk#3533]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
Decided to play around with the latest BizHawk for a while today and noticed I get this error message when selecting "Select" in the  Display Configuration settings, this worked fine in previous versions of BizHawk, ie. my Windows Explorer window would just open.

### Repro
See screenshot;
![2023-01-23_12-24-52](https://user-images.githubusercontent.com/4022372/214132504-002e899e-bad5-44c3-b620-5e66531a8768.png)

### Output
Massive amount of text, so here's link of it instead. :)
https://pastebin.grey.pw/?646ee937ca1aa27d#Gbk9mAH2PTEbkyWtE6ngWmziKHDHSanEymKpmxA4bbnL

### Host env.
Not much to say here, fully update, etc.
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2486

**Comment by CasualPokePlayer** [comment]
This was fixed already in latest dev builds.
