### ISSUE TITLE
Error when creating any NDS cheats

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3535]
An error is preventing me from creating any Nintendo DS cheats.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load Nintendo DS rom
2. open Cheats
3. Add a name to the blank cheat box, leaving Address and Value as is, and press Add

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.CheatEdit.GetCheat()
   at BizHawk.Client.EmuHawk.Cheats.AddCheat()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Host env.
BizHawk dev build at https://github.com/TASEmulators/BizHawk/commit/b11bb4fc226e03c04cfab409c5666b75471d8667; Win10;

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Did this work in 2.8?

**Comment by YoshiRulz** [comment]
Invariant broken here @CasualPokePlayer. (In your defence, it's not documented that `MainMemory`/`SystemBus` must be in the collection.)
![2023-01-25T01:49:39](https://user-images.githubusercontent.com/13409956/214341322-e161c3c6-8610-4457-bf84-788b46c92198.png)
https://github.com/TASEmulators/BizHawk/blob/0b7960ff04677577abf77b1ef0e6531a74539ee7/src/BizHawk.Emulation.Cores/Consoles/Nintendo/NDS/MelonDS.cs#L199

**Comment by CasualPokePlayer** [comment]
I believe this was a specific hack intended to make the debugger happy and be able to switch between ARM7 and ARM9 System Buses depending on current CPU selected for the disassembler iirc?
