### ISSUE TITLE
Missing characters for ANSI decoding for Hex Editor

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3540]
BizHawk's inplementation of Windows ANSI decoding for Hex Editor is missing characters from 0x80 to 0xFF.

This image shows all Windows ANSI characters. (don't look at the selected one)

![image](https://user-images.githubusercontent.com/39802077/215185407-14572bf5-1258-41f4-b901-acbd8fdce5ef.png)

**Comment by CasualPokePlayer** [comment]
BizHawk has an ASCII view, not "Windows ANSI" (which is really just one of Windows' code pages) which is frankly not useful for old consoles, they would be storing text as ASCII if anything, and if not it'd be just some custom encoding.
