### ISSUE TITLE
LUA scripts duplicated on Core Reboot

### ISSUE THREAD

**Issue by Malkierian** [TASEmulators/BizHawk#3543]
### Summary
I understand why LUA scripts need to be reloaded when rebooting the core. However, I don't think instances of the scripts are supposed to still be running after reloading the scripts. Right now, every time I reboot the core, the script duplicates itself. This presents a major problem if I'm trying to TAS and have to playback movies regularly.

### Repro
I want to have a visual input viewer for my TAS videos, so I found and started running this https://github.com/theballaam96/BizInputs though I had to go in and modify it just a bit to make it not spam the console with global reference errors.
But, it works for any other script I put in there. Anyway
1) Open N64 game.
2) Open LUA console, load script.
3) Start movie playback, which causes a core reboot.
4) See extra config window pop up.

### Host env.
- BizHawk 2.8 Windows 10

**Comment by Malkierian** [comment]
Now, to be clear, it doesn't seem to be running two instances when it reloads, it just continues displaying previous instances' windowed dialogs.

**Comment by Malkierian** [comment]
![image](https://user-images.githubusercontent.com/774771/215863692-19e3bd14-4e38-4a1f-8e1d-db49563890da.png)
After 3 movie starts.

**Comment by CasualPokePlayer** [comment]
This was fixed already (since https://github.com/TASEmulators/BizHawk/commit/ee66faba0bc118331f50cae6f9a886727a077199)

**Comment by Malkierian** [comment]
Oh, nice. I'll have to go grab a dev build.
