### ISSUE TITLE
Emulation still pauses when "Pause when menu activated" is unchecked

### ISSUE THREAD

**Issue by Malkierian** [TASEmulators/BizHawk#3545]
### Summary
Unless I'm misunderstanding something about that setting, it's not supposed to pause at all with that unchecked unless you hit the pause key. Not only does it still pause when I bring up a menu form (not just the toolbar, but actually clicking an entry in the menu bar and bringing up its form, like Config -> Customize), but it "pauses" in an obnoxious way, continuously replaying the audio from the last frame before the form came up.

### Repro
1) Uncheck `Pause when menu activated`
2) Load N64 game.
3) Bring up Customize form.

### Host env.
BizHawk devbuild release cf0ce0f5 Jan 27, Windows 10

https://i.imgur.com/GndVJgt.mp4

**Comment by YoshiRulz** [comment]
That setting only concerns the main menu bar, not modal dialogs.

This dialog must not use the helper for opening a modal dialog with the sound temporarily muted.
