### ISSUE TITLE
BGB Core port request

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3549]
Has accuracy advantage over Gambatte and GBHawk. Unfortunately, the source code is private, but I don't know if it can be ported with source code privated out.

**Comment by YoshiRulz** [comment]
Obviously not. And use the template.

**Comment by getCursorsExe** [comment]
Unless we could contact beware (the creator of bgb) for help? I don't think so.

**Comment by CasualPokePlayer** [comment]
I would rather not violate the GPL any further than hawk already is doing. Closed sourced elements should be considered a complete no as long as we have GPL cores (read: most ported cores).
