### ISSUE TITLE
Is possible run Linux build current version without Mono ?

### ISSUE THREAD

**Issue by Augusto7743** [TASEmulators/BizHawk#3551]
Hello.
I see Mono is an requirement.
Mono is used for TAS ? I not use TAS.
An OS with Mono load Mono libraries in system memory even not in use.
Thus being is possible run Bizhawk only for emulating and not TAS without Mono ?

Thanks for reading.
Have an nice week.

**Comment by YoshiRulz** [comment]
> Mono is used for TAS ? I not use TAS.

Mono is the implementation of the CLR, the runtime environment. It's necessary to even start the app.

> An OS with Mono load Mono libraries in system memory even not in use.

If you're referring to the sticky bit, [Wikipedia says](https://en.wikipedia.org/wiki/Sticky_bit#History) Linux has never done that. Modern GNU+Linux systems are much cleverer with RAM management, so you don't need to worry about it. If you're referring to disk space, then yes, that can't be helped.
