### ISSUE TITLE
DS TAS files not working on 2.9

### ISSUE THREAD

**Issue by IsaGoodFriend** [TASEmulators/BizHawk#3558]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
Opening a DS tas in 2.9 is bugged.  Playback is fine, but you're unable to jump around properly.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open a DS rom on 2.8, create a TAS project and save it.
2. Close 2.8 and open 2.9-rc2.
3. Open TAStudio and open the TAS project file, and you will get an error.
4. Pressing continue will run it as normal, but clicking on a frame ahead of the cursor will throw this error infinitely.  

### Output
https://pastebin.com/FFxmYWJ4

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9-rc2; Win11; AMD

**Comment by CasualPokePlayer** [comment]
Export as bk2 and import that. You may still need to do resync work with that.

Savestates are not compatible between versions.
