### ISSUE TITLE
Commodore 64 - desync issue (loading/savestate related?)

### ISSUE THREAD

**Issue by DrD2k9** [TASEmulators/BizHawk#3563]
### Summary
I have had a number of instances where TASing using the C64 core results in desyncs after TASing a while and then clearing greenzone.  Specifically, I'll load/run a game and begin TASing.  Then after clearing greenzone the game will load in differently causing a desync for inputs beyond the loading process.  I'm wondering if this has to do with changes in input during loading and/or savestates during loading affecting the Loading process of the games, but I don't know how to describe much beyond this.

I can say that nearly every time I've had this occur, the loading time after clearing the greenzone appearss to be faster, but not always.

I've only ever TASed in BizHawk using TAStudio, so I don't know if anyone donig classic frameadvance TASing would also experience this issue.

In discussing with NYMX, he has also seen this issue.

I probably should have reported this issue before, but wasn't sure exactly how to describe it.  I'm not even sure what I have described is enough for the devs to go on.

### Repro
I unfortunately don't have a way to definitively reproduce this bug.  Soemtimes it happens, sometimes it doesn't.

### Output
There are no error codes associated with this bug.

### Host env.
-I've had the issue with multiple host computers from different manufacturers (MSI, Dell, HP) with both AMD and Intel processors.
-I've seen this issue over multiple versions of BizHawk.  I'm fairly confident I've seen as far back as version 2.0, but I can't remember exactly when I first encountered it to know if I also saw the issue in 1.x.x versions.

**Comment by CasualPokePlayer** [comment]
I fixed some issues with states here: cd4c3cc3532310c05ba7258a4e9468158507e24a

It's not perfect, floppy disks are not properly savestates (being any changes to the internal copy are not stated). But this might fix the issues you personally encountered (you don't describe the type of games (rom/tape/disk) you encountered this with so I don't know)

**Comment by CasualPokePlayer** [comment]
As of 86b33bd3cefd85e18732cea6325daa8b33535ad0 the disk serializing issues should be fix. I believe that should fix all remaining savestate bugs with C64.
