### ISSUE TITLE
Octoshock: Rewind doesn't seem to work even though rewind buffer is being used

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3566]
### Summary
Rewind doesn't seem to work in Octoshock - however, the rewind buffer dialog reports that memory is being used , and Task Manager corroborates that memory usage, so I assume it's supposed to be supported. My apologies if I am misunderstanding this.

![image](https://user-images.githubusercontent.com/83939/221217794-c7835cbf-7170-4a5f-9b90-89e8ede517d0.png)

### Repro
1. load a PS1 game (I tried Puchi Carat, Moon Remix RPG Adventure, and Star Sweep)
2. try to rewind

### Host env.
- BizHawk dev at 5804ff0; Windows 10

**Comment by YoshiRulz** [comment]
Works fine on 3c3ab6578. Mess with the settings I guess.

**Comment by webbedspace** [comment]
OK, I found the issue… somehow "Input overrides hotkeys" was set 🦂
