### ISSUE TITLE
NES cheats compare byte changes every core reboot

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3567]
This can be reproduced by creating these cheat codes in Super Mario Bros 3.
OXKIPZOS
APKZALAZ
KKKZSPIU
ESKKKTEY
Compare bytes before core reboot:
D1
20
35
F0
Compare bytes after core reboot:
09
32
53
40
This causes cheats to not function at all. This issue existed from 2.3.2.
So in order to make them function, we have to enter these codes EVERY TIME AFTER RELOAD! Very annoying.

**Comment by YoshiRulz** [comment]
Probably #3523.
