### ISSUE TITLE
Hawk-side support for BSNES' RTC

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3577]
see https://github.com/TASEmulators/BizHawk/pull/3457#issuecomment-1435790105

**Comment by Morilli** [comment]
this may also possibly maybe be relevant: https://github.com/ares-emulator/ares/issues/1026

**Comment by CasualPokePlayer** [comment]
Doesn't actually affect us atm since RTC isn't in SaveRAM/our code won't give the core some RTC file so that code is never ran. Not necessarily needed anyhow.
