### ISSUE TITLE
 Impossible to press 3 buttons at the same time (For Example Sonic 3 and Knuckles LockOn Spheres MiniGame ) | Sega Genesis/Mega Drive

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3579]
### Summary
Impossible to press 3 buttons in Using the keyboard, it is impossible to press 3 buttons at the same time, on the gamepad did not check yet

### Repro
1. Load Sonic 3 and Knuckles Now Way Screen
2. Try to press 3 buttons at the same time for open Spheres MiniGame
3. Profit.

### Host env.
- BizHawk 2.8; Windows 11 Dev Channel Build 23403; NVIDIA

P.S On Dev Build not working
Video:https://youtu.be/MyDOFQqdBtE

**Comment by Danik2343** [comment]
I think it's emulator controlls issue, not core.

**Comment by YoshiRulz** [comment]
This is just a [limitation of your keyboard](https://www.youtube.com/watch?v=kOkV9BalNcw). You literally have a keyboard input display in your OBS layout to prove it.

**Comment by Danik2343** [comment]
Okay, thanks for help!
