### ISSUE TITLE
N64 Ares Core is missing the fullscreen blur filter (2.9 RC3)

### ISSUE THREAD

**Issue by Zimond47** [TASEmulators/BizHawk#3587]
While on Mupen+ with Angrylion the graphics are correctly blurred, they are not when using the Ares core. 

For example.
![Wave Race 64 (USA) (Rev A)Ares avi_snapshot_00 08 847](https://user-images.githubusercontent.com/57569506/226176981-c9509dd9-5403-4b2f-9454-dd813b0c2487.jpg)
![Wave Race 64 (USA) (Rev A)mupoen avi_snapshot_00 09 082](https://user-images.githubusercontent.com/57569506/226176982-83eefed5-e159-4ec6-8bac-1544df77defe.jpg)

The sky in Waverace has an unpleasent pattern from dithering on it which is supposed to be blurred by the N64 hardware. 

When I used Angrylion with Project64 there was an option to select "Filtered" or "Unfiltered" which would result in exactly that feature missing, so maybe this setting is not checked in Ares - Angrylion but is in Mupen+Angrylion in Bizhawk? Hope that info helps.

**Comment by thekovic** [comment]
What we're seeing here is the Ares64 doesn't properly emulate the VI anti-dither filter (bit 16 at https://n64brew.dev/wiki/Video_Interface#Configuration_Registers ), displaying as it were permanently forced off. I'm not familiar with BizHawk's code base enough to assess whether this is a core configuration issue or a renderer issue but someone more familiar might be able to tell and locate the problem.

https://cdn.discordapp.com/attachments/280813077853765632/1087035606577721508/image.png

https://cdn.discordapp.com/attachments/280813077853765632/1087035606871310447/image.png

**Comment by CasualPokePlayer** [comment]
This seems to be a bug in ares upstream too, looking at the code. You should see the same bug if you disable Vulkan/Metal hardware acceleration in ares upstream settings. When using parallel-rdp (ares upstream default), it passes all VI IO writes to parallel-rdp to handle it. When not using it (and with BizHawk's angrylion's implementation), ares has its own handling for VI writes. For BizHawk, angrylion just reads out ares' held VI state, which doesn't have that anti-dither bit.

**Comment by thekovic** [comment]
Yes, you are right. Current latest ares uses MAME RDP when Vulkan (ParaLLEl-RDP) is disabled and looking at its output, it seems like it doesn't bother emulating any VI filters at all. Certainly the 16th bit that controls the antidither filter is being neither written nor read. https://github.com/ares-emulator/ares/blob/4b2b00a834ddd993e6f33484f27e7bcea4d5852a/ares/n64/vi/io.cpp#L116
