### ISSUE TITLE
Tool Design-Time error

### ISSUE THREAD

**Issue by TalicZealot** [TASEmulators/BizHawk#3589]
### Summary
Tested on latest build. Attempting to use the form designer in Visual Studio on the main tool form throws an error.
```
Could not load file or assembly 'BizHawk.Bizware.BizwareGL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. 
```
Tool can build and run without issues however. Wasn't an issue in 2.8.
Note: My tool inherits ToolFormBase

**Comment by TalicZealot** [comment]
Adding assembly references to **BizHawk.Bizware.BizwareGL** and **BizHawk.Emulation.Common** then reloading the solution seems to work.

**Comment by YoshiRulz** [comment]
Well if it's that simple, I don't wanna know where the reference to `BizHawk.Bizware.BizwareGL, Version=1.0.0.0` is coming from.
