### ISSUE TITLE
Expose MAME's machine/game compatibility status in frontend

### ISSUE THREAD

**Issue by Spikestuff** [TASEmulators/BizHawk#3593]
_Insert me not paying attention to the repo and not realizing that MAME is now a release for 2.9 instead of experimental here._

As we know with MAME upstream it flashes two types of warnings when a title that can be ran, but has issues.
An Orange one, and a Red one.

For the over-explain something that we know but just doing it for same page sake:
The Orange one can get into game with some minor issues, and is a setting that can be toggled to stop being intrusive "Skip Imperfect Emulation Warnings".
The Red one can not and wouldn't get into game, or have insanely terrible compatibility with a "This System Doesn't Work". Some titles are done like this to hide that they're actually functional to hide from certain companies.

In a mockup provided below would having something like this be an acceptable way to make it not only non-intrusive, but also more acceptable of a core to at least let the user know.
![image](https://user-images.githubusercontent.com/12412764/227771655-4e12db08-82e6-46bd-b2cc-b1df92fe8bfe.png)

This is something that the MAME development team would like to have towards an end user when MAME is a ported core, so the user would at least know that the title has an issue.
And rather than always pointing to the upstream. Having something in Hawk's Core would be at least helpful to our end users.

**Comment by YoshiRulz** [comment]
If the "red" flag is implemented as throwing an exception from the core ctor, there won't be a way to bypass it. This is the same problem as Snes9x' blocklist (and firmware required but not present, though that's solved).
