### ISSUE TITLE
Hex Editor byte read issue for HyperNyma + system desync caused by this

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3598]
There's something weird in HyperNyma core. Reading any byte from Open Bus range in System Bus (0x0000 to 0x1FFF) causes Hex Editor and other tools to act weirdly. It is also possible to create a lag frame from this. I think the reason for this is because HyperNyma [suffers the same fate as BSNESv115+ used to have.](https://github.com/TASEmulators/BizHawk/issues/3060) Unlike TurboNyma, it is possible to write to this location without crashing BizHawk.

**Comment by CasualPokePlayer** [comment]
Unlike TurboNyma, HyperNyma simply was not expected to be used for debugging purposes and thus there's no equivalent PCE_InDebug variable in HyperNyma, and thus reads are not guarenteed to be safe. This can be worked around simply by using the FastMap for reads instead PCERead function table.

**Comment by getCursorsExe** [comment]
It also creates erroneous writes to the System Bus, which causes a system desync.
