### ISSUE TITLE
TouchScreen Problem in DS and DSi + not saving settings for DS

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3599]
It is not visible where the screen will press, it is not synchronized.

**Comment by Danik2343** [comment]
Is it possible to somehow synchronize the touchscreen with the bottom screen in BizHawk

**Comment by Danik2343** [comment]
+ emulator does not save Nintendo DS settings such as nickname and message and color, implement save support in firmware.bin

**Comment by YoshiRulz** [comment]
Those can be changed in the sync settings.

What do you mean by "synchronize the touchscreen with the bottom screen"?

**Comment by Danik2343** [comment]
My cursor is hovered, for example, on the button with the game, the emulator clicks on a completely different place.

**Comment by YoshiRulz** [comment]
Hmm. We've had a couple of reports of that, including #3249, but no-one's been able to reproduce it. Can you backup and delete `config.ini`, and see if it's fixed? And if it is, upload the backup for us.

**Comment by Danik2343** [comment]
old config not working with touchscreen

**Comment by CasualPokePlayer** [comment]
Is this occuring on 2.9 rc3?

**Comment by YoshiRulz** [comment]
Well in the keybinds section there's both `Touch{X,Y}` and `Touch {X,Y}`, which suggests you migrated an old config when updating to 2.8 (https://github.com/TASEmulators/BizHawk/issues/2993#issuecomment-961596624). The presence of a core preference for `DGB`, removed in 2.8, confirms this. But there's still no explanation for the other report where it was working, and then suddenly broke.
