### ISSUE TITLE
buttons doesnt respond in linux 

### ISSUE THREAD

**Issue by yarik303** [TASEmulators/BizHawk#3600]
i am running bizhawk using wine. when i press buttons nothing happends except for mouse buttons. i tried BizHawk-2.8-linux-x64.tar.gz and BizHawk-2.9-rc3-linux-x64.tar.gz.

**Comment by YoshiRulz** [comment]
Don't use WINE.

**Comment by yarik303** [comment]
BRO I DOWNLOADED THEW VERSION FOR LINUX AND THE ONLY FILES WERE FOR WINDOWS WHAT I SUPPOSED TO USE???

**Comment by YoshiRulz** [comment]
> [...] The runtime dependencies are glibc, Mono "complete", OpenAL, and `lsb_release`. .NET Core is **not** a runtime dependency, only Mono. WINE is also **not** a runtime dependency.
>
> Run `EmuHawkMono.sh` to start EmuHawk [...]

—[readme](https://github.com/TASEmulators/BizHawk#unix)
