### ISSUE TITLE
Superscope problem in BSNES core (out of sync with cursor) BSNESv115+ (SuperScope not working)

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3601]
BSNES: The Superscope for SNES is out of sync with the cursor, using a new configuration file.
BSNESV115+: The Supercscope not working

BSNESscreen:
![ZCrYJS2pAl](https://user-images.githubusercontent.com/38865696/228523254-4373056e-d489-44b9-9ba4-04a8b9ffe427.png)

BSNESV115+screen:
![image](https://user-images.githubusercontent.com/38865696/228522958-7a7b4662-04e8-42de-8665-a5f34a7721a4.png)

**Comment by Danik2343** [comment]
Snes9x core: good working

**Comment by Danik2343** [comment]
Faust: SuperScope not exists in core settings.

**Comment by YoshiRulz** [comment]
This game works in Snes9x, but you're not able to select singleplayer mode as the position is stuck in the centre of the screen according to the game.

Binding to the mouse, the usable box covers the bottom half of the window, approximately, across all cores. Is this intentional?

**Comment by CasualPokePlayer** [comment]
Latest commits should fix this mostly
