### ISSUE TITLE
Nintendo DS Bios Not Saving Nickname, BirthDay. Color,Message.

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3603]
When I start any game (in the settings I should start the BIOS first), the settings that I chose in the BIOS, nickname, etc. fly off
When resetting, through a button that is configured in the controller settings, the name is not reset, when the ROM is turned off and on again, or another game, the name is reset.
Settings in core MelonDS name, color etc
It is also not saved in DSi.
The emulator takes some settings from the kernel settings, and some does not take at all.
And if you configure it in the BIOS itself, it will be reset.

**Comment by CasualPokePlayer** [comment]
You can change these in the sync settings. Note they won't be applied from sync settings however unless you also enable the "Firmware Override" setting (this is forced on when recording a movie)

**Comment by Danik2343** [comment]
This works, thanks for helping!
