### ISSUE TITLE
Interlaced games show up wrong in Ares64 core (field order seems to be flipped)

### ISSUE THREAD

**Issue by thekovic** [TASEmulators/BizHawk#3606]
### Summary
Interlaced games display improperly in Ares64 core as the order that field get displayed in seems to be flipped around. The result is distinct jagged steps on any edges of anything that go back forth and badly legible text. This problem is present for the entire image, even when nothing is moving.

### Repro
1. Launch an affected game, i.e. any game with an interlaced resolution. Non-exhaustive list: Indiana Jones and the Infernal Machine, Shadow Man, Armorines, StarCraft 64, Resident Evil 2, Spider-Man (note: some of these games require the Expansion Pak in order to run in interlaced resolution, sometimes this is hidden in the in-game options menu as Hi-Res mode)
2. Observe

### Output
see screenshots below

### Host env.
- BizHawk dev build at [6284c98d](https://gitlab.com/TASVideos/BizHawk/-/commit/6284c98d72e9d39ccd5de8d72d1d8b945ff889ce); Win10 Home 21H2; Intel

Screenshots:
![indy_legal](https://user-images.githubusercontent.com/72971433/229319296-dfecbcbb-2c1c-4a26-ac2a-fc868103c8c0.png)
![indy](https://user-images.githubusercontent.com/72971433/229319299-9cbcf88b-5b51-4279-a7c3-0a6335ae4bbe.png)
![golf](https://user-images.githubusercontent.com/72971433/229319289-a5b436bd-3a03-4784-b29a-124ba4524921.png)
![shadowman](https://user-images.githubusercontent.com/72971433/229319300-81c5eb32-e7f9-49ca-b64a-5f95ccbfe831.png)
![armorines_legal](https://user-images.githubusercontent.com/72971433/229319305-dbaa8a79-a22e-46ad-beed-8bf7be628294.png)
![starcraft64](https://user-images.githubusercontent.com/72971433/229319316-00f16389-cbf9-46af-92d4-2f95372de4ce.png)
![re2](https://user-images.githubusercontent.com/72971433/229319330-a226b96c-c007-4283-87c9-1c764ff71a81.png)

**Comment by CasualPokePlayer** [comment]
I suspect this is ultimately an upstream bug here, due to incorrect handling of VI registers here...
