### ISSUE TITLE
Add "Always Sprites On Top" option for Genplus-gx

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3608]

**Comment by CasualPokePlayer** [comment]
You can already disable non-sprite layers to get a similar effect.

**Comment by vadosnaprimer** [comment]
The effect is not quite similar if we want a camhack encode where Sonic is shown behind walls. It requires dumping separate layers and then overlaying, so this feature would help a lot.

https://tasvideos.org/Forum/Posts/520281

**Comment by WDude** [comment]
I remember bringing this up back in 2019! :P  In addition, some variations on Genplus allowed to toggle layers with different draw priorities, which made visualization very helpful!  https://github.com/TASEmulators/BizHawk/issues/1652

**Comment by nattthebear** [comment]
Does upstream support this?  It's not likely to be added if it requires us digging through the VDP code ourselves

**Comment by getCursorsExe** [comment]
No.

**Comment by getCursorsExe** [comment]
But could we enforce this by modifying somewhere between these lines?
https://github.com/TASEmulators/BizHawk/blob/988ae2729204236f849b65c21c40e32c668fa1a9/waterbox/gpgx/core/vdp_render.c#L3588-L3641
