### ISSUE TITLE
emu.getluacore is listed as deprecated, but no replacement is mentioned.

### ISSUE THREAD

**Issue by Berserker66** [TASEmulators/BizHawk#3609]
### Summary
emu.getluacore is listed as deprecated, but no replacement is mentioned.

### Repro
1. go to https://tasvideos.org/Bizhawk/LuaFunctions
2. go to emu.getluacore
3. read [deprecated]
4. notice there is no listed alternative
5. be sad

### Output
:(

### Host env.
Pretty sure all?

[//]: # "(screenshots, if applicable)"
![image](https://user-images.githubusercontent.com/3189725/229553515-65c916df-8a12-4d45-8514-f63f8f13991b.png)

**Comment by YoshiRulz** [comment]
It prints `"Deprecated function emu.getluacore() used, replace the call with client.get_lua_engine()."` when called.

**Comment by CasualPokePlayer** [comment]
Note, in 2.9, it will be somewhat useless, at most only useful with polyfills with 2.8. There is only 1 lua engine in 2.9 (NLua+Lua).

**Comment by Berserker66** [comment]
well, that's unfortunate, as I used this in this if tree https://github.com/alttpo/sni/blob/a8184b1cb079399a087d69a38abe8e7c1897603e/lua/Connector.lua#L14 to alert the user when they're using nlua, as nlua does not function for our purpose at all and just crashes.

**Comment by CasualPokePlayer** [comment]
NLua+Lua isn't to be compared with NLua+KopiLua. It would be more functional than LuaInterface+Lua.

**Comment by Berserker66** [comment]
what does "more functional" mean in this case? Our problem is that we were only able to load dlls from LuaInterface

**Comment by CasualPokePlayer** [comment]
NLua+Lua can load in dlls just fine.
