### ISSUE TITLE
BSNES core seems a little slower than SNES?

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#3610]
SNES has ≈60.0988Hz speed, same as NES, but BSNES core has ≈60.0984Hz instead, a littler slower than SNES.

**Comment by CasualPokePlayer** [comment]
1. Is this the new (v115+) or old BSNES core?
2. How are you calculating this?

**Comment by Yave-Yu** [comment]
> 1. Is this the new (v115+) or old BSNES core?
> 2. How are you calculating this?

1. BSNES old core.
2. Just replay a movie, there shows speed.

**Comment by CasualPokePlayer** [comment]
The Play Movie dialog doesn't show the speed of the core, it just takes the framerate from a database of framerates based on the region and system, which isn't directly tied to cores (and sometimes is just some approximate), and cores can differ from them, also relevant comment from that database:
https://github.com/TASEmulators/BizHawk/blob/f8a4524df79e1b2f2a234fcb91dcf14c80f5ba2c/src/BizHawk.Client.Common/movie/PlatformFrameRates.cs#L7
