### ISSUE TITLE
Libretro BlastEm is now unusable

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3613]
Opening any ROM with BlastEm libretro core now causes an assertion failure. Choosing any of the 3 options will crash BizHawk.
![image](https://user-images.githubusercontent.com/39802077/230611310-9ed42a60-0074-4da7-8713-94673308867a.png)

**Comment by CasualPokePlayer** [comment]
This is a core bug, they asked for a width and height which exceeded their specified maximum width and height. Complain to them.

**Comment by getCursorsExe** [comment]
This issue did not occur in 2.8 stable, a bad commit must have broke it. Or this is a side effect of rewriting libretro?

**Comment by CasualPokePlayer** [comment]
Side effect when rewriting libretro since we're being more strict. Still doesn't change the fault.
