### ISSUE TITLE
[2.9] Rugrats in Paris for N64 crashes in Ares64

### ISSUE THREAD

**Issue by EZGames69** [TASEmulators/BizHawk#3614]
So I was able to run this game on a dev build awhile back, however the game seems to run into issues when using Mupen64Plus, so I started a TAS project on Ares and got a decent way through the first area of the game.

However, on 2.9's release, the game crashes in the same place it would for Mupen64Plus, right around the area where the characters would start talking:

![image](https://user-images.githubusercontent.com/44628443/230689631-9bc9f6d7-97a1-479d-ae92-f46d95ab327d.png)

It worked just fine in some of the earlier dev builds (likely prior to when Ares64 had a performance boost).  But now is crashing on the same area.

**Comment by CasualPokePlayer** [comment]
Does it also occur upstream? I'm 99% sure this is just a casualty from switching to recompiler.
