### ISSUE TITLE
[Ares]  SW rogue squadron softlock

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#3617]
Running bizhawk 2.9 linux
If you hold A or mash start to try to skip the intro sequence with that lucus arts animation, the game soft locks.

I don't know if that cutscene is skippable, but I guess you can get around it by not trying to skip it

**Comment by YoshiRulz** [comment]
Is this a regression from 2.8? Does it happen on upstream?

**Comment by InfamousKnight** [comment]
It works on 2.8 with ares accuracy core.

But it turns out theres a consistent way to reproduce the problem: 

open bizhawk 2.9
run swrs
record movie
let it play until the n64 logo explosion

And it softlocks. Tested with and without rewind

**Comment by CasualPokePlayer** [comment]
I'm guessing this is likely yet another issue with enabling the recompiler. Please try it in upstream. If it doesn't crash there, then also make savestates during that portion. If that crashes, it's exactly the bug that another one of our issues had.

**Comment by InfamousKnight** [comment]
Upstream ares or bizhawk?

**Comment by CasualPokePlayer** [comment]
> Please try it in upstream.

**Comment by YoshiRulz** [comment]
Game is `SHA1:ED42EED1EE2DB646FF7EF94BA8C5421D164A4F0D`. Repro'd halt on `master` at 8ef8d4efb, it happens around frame 1000. Doesn't happen on ares 132.

**Comment by CasualPokePlayer** [comment]
Did you try making savestates around the freezing section in upstream?

**Comment by CasualPokePlayer** [comment]
Checked upstream myself, savestating makes it freeze. Ultimately it's similar to https://github.com/TASEmulators/BizHawk/issues/3605. At some point the CPU recompiler does an allocator flush and forces all code to be re-emitted, which crashes.

I am suspecting this is actually just a common trait among all the MusyX games.

**Comment by nattthebear** [comment]
Could we set interpreter on a per game or syncsetting basis?

**Comment by CasualPokePlayer** [comment]
The issue there is simply we need to do some edits to ares code to make interpreter not a compile time option (which it currently is, lol). After that, should be perfectly possible to force it with gamedb stuff.

**Comment by nattthebear** [comment]
Could also compile two separate binaries and switch between them :laughing:
