### ISSUE TITLE
Hq2x math review?

### ISSUE THREAD

**Issue by LivingDaylights** [TASEmulators/BizHawk#3628]
Hq2x on every core looks wrong compared to hq2x on every other emulator under the sun

a good example is anything snes nes th16 or genesis with round edges. Bizhawk adds dimples.

One easy way to spot is pac man in pacmania on genesis. On everything else he is round in bizhawk distored. Check it out and you will know what i mean.

**Comment by LivingDaylights** [comment]
how it should look
![OTHERS](https://user-images.githubusercontent.com/130517299/231444324-0dd14d13-c39a-45a3-b251-b3854536ffdc.JPG)



and how bizhawk looks
![BIZ](https://user-images.githubusercontent.com/130517299/231444444-e2ee7634-1e18-4526-9a81-b3d993f6b5b7.JPG)



not a huge deal just noticeable in almost every 8 or 16 bit game, very noticeable on larger screens and its probably a simple fix maybe.


If no one care or if people are going to get mad just close this.


Was only sharing a observation.

**Comment by LivingDaylights** [comment]
more noticeable if you check the actual game not these pics, but even in the pics follow that black outline.

**Comment by CasualPokePlayer** [comment]
If you untick "Maintain Aspect Ratio" in Display settings, does it look correct?

**Comment by LivingDaylights** [comment]
> If you untick "Maintain Aspect Ratio" in Display settings, does it look correct?

No.

**Comment by LivingDaylights** [comment]
After talking to someone about this it’s working as expected. 

Its just a diff version of hq2x than what i was loading in other emulators etc
