### ISSUE TITLE
Bizhawk include this shader?

### ISSUE THREAD

**Issue by LivingDaylights** [TASEmulators/BizHawk#3636]
I came across a shader for Bizhawk and dithering on Nesdev.

I find it handy especially on Sega Gan/MD games where dithering was very very very often used for shades and transperancies.

Here are screenshots comparing

no shader
![no shader](https://user-images.githubusercontent.com/130517299/232468372-7b1fab34-edee-4686-a7b2-5834a8c548ed.JPG)

with shdader

![horizontal_filter](https://user-images.githubusercontent.com/130517299/232468422-988f652a-0460-44ad-8fe7-012e06ae420e.JPG)

Been using this filter alot and I believe others out there would use it.

the shader 
[horizontal_filters.zip](https://github.com/TASEmulators/BizHawk/files/11249486/horizontal_filters.zip)

and I am not looking for credit didnt do anything, found it here

https://forums.nesdev.org/viewtopic.php?p=182801#p182801

**Comment by CasualPokePlayer** [comment]
We can't just include random shaders on the internet. They would need to be licensed appropriately (optimally MIT or similar) in order to be included.
