### ISSUE TITLE
BSNESv115+ snes_get_board returns empty string

### ISSUE THREAD

**Issue by Morilli** [TASEmulators/BizHawk#3638]
Since 0a2d4405f08481651bdea2499a6055abba7789de, the board name reported by bsnes is an empty string instead of the value it should be. I tried looking into it but haven't figured out the cause yet. Leaving this here so I don't forget; this should probably be fixed as I believe something relies on that.

The relevant code:
https://github.com/TASEmulators/BizHawk/blob/0f2a76bd5e9ea359bcc3b84c079f8d4de6e94b72/waterbox/bsnescore/bsnes/target-bsnescore/bsnescore.cpp#L333-L339

The failure seems to origin from this line and the underlying code it calls: https://github.com/TASEmulators/BizHawk/blob/0f2a76bd5e9ea359bcc3b84c079f8d4de6e94b72/waterbox/bsnescore/bsnes/target-bsnescore/program.cpp#L386

**Comment by Morilli** [comment]
So as an update, I did some tests and it turns out, even before https://github.com/TASEmulators/BizHawk/commit/0a2d4405f08481651bdea2499a6055abba7789de debug builds are broken as well, but release builds work fine. After https://github.com/TASEmulators/BizHawk/commit/0a2d4405f08481651bdea2499a6055abba7789de, both debug and release builds just return an empty string.

I'm going to assume that some undefined behavior is being invoked or something with allocations is poorly managed.

**Comment by nattthebear** [comment]
Does the pointed-at memory live long enough?  If it does, how does this function not leak?

**Comment by Morilli** [comment]
When debugging this I did print out the value in the c++ core to make sure the conversion c++->c# isn't affecting anything, and the issue is already present there.

**Comment by nattthebear** [comment]
You'd need to print out the value after the C++ function leaves and before it returns to C#, the issue is any destructors that are running on the close of that function.

**Comment by nattthebear** [comment]
IE, what happens with something like this?

```cpp

const char* board; 
const char* snes_get_board_impl(void) 
{ 
     if (!board) board = program->superFamicom.document["game/board"].text().data(); 
  
     return board; 
}

EXPORT const char* set_get_board(void)
{
  auto foo = snes_get_board_impl();
  puts(foo);
  return foo;
}

```

**Comment by Morilli** [comment]
@nattthebear this is also broken. As I said, the returned string is already empty BEFORE exiting to c#.

**Comment by nattthebear** [comment]
Got it, I read your previous statement backwards.
