### ISSUE TITLE
Aggressive usage of `client.screenshottoclipboard()` with Windows clipboard history enabled reliably crashes scripts

### ISSUE THREAD

**Issue by 40Cakes** [TASEmulators/BizHawk#3642]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Calling `client.screenshottoclipboard()` at a very fast rate will reliably crash the script if you have Windows clipboard history enabled.
I am working on a Pokemon shiny hunting bot, doing some image recognition with cv2 and I wanted to use the `client.screenshottoclipboard()` function quite aggressively to make the bot as responsive as possible.

I noticed that the Lua script would frequently bomb out, after some testing I discovered that it no longer crashed if I disabled Window's clipboard history setting (Control Panel > System > Clipboard > Clipboard history)

While coming here to report the issue, I noticed that 2.9 had been released so I tested on that as well and still the same issue with slightly different output, provided both.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
Run this script with clipboard history enabled, wait a few mins, ???, profit
```
-- test.lua
while true do
    client.screenshottoclipboard()
    emu.frameadvance()
end
```

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
BizHawk 2.8 Output:
```
NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)
   at NLua.Lua.PanicCallback(IntPtr luaState)
   at lua_error(lua_State* )
   at NLua.ObjectTranslator.throwError(IntPtr luaState, Object e)
   at NLua.Lua.SetPendingException(Exception e)
   at NLua.LuaMethodWrapper.call(IntPtr luaState)
   at NLua.MetaFunctions.runFunctionDelegate(IntPtr luaState)
   at lua_resume(lua_State* , Int32 )
   at BizHawk.Client.EmuHawk.Win32LuaLibraries.ResumeScript(LuaFile lf)
   at BizHawk.Client.EmuHawk.LuaConsole.<>c__DisplayClass61_1.<ResumeScripts>b__1()
   at BizHawk.Client.Common.LuaSandbox.Sandbox(Action callback, Action exceptionCallback)
```

BizHawk 2.9 Output
```
NLua.Exceptions.LuaScriptException: A .NET exception occured in user-code
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetImage(Image image)
   at BizHawk.Client.EmuHawk.ListViewExtensions.ToClipBoard(Bitmap bitmap)
   at BizHawk.Client.EmuHawk.MainForm.TakeScreenshotToClipboard()
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9 x64; Win10 Version 10.0.19045 Build 19045; AMD Ryzen 9 5900X

**Comment by Morilli** [comment]
From research it seems like this is actually a windows-level issue which can not really be worked around: https://stackoverflow.com/questions/68666/clipbrd-e-cant-open-error-when-setting-the-clipboard-from-net

Essentially, the clipboard needs to be opened in order to put data on it, but only one process can open the clipboard at any time. Thus, if any other application or process has the clipboard open, setting data will fail. There is already a builtin retry mechanism in the called method which attempts up to 10 times with a 100ms delay every time, and only then throws an error.

With that in mind, your goal of making your bot "as responsive as possible" may not actually be reliable, even if the clipboard function does not throw, because there could still be delay. I did experiment a bit with some edits to the existing clipboard setting code but couldn't get anything working that works better than what is already being done.

**Comment by 40Cakes** [comment]
Thank you for looking into it, figured it could have been the Clipboard API itself, classic Windows.

Ah well, I've been able to remove Windows as a dependency from my Python script, and now looks like a good a time as any to move the bot and OBS stream over to Linux!

I'll do some clipboard stress testing on Linux and report back any findings if encounter any similar issues but I imagine it'll be much stabler.

**Comment by CasualPokePlayer** [comment]
I would suggest looking at our comm.socketServerScreenShot/comm.socketServerScreenShotResponse or comm.mmfScreenshot/comm.mmfSetFilename functions, They might be better for your purposes.
