### ISSUE TITLE
BizHawk does not inhibit display or system sleep while running

### ISSUE THREAD

**Issue by koitsu** [TASEmulators/BizHawk#3644]
## Summary
BizHawk does not inhibit display or system sleep while running.  This is a common problem that plagues even AAA-gaming-industry titles, so don't feel bad.

## Repro
Demonstrating lack of display sleep inhibition:

1. Enable display sleep in Windows.  In Windows 10: System -> Power and Sleep -> Screen -> When plugged in, turn off after: N minutes (example: 2 minutes)
2. Launch BizHawk + load/run a game
3. Wait 2 minutes
4. Display will go into sleep mode

## Solutions
There's 3 main methodologies you can use.  I am not familiar with BizHawk's code so I don't know which is easiest to implement.

It's important to give this feature a GUI setting/toggle somewhere (probably under Config -> Customize -> General or Advanced), and the feature default to disabled (since that's how BizHawk has been behaving all this time).

### Newer method (supported by Windows 7 onward)

Leverage the [Windows Power Management API](https://learn.microsoft.com/en-gb/windows/win32/power/power-management-reference?redirectedfrom=MSDN), specifically functions [PowerCreateRequest()](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-powercreaterequest) and [PowerSetRequest()](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-powersetrequest) for a RequestType of PowerRequestDisplayRequired (inhibit display sleep) or PowerRequestSystemRequired (inhibit system sleep).

You can verify things are inhibited by launching a Command Prompt as Administrator and using `powercfg.exe /requests`.  You should see the BizHawk process listed under DISPLAY, with the line "Video Wake Lock" under it.  (For PowerRequestSystemRequired, it would be under SYSTEM).

If you want to see how this manifests today, run Chrome and watch a video somewhere (YouTube, Twitch, etc.): you'll find chrome.exe listed under DISPLAY and SYSTEM (thus, inhibiting display and system sleep).

### Older method 1 (supported by Windows XP onward)

Use [SetThreadExecutionState()](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadexecutionstate).  This is described at [the end of the nesdev forum thread mentioned below](https://forums.nesdev.org/viewtopic.php?p=248854#p248854).

### Older method 2 (supported by Windows 2000 onward)

In your main window handler, add support for handling the [WM_SYSCOMMAND message](https://learn.microsoft.com/en-us/windows/win32/menurc/wm-syscommand) to detect SC_SCREENSAVE or SC_MONITORPOWER messages:

```c
case WM_SYSCOMMAND:
    if (running && (((wParam & 0xFFF0) == SC_SCREENSAVE) || ((wParam & 0xFFF0) == SC_MONITORPOWER)))
        return 0;
    // otherwise, proceed to DefWindowProc
```

You cannot verify this method using `powercfg.exe /requests`, given that window message handlers do not "register" with the Power Management API, but it (obviously) does work.

I forget how to inhibit system sleep using this method.

### SDL2 and/or Linux

There is discussion of how to implement this functionality in SDL2 and/or Linux in [a nesdev forum thread I started nearly 10 years ago](https://forums.nesdev.org/viewtopic.php?p=118407).

## Important note

Please DO NOT implement a solution by changing system settings (Windows power profiles).  I've lectured several emulator authors about this in the past.  It is not the right solution and is extremely inappropriate to do, plus creates numerous problems in the case of an application crash or force-kill.

## Host environment
- BizHawk 2.9; Win10 Pro 22H2 (19045.2728); x64; Intel CPU, NVIDIA GPU

**Comment by CasualPokePlayer** [comment]
To be clear, we do not support Windows XP and below at all (and Windows 7-8.1 is ""unsupported""), so the older solutions wouldn't really be applicable to us.

Doing off SDL's source, it seems `XScreenSaverSuspend/XResetScreenSaver` or (if wayland is ever supported) `zwp_idle_inhibit_manager_v1_create_inhibitor/zwp_idle_inhibitor_v1_destroy` is the "correct" API to use. Although in that forum post, Near seems to note that `XScreenSaverSuspend` "does not work" (odd then that SDL would use it?), I suppose then they might have not checked if that extension was available (I would guess it wasn't), or maybe it was just bugged for them.

**Comment by nattthebear** [comment]
I'd say this is working as intended.  If the user is interacting with the game and making inputs, then we won't go to screensaver, just like any other application.  If the user is not interacting with the game, then we should go to screensaver just like any other application.

The applications that should call these special APIs are ones where the user might spend a long time passively viewing the screen without making any inputs.  Video players, sure, but how does an emulator fit into that?

**Comment by nattthebear** [comment]
That seems to be an OS bug, it should have the high level responsibility of enumerating input devices and counting, across all of them, what counts as idle or not.

**Comment by koitsu** [comment]
@nattthebear Your argument is ridiculous.

**Comment by koitsu** [comment]
I will not be commenting on this ticket going forward.  BizHawk team can decide what to do with it.  I've done all I can to present the technical information on how to solve this, and advocating for the behaviour to default to off (to remain compatible with pre-existing approach).  Happy hacking!

**Comment by CasualPokePlayer** [comment]
To be clear, this (I guess unintentionally) is now implemented in practice with SDL2 now being used for our display methods, and on SDL video init, [SDL will disable the screensaver by default](https://github.com/libsdl-org/SDL/blob/bbcf40e811785400df741023c4437762dc9ea4b0/src/video/SDL_video.c#L539).

This probably should be adjusted in the future so we have some setting to un-disable the screensaver / give user control over this.

**Comment by YoshiRulz** [comment]
SDL has an [implementation for Linux](https://github.com/libsdl-org/SDL/blob/c4ca64deaf556ad298cdd4f226ba838dec7ffb0b/src/video/x11/SDL_x11events.c#L1877) but it doesn't seem to be working.
Firefox will trigger what KDE Plasma calls "Presentation Mode" when playing video (there's an additional global sleep toggle which seems to serve the same purpose, not sure what the deal is there), but EmuHawk dev builds do not.

**Comment by CasualPokePlayer** [comment]
I suspect Linux might not work for all cases or maybe just requires some extra package (likely would need the libxss1 package installed)

**Comment by YoshiRulz** [comment]
It is "installed" (there's a `libXScrnSaver` in `SDL2`'s closure which provides `libXss.so.1.0.0`). It's definitely not inhibiting sleep. I'll add this to #1430.

**Comment by CasualPokePlayer** [comment]
Not sure what you're talking about "closure", it's just calling a function pointer it gets from dlopen'ing that .so, and it doesn't do that if it's not available.

**Comment by YoshiRulz** [comment]
It's Nix jargon, referring to the set of rundeps including transitive deps.

**Comment by nattthebear** [comment]
> I guess unintentionally

I never had a particularly strong opinion about this one way or the other.  There was only one person advocating for, and in all of their posts they never gave a single reason why this should be done, only how.  It didn't seem that useful to me, and in the absence of any other advocates, I just closed it.

**Comment by CasualPokePlayer** [comment]
fwiw, the fact we already had code to do this (but it seemed to just broken) seems to have fixed what was supposed to be happening.
