### ISSUE TITLE
Hq2x filtering not functioning

### ISSUE THREAD

**Issue by Kalto-Mate** [TASEmulators/BizHawk#3645]
### Summary
Hq2x filtering (and maybe others if installed) does not work in 2.9 whatsoever. I recently jumped from 2.2 to 2.9 to get around an OBS capturing problem, and to my surprise the same settings yield no result in the most recent version.
![image](https://user-images.githubusercontent.com/74378599/234076196-6a2e8b24-6a32-4ab7-acd6-2b6ea3048481.png)

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9 x64, Win 10, GeForce RTX 3070, running gameboy color games

**Comment by Kalto-Mate** [comment]
A case of corrupt config file. Configs below 2.3 are meant to recreate a new one instead. The fresh generated one however failed to be up to code, and my guess is some field that is no longer used placed the software in some unforeseen state where it's stable but settings are incorrect.

**Comment by Spikestuff** [comment]
It's your user prescale.
![image](https://user-images.githubusercontent.com/12412764/234234562-4b3581a0-9925-4c65-83a4-b90d618d844a.png)
