### ISSUE TITLE
[GameBoy Link] Buzzing noise when one of the Players is muted

### ISSUE THREAD

**Issue by kexdd** [TASEmulators/BizHawk#3648]
(Bizhawk 2.9)
When playing 2 games in Game Boy Link mode, muting either of the Players produces a buzzing noise in one channel. Muting Player 1 gives buzzing noise in left channel, and muting Player 2 gives buzzing noise in right channel.

### Repro
Load Pokemon Blue and Pokemon Red (USA/Europe versions) into multicart, select GBC mode for both in GB Link -> Settings, then mute one of the Players.

Here is a video showing the issue:
https://www.youtube.com/watch?v=BAc5RZGgkzs

**Comment by YoshiRulz** [comment]
Please keep discussion of the SGB fork under #3635.
