### ISSUE TITLE
Can't build commit 384a4e1 with Visual Studio 2022

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3653]
384a4e1

**Comment by YoshiRulz** [comment]
There is no such version? This is probably related to #3637 in any case.

**Comment by nattthebear** [comment]
What's the error message?

**Comment by getCursorsExe** [comment]
There are lot of error messages relating to variable "ReflectionCache", but one of bad commits caused BIzHawk to be impossible to be lauched at all on my device.

**Comment by YoshiRulz** [comment]
Is this in VS2019? Is the .NET SDK 6.0.300 or later available in the VS Installer?

**Comment by getCursorsExe** [comment]
No. It's in Visual Studio 2022.

**Comment by YoshiRulz** [comment]
> There are lot of error messages relating to variable "ReflectionCache" [...]

What are the messages? It would be helpful if you included some of these details in your initial report.

If you stopped being able to build after pulling new commits into an existing clone, try cleaning and then rebuilding.

**Comment by CasualPokePlayer** [comment]
Errors in ReflectionCache don't cause any build failures (I have errors there and builds work fine), I would figure they're normal.

**Comment by getCursorsExe** [comment]
Yikes, I have to re-clone the entire project again.

**Comment by getCursorsExe** [comment]
Nope. Nothing.

**Comment by getCursorsExe** [comment]
I'll think what to do after some time.

**Comment by getCursorsExe** [comment]
Should we undo #3637?

**Comment by nattthebear** [comment]
That PR has not yet been applied, so nothing to undo.  You could try building with it though, to see if it fixes your problem.

**Comment by getCursorsExe** [comment]
Oops.

**Comment by getCursorsExe** [comment]
It was Visual Studio 2022's fault. To fix this, I had sacrifice BizHawk's config, Save RAM, and more. Literally _everything_.
