### ISSUE TITLE
mame crashing

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#3657]
A user reported a problem with all arcade games crashing on 2.9 and 2.9.1.

![изображение](https://user-images.githubusercontent.com/7092625/236906541-90ed1180-97e2-42df-b49d-ed0db1425000.png)

```
Сигнатура проблемы:
  Имя события проблемы:    CLR20r3
  Сигнатура проблемы 01:    EmuHawk.exe
  Сигнатура проблемы 02:    2.9.1.0
  Сигнатура проблемы 03:    ae5c3af3
  Сигнатура проблемы 04:    BizInvokeProxyAssembly
  Сигнатура проблемы 05:    0.0.0.0
  Сигнатура проблемы 06:    0
  Сигнатура проблемы 07:    1
  Сигнатура проблемы 08:    62
  Сигнатура проблемы 09:    System.AccessViolationException
  Версия ОС:    6.1.7601.2.1.0.256.48
  Код языка:    1049
  Дополнительные сведения 1:    e5b9
  Дополнительные сведения 2:    e5b960f6cfec93d0cefe73d6e003f7f2
  Дополнительные сведения 3:    7bab
  Дополнительные сведения 4:    7babe92cd7306baee73c3e7d168ae5b6
```

`EmuHawk.exe > log.txt 2>&1` gives this on release build:

> Using DirectInput+XInput for host input (keyboard + gamepads)
> ROM was not a multiple of 1024 bytes, and not a recognized header size: 1022. Assume it's purely ROM data.
> Game was not in DB. CRC: 9AE573F2 MD5: B3135AFDF61FAC5B599FFD7225DD519A
> thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: WinApi failure code: 1455', src\memory_block\mod.rs:265:50
> note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

and this on debug build 
[log.txt](https://github.com/TASEmulators/BizHawk/files/11424234/log.txt)

`unzip` is at it again?

Opens fine in my old mamehawk https://disk.yandex.ru/d/WlZCJqoowndnuw

**Comment by CasualPokePlayer** [comment]
This just indicates that CreateFileMappingW is giving an error. If this is erroring at all, I'd expect other waterbox cores to similarly crash (and frankly waterboxing can't work without this function, as thos function is just use to create a memory view from the core RAM mirror to the canonical waterbox address.

**Comment by CasualPokePlayer** [comment]
```
ERROR_COMMITMENT_LIMIT

    1455 (0x5AF)

    The paging file is too small for this operation to complete.
```
You're just running out of RAM, that's all.

For comparison, I would also suggest checking out a DS game for comparison, as that would be similarly sized.

**Comment by CasualPokePlayer** [comment]
How big is the swap file set to?

**Comment by CasualPokePlayer** [comment]
Does disabling rewind help?

**Comment by vadosnaprimer** [comment]
Nope.

**Comment by CasualPokePlayer** [comment]
I'm not sure what else you can do other than reboot your PC and immediately launch the MAME core and see if that works. The MAME core memory layout should only be around 1.5 GiB, which surely can be mapped to the page file.

**Comment by nattthebear** [comment]
The size of the page file doesn't directly matter.  Mappings can succeed that are larger than the pagefile, or with swapping entirely disabled.  I tested both of those scenarios back in the day.

You may need a lot of ram, though.

**Comment by CasualPokePlayer** [comment]
> The size of the page file doesn't directly matter. Mappings can succeed that are larger than the pagefile, or with swapping entirely disabled. I tested both of those scenarios back in the day.

Was this with Windows 8.1+? Windows apparently improved this function there, ["which defers committing the page tables until you actually use them."](https://web.archive.org/web/20160220135102/https://blogs.msdn.microsoft.com/oldnewthing/20150130-00/?p=44793)

**Comment by nattthebear** [comment]
It was on Windows 7, see https://github.com/TASEmulators/BizHawk/commit/aecdc645fa2f41218f4c22ff5a6f856c7bbf8487

**Comment by CasualPokePlayer** [comment]
Actually, what I linked is probably N/A anyways, as we have it with SEC_COMMIT (implicit default used in Rust version), rather than SEC_RESERVE. Although the latter might be what we'd want anyway, since the handle is meant to be committed with MapViewOfFileEx later on (granted, since we're committing all of it anyways, it probably doesn't matter, unless that makes Windows smarter with mapping and allows it to only map what's actually used?).

**Comment by nattthebear** [comment]
Would it be difficult to split compile Mame, with one wbx per supported system, the same way we split compile Mednafen?  That would greatly decrease the memory pressure, but I suspect it's a huge undertaking given the size and complexity of Mame.

**Comment by vadosnaprimer** [comment]
Wouldn't that result in infrastructure overhead being present in all the hundreds of individual builds, blowing up package size? And why would it decrease memory pressure, unless mame is refactored to rip out that infrastructure?

**Comment by nattthebear** [comment]
Infrastructure overhead?  Maybe.  Depends on how easy it is to script building MAME for single boards, and then how easy it is to detect which one to run.  Size overhead in the package?  Yes, quite a bit.  The memory pressure would likely go down because of the reduced `.data` and `.bss`, although you'd have to profile what the core is actually spending memory on to be sure.

**Comment by CasualPokePlayer** [comment]
To be clear most of the usage will come from srbk and mmap memory sections as those are set to a total of 1.5 GiB (as some MAME drivers really do use that much memory)

**Comment by vadosnaprimer** [comment]
> Depends on how easy it is to script building MAME for single boards

Trivial, it's an official feature. Devs don't build the entire thing while working on parts.

> how easy it is to detect which one to run

`mame -listxml` prints info on which source file runs which games, so also easy to obtain.

**Comment by nattthebear** [comment]
>To be clear most of the usage will come from srbk and mmap memory sections

Then the best fix would be to modify the waterbox host code to allow it to not prerequest that memory from the host OS until it knows it needs it.

**Comment by CasualPokePlayer** [comment]
I assume really that'd be trying to reserve that address space but trying to avoid actually committing memory there? I assume we would still want to ensure nothing else will try to use that address space (otherwise we'd be screwed)

**Comment by CasualPokePlayer** [comment]
Any chance the latest dev build "fixes" this issue? It should use much less memory here.

**Comment by vadosnaprimer** [comment]
Nope, same.
