### ISSUE TITLE
Arcade lag frame 

### ISSUE THREAD

**Issue by daisuke45** [TASEmulators/BizHawk#3660]
Hello, thank you for your great job.
I'd like to report an issue playing neogeo game like metal slug where the lag counter option don't increment and stay to zero all the game.
thank for reading

**Comment by CasualPokePlayer** [comment]
This is a common issue for Arcade games which doesn't have any actual fix. The core has lag detection hooked up, but many games have behavior it seems which makes it so every frame will have input polled, and thus the lag counter never increases.
