### ISSUE TITLE
pce bug Lady Sword - Ryakudatsu Sareta 10-nin no Otome (Japan) (Unl)

### ISSUE THREAD

**Issue by 007mesen** [TASEmulators/BizHawk#3663]
Lady Sword - Ryakudatsu Sareta 10-nin no Otome (Japan) (Unl)

skipps title screen missing graphics right from boot,

Effects TurboNyma, Hyper Nyma and PCE Hawk

Works properly Upstream Mednafen
Works Properly LIbretro Mednafen 
And Properly on Mesen2

JUst thought I would report it was testing mesen and comparing behaviors bumped into this issue with bizhawk so proceeded to compare upstream.

**Comment by CasualPokePlayer** [comment]
Not sure what you are talking about here? The intro seems to play back the same across upstream mednafen and us. The only thing notable I can see is TurboNyma and PCEHawk gets an extra message on startup which seems to translate to a warning that it can't find any BRAM (which really just means a missing gamedb entry from us, and it wouldn't affect HyperNyma so it wouldn't be the same issue you're reporting?)

**Comment by 007mesen** [comment]
My bad i reported it wrong wasnt effecting hyper. And yes its that message so you fixed it.
