### ISSUE TITLE
Rewind input in movie file?

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#3667]
https://tasvideos.org/UserFiles/Info/638203605891607986

while playing back that movie, I noticed at the 32 mark, that rewinds are stored in the input file? Possibly other places too in that file as I've noticed I'm not as ahead as I thought with the world record of that game.

bizhawk version BizHawk_devbuild_37ef137a

**Comment by YoshiRulz** [comment]
Input movies cannot trigger rewind. You can open up the file and check for yourself, rewind isn't one of the keys. The R at frame ~115000 is for DPad Right.

**Comment by InfamousKnight** [comment]
This is not a feature request. By 32 Mark, I mean 32 minutes into the movie.  At that point, you can see rewinding. Rewinding is also not a game feature to be clear.
