### ISSUE TITLE
QuickNes has color deviation

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#3668]
QuickNes core on BizHawk's screen color is not fully same as palette, has a little color deviation, such as 0,181,255 display as 0,181,254, 66,148,0 display as 65,148,0.

**Comment by nattthebear** [comment]
Can you attach the `.pal` file you used?

**Comment by Yave-Yu** [comment]
> Can you attach the `.pal` file you used?

Here: 
[HeleReality.pal.zip](https://github.com/TASEmulators/BizHawk/files/11560553/HeleReality.pal.zip)
