### ISSUE TITLE
Bizhawk loading and hang up issue

### ISSUE THREAD

**Issue by ChrisBrowand1985** [TASEmulators/BizHawk#3673]
BizHawk taking extra time to open and randomly freezing up for up to forty-five seconds

### Summary
When opening BizHawk there is a fifteen to twenty second delay before it starts. Emulator locks up randomly for thirty to sixty seconds at a time. This occurs on multiple versions of Bizhawk with at least BSNESv115+ and mGBA cores. Test roms were Pokemon Emerald Randomized and Final Fantasy 4: Free enterprise randomized. No error message pops up. Computer specs listed below

### Repro

1. Open BizHawk
2. Wait till it temporarily locks up
3. Wait for it to resume function

### Host env.
- Operating System:            Windows 10 Home version 22H2 64-bit OS
- CPU:                                  Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz 64-bit processor
- Ram:                                  32.0 GB
- GPU:                                  NVIDIA GeForce GTX 1070 Ti

**Comment by YoshiRulz** [comment]
> [...] mSGB [...]

Did you mean mGBA?

**Comment by CasualPokePlayer** [comment]
To clarify, you intend to say that all you were doing is using those ROMs, and there wasn't anything else being done. No other tools opened up, no lua scripts involved, nothing out of the ordinary?

Also, what version of BizHawk is this?

**Comment by ChrisBrowand1985** [comment]
This is correct. This occurred on multiple versions including the newest 2.9.1.

**Comment by ChrisBrowand1985** [comment]
So I somehow the problem went away with no explanation. So *shrug*. Thank you everyone for your help
