### ISSUE TITLE
When gamedb is disabled, SFC Panel De Pon is autodetected as the BSX version

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3674]
### Summary
I don't use the current gamedb (due to how it forces screenshots/saves to use filenames in No-Intro format) and normally use a completely blank gamedb.txt. However, recently upgrading to a new BizHawk interim means that this ROM is always opened in the Satellaview core (when BSNES is despite being a SFC ROM.

This did NOT occur with previous dev builds (last one I used is from mid-January).

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load Panel De Pon (SHA-1 is EAD855D774C9943F7FFB5B4F429B2DD07FB6F606)
2. The Satellaview core is used to open it

### Host env.
- BizHawk dev build at 9e5fb35; Win 10;

**Comment by CasualPokePlayer** [comment]
I would say the behavior of it being detected as using Satellaview is actually correct, but the gamedb, being so old, is in fact wrong here. When you don't have a gamedb, it goes through header heuristics to determine if it should go to BSX cores or SNES cores, which it would seem those succeeded for BSX. The gamedb can just override this by specifying the system before it can go through these heuristics in the first place. The old BSNES core wouldn't be selected in such a case, only the newer BSNESv115+ core can, as it is the only core which uses the BSX system id (along with its sub variant, of course).

**Comment by nattthebear** [comment]
Overriding gamedb is an advanced facility for advanced users who specifically intend to modify normal behavior and execute ROMs differently.  This isn't anything we should change.
