### ISSUE TITLE
Deleting too many frames is massively inefficient

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#3675]
### Summary
I brought this up on the TASVideos Discord server, and it seems like I'm not the only one with this issue.

Basically, deleting a large number of frames takes a disproportionate amount of time. By comparison, even performing a delete that's identical to a truncate takes much longer, while truncate is basically instant.

### Repro
1. Open a game
2. Open TAStudio
3. Insert 99999 frames (I used `Ctrl+Shift+Insert`)
4. Select frames 1-100000
5. Delete those frames (I used `Ctrl+Delete`)

Doing these steps with 50000 frames took me 30 seconds, and 99999 frames took me several minutes. I also did variations where the selected frames were more near the middle of the movie.

### Host env.
- BizHawk 2.4.2; Win11 Home 22H2; Intel/Intel
  - (So probably not a regression.)
- BizHawk 2.9.1; Win11 Home 22H2; Intel/Intel
- BizHawk dev build at 9e5fb35; Win11 Home 22H2; Intel/Intel

**Comment by Morilli** [comment]
As discussed on discord, this is due to a large `RemoveWhere` call on a `SortedSet<Cell>`, which performs terribly on .net framework while working fine on .net6+. We could consider local workarounds for now, but ultimately .net6 would be great as it just solves this itself.

**Comment by nattthebear** [comment]
Bizhawk can never move to .net6, so we'll need to consider local workarounds.

**Comment by nattthebear** [comment]
It's easier to leave an emoji reaction on a comment than to do a full rewrite of the Bizhawk frontend to separate it from winforms.

**Comment by Morilli** [comment]
Of course doing a full UI rewrite is costly and not trivially done in a day. However, it *could* be done.

Also, targeting .NET6 on windows is already possible without issues, we just need to target .net framework for linux.

**Comment by CasualPokePlayer** [comment]
At this moment, we can already just try to migrate immediately with Avalonia given it supports netstandard 2.0. Even then, the other deps can easily be replaced by alternatives (the hardest being Veldrid, but a quick OpenGL only variant would be easy)
