### ISSUE TITLE
JagCD Myst freezes at the end

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#3680]
https://youtu.be/dhqMeTbdGY0?t=210

Replay https://tasvideos.org/8202S to reproduce.

**Comment by CasualPokePlayer** [comment]
I recall being told this and really it's likely just an issue with CD timings (and adjusting it back to fix it for Myst breaks other games).

Now fixing CD timings itself is a bit predicated on fixing timings in general as VirtualJaguar has completely fubar'd timings which aren't helping. I might as well just slap in per game timings in thas they are hopelessly bad in their current state.

**Comment by vadosnaprimer** [comment]
As CPP noted on Discord, the whole thing is broken and hacking the timings is not going to make the core more accurate. So it's better to tweak movies to not freeze, which I successfully did.
