### ISSUE TITLE
[F.Rq.] Allow pasting `0xHHHH`-formatted numbers in a `HexTextBox` (e.g. in `WatchEditor`)

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3682]
Went to add Ctrl+V check to keydown handler, but I have no idea what these magic numbers are. [Official docs](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.keypresseventargs.keychar?view=netframework-4.8#remarks) ([current](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.keypresseventargs.keychar?view=windowsdesktop-8.0#remarks)) were no help, nor was StackOverflow.
https://github.com/TASEmulators/BizHawk/blob/13dd04a026855f9ef087254114565eddfd6522b0/src/BizHawk.Client.EmuHawk/CustomControls/HexTextBox.cs#L70-L75

**Comment by Morilli** [comment]
I'm in favor of removing all that custom logic and just doing a simple check for validity after the user is finished entering the number, like in <https://github.com/TASEmulators/BizHawk/pull/3181/commits/c78c0c38345d926514c547f6ad7a3d4cf56a9ba1>

**Comment by kalimag** [comment]
Supporting the `$HH` format used by most (dis)assemblers would also be nice to have. 

Same goes for trimming whitespace before truncating the length.
