### ISSUE TITLE
Running BizHawk emulator on a Ubuntu Virtual Machine using a MacOs host cannot load ROMS

### ISSUE THREAD

**Issue by Filippogigante** [TASEmulators/BizHawk#3687]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
I am trying to load a basic Fire Red ROM on BizHawk 2.9.1 on my ubuntu virtual machine. It throws this error when i load the ROM .

### Output

<img width="1276" alt="Screenshot 2023-06-18 alle 19 07 39" src="https://github.com/TASEmulators/BizHawk/assets/109180521/57dc9be3-efaa-4901-bdc7-534eea9ee3c4">

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1 ; MacOS Ventura 13.3 (Host of the virtual machine) , Ubuntu 22.04.2 LTS (virtual machine where i'm running the emulator) 
 

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Can you confirm the file exists in the `dll` dir?

**Comment by Filippogigante** [comment]
> Can you confirm the file (`libbizhash.so`) exists in the `dll` dir?

I confirm it exists in the dll dir, Yoshi.

**Comment by YoshiRulz** [comment]
Can you try launching EmuHawk from the terminal as `BIZHAWK_INT_SYSLIB_PATH="/usr/lib/x86_64-linux-gnu" LD_LIBRARY_PATH="$PWD/dll:$PWD:/usr/lib/x86_64-linux-gnu" mono EmuHawk.exe`?

**Comment by Filippogigante** [comment]
Failed to load module "canberra-gtk-module"
Using OpenTK 3 for host input (keyboard + gamepads)
[ALSOFT] (WW) Failed to open playback device: Could not open /dev/dsp: No such file or directory
[ALSOFT] (WW) Error generated on device (nil), code 0xa004
[ALSOFT] (WW) Error generated on device (nil), code 0xa001
mono: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
[xcb] Unknown sequence number while processing reply
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
mono: ../../src/xcb_io.c:730: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

**Comment by Filippogigante** [comment]
Then it prints a lot of debugging lines, i can send them if you want.

**Comment by YoshiRulz** [comment]
I believe that's due to missing drivers, but you clearly have them, and they should be under `/usr/lib/x86_64-linux-gnu/dri`. Check where `virtio_gpu_dri.so` is, and add it to `LD_LIBRARY_PATH` if necessary.

**Comment by Filippogigante** [comment]
I don't really know how to do this. I tried setting `LD_LIBRARY_PATH` to `/usr/lib/aarch64-linux-gnu/dri` path and then executing the command : `BIZHAWK_INT_SYSLIB_PATH="/usr/lib/x86_64-linux-gnu" LD_LIBRARY_PATH="$PWD/dll:$PWD:/usr/lib/x86_64-linux-gnu" mono EmuHawk.exe` , it gave me less errors in stdout but still it cannot load the rom and prints the same error when i try executing the ROM.

**Comment by YoshiRulz** [comment]
Just checking—is this an AArch64 VM? BizHawk is for x86_64 only (it's in the filename). The managed parts may run in Mono on ARM, but none of us have ever tested it, and we've [had similar reports](https://github.com/TASEmulators/BizHawk/issues/2731#issuecomment-1417262885) from someone who did test it. A quick search brings up the QEMU-based [UTM](https://mac.getutm.app/) for virtualising x86_64 on Apple Silicon Macs.

Going back to the start, please run `MONO_LOG_LEVEL=debug MONO_LOG_MASK=dll ./EmuHawkMono.sh` and upload `EmuHawkMono_*.txt` [as Gists](https://gist.github.com/). That will clarify exactly what's happening w.r.t. lib loading.

**Comment by Filippogigante** [comment]
Yes i'm running it on an AArch64 VM, i just went full retard mode and didn't see x86_64 at all. Sorry for the inconvenience but i am not used to do this kind of stuff. I don't think i will emulate x86_64 as it will get super slow. Thank you anyways for your fast replies.

**Comment by Filippogigante** [comment]
ò

**Comment by CasualPokePlayer** [comment]
Note for non-x86_64 users: https://github.com/TASEmulators/BizHawk/commit/cd4e58eacabf04e5a05a4cf2ef15200ac1676e9a
