### ISSUE TITLE
[Feature Request] Double click RAM watch to poke

### ISSUE THREAD

**Issue by kalimag** [TASEmulators/BizHawk#3688]
Personally I tend to poke watches far more often than I edit their properties, so I'd like to open the poke window with a double click (instead of opening the edit window as it currently does). 

I can create a PR for this but wanted to ask for feedback first. I figure the way to do this would be either

1. Add a setting that changes what the double click does to the ram watch menu
2. Open poke when double clicking the value cell, open edit on the other cells
I prefer this because it's more flexible, but I don't know how intuitive this is to other users
3. Both (add settings for always edit/always poke/depending on cell)
4. Always poke

**Comment by YoshiRulz** [comment]
I like 1).

**Comment by kalimag** [comment]
I have this PR mostly ready except for the edit.

>add a small message to the top of the poke and edit dialogs saying how to configure it that's only visible when triggered via a double-click

How about showing a message box like this the first time a watch is double-clicked?

![image](https://github.com/TASEmulators/BizHawk/assets/14197345/b43710b6-b1e3-4613-ba36-e1597f70bb97)
