### ISSUE TITLE
NES with QuickNES Graphic Bug - Bizhawk 2.9.1

### ISSUE THREAD

**Issue by PegHorse** [TASEmulators/BizHawk#3703]
Hi,

![image](https://github.com/TASEmulators/BizHawk/assets/7678316/72ae9405-236e-4457-830c-d286258fa016)

With Bizhaw 2.9.1, using QuickNES.
The emulation is freaking out a few seconds later after running the game.

Step to reproduce :
- Download Double Dragon III Europe Version
- Play with QuickNES

After the bug, i've tried with Neshawk, it's working so i can't explain it.

Note : I've changed the ROM for US Version instead of Europe and it is working with both cores for whatever reason...

And that's it.
No display message error.

Thanks

**Comment by nattthebear** [comment]
QuickNES does not support PAL at all.  The only thing to fix here would be to send this rom to the other core every time.
