### ISSUE TITLE
BizHawk cores BSNES 2012/Faust/BSNESv115+/Snes9x supporting MSU-1?

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3705]
BizHawk cores BSNES 2012/Faust/BSNESv115+/Snes9x supporting MSU-1?
MSU-1 coprocessor with CD quality sound, original creator buyy aka Near (R.I.P :()

**Comment by nattthebear** [comment]
maybe/yes/yes/no... are you having a problem with a MSU game?

**Comment by Danik2343** [comment]
I have no problems with hacks with MSU-1, I'm just interested in the question. Thanks for Answer!
