### ISSUE TITLE
[NesHawk] Duck Hunt Not Working Shoting in Ducks, Clays too [BizHawk 2.9.1]

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3706]
Bizhawk 2.9.1 
![EmuHawk_Lm7rPrnzU8](https://github.com/TASEmulators/BizHawk/assets/38865696/53dd8702-b236-460e-a99c-b74f5c19ac38)
P.S I installed QuickNes and returned to NesHawk, everything worked, I did not change anything except the cores.

**Comment by Danik2343** [comment]
Power NES (hotkey) = breaks.
Reset NES (hotkey) = good.

**Comment by Danik2343** [comment]
UPD: Latest Dev: same issue.

**Comment by YoshiRulz** [comment]
DrD2k9 said:
> That issue may be due to where the target is aimed when the game actually reads the coordinate position.  In Duck Hunt, the fire takes place a handful of frames before the coordinates are read.  Holding the mouse over the duck until the white box appears and it works fine.
> in other words, the game doesn't read the targeting coordinates on the same frame(s) as when the trigger is pulled.

See [this publication](https://tasvideos.org/5280M) made on NesHawk 2.8 for sample gameplay.
