### ISSUE TITLE
[Feature request] MAME: Non-Sync options to hide the gear hud in certain games

### ISSUE THREAD

**Issue by danylopez123** [TASEmulators/BizHawk#3715]
I've been thinking on something to request for the ported MAME core, a feature to hide the Low & High gear hud from certain games that shows them.
Like in MAME where you go to video options from a game and there's the different settings for choosing a background type if there's any or you loaded an Artwork file.

**Comment by vadosnaprimer** [comment]
We can't do it because there's no option in original MAME to disable this display in all games at once. If you request that from them, maybe they fix it, then we could copy the fix.

**Comment by Mad-Matty** [comment]
A temporary solution in the absence of a proper fix is to override the default layout by dropping a 'default.lay' file with the gear disabled into the rom image (may work with xml multibundler as well)
[default.lay.txt](https://github.com/TASEmulators/BizHawk/files/12196025/default.lay.txt)

**Comment by danylopez123** [comment]
> A temporary solution in the absence of a proper fix is to override the default layout by dropping a 'default.lay' file with the gear disabled into the rom zip (may work with xml multibundler as well) [default.lay.txt](https://github.com/TASEmulators/BizHawk/files/12196025/default.lay.txt)

Hey, thanks for the file, seems to hide the gear hud just fine.
By the way, can you also make a version that also hides the crosshairs from lightgun games? Seems that it shows the crosshair for a few seconds then hide.
