### ISSUE TITLE
ffmpeg broken video encode for some file formats when using angrylion

### ISSUE THREAD

**Issue by grisenx2** [TASEmulators/BizHawk#3717]
When I record an video with the ffmpeg codec with angrylion as the active plugin, the exported result appears smeared, pixelated, and unviewable. This issue appears when using video formats such as MP4, Matroska, among others.
![ffmpeg_angrylion](https://github.com/TASEmulators/BizHawk/assets/141264034/ad7a4b45-4c23-40f2-8fd1-d582d4bb4bc1)

**Comment by YoshiRulz** [comment]
Which version are you using?

**Comment by grisenx2** [comment]
2.9.1

**Comment by grisenx2** [comment]
this is affected for both mupen64plus and ares64 cores when using angrylion

**Comment by vadosnaprimer** [comment]
It's a decoder issue. ffmpeg's default codec libx264 outputs 4:4:4 video by default, and not all players support it.
