### ISSUE TITLE
Mame Controller Setting in Analog Sensitivity for Jurassic Park Modifies Shooting Distance

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASEmulators/BizHawk#3720]
Sensitivity in games usually denotes how much your input changes some type of cursor or character movement. Where higher sensitivity means more change in the game in response to less input. However the inputs are usually with certain set ranges.

In Jurassic Park with the analog controls, modifying the Sensitivity down to say 20% will only allow my crosshair to cross half the screen.  So here the range itself is being modified which is odd.

Example with these settings:
![image](https://github.com/TASEmulators/BizHawk/assets/34147391/db27230f-d352-45ac-8ca7-c9de284ca72b)
Max distance across screen.
![image](https://github.com/TASEmulators/BizHawk/assets/34147391/aca622f2-dc72-4095-b360-4d3ee3e9e66e)

With sensitivity at 40%
![image](https://github.com/TASEmulators/BizHawk/assets/34147391/ad4ab501-3a3b-41d4-96f7-42d6cdcba934)

It is able to go to cross almost all the distance.
![image](https://github.com/TASEmulators/BizHawk/assets/34147391/5fd7993e-df2c-40fd-aee7-ee6fd084ead4)

Only at 80% can you shoot at the corners of the screen. 

Not sure what other games might be impacted by this.

**Comment by YoshiRulz** [comment]
Working as intended. "Sensitivity" is a misnomer, it actually affects the *output* range.
