### ISSUE TITLE
TIC-80 floating point error (Super Meat Boy demake)

### ISSUE THREAD

**Issue by Randomno** [TASEmulators/BizHawk#3726]
https://tic80.com/play?cart=1512

The in-game timer has what is presumably a floating point error when playing the game in BizHawk.

![image](https://github.com/TASEmulators/BizHawk/assets/17330834/f7b94056-8f00-4c2c-bc4f-f44a79cc7ff7)

**Comment by CasualPokePlayer** [comment]
Seems to be an issue when compiling with Clang, doesn't happen with GCC (also this is regardless of optimization flags, interestingly enough)

**Comment by CasualPokePlayer** [comment]
Looking further, it appears to be a difference in the floor() libc function. It appears to be due to the -frounding-math flag musl passes, which seemingly is just not respected with gcc, while clang does respect it and results in a slightly different result for the floor() function, causing this weird floating point issue. Passing -fno-rounding-math in musl to override the -frounding-math flag results in the "correct" behavior.

**Comment by CasualPokePlayer** [comment]
Scratch the floor function. Doing some more tests seem to indicate that is not the issue, and in fact frounding-math shouldn't cause any issues. What appears to be happening is for some reason, the rounding mode is being set to downward or toward zero on clang, but gcc has the rounding mode still set to its default (to nearest), and this is somehow affected by frounding-math on clang?

**Comment by CasualPokePlayer** [comment]
Doing some testing the rounding mode is definitely still at to nearest, although it's very odd that changing the rounding mode can "replicate" this issue.

**Comment by CasualPokePlayer** [comment]
I can't wrap my head around this, it would seem that code is being compiled correctly, but the CPU is just doing the wrong thing here??? And even trying to do a small reproducible example in *assembly* based on the actual compiled code just yields the ""correct"" result for some reason?

**Comment by CasualPokePlayer** [comment]
SOMETHING and I don't know what but I'm guessing something .NET is changing the precision mode over from 64 bits to 53 bits, causing a loss of precision. clang is producing correct code, it is just acting on an assumption (which normally is correct) that the precision mode is 64 bits as that's what the SysV ABI would normally mandate).
