### ISSUE TITLE
BizHawk handles imported SNES9x CRC32 incorrectly

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#3727]
I am attempting a resync of this movie: https://tasvideos.org/2320M When I imported it into BizHawk, it said `Warning: Movie hash doesn't match the ROM`, which was somewhat surprising, because I had checked the checksum beforehand when I was verifying sync in SNES9x-rr.

~~I had a look at BizHawk's imported movie header, and it had the unusual value `CRC32 -784797148`, which doesn't seem like a proper CRC32 -- in SNES9x, the CRC32 was reported as `D138F224`.~~ This part is fixed in a496f09f072ed0d091a21a70030bbdeaff41b64a

I guess I've also noticed similar issues before: #2336 Maybe this shouldn't be a separate issue, but this focuses on a single actionable specific case, rather than a broader code issue.

### Host env.
- BizHawk 2.9.1; Win11 Home 22H2; Intel/Intel

**Comment by YoshiRulz** [comment]
They're the same number, so it's just a formatting problem.

**Comment by RetroEdit** [comment]
I'm not sure how `-784797148` is the same number as `D138F224`, even taking into account unsigned to signed conversions.

**Comment by YoshiRulz** [comment]
```
$> python -c 'print(-(0x1_0000_0000 - 0xD138F224))' # prints in decimal by default
-784797148
```

**Comment by RetroEdit** [comment]
@Morilli Will this fix the actual issue, that it's not comparing properly? The formatting in the header is one thing, but I'm not sure if that would fix the root issue. GitLab hasn't built yet, and I don't feel like pulling down from source and building myself right now, but this should be checked if it hasn't already (unless I'm missing something obvious about other related code in a496f09f072ed0d091a21a70030bbdeaff41b64a).

**Comment by RetroEdit** [comment]
I tend to think we should be updating the hash to use SHA-1 during import, and use the CRC-32 for the initial validation check. We could ask the user if they want to add the SHA-1 when the import occurs, but it's probably reasonable to do it automatically and warn/ask for confirmation if the imported CRC-32/etc. doesn't match the current game.

(Ideally, we wouldn't be using SHA-1 as our primary key, since it's an outdated hash algorithm nowadays, but that's a whole other can of worms that's more about ROM databases, and it might be borrowing worry anyway -- after all, Git still uses SHA-1, although it is being phased out supposedly).

**Comment by Morilli** [comment]
> only warn/ask for confirmation if the imported CRC-32/etc. doesn't match the current game
Well in that case there would be no way to update the hash. Calculating the missing hash from the currently loaded ROM needs to happen at some point, and if the ROM at the time of importing the movie doesn't match or doesn't exist (which should be possible, but isn't currently), it needs to be deferred to some later time...
