### ISSUE TITLE
[3DS] Driver renegade doesnt launch(3ds load error)

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#3732]
Unless the core isn't released yet, driver renegade.3ds doesn't open at all.

Its a decrypted rom

Using 0af4d125

**Comment by CasualPokePlayer** [comment]
Could you please screenshot the exact load error here.

**Comment by InfamousKnight** [comment]
![3dserror](https://github.com/TASEmulators/BizHawk/assets/2607985/369ab12c-9054-49d3-87fa-ff51fbf36b09)

**Comment by CasualPokePlayer** [comment]
This isn't related to the game at all here, and the fact you are on Linux is more the issue here. Due to an issue with libstdc++ the core can't be compiled with, rather it has to use libc++. Install the `libc++1` package for your distro

**Comment by InfamousKnight** [comment]
Fixed by installing libc++1 

thank you
