### ISSUE TITLE
[BSNESv115+] Kaizou Choujin Shubibinman Zero (2017 cart release) doesn't work

### ISSUE THREAD

**Issue by Sonia-7** [TASEmulators/BizHawk#3749]
The game was originally released for Satellaview in 1997, but it got a physical cart release in 2017, which is in No Intro. It runs fine in Ares v132, but if you try to run it in BizHawk, you get this error:

![Error](https://github.com/TASEmulators/BizHawk/assets/24638400/22d3b19d-d7e2-42fd-9361-53ecd2efc5d7)

The emulator insists it's a Satellaview game even though it's just a regular cart. It doesn't need anything from Satellaview to run.

**Comment by YoshiRulz** [comment]
Just checking which file it is before I start digging into headers:

gamedb (only has Satellaview version): `5B6A4D0740183703F35A349AFB6088A8603D8966`

My copies:
```
$> sha1sum *
1b28d0883c4881e9ba70c1b280be1ac263572c19	BS Kaizou Choujin Shubibinman Zero (J).smc
4b6d6f51173984c2f1e2f379c53174e8e5083cae	Kaizou Choujin Shubibinman Zero (Japan).sfc
$> tail -c 1m BS\ Kaizou\ Choujin\ Shubibinman\ Zero\ \(J\).smc | sha1sum # header?
01ee6bf358d39b7346f97e6c0f0ce20e293b8f4a	-
$> I presume 4B6D... is the version you're referring to, but I'm wondering why my copy of the Satellaview version doesn't match the DB
```

**Comment by CasualPokePlayer** [comment]
The gamedb would be based on an ancient nointro (or some other db idk) db. The proper .bs dump hashes wouldn't be in the gamedb unless they got recently added in.

**Comment by Sonia-7** [comment]
Just saw the new label. Not sure what kind of response you're waiting from me exactly, but if it's a confirmation that "4B6D..." is the dump I used, then yes.

**Comment by YoshiRulz** [comment]
It's *correctly* being identified as a Satallaview (broadcast) rom, [HiROM, FastROM](https://satellaview.fandom.com/wiki/Satellaview_ROM_header#ROM_Speed_&_Map_mode), title "シュビビンマン零", 1 play remaining.

This wasn't a totally pointless exercise though; I noticed my impl. for the plays remaining field is wrong.
