### ISSUE TITLE
mGBA: Wade Hixton's Counter Punch crash

### ISSUE THREAD

**Issue by Reinc01** [TASEmulators/BizHawk#3762]
After beating the first opponent and watching the cutscene, the game crashes to a black screen with garbage sound effect playing on repeat.

Save file: [Wade Hixton's Counter Punch (USA, Europe).mGBA.QuickSave7.zip](https://github.com/TASEmulators/BizHawk/files/12452468/Wade.Hixton.s.Counter.Punch.USA.Europe.mGBA.QuickSave7.zip)

**Comment by YoshiRulz** [comment]
Does this happen on standalone mGBA?

**Comment by Reinc01** [comment]
I've tried playing on standalone mGBA once, and there was no crash at that point.

**Comment by RetroEdit** [comment]
Does this happen consistently? I played through the first fight and it didn't happen.

Is it possible this is just a game bug that happens occasionally? Some GBA games have bugs like this.

**Comment by RetroEdit** [comment]
I beat the first fight twice on BizHawk 2.9.1 and didn't run into the bug. I loaded the savestate you provided, and I did reproduce it... it does only corrupt after the cutscenes in that savestate, which is interesting.

Here's a test `.bk2` movie I made that plays through the first fight and doesn't crash after those cutscenes: [wade_hixton_test.zip](https://github.com/TASEmulators/BizHawk/files/12459775/wade_hixton_test.zip)

**Comment by YoshiRulz** [comment]
If this was a bug that upstream had fixed at the time you tested it, that fix will be in dev builds.
