### ISSUE TITLE
Movie creation: GB firmware defaulting is unintuitive

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#3763]
## Repro
For the purposes of this, I'll use Game Boy as an example, but this probably applies to other platforms with firmware.
1. Download a BizHawk version (or build it)
2. Configure your `Firmware` path to one with Game Boy firmware and optionally configure your `ROM` path.
3. Launch a Game Boy game.
4. Open the record movie dialog using `File > Movie > Record Movie...`
5. Choose reasonable values for `File` and `Author` and choose `Record from`: `Power-On` and press `OK`

This will present a warning: `Warning: Detected disabled BIOS during movie recording. It is recommended to use a BIOS for movie recording. Change SyncSettings to run with a BIOS.`

But then it still just has the undesired behavior of creating the movie anyway. There's no opportunity to go back and correct before the movie is created. At present, you can of course avoid this by remembering to change sync settings beforehand. Changing `Config > Profiles...` to `Tool-assisted Speedruns` also works mostly. In both cases, I think you have to remember to reboot core to apply them (not sure the `Record Movie` reboot counts for these purposes).

## Proposed mitigation
- [ ] 1. Allow sync setting changes inside the `Record Movie` dialog and warn *there* if the current sync settings are bad. At the very least, don't create movies and *then* warn about them; have some way of avoiding that situation.
- [ ] 1a. Maybe have a button to open the sync settings dialog if relevant?
- [ ] 1b. If sync settings can be configured in `Record Movie`, these interactions will have to be considered carefully with `Record From: Now`; sync setting changes should be disabled for that particular setting.
- [ ] 2. Furthermore, if a valid firmware path itself isn't configured, this can't currently be easily handled within the `Record Movie` dialog. I'm not currently sure how to handle the case where the relevant platform's firmware is missing.

## Comparison to GBA
If you do this with a GBA game, it actually has a more stringent firmware requirement, and it will actually implicitly change the sync setting without informing the user if the firmware is available.

If the firmware is unavailable, you will get an error: `A BIOS is required for deterministic recordings!: The core needs certain firmware to load this ROM. Open the firmware manager now?` And the movie will be created anyway and then the game will be unloaded.

### Host env.
- Tested on BizHawk 2.9.1 and c10d292, though this affects all versions that I'm aware of to some extent.

**Comment by YoshiRulz** [comment]
Is this just a `ShowMessageBox` that should be a `ShowMessageBox2`? We should not be messing with the Record Movie flow by letting you change (sync) settings while it's open. As for when no firmware customisation is set, that's handled properly now, the core ctor throws (and that's propagated through the movie start), and the user either adds firmware or changes the sync settings without the core loaded.

**Comment by RetroEdit** [comment]
I actually don't understand the concern about Record Movie flow. I'm not suggesting you change and immediately apply sync settings; instead you should be able to alter them for movie configuration, since it will have to reboot the core anyway to begin recording the movie (for `Power-On` and probably `SaveRam`). As I see it, sync settings are a fundamental part of recording a movie, since they're set in stone after the movie is created, so having them in a separate menu completely disconnected from `Record movie` doesn't make sense to me.

Currently, you can enter `Record movie` and then exit it without starting a movie, and it doesn't disrupt the game.

I think prematurely creating movies when sync settings are probably incorrect is not ideal and a confusing situation for the user. And I'm fairly sure I've seen specific cases where it's led to people recording movies/TASing with the wrong settings because it's not conveniently communicated to the user.

**Comment by CasualPokePlayer** [comment]
`Warning: Detected disabled BIOS during movie recording. It is recommended to use a BIOS for movie recording. Change SyncSettings to run with a BIOS.` and `A BIOS is required for deterministic recordings!: The core needs certain firmware to load this ROM. Open the firmware manager now?` happen in the core ctors here, so this is arguably well within the Record Movie flow and probably can't avoid making a movie here?

**Comment by YoshiRulz** [comment]
Well then I don't understand why that can't abort movie start.

**Comment by YoshiRulz** [comment]
Can you guys copy-paste the error message verbatim next time? Or better yet, grab the permalink:
https://github.com/TASEmulators/BizHawk/blob/362269c982073946062a9de76b81d9ccb2380c68/src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.cs#L94
Compare to mGBA:
https://github.com/TASEmulators/BizHawk/blob/362269c982073946062a9de76b81d9ccb2380c68/src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBA/MGBAHawk.cs#L32
https://github.com/TASEmulators/BizHawk/blob/362269c982073946062a9de76b81d9ccb2380c68/src/BizHawk.Client.EmuHawk/MainForm.cs#L3692-L3698
However, Gambatte will throw `MissingFirmwareException` if *"Use official Nintendo BootROM" is enabled* and the firmware customisation is empty:
https://github.com/TASEmulators/BizHawk/blob/362269c982073946062a9de76b81d9ccb2380c68/src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.cs#L83

This is simply a case of Gambatte's maintainer(s) deciding that you should be allowed to record w/ HLE BIOS, while mGBA's maintainer(s) didn't want that. We want consistency, so someone has to be wrong, but who? With #2832 it seems we've agreed on aborting core load as an acceptable UX, meaning Gambatte needs a 1-line fix.
That said, I'm personally sympathetic to your idea from the OP of including a warning in the Record Movie dialog. It's just that I think it would require either an `IBIOSTogglable` abstraction for sync settings structs, or shoehorning in an extra core init (like https://github.com/TASEmulators/BizHawk/commit/34d794b368a2943aa20a735f1045d63a69f094c3).

**Comment by CasualPokePlayer** [comment]
Arguably Gambatte should just be changed to mGBA's behavior, force enable bios and throw if not present.

As an exception however, skip the bios regardless if it detects that the rom is not bootable by the bios' standard (no Nintendo logo / wrong header checksum), and notify user of this state and the bios is being skipped. The native core should provide this info normally (may especially be relevant with weird mappers where you can't reliable check if the header is acceptable for bios standards). This is done already in mGBA.

**Comment by CasualPokePlayer** [comment]
> Arguably Gambatte should just be changed to mGBA's behavior, force enable bios and throw if not present.

This is now the case since https://github.com/TASEmulators/BizHawk/commit/d788e603fd6e534bbf2e7dac23d4d1d81be33ed3
