### ISSUE TITLE
Bizhawk Key Bindings for Arrow Keys Not Being Recognized

### ISSUE THREAD

**Issue by lordzilong** [TASEmulators/BizHawk#3777]
### Problem:
In any Bizhawk/Emuhawk emulator the arrow keys function in the menus and setting the key bindings within controllers but will not work as keys when used in any game in any emulator.

### Details:
Having set the key bindings for movement to Up, Down, Left, Right (Arrow Keys) in 5+ tested emulators in Bizhawk/Emuhawk it recognizes the use of my arrow keys in the menus and for assigning the binding perfectly normal. However, when playing anything in the emulator they will not function. Assigning any other keys works fine, however assigning arrow keys does not. I have set 'Display Input' and no icon appears when using the arrow keys that were keybound so it is not recognizing their use as it should be.

--------------------------------

Sorry if this is not where I should make a post such as this. I may just be too dense to understand something that someone more knowledgeable finds very simple. I am very new to Bizhawk. But this has stumped me, and I ran out of ideas to attempt to solve it. Thank you in advance for any ideas or assistance.

**Comment by YoshiRulz** [comment]
Did you figure out why it wasn't working?
