### ISSUE TITLE
fm2 movies for FDS games cause an IndexOutOfRangeException

### ISSUE THREAD

**Issue by TakuikaNinja** [TASEmulators/BizHawk#3779]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Attempting to play an FDS movie converted from fm2 files (drag & drop/import movie) causes an IndexOutOfRangeException. From what I can tell in the source code, this functionality does not appear to be finished.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Start an FDS game. (games tried: SMB2J, Tonkachi Mario)
2. Drag and drop an fm2 file, or import it and then play the converted movie file.
3. "Fatal Error: IndexOutOfRangeException" window appears

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
![image](https://github.com/TASEmulators/BizHawk/assets/43363447/1d177655-a71a-468f-b93c-2b2b4335540b)

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9, Linux (EndeavourOS)

**Comment by YoshiRulz** [comment]
Full stacktrace when importing https://tasvideos.org/3348M:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at BizHawk.Client.Common.Bk2Controller.SetFromMnemonic (System.String mnemonic) [0x0005b] in <973fb7a12a68494182a2aa93dd31a9ec>:0 
  at BizHawk.Client.Common.Bk2Movie.GetInputState (System.Int32 frame) [0x0007a] in <973fb7a12a68494182a2aa93dd31a9ec>:0 
  at BizHawk.Client.Common.MovieSession.LatchInputToLog () [0x00017] in <973fb7a12a68494182a2aa93dd31a9ec>:0 
  at BizHawk.Client.Common.MovieSession.HandleFrameBefore () [0x00082] in <973fb7a12a68494182a2aa93dd31a9ec>:0 
  at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core (System.Boolean force) [0x0034d] in <4ecfa9309b57435ebe194da8a64e8a1d>:0 
  at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop () [0x001e7] in <4ecfa9309b57435ebe194da8a64e8a1d>:0 
  at (wrapper remoting-invoke-with-check) BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
  at BizHawk.Client.EmuHawk.Program.SubMain (System.String[] args) [0x003dd] in <4ecfa9309b57435ebe194da8a64e8a1d>:0 
```

**Comment by YoshiRulz** [comment]
adelikat ran into a separate crash https://tasvideos.org/Forum/Posts/532313

**Comment by YoshiRulz** [comment]
Per https://github.com/TASEmulators/BizHawk/commit/f32277ebd620efdde8683df185c694c33f371809#comments the importer no longer throws, though the LogKey will be incorrect.

**Comment by Morilli** [comment]
Small correction: The logkey is "correct" for what has been imported, aka every control that has been handled is specified in the logkey. The issue is that the importer does not handle FDS controls, so they are simply not imported. The controller definition also does not match what the core internally constructs when playing the movie, leading to a mismatch in available controls from the movie and bizhawk when playing it.

See https://github.com/TASEmulators/BizHawk/blob/f32277ebd620efdde8683df185c694c33f371809/src/BizHawk.Client.Common/movie/import/Fm2Import.cs#L268 and ignore https://github.com/TASEmulators/BizHawk/blob/f32277ebd620efdde8683df185c694c33f371809/src/BizHawk.Client.Common/movie/import/Fm2Import.cs#L183-L188 because that code is currently no-op.
