### ISSUE TITLE
HQ2X broken in latest dev builds ok in 2.9.1

### ISSUE THREAD

**Issue by 007mesen** [TASEmulators/BizHawk#3781]
HQ2X broken in latest dev builds ok in 2.9.1

turn on HQ2X everything looks overly fuzzy.

Compare to 2.9.1

One place it is super evident and easy to see is the atari 7800 bios screen, it really shows there.

but that being said it looks like a rf mess everywhere.

**Comment by Morilli** [comment]
Git bisect gives 59fcdb04cd5a188e2278cb62c5298d4335e7e609 @CasualPokePlayer
