### ISSUE TITLE
What do I do to play on BizHawk, Amiga and Atari ST?

### ISSUE THREAD

**Issue by lhvista2007** [TASEmulators/BizHawk#3785]
Hey, guys... Noting this error of the Amiga with 'puae_libretro.dll' and Atari ST with 'hatari_libretro.dll'... In the Amiga appears information on the screen in cycle that lacks KickStart and in Atari ST gives error message ... If it is because of the lack of BIOS, Firmware, ROMs, I don't know how many, what do I do to add in a folder, like ROM files, Firmware, BIOS in the folder type System, Firmware, BIOS, ROMs, I don't know, inside the folder of the BizHawk emulator? As in the case of the Amiga lacks Kiackstart files and the Atari ST lacks tos.img... What do I do? Thank you...

![screencap](https://cdn.discordapp.com/attachments/280813077853765632/1158165899547787324/Amiga.png?ex=651b418c&is=6519f00c&hm=f5f8ad11e6b124704c1a63f0b8b3194489f89943b8621af8ba20a3235a6b3261&)

![screencap](https://cdn.discordapp.com/attachments/280813077853765632/1158165899858149397/Atari_ST.png?ex=651b418c&is=6519f00c&hm=b3e83a34d23a5b8177a0f50a3ff808f27987e5de59ffbfc623948453406a616c&)

**Comment by YoshiRulz** [comment]
Have you read [the documentation for the core](https://docs.libretro.com/library/puae/#bios)?

**Comment by CasualPokePlayer** [comment]
We're not responsible for individual libretro cores' firmware requirements or whatever. It is up to the user to find the documentation for the core (typically on libretro's website) and follow it accordingly.

**Comment by YoshiRulz** [comment]
Resolved by OP on Discord:
> Need to put System folder with firmware in BizHawk/Libretro/System/corefilename_libretro/(firmware)
