### ISSUE TITLE
Accepting Hotkeys from another program

### ISSUE THREAD

**Issue by ChaosTiki** [TASEmulators/BizHawk#3786]
I apologize if this is not where I can get an answer to this question.  I have been using Bizhawk 2.9.1 and setting up hotkeys to do some Rewind, Pause, Speed Up and Speed Down.  They work in Bizhawk when I manually input them on my keyboard, but when I try to have another program (Sammi) input them, Bizhawk does not see the inputs.  I have confirmed that the other program is outputting the hotkeys.  What would cause Bizhawk to not see those hotkey presses?  I have the other program running as administrator and got a warning from Bizhawk to not run it in administrator mode.

**Comment by YoshiRulz** [comment]
This is because host input is read directly via DirectInput, and not from the main window. Use ApiHawk to communicate with another process.
