### ISSUE TITLE
Player 2 can't go left, but left key is being detected

### ISSUE THREAD

**Issue by KronosPNG** [TASEmulators/BizHawk#3787]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
I'm emulating Mortal Kombat II for the SNES, for whatever reason player 2 can't go left.
I have tried then too show inputs from both keyboard and controller, in both cases the "left" input is detected but doesn't seem to go through. Is there any way to fix this? heisenbug

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1; Win11 ; Intel/NVIDIA

[//]: # "(screenshots, if applicable)"
![Screenshot (20)](https://github.com/TASEmulators/BizHawk/assets/105851736/5d4f7054-415d-4659-9f1e-eceb7a8b9d4b)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
Works fine with the new BSNES core, just not Snes9x for some reason. I don't believe we have a blocklist for this so closing as wontfix.

**Comment by CasualPokePlayer** [comment]
Does this still end up occuring with https://github.com/TASEmulators/BizHawk/pull/3729?
