### ISSUE TITLE
[Linux] xbox one controller bindings wrong

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#3798]
I don't know if its my controller in particular, but I'm seeing some strange issues.

When mapping the controller inputs, Up depad is always interpreted as Down depad. If I press Right button, it always presses down along with it.

Have seen this happen with melonds and octoshock

Is anyone else having this problem?

using commit ac3913de

**Comment by YoshiRulz** [comment]
CNR on NixOS, same gamepad presumably (`045e:02ea`), same commit, same core.

**Comment by CasualPokePlayer** [comment]
The core itself shouldn't matter (the cores shouldn't care/influence host input details).

Linux would just be using SDL's for gamepads, which internally is either udev (if it's going with HIDAPI) or *probably* just evdev.

**Comment by YoshiRulz** [comment]
The VID+PID is no longer printed to the console, even in Debug config, so you'll need to use `lsusb`.

**Comment by InfamousKnight** [comment]
Its usb connected.

Stable bizhawk 2.9.1 works fine. And I dont know for sure which xbox one controller type it is. I know its wired

**Comment by CasualPokePlayer** [comment]
The "Xbox One controller type" in this case is "PowerA Xbox ONE liquid metal controller"
https://github.com/libsdl-org/SDL/commit/bedc509afcf49a358e79a01b23ab9ff6cf53c57c
Apparently too it's in SDL's own database of controllers?

**Comment by CasualPokePlayer** [comment]
Does the controller work with Steam games anyways?

**Comment by InfamousKnight** [comment]
What does steam have to do with it? I do know 2.9.1 works just not dev build

**Comment by CasualPokePlayer** [comment]
Steam games would also use SDL2.

**Comment by YoshiRulz** [comment]
Steam has its own gamepad mappings though, maybe not an ideal baseline to use.

**Comment by InfamousKnight** [comment]
On commit 5fc37d6aac0be9d472bd8f2cc43719325e4b1a9e the issue is still present..

Not really sure what else to do here..

**Comment by CasualPokePlayer** [comment]
> If I press Right button, it always presses down along with it.
What do you mean by this exactly?

**Comment by InfamousKnight** [comment]
Because nobody else can reproduce this, I'm going to assume it's my controller.

closing as I don't think there's anything that can be done

**Comment by InfamousKnight** [comment]
I found analog controls work just fine though. So I guess if someone has a controller like mine, then don't map anything to dpad
