### ISSUE TITLE
[Scripting] Events for core start/stop/reset

### ISSUE THREAD

**Issue by v1993** [TASEmulators/BizHawk#3800]
It would be quite useful to have an event that fires when emulation is first started.

I plan to implement main script functionality using a bunch of breakpoints set using `event.on_bus_exec`, which must be executed once core has been loaded; callbacks are also lost on emulation restarts. I can enable "start paused" option and reload the script then unpause (some modifications should be done pretty early in execution), but this is rather inconvenient. Another option is to call `emu.reboot_core()` from script and set up breakpoints afterwards, but, once again, it's less than perfect.

With `event.on_core_start`/`event.on_core_stop`/`event.on_core_reset` callbacks in place it would be very well possible to make the experience seamless - breakpoints would be just set up in start/reset callbacks, so script could be loaded once before starting emulation and just work regardless of what user does.

**Comment by CasualPokePlayer** [comment]
Starting and stopping a core implicitly switches cores (from core A to core B or from core B to NullHawk). From what I can tell too, you're only caring about core reboots (which is really more analogous to doing Open ROM again; also it's just core B to a new instance of core B). You only need some on_core_change callback here (maybe core name passed onto the callback here).

**Comment by YoshiRulz** [comment]
The entry point for core change/start/stop is the top of the script.

**Comment by kalimag** [comment]
One theoretical exception to that are `client.openrom()` or `client.reboot_core()` calls in a different script, which (re)start the core without restarting scripts.

If your own script is calling those functions you know when to re-run your initialization stuff of course, but if a second script is using them there wouldn't be any good way to detect that.

**Comment by v1993** [comment]
@YoshiRulz It's not working as intended for me. My scripts that calls `event.on_bus_read` and then exits does not get re-executed on core resets. I suppose adding a frame advance loop may fix this, but that seems kinda unnecessary when all I need is really callbacks.

Either way, documentation says that (emphasis mine)

> so to run something every frame you'll need to end the script with an infinite loop (*or you could set a callback on one of the events instead*)

So I'd say scripts that set up callbacks and then exit not being re-run on core reset is a bug. To tie in with their callback-based approach an alternative to re-running those scripts would be to add core events like I've suggested.

**Comment by YoshiRulz** [comment]
I don't think a callback-only paradigm has ever been encouraged, so while it does *feel* wrong that this isn't possible, I wouldn't call it a bug.
Relaunching stopped scripts is out of the question, even if we filter for those with registered callbacks (which we're already tracking). The file could contain garbage, or an unfinished script that in its current form deletes all your files. We could add an `emu.restart_this_script()` or `emu.yield(true)` to indicate a script is 'gracefully stopped' and should be run again on core load, but a one-line `emu.frameadvance` loop has the same effect and isn't much harder for the script author.
