### ISSUE TITLE
The arcade version of ghosts and goblins doesnt work

### ISSUE THREAD

**Issue by ExGuestCJ** [TASEmulators/BizHawk#3806]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
When i open the zip file for the ghosts and goblins arcade version the emulator crashes

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. open the emulator
2. open the zip file of ghosts and goblins

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
the emulator just crashes

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1 x64: dell inspiron 3531

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by Spikestuff** [comment]
User error?
![image](https://github.com/TASEmulators/BizHawk/assets/12412764/3d8325aa-6ccc-45d4-a916-6a4a39b068e3)

**Comment by ExGuestCJ** [comment]
I think i used the wrong rom

**Comment by ExGuestCJ** [comment]
it still doesnt work

**Comment by YoshiRulz** [comment]
> dell inspiron 3531

> 1x 4 GiB

Do you have enough memory?

**Comment by ExGuestCJ** [comment]
> > dell inspiron 3531
> 
> > 1x 4 GiB
> 
> Do you have enough memory? Try again without any other programs open.

yes i have enough memory
