### ISSUE TITLE
Latest dev build issues in window mode

### ISSUE THREAD

**Issue by 007mesen** [TASEmulators/BizHawk#3807]
Latest dev build https://github.com/TASEmulators/BizHawk/commit/62501ad859731f03fd293ebaf37ce3e86ec5d4e7 under windows x64

running roms in windowed mode results in black display till reszing or switching to full screen.

issue not present in 2.9.1

**Comment by YoshiRulz** [comment]
Could you go to `Help` > `About...` and copy the commit hash?

**Comment by 007mesen** [comment]
62501ad

**Comment by CasualPokePlayer** [comment]
Screenshot your config in Config -> Display

**Comment by 007mesen** [comment]
Will do when im at a pc again. Issue happened no matter settings, even fresh download unzip and drag drop any random rom any core

**Comment by 007mesen** [comment]
Issue happens when using bilinear filter and hq2x.


Load rom go fullscreen to window and black till resize.

2.9.1 works as expected

**Comment by CasualPokePlayer** [comment]
Does it happen for D3D9 or OpenGL display methods (or both?)

**Comment by 007mesen** [comment]
Both

**Comment by CasualPokePlayer** [comment]
I can't repro this with bilinear filter + hq2x. Although, I seem to be able to repro something similar by setting the prescale to exactly the window multiplier (or checking auto prescale, which also does that), while having bilinear or bicubic filtering enabled.
