### ISSUE TITLE
TAS Videos "Activity" page is not calculating "Time Since Last" correctly.

### ISSUE THREAD

**Issue by nymx-tas** [TASEmulators/BizHawk#3816]
I was asked to report this issue by feos. I've noticed that the "Time since last" column is no longer resetting to zero for me. It looks like this is the case with others as well.  Currently, it says that I"m 17 days, which can't be since I have approved a number of submissions in the past week and have claimed replacements for each submission completed.

**Comment by CasualPokePlayer** [comment]
This is the BizHawk github.

**Comment by YoshiRulz** [comment]
Moved to https://tasvideos.org/Forum/Posts/526143.

(For the record, TASVideos.org's repo is https://github.com/TASVideos/tasvideos.)
