### ISSUE TITLE
Unckecing or changing level of RW&FF volume doesn't work

### ISSUE THREAD

**Issue by nefariouslegion** [TASEmulators/BizHawk#3819]
### Summary
I've setup a Pokemon Emerald Randomizer ROM (that also randomizes my team every battle) with Ironmon Tracker Lua script running. But when I try to set the RW & FF volume to a lower level or uncheck it nothing changes. I'd expect the volume to be lower (or muted if unchecked) when decreasing or increasing game speed. But that doesn't seem to work

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load ROM
2. Click Config > Sound
3. Lower or uncheck RW & FF volume
4. Nothing changes like it should

Using 2.9.1.

**Comment by YoshiRulz** [comment]
Which version of EmuHawk are you using?

**Comment by nefariouslegion** [comment]
> Which version of EmuHawk are you using?

Version 2.9.1

**Comment by CasualPokePlayer** [comment]
FF here refers to the fast forward when holding Tab (default fast forward hotke), not changing clock throttle's speed precent. This is intended.
