### ISSUE TITLE
When opening Battletoads with quicknes enabled it switches to neshawk

### ISSUE THREAD

**Issue by ExGuestCJ** [TASEmulators/BizHawk#3823]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
When opening Battletoads with quicknes enabled it switches to neshawk.
### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Choose a rom
2. Open the rom of the american nes version of Battletoads

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1 x64: DELL inspiron 3531

[//]: # "(screenshots, if applicable)"
![download](https://github.com/TASEmulators/BizHawk/assets/88068182/4d63eec4-8d4e-4508-956c-f55a51b963d6)
![download](https://github.com/TASEmulators/BizHawk/assets/88068182/982dcbfe-fd0f-4bd2-a22f-7fb0350c099f)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by ExGuestCJ** [comment]
i think i did it wrong

**Comment by YoshiRulz** [comment]
CNR with `SHA1:5C3A497A82BE60704DEDF45248B6AD9B32C855AB` at eeb824d03, though note that no revision has a core override or is in QuickNes' blocklist.

**Comment by ExGuestCJ** [comment]
> CNR with `SHA1:5C3A497A82BE60704DEDF45248B6AD9B32C855AB` at [eeb824d](https://github.com/TASEmulators/BizHawk/commit/eeb824d035ac8bf0c6cf2046a0fbf4346790163f), though note that no revision has a core override or is in QuickNes' blocklist.

what does that even mean?

**Comment by YoshiRulz** [comment]
My copy is `SHA1:5C3A497A...` and I'm able to load it with QuickNes. I'm not using 2.9.1, but a 2.9.2 dev build.

QuickNes has this list:
https://github.com/TASEmulators/BizHawk/blob/6a8033678795555b8641a5b00e1f4ef961946eca/src/BizHawk.Emulation.Cores/Consoles/Nintendo/QuickNES/QuickNES.cs#L278-L279
Battletoads isn't in there.

**Comment by ExGuestCJ** [comment]
oh

**Comment by YoshiRulz** [comment]
Can you backup and delete `config.ini` and try again?

**Comment by ExGuestCJ** [comment]
didnt work

**Comment by ExGuestCJ** [comment]
i mean, the same thing happenned

**Comment by ExGuestCJ** [comment]
I opened both the zipped file and the uncompressed file

**Comment by ExGuestCJ** [comment]
Yes, other games work

**Comment by CasualPokePlayer** [comment]
How big is the Battletoads ROM file?

**Comment by ExGuestCJ** [comment]
181.28 KB

**Comment by ExGuestCJ** [comment]
Zipped

**Comment by CasualPokePlayer** [comment]
What is the size unzipped.

**Comment by ExGuestCJ** [comment]
256.01 KB

**Comment by CasualPokePlayer** [comment]
Could you go to the Properties of the ROM file in Windows file explorer and post the "Size" (the bytes specifically)

**Comment by ExGuestCJ** [comment]
262160 unzipped and 185632 zipped

**Comment by CasualPokePlayer** [comment]
Could you please report the SHA-1 of the unzipped file.

**Comment by ExGuestCJ** [comment]
File: B5E4AF9DF63361498ED54A4E71BFE01E8D1A1481
Rom:D85C9FF489672534FBF61A15F8FA56FFF489A34B

**Comment by CasualPokePlayer** [comment]
This is just indicating the iNES header is bad in some way, which QuickNes chokes with but NesHawk doesn't (probably as NesHawk doesn't require actually using the iNES header, so it probably doesn't care if it's bad or good).

**Comment by ExGuestCJ** [comment]
Oh well

**Comment by YoshiRulz** [comment]
Calling this part of #2336 I guess?
