### ISSUE TITLE
MelonDS Pokemon HeartGold Speed Increase/Decrease Speed does not go past 300%

### ISSUE THREAD

**Issue by nefariouslegion** [TASEmulators/BizHawk#3824]
### Summary
When playing Pokemon HeartGold pressing the Fast Forward, Increase Speed and Decrease speed hotkeys they don't work. They don't go past 300% even though it indicates I'm speeding up to 400%+.

### Repro
1. Load up HeartGold ROM
2. Try to Fast Forward, Increase or Decrease Speed

### Host env.
List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1 Windows 11

**Comment by YoshiRulz** [comment]
The speed maxing out at 300% is not a bug, it simply indicates you've reached the limits of your CPU's single-threaded performance.

**Comment by nefariouslegion** [comment]
I find that odd considering I have a Ryzen 9 5900X which is no slouch
________________________________

**Comment by CasualPokePlayer** [comment]
DS emulation is intensive, especially for BizHawk which is locked with the interpreter. 300% speed is already very good, my own PC can't go past 200% for that game.

**Comment by nefariouslegion** [comment]
Ah ok thank you for the explanation. I guess I was just naive thinking it would be able to go faster
