### ISSUE TITLE
Add more window size option?

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#3826]
Such as 6x, 7x, etc.
On high resolution screen 5x (current biggest) is a bit small.

**Comment by YoshiRulz** [comment]
You can set an explicit resolution in `Config` > `Display...`.

As far as this request goes, I still think https://github.com/TASEmulators/BizHawk/issues/3039#issuecomment-1118522713 is the way to go, but adding more to the existing system is basically free so why not.

**Comment by vadosnaprimer** [comment]
I don't think replacing multipliers with resolutions will solve anyone's problems on its own. At least the menu should mention both resolution and multiplier, but still I don't think it's important as explained to my reply to that comment.
