### ISSUE TITLE
ffmpeg 4.4.1 broken decode (smeared/garbled video output)

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#3829]
So I occasionally use BizHawk to record some game footage and use ffmpeg to output to MP4, but the footage appears blurry, pixelated, and grey in certain areas, rendering it unwatchable. This seems to only persist starting with ffmpeg version 4.4.1, and there was no such decoder problems with pervious versions of ffmpeg (20181118-529debc and earlier) where the video would preview as expected. Until a fix for 4.4.1's decoder comes around, would it be possible for future versions of BizHawk to provide the option to download and use older versions of ffmpeg rather than rely specifically on the latest version?

**Comment by Morilli** [comment]
Are you sure this is a problem of ffmpeg and not of the program you're using to watch the generated videos?
ffmpeg 4.4.1 has been in bizhawk for a while, so it can't be a general issue.

Could you perhaps post one of the broken videos here and give more information about what you recorded, aka: what settings are you using for ffmpeg, what core, etc.?

**Comment by Distnergistic** [comment]
It's problem with ffmpeg 4.4.1's codec not being supported with certain video players, such as Windows Media Player. With versions of ffmpeg that came with BizHawk prior to 20181118-529debc (when it became a seperate download), the exported videos would work with Windows Media Player with no issue, and starting with 20181118-529debc, WMP playback would no longer work.

**Comment by Morilli** [comment]
I don't believe we care about supporting any video player ever as long as the videos are technically fine.

There are lots of video formats you can create with bizhawk that most likely won't play with something like the windows media player, like lossless video. I would recommend getting a better video player that is capable of playing more modern video files, like the [VLC media player](https://www.videolan.org/vlc/download-windows.html).

**Comment by CasualPokePlayer** [comment]
"ffmpeg 4.4.1's codec" tells us nothing, there's hundreds of codecs which ffmpeg supports.

Also since the user apparently deleted their github account (lmao?) I'll just close this and blame Windows Media Player being bad.
