### ISSUE TITLE
melonDS: Can't read ROM from Lua scripts

### ISSUE THREAD

**Issue by raphaelr** [TASEmulators/BizHawk#3830]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
melonDS has no "ROM" memory domain, like mGBA has. This means Lua scripts can't read from the ROM using e.g. `memory.read_u32_le(addr, "ROM")`.

There is a line in the code to add it but the memory domain is still not there:
https://github.com/TASEmulators/BizHawk/blob/4ad9b7b2bf3407a9ded8aae0038d47f85185191e/waterbox/melon/BizDebugging.cpp#L251-L255

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Run this in the Lua console: `print(memory.getmemorydomainlist())`

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
"0": "Main RAM"
"1": "Shared WRAM"
"2": "ARM7 WRAM"
"3": "Instruction TCM"
"4": "Data TCM"
"5": "ARM9 BIOS"
"6": "ARM7 BIOS"
"7": "ARM9 System Bus"
"8": "ARM7 System Bus"
"9": "Waterbox PageData"
```

There should be an additional "ROM" entry.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1; Win10 Pro 19045.570; Intel/Intel

**Comment by YoshiRulz** [comment]
The code you linked was added in https://github.com/TASEmulators/BizHawk/commit/f7786e81b9b6b67adca43273513847a25f911677, so it wouldn't have been in 2.9.1.
