### ISSUE TITLE
Freezing many values in hex editor, then choosing not to freeze will still freeze the first value (Bizhawk 2.8)

### ISSUE THREAD

**Issue by mugg91** [TASEmulators/BizHawk#3833]
### Summary
Playing Game Boy game on Bizhawk 2.8 (I can't verify on newer version right now), open hex editor and freeze a lot of values. 
When the pop up comes up saying it might be a bad idea to freeze so many values, then choosing to not freeze any values, the emulator will still freeze the first value.

### Expected Behavior
When being asked "Do it anyway?" and choosing "No", it should not freeze any values.

**Comment by mugg91** [comment]
Actually it freezes the address that is currently selected, indicated by pink color without black border.

Click on any address and drag down by a large margin to select many addresses, then freeze, choose no, and the address you first clicked on will be the one that will be frozen.

**Comment by YoshiRulz** [comment]
Selection is written as 1+N.
