### ISSUE TITLE
Weird bug regarding pausing

### ISSUE THREAD

**Issue by Blacksuit26** [TASEmulators/BizHawk#3836]
My pause button is tied to NumPadSlash and whenever I try to pause, it only pauses or unpauses for as long as it's held down, additionally, NumPadStar pauses the way I would expect NumPadSlash to pause even though it's not bound TO pause and also for some reason the rewind button ALSO pauses, I have no idea what is causing this and I need help

**Comment by YoshiRulz** [comment]
> (Nvm, I figured it out)

Care to share?
