### ISSUE TITLE
Random crashes when playing PS1 games on Manjaro Linux

### ISSUE THREAD

**Issue by monstro1** [TASEmulators/BizHawk#3843]
### Summary
Trying to run PS1 games will result in random hanging and crashing. Trying to load a rom from the .cue file causes the emulator to freeze, requiring me to kill the process with CTRL+C. I tried loading some gba roms, and they all play without any issues. I managed to get some games to run by first loading a gba game and then loading a ps1 game afterward. But even when it does start to work, certain actions like maximizing the window, clicking anything in the menu, or alt-tabbing out cause the emulator to freeze.

### Host env.
Manjaro Linux running KDE/Plasma
CPU: 12th Gen Intel i5-12600KF (16) @ 4.900GHz
GPU: AMD ATI Radeon RX 6600/6600 XT/6600M

**Comment by YoshiRulz** [comment]
Can you upload the `EmuHawkMono_last*.txt` files? Are you using 2.9.1?

**Comment by monstro1** [comment]
[EmuHawkMono_laststdout.txt](https://github.com/TASEmulators/BizHawk/files/13891887/EmuHawkMono_laststdout.txt)
laststderr.txt is empty. And yes, I am on 2.9.1

**Comment by YoshiRulz** [comment]
> `SHA1:10155D8D6E6E832D6EA66DB9BC098321FB5E8EBF`

![screencap](https://github.com/TASEmulators/BizHawk/assets/13409956/2bc3816d-68cf-4979-ac9c-69a38d7d5851)
Take another firmware dump and try again.

**Comment by monstro1** [comment]
I tried the `sha1:0555...` firmware, same issue

**Comment by YoshiRulz** [comment]
Well that's really all there was in that log (which I suppose is to be expected from a hang). Can you try the same game in a dev build? If it's still giving you trouble there, I think we'll have to make you an instrumented build to figure out where the failure is coming from.

**Comment by monstro1** [comment]
Just tried the latest dev build and it worked perfectly -- no hangs at all
