### ISSUE TITLE
CPCHawk - Incorrect Text Label Under "Other Non-Sync Settings"

### ISSUE THREAD

**Issue by ShinobiWannabe** [TASEmulators/BizHawk#3845]
After running a CPC game select -> Amstrad CPC -> "Non-Sync Settings".  The text label underneath reads  "ZX Spectrum Misc Non-Sync Settings".

Should read "Amstrad CPC Misc Non-Sync Settings".

Guessing this core was made off a ZX Spectrum core.
![image](https://github.com/TASEmulators/BizHawk/assets/34147391/f3b9e4f4-4b73-4f56-95b3-19838bd0f2ad)

**Comment by Asnivor** [comment]
https://github.com/TASEmulators/BizHawk/issues/3844#issuecomment-1891061000
