### ISSUE TITLE
Write breakpoint seemingly not triggering when mGBA EWRAM address gets written to

### ISSUE THREAD

**Issue by cIymax** [TASEmulators/BizHawk#3847]
### Summary

My write breakpoint in mGBA doesn't appear to break execution even when the relevant memory location is written to.
Not sure if this is an issue or if there's some other explanation (I could be missing something), but I thought I'd report it here just in case.

### Video demo

https://www.youtube.com/watch?v=kIHvoRYlVUA

### Repro

1. Run EmuHawk.
2. Load the game, Final Fantasy V: Advance, US edition.
3. Start a new game.  
4. Open the debugger (Tools -> Debugger).
5. Add a write breakpoint at 200DF7C.  This is where the job flags for the game are stored.  They keep track of which jobs you have access to.
6. Open the RAM watch window (Tools -> RAM Watch).
7. Add a watch at DF7C, size of "4 bytes," display type "Hex."  Leave Big Endian unchecked.  Memory domain is "EWRAM."  This should correspond to the address at step 5.
8. In your new game, toward the end of the intro cutscene, the memory location will be written to, but execution doesn't break.  The memory location is written to because the game is initializing the job flags.

### Notes

1. Interestingly, the write breakpoint triggers correctly, I believe, in the game's attract mode.  To test this, reset the game with the write breakpoint still intact.
2. The next test after the one at the end of the opening cutscene is when finding the Wind Crystal, but I haven't trekked there to do that test.
3. A read breakpoint at the same address works correctly and triggers when you pull up the in-game menu when in game.
4. Also did a trace of the relevant frame.  It yielded ~100K instructions (and doesn't seem to let me log memory values per line), which is why a working breakpoint would be very helpful.

### Host env.

Versions: EmuHawk 2.9.1 (x64) / mGBA 0.1
Game: Final Fantasy V Advance (US)
Memory address: 0x0200DF7C / EWRAM 0x00DF7C
Value change: 0x00000000 to 0x02000000

**Comment by kalimag** [comment]
The game could be writing a single byte or a half word in the middle of those 4 bytes, instead of a full word. Check if you get a hit on the address +1/+2/+3, or set the mask to `FFFF FFFC`.

**Comment by cIymax** [comment]
Thank you!  I tried all four byte offsets and finally got a hit at +3.  I will mark this as Resolved.

p.s. I previously considered setting breakpoints on those four bytes individually but didn't explore it further when I didn't find a way to limit a breakpoint to a single byte.  (I had assumed a breakpoint for a word would not be catching a byte at the same address and offset, but it seems my assumption may be incorrect.)  Also, I previously tried fiddling with the masks but got this error.

![err](https://github.com/TASEmulators/BizHawk/assets/94894395/0f93273f-dba1-497b-9983-333c63fafb4c)
