### ISSUE TITLE
SegaCD: Dungeon Explorer broken in Bizhawk

### ISSUE THREAD

**Issue by Meerkov** [TASEmulators/BizHawk#3850]
### Summary
Works in Fusion 3.64
Broken in Bizhawk Genplus-GX

### Repro
1. start a new game
2. Walk north until you reach a dungeon
3. Die immediately
4. Continue game

### Output
All the sprites are broken, you can't attack, the game gets progressively more broken the more you play.

### Host env.
Bizhawk 2.9

[//]: # "(screenshots, if applicable)"

![image](https://github.com/TASEmulators/BizHawk/assets/8139496/06ae55de-55cf-459e-82d9-d20676271d70)

**Comment by YoshiRulz** [comment]
https://github.com/ekeeke/Genesis-Plus-GX/issues/40#issuecomment-71401540
