### ISSUE TITLE
Lua forms library: elements misplaced when only x is supplied

### ISSUE THREAD

**Issue by j-ac** [TASEmulators/BizHawk#3851]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
When using functions with optional x/y values in the Lua forms library (button(), checkbox() etc), supplying only x causes both x and y to revert to default (0). I feel this is a bug as any optional parameter should be omittable, and supplying only x has a usecase whenever the user wants an element along the top of the form. If this bug is a wontfix, this behavior should at least be documented.

### Repro
Any of the following commented API calls (and others) will reveal a misplaced element:
```lua
handle = forms.newform()

--forms.button(handle, "Click", nil, 50)
--forms.dropdown(handle, tbl, 40)
--forms.label(handle, "Label", 70)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1 x64. Win10 Pro

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
This *is* intentional, and it *should* be documented.

**Comment by YoshiRulz** [comment]
Resolved by https://github.com/TASEmulators/BizHawk/commit/170d1a62ed9fb495cf8a33c884aa3f6c1b797338. I will also be improving the documentation.

**Comment by YoshiRulz** [comment]
With ^ and preceding commits, I believe all errors are now flagged at run-time.

I ran out of steam halfway through rewriting the docs, but while they won't be in RC1, I promise they'll be in the release!
