### ISSUE TITLE
Paper Mario 64 SaveRAM from Mupen64Plus is completely incompitable with Ares64

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3873]
Played Paper Mario 64 with Mupen64Plus for and while, but when I used Ares64 the save file is gone. It is still present on Mupen64Plus (although it copies the save into every slot due to a core bug).

**Comment by CasualPokePlayer** [comment]
This is not anything resolvable. We don't neccessarily guarantee compatibility between cores for save files (other than "it usually works"). N64 is an odd case as the mupen core effectively makes its save file "all" save formats at the same time, while ares is more coarse with its save files, instead only creating a save file for the actual save format used.

**Comment by getCursorsExe** [comment]
Why this doesn't happen in other games then?

**Comment by YoshiRulz** [comment]
N64 carts can use at least 3 different kinds of persistent memory, that may be part of it.

**Comment by CasualPokePlayer** [comment]
The mupen save format has all save formats in the file, with eeprom being placed first. SM64 happens to use eeprom so it works by happenstance.
