### ISSUE TITLE
STROOP not working.

### ISSUE THREAD

**Issue by Wita5237** [TASEmulators/BizHawk#3874]
I find the provided ramwatch inadequate. I decided to use STROOP. Unfortunately, when I select emuhawk in the STROOP menu, emuhawk does not send any data and stroop thinks Mario is outside peach's Castle no matter where he really is.

**Comment by CasualPokePlayer** [comment]
Looking at STROOP, it looks like it uses some [hardcoded offset](https://github.com/SM64-TAS-ABC/STROOP/blob/295c79518050011d523928b418f76145acffeb38/STROOP/Config/Config.xml#L18) from the mupen64plus.dll file. This is subject to break any time the core gets recompiled (which was done in BizHawk 2.9, and has occurred again in the latest dev builds / 2.9.2).

This is ultimately just an issue with STROOP, not BizHawk. Go to their issue tracker.
