### ISSUE TITLE
Ares upscaling is present in upstream, but not BizHawk

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3876]
This is present in ares, but not BizHawk.
![image](https://github.com/TASEmulators/BizHawk/assets/39802077/374ffab5-c4e9-4d1f-aab1-fa1736b19582)

**Comment by CasualPokePlayer** [comment]
This is intentional with angrylion-rdp being used.

**Comment by getCursorsExe** [comment]
Too bad GLideN64 is not present.
