### ISSUE TITLE
Update Angrylion plugin to Angrylion-Plus for Ares64

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3882]
The last commit for the plugin is 8 years ago, meaning the plugin is discontinued. Since it is very old, it can cause problems with certain games.
There is a [thread regarding this](https://github.com/TASEmulators/BizHawk/issues/1872), but this was for Mupen64Plus, not Ares64.
Since Ares64 is waterboxed I don't mind if this gets rejected or not. I understand that waterbox doesn't allow more plugins to be added. This one is a plugin update, not a plugin addition to Ares64 (like [here](https://github.com/TASEmulators/BizHawk/issues/3877)).

**Comment by getCursorsExe** [comment]
If you have to reject this, it's okay.

**Comment by YoshiRulz** [comment]
If this is possible, it's the upstream project's concern, not ours.

**Comment by getCursorsExe** [comment]
I understand.

**Comment by CasualPokePlayer** [comment]
1. angrylion upstream was last updated on 2021
2. angrylion-plus offers effectively no actual accuracy improvements, it only offers speed through multithreading (which is not really possible with waterbox, also their multithreading decreases accuracy in some cases due to the way it's done).

**Comment by getCursorsExe** [comment]
Oh okay.

**Comment by getCursorsExe** [comment]
The core is waterboxed, but you still can make angrylion-plus singlethreaded.
