### ISSUE TITLE
Mi ni Ikuzo! Hedgehog on PlayStation breaks save states

### ISSUE THREAD

**Issue by noddy360** [TASEmulators/BizHawk#3884]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
The homebrew fan game Mi ni Ikuzo! Hedgehog for the PlayStation completely breaks save states. You're unable to load save states, as trying to load one crashes BizHawk. Using TAStudio also just throws you an error endlessly when trying to use the piano roll to go back to any previous frame. (Also the PS1 BIOS will be skipped although I'm not sure if that's normal or not.)

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open BizHawk and Open ROM.
2. Load "MINIC.exe". BizHawk will recognize it as a PlayStation game. (Keep in mind the Octoshock core will load the game. Trying to switch to Nymashock won't work for some reason as Octoshock will be forced for this game.)
3. Save a state, then try to reload it.
4. Additionally, try opening TAStudio. Then, by using the piano roll, try to go back a frame.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
Error when loading save state:
```
System.ArgumentOutOfRangeException: El índice estaba fuera del intervalo. Debe ser un valor no negativo e inferior al tamaño de la colección.
Nombre del parámetro: index
   en System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   en BizHawk.Emulation.Cores.Sony.PSX.Octoshock.PokeDisc()
   en BizHawk.Emulation.Cores.Sony.PSX.Octoshock.LoadStateBinary(BinaryReader reader)
   en BizHawk.Client.Common.ZipStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback, Boolean isZstdCompressed)
   en BizHawk.Client.Common.ZipStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`1 callback)
   en BizHawk.Client.Common.ZipStateLoader.GetCoreState(Action`1 callbackBinary, Action`1 callbackText)
   en BizHawk.Client.Common.SavestateFile.Load(String path, IDialogParent dialogParent)
   en BizHawk.Client.EmuHawk.MainForm.LoadState(String path, String userFriendlyStateName, Boolean suppressOSD)
   en BizHawk.Client.EmuHawk.MainForm.LoadQuickSave(Int32 slot, Boolean suppressOSD)
   en BizHawk.Client.EmuHawk.MainForm.<CheckHotkey>g__SelectAndLoadFromSlot|1037_1(Int32 slot)
   en BizHawk.Client.EmuHawk.MainForm.CheckHotkey(String trigger)
   en BizHawk.Client.EmuHawk.MainForm.<ProcessInput>b__143_0(Boolean current, String trigger)
   en System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   en BizHawk.Client.EmuHawk.MainForm.ProcessInput(InputCoalescer hotkeyCoalescer, ControllerInputCoalescer finalHostController, Func`2 searchHotkeyBindings, Func`2 activeControllerHasBinding)
   en BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   en BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1; Win10; Intel
- BizHawk dev build at 328d36d; Win10; Intel

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
Nymashock doesn't support .exe games currently (if anything I'd just close this on .exe game support in Nymashock, since Octoshock is effectively deprecated if anything)

**Comment by YoshiRulz** [comment]
Please try in a dev build; Nymashock can now load `.exe` roms.

**Comment by noddy360** [comment]
It works now. Thank you.
