### ISSUE TITLE
Change A7800Hawk's default peripherals to 2xProLine (from 2xJoystick)

### ISSUE THREAD

**Issue by rcividanes** [TASEmulators/BizHawk#3895]
The control configuration for Atari 7800 emulator only have a one button.
It's necessary to include more one button. 
The original Atari 7800 control had two buttons

A new information.
I make some tentatives for configure the second button. In determinate moment I used a virtual control and press button power. In sequence I access the control configuration again and all buttons form Atari 7800 control appear.

**Comment by YoshiRulz** [comment]
Set `A7800` > `Controller Settings` > `Port 1` to "ProLine Controller".

**Comment by rcividanes** [comment]
Yes, ProLine is default, but, it's don't work in the first run.
I run EmuHawk and run the ROM and I configurated the control (only one button was available for config) .
So, I open another ROM for 7800 and I change default control for ProLine again. Don't work. 
I try so many times and, magical, it's work. But, sincerely I don't know how.

**Comment by YoshiRulz** [comment]
After closing the settings dialog, your changes won't take effect until you load a rom (or reload the current rom). There's a reminder which appears in the main window, but it goes away after only a few seconds.
