### ISSUE TITLE
Wire up Game Gear, Master System, and SG-1000 support in Genplus-gx

### ISSUE THREAD

**Issue by SergioMartin86** [TASEmulators/BizHawk#3896]
The benefit of this would be having an additional, well tested core (GPGX) for these two systems.

The core is being implemented already #3889.  We'd only need to add BK core changes to direct GG, SG1000, SMS games to it.

**Comment by nattthebear** [comment]
Does anyone remember why we didn't do this the first time around?  I think there was some objection.

**Comment by SergioMartin86** [comment]
Will proceed with this into a new PR. Any pointers/clues as to what files I should be looking into to add this core as target for SMS/GG?

**Comment by YoshiRulz** [comment]
https://github.com/TASEmulators/BizHawk/blob/5cb1fe00423a7fe4997596bf0f3ccd6e0668ec19/src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGX.cs#L18
https://github.com/TASEmulators/BizHawk/blob/5cb1fe00423a7fe4997596bf0f3ccd6e0668ec19/src/BizHawk.Client.Common/config/Config.cs#L25

**Comment by CasualPokePlayer** [comment]
(sort of a dupe of https://github.com/TASEmulators/BizHawk/issues/3214)
