### ISSUE TITLE
Marker changes to branches can save even when the branch itself isn't saved

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#3899]
I think this is a bind markers to input-specific issues, since markers only associate with specific branches when that option is checked (otherwise markers are global and independent of the currently loaded branch).

I'm actually rather surprised this bug wasn't noticed before. I've noticed related marker change anomalies for a while, but finally spent a few minutes and traced the root cause today.

### Repro
1) Open a game and then TAStudio
2) Place a marker at frame 10
3) Add a branch 'A'
4) Add a branch 'B'
5) Select a frame before the marker and press `Insert` (or equivalent hotkey) 10 times to move the marker. Don't press update branch.
5a) *Alternatively*, alt-click drag to move the marker to frame 20.
5b) Note: the issue only reproduces with insert/deletes, not `Ctrl+Insert` cloning.
6) Load branch 'A'
7) Load branch 'B'. Note how the marker is at frame 20, even though the marker change shouldn't have been saved.

### Expected behavior
Any marker changes to a branch only save when `Update Branch` is pressed (i.e., when the branch itself is saved).

### Host env.
- BizHawk 2.9.1
- BizHawk 1ff7d545
  - (most recent commit at time of writing)

**Comment by Morilli** [comment]
TIL markers are unique per branch when that option is checked...
