### ISSUE TITLE
[genesisplusgx] "VDP mode" option (for eliminate region lockups / megakey behavior)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASEmulators/BizHawk#3917]
Hello, bizhawk-devs!
Can you add "VDP mode" option to genesisplusgx settings please? 
This option is already implemented in ekeeke's Wii/Gamecube genplusgx port and the libretro port also.

Information:
https://github.com/ekeeke/Genesis-Plus-GX/issues/558
https://github.com/libretro/Genesis-Plus-GX/issues/349

There are many of good NTSC games that haven't been released for the PAL region,
and now it works very good on PAL mode using this genplusgx feature (or using megakey, if we're talking about hardware)
Also, some of NTSC games have slightly different behavior compared to their European releases, so this feature could be useful.

**Comment by YoshiRulz** [comment]
`config.region_detect` is already exposed (as "Autodetect Region", bit of a misnomer), `config.vdp_mode` is currently hardcoded (and was before the update):
https://github.com/TASEmulators/BizHawk/blob/0122dec0993e871fe0c81077cd81b60034267a05/waterbox/gpgx/cinterface/cinterface.c#L921

**Comment by eugene-s-nesdev** [comment]
Autodetect region - is correct, it will prevent region lockups.
Ekeeke / libretro devs have added an additional option to force VDP mode (0 = auto, 1 = 60Hz, 2 = 50Hz)
and user can set it regardless to region detect.
