### ISSUE TITLE
[GPGX] SMS Paddle games don't load and use SMSHawk instead

### ISSUE THREAD

**Issue by Sonia-7** [TASEmulators/BizHawk#3919]
The following games have the Paddle controller as mandatory:

-BMX Trial: Alex Kidd
-Galactic Protector
-Megumi Rescue
-Woody Pop: Shinjinrui no Block Kuzugi

If you load any of them with the GPGX core, they don't run there and the emulator sends you to SMSHawk.

**Comment by Morilli** [comment]
Does everything work as expected with 3bab84445c9f30d5e43d94bf6fc932530c545118?

**Comment by Sonia-7** [comment]
Yes. Thank you Morilli!
