### ISSUE TITLE
[Core Port Req.] Ares's MD core

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3922]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for duplicate core requests, both on the issue tracker and on this Wiki page: https://github.com/TASEmulators/BizHawk/wiki/Core-Requests"

### Upstream info
- Target platforms: Windows
- [Source repo](https://github.com/ares-emulator/ares)
- Language(s): C++

### Merits
Slightly slower but more stable than Genplus-gx. Has support for CD 32x unlike PicoDrive.

### Technical details
[//]: # "Non-exhaustive list of things to consider:"
- (able to build .dll/.so for P/Invoke?) I think yes
- (frontend/backend separation--for example, can backend be built without SDL?) I don't know
- (can force single-threaded?) most likely yes
- (has I/O abstraction accepting byte array, or only accepts file paths? for disc-based consoles, can swap out implementation for BizHawk's?) haven't tested yet
- (savestate quality) perfect, SRAM also saved

This core has inaccurate audio, Nuked driver is most likely needed.

**Comment by vadosnaprimer** [comment]
What does "more stable than Genplus-gx" mean?

**Comment by getCursorsExe** [comment]
remember this? #1760

**Comment by YoshiRulz** [comment]
Is that still occurring after the GPGX update?

**Comment by CasualPokePlayer** [comment]
Even before the GPGX update it wouldn't have occurred, it would have been fixed since https://github.com/TASEmulators/BizHawk/commit/25bdeb7f69ed7089cc74762ab98a7eb8d7c9aa5b

**Comment by getCursorsExe** [comment]
> Besides that this claim just can't be done without some deep examination of the code

Lock this thread right now.

**Comment by getCursorsExe** [comment]
This means that I have made a bad mistake now.

**Comment by nattthebear** [comment]
For clarity, I want to emphasize that https://github.com/TASEmulators/BizHawk/issues/1760 is a complete unrecoverable crash on real hardware.
