### ISSUE TITLE
tastudio suggests to save tasproj changes on every bk2 import

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#3933]
You load bk2 into bizhawk, open tastudio, it first asks you if you want to save the bk2, then after you answer it instantly asks you again if you want to save changes but this time using a tastudio dialog, even tho there are no changes.

**Comment by Morilli** [comment]
Does this happen on the current dev version or just 2.9.1? Because I tested and can't reproduce on current master.

**Comment by vadosnaprimer** [comment]
Forgot to check.
