### ISSUE TITLE
TIC-80 mouse inputs not working as expected

### ISSUE THREAD

**Issue by Randomno** [TASEmulators/BizHawk#3938]
The mouse X and Y coordinates end up like this:

![image](https://github.com/TASEmulators/BizHawk/assets/17330834/d4cc6e1f-ed1c-491e-9822-f6ecc84fb2ee)

Some of the buttons are also mapped wrong, for example Relative Mouse Toggle in BizHawk is actually left mouse click, and Mouse Scroll Y is right mouse click.

**Comment by Randomno** [comment]
[coords.zip](https://github.com/user-attachments/files/15572026/coords.zip)

2 TIC-80 programs to test this if necessary

**Comment by Randomno** [comment]
Thanks, this makes the mouse a lot more usable.

There still seem to be some issues with relative mouse, but I'm not sure what exactly. Trying to play [Portal 3D](https://tic80.com/play?cart=3538), the menu options aren't highlighted correctly. In-game, to play as intended you have to hold down the toggle hotkey the entire time.

So it's probably functional enough to make a TAS, just not very friendly for normal play.

**Comment by CasualPokePlayer** [comment]
From what I can tell the "toggle" in TIC80 code is only present when it's actually set. It might be that the frontend is supposed to implement the stickiness of the toggle here itself.

**Comment by Randomno** [comment]
Tbh I don't understand why this is even a hotkey, seems like the game should be controlling the mouse mode rather than the emulator. But I don't understand most of this anyway.

https://github.com/nesbox/TIC-80/issues/986#issuecomment-880728685

With this code, pressing A swaps to relative mode. Coords are 0,0 when mouse is stationary.

**Comment by CasualPokePlayer** [comment]
Seems like the toggle is intended as a flag to the game that the mouse are relative coordinates rather than absolute coordinates, and is more a frontend detail if anything. It might make more sense to actually have this as a sync setting perhaps.

**Comment by CasualPokePlayer** [comment]
Actually, nevermind, I read more of the code, it seems like it is indeed a flag by the game whether it wants relative or absolute inputs, and the frontend should be respecting that.

**Comment by CasualPokePlayer** [comment]
Latest commits should hopefully make mouse input correct.
