### ISSUE TITLE
Am I missing something? Can't run devbuild 2c6129fb

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#3939]
From 2.9.1 stable to 2c6129fb dev, first time I run it, config file corrupted then deleted it. Later it won't pop up anymore, am I missing something? Windows 10 1809 64-bit.

**Comment by Morilli** [comment]
It sounds like you overwrote your existing installation with the dev version. Please extract the bizhawk dev version into a separate folder and try launching it again.

**Comment by Morilli** [comment]
I'm going to close this due to inactivity. Please report back if you still have issues.

**Comment by Yave-Yu** [comment]
Uh I almost forget this😂… So now I downloaded 90c79d22 then create an empty folder and put BizHawk in, but still can't open, EmuHawk.exe just stay a short while (using Task Manager to see) then disappear for no reason.

**Comment by Morilli** [comment]
Do you see any error message at all? If not, is there any error message related to `EmuHawk.exe` in windows' event viewer (under windows protocols -> application)?

Another thing you could try is download a debug build [from Gitlab](https://gitlab.com/TASVideos/BizHawk/-/jobs/7131684156) ([directlink](https://gitlab.com/TASVideos/BizHawk/-/jobs/7131684156/artifacts/download)), open the folder in powershell (shift-rightclick the background in the explorer window and select `open in powershell`) and then run `./EmuHawk.exe` in that command window. There could be additional information in the console output.

**Comment by Yave-Yu** [comment]
Ran this debug build in PowerShell, looks like somehow D3D11 error.
![20240619185313](https://github.com/TASEmulators/BizHawk/assets/54294476/77024f0d-8c6c-4050-a504-e2faf1328771)

**Comment by Morilli** [comment]
Yeah this is something in the new D3D11 code failing when querying information about Direct3D<->OpenGL interop methods.

Could you tell me what graphics card / cpu you're using? Also, are your drivers up-to-date?

@CasualPokePlayer any other ideas?

**Comment by CasualPokePlayer** [comment]
That seems like some kind of bug within the driver itself, which is extremely strange.

Does the machine have multiple GPUs? If so, could you check if force enabling the dedicated GPU in Windows settings ends up changing anything?

**Comment by Yave-Yu** [comment]
i7-4170HQ's HD4600, driver is not up-to-date for stable reason, my laptop has GTX850M (GPU only) but I not enable it to render BizHawk by default.

**Comment by CasualPokePlayer** [comment]
Could you try to force it to use the GTX850M and see if it still crashes or not? If it doesn't, it sounds like BizHawk just needs to try to check if the OpenGL GPU is the same as the D3D11 GPU.

**Comment by Yave-Yu** [comment]
Try using GTX850M to render it works.
![QQ20240620085820](https://github.com/TASEmulators/BizHawk/assets/54294476/3633ea11-d834-4dae-95a3-4dd2e3f10f59)

**Comment by CasualPokePlayer** [comment]
Then my theory is right, the OpenGL driver was using the Intel iGPU and D3D11 was just using the GTX850M instead, and the extension ended up crashing due to not gracefully handling the difference (thanks Intel).

Shouldn't be too hard to fix per se, just need to try to avoid using the extension if we detect the GPUs between the APIs are different.
