### ISSUE TITLE
Keyboard and controller don´t work

### ISSUE THREAD

**Issue by virto7** [TASEmulators/BizHawk#3943]
Hi, yestarday I downloaded the lastest version of bizhawk to play Super Mario World, I played for a few hours, then, I closed the emulator and turn off the PC. Today, turned on the PC and opened de emulator, the keyboard and the controller don´t respond, I tried everythink, but nothing worked. Apparently, the first time I close the emulator and open again after the download, the keyboard and the controller don´t work. I don´t now if I´m doing something wrong.

Sorry for my bad english.

**Comment by YoshiRulz** [comment]
I take it you figured out what was wrong then?

**Comment by virto7** [comment]
I'm just dumb, I forgot to install some of prerequisites, sorry for the incovenience
