### ISSUE TITLE
Don't send email if CI job got canceled by a new commit

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#3944]
Some jobs take a while, and getting an email or 2 every single time you haven't waited it out is very annoying.

Emailing on build failure is fine, tho if they can't be tweaked independently I'd better not get an email at all.

**Comment by YoshiRulz** [comment]
I'm not getting any emails for failed workflows, only in-app notifications.

**Comment by vadosnaprimer** [comment]
I disabled the CI failure report in the settings, which, being the second clause in my post, is fine.
