### ISSUE TITLE
Add github artifacts link to readme

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#3945]

**Comment by YoshiRulz** [comment]
Per https://github.com/TASEmulators/BizHawk/issues/3934#issuecomment-2145868097 you need to be logged-in to access them.

**Comment by vadosnaprimer** [comment]
Fixed by https://github.com/TASEmulators/BizHawk/commit/70e118b93fed686c3965b48c3f48f087970143d5
