### ISSUE TITLE
Support drag'n'drop in multidisk bundler

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#3950]
The most important aspect is dropping several ROM files onto the dialog, so it would add them to the existing fields and create the needed amount of extra fields so all files fit.

Ability to also sort the fields would be nice but not critical, and I can make a separate issue for it.

If an xml file is dropped, it'd be nice to import it but also not critical. If an xml file is dropped along with a bunch of other files, we have to prefer the xml file, or just give an error maybe. Also error if another xml is already loaded? Not critical anyway.

**Comment by Morilli** [comment]
You should already be able to drag-and-drop files into the textboxes to fill them. You can't actually import more than 1 rom at a time this way, but then there's the consideration of order. Is there actually a scenario where dropping many (>5 or so) roms at once is wanted?

**Comment by YoshiRulz** [comment]
MAME.

**Comment by vadosnaprimer** [comment]
And Amiga. A lot of games come on multiple disks.

**Comment by Morilli** [comment]
Have done a basic implementation, let me know if there's something that could be improved in it.
