### ISSUE TITLE
Jeopardy for Sega CD causes crash to desktop

### ISSUE THREAD

**Issue by Meerkov** [TASEmulators/BizHawk#3955]
To reproduce, just startup Jeopardy! for the segaCD. After approximately 2164 frames, the entire emulator will crash to desktop.

Expected behavior:
Gens core does not crash (verified Upstream in RetroArch).
Emulator itself doesn't crash (the entire emulator crashing to desktop is pretty bad, there probably should be an exception handler for whatever issue went wrong).

**Comment by YoshiRulz** [comment]
Which version are you using? What format is your rom in? If it's `.cue`+`.bin`, please copy the `.cue`'s contents here.

**Comment by Meerkov** [comment]
2.9.1 release.
```
FILE "Jeopardy! (USA) (Track 1).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "Jeopardy! (USA) (Track 2).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Jeopardy! (USA) (Track 3).bin" BINARY
  TRACK 03 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00

```

**Comment by Morilli** [comment]
GPGX was updated recently, could you try a recent dev build and see if this has been fixed?

**Comment by Meerkov** [comment]
SegaCD, not genesis.

**Comment by YoshiRulz** [comment]
As Morilli said, the core *has* been updated in dev builds. Though Spike seems to have the game working in the last release (ignore the sysID, look at the disc light; that is the FMV variant).

**Comment by CasualPokePlayer** [comment]
> I am curious about an app crash from loading a rom. Failed loads should present as an exception dialog, as you mentioned.

Unmanaged cores doing something bad to cause a crash would generally just crash the application entirely, as that is unmanaged code, you can't just catch that C# side. Even the less questionable third party cores can still have issues for particularly strange ROMs/BIOSs.
