### ISSUE TITLE
arrow keys ,  z ,  and x keys are not registering

### ISSUE THREAD

**Issue by brvsket** [TASEmulators/BizHawk#3958]
### Summary
pressing these keys dont do anything when i try to use them ingame .  keys still work if you hold shift ,  though this forces them to hold down ,  which means you can pretty much only press them once .

### Repro
go onto GBA game
set controls to:
up - up
left - left
down - down
right - right
enter - start
select - shift
Z - A
X - B

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1 : Win10 Home; AMD/NVIDIA

**Comment by YoshiRulz** [comment]
Did you figure out why it wasn't working?
