### ISSUE TITLE
Firmware UX improvements, mainly re: status

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3974]
- ~~The invariant of ["exactly 1 Ideal option per record"](https://github.com/TASEmulators/BizHawk/blob/8fda95066cff5bcf15df72dd112bd1c324b553b4/src/BizHawk.Client.EmuHawk/config/FirmwaresConfig.cs#L39) is currently broken, both by records with multiple Ideal options, and I think by a couple records with none.~~ This restriction on humans has been lifted and the documentation changed to match the existing behaviour.
- [x] The autodetect code (in `FirmwareManager` IIRC) chooses the *first record* which can be resolved to a file. But that means, if you had both an Ideal and an Acceptable firmware in your firmware dir, it might use the Acceptable one. This could be fixed by ensuring the options list is sorted by status.
- ~~A review of which firmwares work and which don't might be warranted, but once you start testing games, there's no obvious cut-off point. The requirements could grow indefinitely. So maybe just... have TASVideos judges read them over?~~ judges apparently not interested
- #3493

**Comment by Morilli** [comment]
> The invariant of ["exactly 1 Ideal option per record"](https://github.com/TASEmulators/BizHawk/blob/8fda95066cff5bcf15df72dd112bd1c324b553b4/src/BizHawk.Client.EmuHawk/config/FirmwaresConfig.cs#L39) is currently broken

Looking at e18a349, it feels like setting all to ideal makes sense, so maybe this invariant doesn't need to exist?
In any case, unit tests could work nicely to enforce the first two points.

**Comment by YoshiRulz** [comment]
Yes, I forgot to mention these aren't covered by the existing unit tests, hence they've been neglected.

**Comment by vadosnaprimer** [comment]
> So maybe just... have TASVideos judges read them over?

What do you mean?

**Comment by YoshiRulz** [comment]
>> So maybe just... have TASVideos judges read them over?
>
> What do you mean?

Asking people from the TASing community with extensive knowledge of a particular console, such as judges, to confirm that we've made the best choices. (Which I believe is how the FW database was populated in the first place.)

> I think we need different icons, because the current ones are too cryptic. [...] a star from SMW.

I'm sympathetic to this, but we only "just" got them working properly in https://github.com/TASEmulators/BizHawk/commit/1026503d9241203987dc695a01e4907dcaaffb1f (2.9).
If you do change them, please use only Public Domain images—see also [my personal notes #36](https://gitlab.com/YoshiRulz/yoshis-hawk-thoughts/-/issues/36).

> Also I don't see the benefit of only allowing 1 to be ideal.

It would help reduce the diversity of setups. (A boon for judges?) Unfortunately, these bugs prevent that.

**Comment by vadosnaprimer** [comment]
> Asking people from the TASing community with extensive knowledge of a particular console, such as judges, to confirm that we've made the best choices. (Which I believe is how the FW database was populated in the first place.)

People who added the cores had the most knowledge about firmwares. I don't think judges were involved at any point in any way.

> I'm sympathetic to this, but we only "just" got them working properly in https://github.com/TASEmulators/BizHawk/commit/1026503d9241203987dc695a01e4907dcaaffb1f (2.9).

"Properly" is a subjective assessment, and I don't remember anyone for whom the current icons were immediately perfectly clear. Also 2.9 was just last year, I don't think everyone accustomed to them once and for all.

> It would help reduce the diversity of setups. (A boon for judges?)

Has this been discussed with them, to determine it's the problem they're having? Since hawk auto selects the needed firmware given the path, all judges look at is whether it's an acceptable BIOS for a given machine, which hawk indicates.

**Comment by CasualPokePlayer** [comment]
Ideal should generally be what's ideal to the core. The ideal choices for PSX for example would the v3.0 images, as that's what mednafen was designed with. This would have nothing involving TASVideos judges.

For the example SGB records, iirc I did that under the assumption that "all of them are equally ideal" and by logic assigning multiple ideal tags (although that was long ago so idk)

**Comment by Morilli** [comment]
Can we consider this resolved now or does anyone disagree with the changes made? Namely that ideal does NOT need to exist exactly once and that the firmware manager will now prefer ideal over acceptable firmware in case both are available?

**Comment by vadosnaprimer** [comment]
I guess so.

**Comment by YoshiRulz** [comment]
Leaving this open as a reminder to double-check firmwares' statuses, but the part I wanted to get resolved for 2.10 now has been, thank you.

**Comment by vadosnaprimer** [comment]
How do we double-check them?

**Comment by YoshiRulz** [comment]
In a semi-automated way, by comparing against others' lists.

In a manual way, by having someone review the firmware's variants/history and sort them into the same status "buckets" we use.

I think it's more important that we downgrade unusable options which are incorrectly marked as good than vice-versa.

**Comment by vadosnaprimer** [comment]
> In a semi-automated way, by comparing against others' lists.

Comparing what, to what lists, and on what matter?

> In a manual way, by having someone review the firmware's variants/history and sort them into the same status "buckets" we use.

Sort them where? Who wants to do it? And most importantly, who needs it and for what?

> I think it's more important that we downgrade unusable options which are incorrectly marked as good than vice-versa.

How many do you know of? I'm not convinced they exist.

> The requirements could grow indefinitely. So maybe just... have TASVideos judges read them over?

Denied. Nobody knows the benefit of this, the insane amount of work it requires, and nobody has the time on this.

All in all, this is completely pointless and should be closed.
