### ISSUE TITLE
GB: Default settings don't properly save the boot ROM in movie settings

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#3980]
Follow-up to #3763

Basically, the boot ROM's info is not properly saved into the movie. Instead, BizHawk silently seems to ~~choose an arbitrary boot ROM if one is available~~ infer the boot ROM from the GB mode sync settings(?). This leads to movies where the sync settings don't properly indicate the firmware hash and don't have `"EnableBIOS":true` even though the boot intro plays.

Expected behavior: BizHawk saves a specific firmware hash in the movie and sets `"EnableBIOS":true` in the sync settings.

**Comment by RetroEdit** [comment]
Gambatte and probably exclusive to 2.9.2 judging by how the previous issue was resolved -- I didn't test GBHawk, so maybe it also has the issue?

**Comment by CasualPokePlayer** [comment]
What did you expect exactly? A GB bootrom to play when in GBC mode? a GBC bootrom to play in GB mode? A GBA bootrom to play in GBC mode? A GBC bootrom to play in GBA mode? These are all nonsense. There's 1 firmware slot in the firmware config for each mode, and regardless, the firmware hash used in the movie is stored in the movie (this is implemented in a core agnostic manner, stored in the movie header).

**Comment by RetroEdit** [comment]
The hash is not stored in the movie header with default settings. Conceivably if there's only one firmware allowed for each mode, enough info is technically available, but the hash is not saved. Check it yourself.

**Comment by YoshiRulz** [comment]
The checksum should be stored, even if there's only 1 option for that record.

**Comment by CasualPokePlayer** [comment]
If it's not being stored, that should end up affecting every single core using firmware, not just GB.

**Comment by YoshiRulz** [comment]
I tried inserting `_syncSettings.EnableBIOS = useBios;` here:
https://github.com/TASEmulators/BizHawk/blob/9f5a5d8593415a0e703e23037da2f6aa6a3d6cf5/src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.cs#L137-L138
...but, while that works at runtime, the sync settings must already be written to disk or at least cloned by that point, because it's still `"EnableBIOS":false`. Which to me indicates a deeper problem in the movie system.

**Comment by YoshiRulz** [comment]
`FirmwareManager.RecentlyServed` is read in `PopulateWithDefaultHeaderValues`, which is before the core is initialised.

**Comment by CasualPokePlayer** [comment]
MovieConversionExtensions.PopulateWithDefaultHeaderValues called before initing the core itself sounds like a severe bug.

**Comment by Morilli** [comment]
> MovieConversionExtensions.PopulateWithDefaultHeaderValues called before initing the core itself sounds like a severe bug, and likely has other issues besides the firmware issue...

It looks like a bug like this was bound to happen: It is required to have a core loaded before starting a movie [record/playback], but the core is also thrown out and re-inited. So the code basically expects the core to already be in a perfectly correct state, uses that state, and then throws the core out and gets a new one for the movie.

Ideally you would not need to have a core loaded when starting a movie [record/playback] at all. After all, you're going to get a new one anyway. Maybe allowing this would make the logic and its flaws clearer. At least play movie *should* be perfectly usable without a loaded core.

**Comment by Morilli** [comment]
Hm, I have some changes prepared but they don't quite work. No part of the movie playing/starting/queueing flow actually knows whether you're creating a new movie or loading an existing one. Only the callsites know, but that information isn't passed on anywhere...
