### ISSUE TITLE
HQ2X does nothing when using BSNES 115 cores

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#3990]
HQ2X does nothing when using BSNES 115 cores

**Comment by YoshiRulz** [comment]
Works for me in 2.9.1.

**Comment by Irata-sys** [comment]
> Works for me in 2.9.1.

Works for me too in 2.9.1.

not in latest dev build. Sorry should of been more specific.

**Comment by YoshiRulz** [comment]
Works on beee1eb82065cf0d840b65de8fcc84ded73a6d58. Can you copy the exact version from `Help` > `About`? What OS do you have? Is it working with other cores? (I wouldn't have to ask these questions if you'd filled out the issue template.)

**Comment by CasualPokePlayer** [comment]
Specifically that core? Are you sure it's not some general issue that affects all cores? These shaders shouldn't have core specific behavior.

Also, what GPU do you have?
