### ISSUE TITLE
Add a hotkey for "Clone # Times" in the TAStudio tab

### ISSUE THREAD

**Issue by Pixiuchu** [TASEmulators/BizHawk#3992]
#2242 was implemented four years ago, however currently the only way to access this feature is by right clicking in TAStudio and clicking the "Clone # Times" option. There is a hotkey for "Clone Frames" in the TAStudio hotkey tab, but nothing for "Clone # Times". Although there is a "Insert # Frames" hotkey. This would be great for efficiency in some cases if it were added.

**Comment by Morilli** [comment]
Looking at the current default bindings, would anyone be opposed to changing `Insert # of Frames` to `Shift+Insert` by default and making the `Clone # Times` keybinding `Ctrl+Shift+Insert`?
![image](https://github.com/user-attachments/assets/1fff374c-417f-4f67-a587-603936c28ca3)

**Comment by vadosnaprimer** [comment]
Why change, instead of adding `Shift+Insert` for `Clone # Times`?

**Comment by Morilli** [comment]
It just feel more logical to me to add `Shift` for the `# times` variant.

**Comment by vadosnaprimer** [comment]
Ah! Clone is Ctrl+Insert, and Clone # times is just a variant of that, so the hotkey for it should just be a variant of Ctrl+Insert. Makes sense!

And Insert # of frames is not a variant of Clone, but a variant of Insert, so it makes sense to only make its hotkey different from  Insert hotkey by one extra key.
