### ISSUE TITLE
Menu “Backwards”

### ISSUE THREAD

**Issue by WeirdOddWodd** [TASEmulators/BizHawk#4003]
There looks to be a minor bug with BizHawk 2.9.1 wherein the menu system navigation (particularly, the topmost level [![image](https://github.com/user-attachments/assets/a8db6813-4642-49b5-bbf5-12f739c9d60b)]) is “backwards.” To produce this, do the following:
1. Open BizHawk in windowed mode.
2. Press Alt—the focus should now shift to the menu system. (If, for some reason, it doesn’t, then press, for example, Alt-F to open the File menu, but close the menu). Using the mouse to open it also produces the behavior.
3. Press the left arrow key. You should see the menu navigate to the right instead of the left.

**Comment by Morilli** [comment]
I can't reproduce this on either 2.9.1 or the current dev build. Do you have some sort of unusual keyboard layout? In any case try a [current dev build](https://nightly.link/TASEmulators/BizHawk/workflows/ci/master/BizHawk-dev-windows.zip) to see if your problem is still present there.

**Comment by WeirdOddWodd** [comment]
Thank you for the message, Mortiz. I will have to do some more research on the behavior. I found that even build 2.3 exhibited the behavior. I am not sure what would cause it, though. I tested some other applications on my computer and observed the behavior only in BizHawk, which is why I suspected that it was bugged. However, the fact that you are unable to produce the behavior and the fact that it occurred in a much older build suggests that the problem is probably not related to BizHawk. I generally run BizHawk in windowed-full screen mode and have it set to go to this mode upon startup. So, I hadn’t observed that behavior before (or had forgotten about it, if I had observed it).

**Comment by Asnivor** [comment]
Might be this? https://stackoverflow.com/a/16306598

Related to Windows RightAlignedMenu settings.

**Comment by WeirdOddWodd** [comment]
That might be the cause. I can confirm that changing the dominant writing hand in Windows settings from right to left affects BizHawk’s menu navigation direction via keyboard arrow keys. However, since I primarily play on a desktop computer and don’t have screens with pen input, I cannot change the writing setting.
