### ISSUE TITLE
Is PlayStation 2 (DobieStation) supported?.

### ISSUE THREAD

**Issue by ElektroStudios** [TASEmulators/BizHawk#4013]
Excuse me, because this is a doubt instead of a core request:

Is PlayStation 2 (DobieStation) supported?.

I've investigated a little bit through the issues section and seen that PCSX2 can't be implemented, however [this issue ](https://github.com/TASEmulators/BizHawk/issues/2250) from year 2020 clearly states the intention to implement DobieStation:

> Closing because I got the information I needed to make my decision: I proceeded with the project and added DobieStation to Bizhawk.

However, when I try to load a PS2's disc image in BIN format in emuhawk.exe, this dialog window is shown:

![WinSnap 03](https://github.com/user-attachments/assets/b2cd89de-09f1-4472-8fd4-3bde4d0459dc)

But PlayStation 2 is not listed in that window.

And if I try to load the cue-sheet file (*.cue) of the BIN image, or another PS2 image in ISO format, I get this error telling that a core (a PS2 emulator core?) accepted the rom:

![WinSnap 04](https://github.com/user-attachments/assets/7afd535c-82ae-4a3d-ada3-501c35a56501)

All this is causing me much confusion due the affirmation in the linked issue above, that is why I'm asking if PlayStation 2 (DobieStation) is supported or it is not.

Please don't take this as a feature request, it is just a doubt and I didn't found a better place to ask for it.

Thanks in advance!.

**Comment by CasualPokePlayer** [comment]
FYI, the error is misleading you, no core actually accepted the rom, as it is throwing earlier than that point. Rather it's telling you the .cue file is malformed and is referencing a file that does not exist.
