### ISSUE TITLE
Add forms.resizeComponent() or forms.deleteComponent() to FormsLuaLibrary.cs file

### ISSUE THREAD

**Issue by KonkeyDong** [TASEmulators/BizHawk#4014]
I was writing a [minimap display for a Gameboy game](https://github.com/KonkeyDong/bizhawk_lua_scripts/tree/main/Gameboy_and_Gameboy_Color/Zelda_Links_Awakening_DX/minimap_display) and realized that there wasn't any way to **resize form components** such as a `pictureBox`. I was glancing at the code and noticed that there is a [forms.setsize() method defined](https://github.com/TASEmulators/BizHawk/blob/8c9587e00bb34d0c08b0104eee209bb23405cec4/src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/FormsLuaLibrary.cs#L1405) for resizing the entire form, but none for resizing any of the components.

Because of this, I have no way to resize a form for scaling reasons once I call `forms.pictureBox()` on a form. I would think that the method signature would be something like:

```lua
local component_handler = forms.resizeComponent(componentHandle, width, height)
```

I think this would be a simple yet handy feature to have as it would allow for more dynamic forms for display purposes. Thoughts?

**Comment by CasualPokePlayer** [comment]
I'm fairly sure forms.setsize() would in fact work for individual components? There even seems to be specific support for the [pictureBox](https://github.com/TASEmulators/BizHawk/blob/8c9587e00bb34d0c08b0104eee209bb23405cec4/src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/FormsLuaLibrary.cs#L46).

**Comment by YoshiRulz** [comment]
^ And if that wasn't available, you could have used `forms.setproperty`.

**Comment by KonkeyDong** [comment]
Thanks!

I didn't see where in the [Lua Functions](https://tasvideos.org/Bizhawk/LuaFunctions) page what **string values** could be used for the `forms.setproperty()`. I'll provide a list that I was able to find for anyone else that may have stumbled a similar problem while consulting Google:

* `"Text"`: The text displayed by the control.
* `"BackColor"`: The background color.
* `"ForeColor"`: The text color.
* `"Width"`: The width of the control.
* `"Height"`: The height of the control.
* `"Left"`: The X coordinate of the control.
* `"Top"`: The Y coordinate of the control. 

## Important Notes:
* The exact properties you can modify depend on the type of control. For example, a `TextBox` has a `Text` property, while a `PictureBox` might not.
* If you try to set a property that doesn't exist or is incompatible with the control, you might encounter an error.
