### ISSUE TITLE
When Dumping Create a Warning if/when Closing the Program.

### ISSUE THREAD

**Issue by Spikestuff** [TASEmulators/BizHawk#4017]
Basically a failsafe I guess.

So as written in the title.
Just have a pop out window reminding the user that they're currently dumping and if they are sure to suspend the program.

Probably also create this instance in basic movie recording as well (since TAStudio has this warning about unsaved work).

**Comment by YoshiRulz** [comment]
It was already calling `MovieSession.StopMovie(saveChanges: true)`, though unconditionally.
