### ISSUE TITLE
AMD 780M can't open BizHawk latest dev

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#4030]
Windows 10 22H2 64-bit
Direct3D11 exception
![f6e734cb-ded8-4ad2-bfe3-ec384c894a44](https://github.com/user-attachments/assets/adada851-66bc-4cfe-a0ef-71410a3b9b55)

**Comment by YoshiRulz** [comment]
Does this prevent you from using EmuHawk, or does it just switch to the fallback method? If you can still use EmuHawk, please go to `Help` > `About...` and copy the info in the bottom-left.

**Comment by CasualPokePlayer** [comment]
It looks like the SDL2 dll is outright missing (which would also prevent OpenGL from working), which is indicating it wasn't installed correctly.

**Comment by YoshiRulz** [comment]
Did CPP guess right then?

**Comment by Yave-Yu** [comment]
No problem, I redownload BizHawk and extract then it works.
