### ISSUE TITLE
Quickernes dll location windows… rc.

### ISSUE THREAD

**Issue by 007-beep** [TASEmulators/BizHawk#4038]
The rc tells ppl to put the quickernes dll in system folder. This suggestion can work… pointless. Just put in same dir as emuhawk… it will work. Windows will always find the dll if its in the same dir as executable and your not littering the system folder later….

**Comment by YoshiRulz** [comment]
The note does not say to put it in your `System` folder. Don't do that.

**Comment by CasualPokePlayer** [comment]
> You should be able to drop this copy into the dll folder.

![image](https://github.com/user-attachments/assets/f811303b-245f-43f6-aff8-46fbe47193d7)
