### ISSUE TITLE
"New watch" window layout

### ISSUE THREAD

**Issue by shenef** [TASEmulators/BizHawk#4046]
### Summary
At least for GBA, the Memory Domain field has an impact on the size of the Address field:
![image](https://github.com/user-attachments/assets/23ec41eb-738f-4e8b-bcee-691541f94d6a) ![image](https://github.com/user-attachments/assets/df1535b9-ad70-46ff-ad9f-10d8abda61a5)

So, currently we often have to first navigate down to the Domain selection and then back up to the Address.
I'm not sure how this would affect other platforms but it seems to make more sense to pull the Memory Domain field up, above the Address field.

Besides, the sizing and positions of the fields in this window generally seem a bit odd.
Quick and rough mockup where the elements are a bit better sized and aligned:
![image](https://github.com/user-attachments/assets/580db0b1-ab76-4c6e-8c02-e5e727ce1466)

**Comment by YoshiRulz** [comment]
The endianness checkbox can also be merged into the size dropdown, and notes moved to the end. IIRC when the dialog is opened in "edit mode" the notes field is focused.

see also #3688

**Comment by YoshiRulz** [comment]
At least make all the labels line up...

**Comment by Morilli** [comment]
Not sure why the revert was necessary when you were gonna delete the files anyway... designer diffs are naturally unreadable, that is what happens when you use the designer to design instead of writing code manually.
