### ISSUE TITLE
Force software renderer on windows

### ISSUE THREAD

**Issue by InfamousKnight** [TASEmulators/BizHawk#4049]
In my effort to get bizhawk working on android using winlator, it appears everything works except for waterbox Cores.

My guess is the renderer. Anyway to force software renderer? I don't know if it would work though..

**Comment by CasualPokePlayer** [comment]
I don't know how you got to such a conclusion. Waterbox cores all would implicitly be software rendered (the only exception is melonDS, if you select the OpenGL renderer in sync settings, and even then that's not the default).

The display method (whose entire job is to slap a 2D image onto your screen) is also just core agnostic (again, slapping 2D image that has already been rendered by the core onto your screen), it wouldn't just work for some cores but not others (and there is already a software only option for it: GDI+).

What do you even mean by "doesn't work." If it's just closing immediately, it's probably just the fault of that cursed setup not liking waterbox cores fundamentally. If it's some black screen, that's just ??? (but there's probably nothing that can be done for you regardless)

**Comment by InfamousKnight** [comment]
Its crashing. I tried melonds and nymaoctoshock and they crash. I haven't tried other Cores yet

**Comment by CasualPokePlayer** [comment]
Well whatever you're using likely just doesn't like waterbox's memory tricks if anything. Not anything that could be done other than go use an actual PC.

**Comment by InfamousKnight** [comment]
I see. Well it answered my question on whether or not the renderer is the problem. If it was, mgba, mupen64 and octoshock wouldn't work either. 

The whole point of running this on android is in the event my laptop gets used up, I won't have to buy a new one. My android is pretty close to replacing my actual pc for everything.
