### ISSUE TITLE
TAStudio: remember when optional columns are enabled

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#4059]
I'm noticing that TAStudio is not remembering the Light Sensor column properly in 2.10-rc1.

In 2.9.1, it appears to properly load it from `ClientSettings.json` in the `.tasproj`, but I'm noticing it doesn't really do that for 2.10-rc1, even though it properly saves as `"Visible":true` there.

**Comment by YoshiRulz** [comment]
This may have been fixed with a more recent commit.

**Comment by CasualPokePlayer** [comment]
https://github.com/TASEmulators/BizHawk/commit/e48e6c69f243c42ac7474a541e36bc1f8528ee93 was supposed to fix it (it did regress some point before). If it's happening in 2.10-rc1 it probably regressed again?

**Comment by RetroEdit** [comment]
Looks like this was fixed in the intervening time since 2.10-rc1. It works in 9a440d03016692d88f1a047b5aa81d5db7069653.

**Comment by Morilli** [comment]
I'm wondering what exactly the failure scenario is. I was only aware of the issue mentioned in 2ad7fc095c5b220db77cc65b9152baa575d828c9, where loading a playing tasproj (via play movie) into TAStudio would fail to apply the client settings stored in the tasproj file, but that issue should have been present in 2.9.1 too.

Was that what you were doing?

**Comment by RetroEdit** [comment]
Nah, that's not what I was doing.

I'll describe the repro steps more precisely in case I accidentally closed this too early:

1. Load game
1a. For my testing, I loaded a GB game and enabled the 'Power' column. I did some additional testing with the Light Sensor column in GBA to double-check whether it worked in the newest version.
3. `File > Movie > Record Movie...`
2a. This also seemed to work with opening TAStudio directly, but it's more convenient for naming the movie file and having the movie file actually save to the `File > Movie > Recent` list.
4. `Tools > TAStudio` to open TAStudio
5. Enable missing columns
6. Save tasproj, close BizHawk
7. Reopen BizHawk and load game, tasproj, and then TAStudio.

This works in both 2.9.1 and latest dev build, but not for 2.10-rc1

**Comment by Morilli** [comment]
How are you performing step 6? If you open the tasproj via `Movie > Recent`, you'll run into this problem as I described above (on 2.10-rc1). Opening the tasproj via TAStudio correctly sets the columns.

I assume this was caused by 42aa9d991dc3dde03234a15ddfdc2efdebf1c097, as previously TAStudio would reload the tasproj from disk on load which also correctly loaded client settings.

**Comment by RetroEdit** [comment]
I'm opening via `File > Movie > Recent`, then pressing `Tools > TAStudio` to open TAStudio.
