### ISSUE TITLE
Emulator not running any game!

### ISSUE THREAD

**Issue by MInessota** [TASEmulators/BizHawk#4067]
Hi,

I can't play any game in this new version (2.10-RC1) of the emulator! In the old version (2.9.1) it works perfectly here!

![gba](https://github.com/user-attachments/assets/5406d249-dd0b-430a-800a-43cffaaa55a4)
![saturn](https://github.com/user-attachments/assets/086a9ae0-7d51-426b-bd49-fc8fe22977d0)

Linux Mint 21.3 - Lenovo Ideapad S145 (Intel CPU/iGPU it seems --yoshi)

Thank you so much for all the work, the emulator Bizhawk is amazing, thanks to him that I can play SEGA Saturn games on Linux!!!

**Comment by CasualPokePlayer** [comment]
Are .so files actually present in the dll/ folder.

**Comment by MInessota** [comment]
Hi,
I downloaded the new version of the emulator again and I actually noticed that the `dll` folder was missing some files... I think there must have been a bug when I went to extract the file!

Now it works perfectly, thank you very much for your help (^o^)//
