### ISSUE TITLE
PUAE core - Mouse pointer position is limited

### ISSUE THREAD

**Issue by SergioMartin86** [TASEmulators/BizHawk#4080]
### Summary
I wanted to move the mouse pointer to click on the game's icon, but I can only move it to ~X,Y = (255,255) using TAStudio.

### Repro

* Get this game: Lost Dutchman Mine v1.0 (1989)(Magnetic Images)
* Boot up
* Try to click LDM

### Output
Couldn't click LDM

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.10 RC

[//]: # "(screenshots, if applicable)"

![image](https://github.com/user-attachments/assets/135c256b-6a19-4ebb-83ec-b60521f78fe9)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
You're not setting absolute coordinates here, mouse inputs are relative. Set it to 255, 200 for another frame and it will probably move further.

**Comment by SergioMartin86** [comment]
Got it, thanks

**Comment by vadosnaprimer** [comment]
See if this setting helps

![изображение](https://github.com/user-attachments/assets/563a27ae-9263-49da-8097-9069cfd8d196)
