### ISSUE TITLE
Auto-Hide Mouse Cursor Doesn't work

### ISSUE THREAD

**Issue by Gabrielcnnunes** [TASEmulators/BizHawk#4086]
The option to auto-hide mouse curso is not working for me, the mouse flickers each 2 seconds but doesn't disappear. How can I solve this.

**Comment by CasualPokePlayer** [comment]
Are you actually in fullscreen mode? The setting only actually does something if you're in fullscreen mode. (It appears to be working fine for me)

Also, what BizHawk version, and what OS? (Windows 10? Windows 11? Some Linux distro?)

**Comment by Gabrielcnnunes** [comment]
https://www.youtube.com/watch?v=RYwOwf-FuXM

**Comment by CasualPokePlayer** [comment]
Is this with some USB mouse? Does the problem go away if say you unplug that mouse?

**Comment by Gabrielcnnunes** [comment]
Yes, it's an USB mouse. When I disconect my mouse from USB the problem persists.

**Comment by CasualPokePlayer** [comment]
77d19e0fed225684ea4b8bc766bad25d871b1ad3 may fix this, try the latest dev build.

**Comment by Gabrielcnnunes** [comment]
> [77d19e0](https://github.com/TASEmulators/BizHawk/commit/77d19e0fed225684ea4b8bc766bad25d871b1ad3) may fix this, try the latest dev build.

Where can I click to download it?

**Comment by CasualPokePlayer** [comment]
https://github.com/TASEmulators/BizHawk/actions/runs/11301565357/artifacts/2047800328

**Comment by Gabrielcnnunes** [comment]
Thank you.

**Comment by Morilli** [comment]
So... did it fix your issue? @Gabrielcnnunes

**Comment by Gabrielcnnunes** [comment]
> So... did it fix your issue? @Gabrielcnnunes

Yes. Thank you.
