### ISSUE TITLE
TAStudio doesn't open properly

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#4091]
In 77d19e0f there's some really odd behavior going on with opening TAStudio (regression from 2.9.1).

I was able to open it initially somehow (probably because `.bk2` -> `.tasproj` conversion works), but under many conditions, it doesn't open properly.

Here's some repro steps from clean config:
1. Pause, probably enable `View > Display Frame Count` for better clarity
2. Open a game (game probably doesn't matter, worked with both GB and NES games)
3. `File > Movie > Record movie...`
4. Record some frames (probably optional, but I recorded ~300 frames)
5. Open TAStudio (`Tools > TAStudio`)
6. Save movie and close TAStudio.
6a. Optionally advance a few frames before saving.
7. Reopen movie from `File > Movie > Recent...`
8. Open TAStudio (`Tools > TAStudio`)

The TAStudio window will fail to open and the screen will show `Movie playback stopped` and `TAStudio disengaged`. The movie will remain open. Also, it will set your `OnMovieEnd` setting to `Stop`. If you advanced some frames before saving the `.tasproj`, it will unpause.

**Comment by RetroEdit** [comment]
I guess unsurprisingly, my bisect says a43a64b89994b94dd534402c0587cc817839c03e (meant to fix #4068) is the culprit.

**Comment by Morilli** [comment]
The part about the movie end action being reset is still an issue when TAStudio otherwise fails to load upon opening. It does set the movie end action to its stored value, but it doesn't actually have a proper value stored. But that's kind of #3989 again.
