### ISSUE TITLE
Meldon DS - Hybrid Mode. X Touch Axis on the wrong position (2.10 RC1)

### ISSUE THREAD

**Issue by Zimond47** [TASEmulators/BizHawk#4096]
When using the Hybrid mode in Melon DS (Bizhawk  2.10 RC1) the X axis of the touchscreen is missplaced. It is on the left side of the whole window, so here in the screenshot I needed to click under the staircase to hit the weapon buttons. Y axis is correct.

![grafik](https://github.com/user-attachments/assets/bc0e898e-f821-463b-8bba-b9663e441e92)

Edit : In horizontal Mode both axis are completely off set.

**Comment by Morilli** [comment]
Yeah that's an unfortunate side effect of the implementation of mouse input -> axis value. There is no knowledge of actual screen bounds and how to transform them, it's a simple position / max size logic.
The same issue can be seen by enabling overscan on snes and most likely also by setting custom cropping.

**Comment by CasualPokePlayer** [comment]
I am fairly certain this is the result of savestate usage actually, which I fixed in https://github.com/TASEmulators/BizHawk/commit/84130285aaf65b681e0a71aec4b3bee428505778. Please retest on the latest dev build.

**Comment by Zimond47** [comment]
> > Yeah that's an unfortunate side effect of the implementation of mouse input -> axis value. There is no knowledge of actual screen bounds and how to transform them, it's a simple position / max size logic.
> 
> This does not apply for NDS and 3DS cores, [which have custom implementations](https://github.com/TASEmulators/BizHawk/blob/9acdcdbcf7f2b34f5f2fa100727f5ab90aa11411/src/BizHawk.Client.Common/DisplayManager/DisplayManagerBase.cs#L465-L473) required to handle this transformation (due to the fact the touch screen is not the entire screen).
> 
> I am fairly certain this is the result of savestate usage anyways, which I fixed in [8413028](https://github.com/TASEmulators/BizHawk/commit/84130285aaf65b681e0a71aec4b3bee428505778). Please retest on the latest dev build.

well, my bad. Can be closed than. Works as intended in the latest dev build. With the RC1 I simply forgot to check newer Dev Builds sorry.
