### ISSUE TITLE
Invalid security warning displayed on Windows LTSC

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#4100]
The latest BizHawk build showed me this warning when I opened it:

    Quick reminder: Your copy of Windows 10 (build 19044) is no longer supported by Microsoft.

    EmuHawk will probably continue working, but please update to at least 22H2 for increased security.

The Windows version I'm using will be supported [until 2032](https://learn.microsoft.com/en-us/windows/release-health/release-information#enterprise-and-iot-enterprise-ltsbltsc-editions), though.

You can check the value of `ProductName` in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion`  to avoid showing this to LTSC users:

![screenshot](https://github.com/user-attachments/assets/3e84fe1b-67c7-4568-9e31-cafeddf6ef4e)

**Comment by YoshiRulz** [comment]
Dammit I was hoping that would be too niche for anyone to be running it. Thanks for the suggested fix, I'll get on that.
