### ISSUE TITLE
BH 2.10 RC 1 - 3DS How to install DLC from .cia

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#4105]
BH 2.10 RC 1 - 3DS How to install DLC from .cia

**Comment by CasualPokePlayer** [comment]
"Open ROM..."

**Comment by Danik2343** [comment]
Not working, 
![EmuHawk_ldDjeCHmA6](https://github.com/user-attachments/assets/fa8c99fb-689b-497a-b46f-eeb6fb4372f5)
Make option to install CIA from Lime (aka Citra) emulator.

**Comment by Danik2343** [comment]
Now I understand, the DLC has loaded, but it says an error, it would be better to write something like the DLC has been loaded into a virtual SD card

**Comment by CasualPokePlayer** [comment]
There isn't really a way to not have it be an error. It's not executable. That may just be an error. That might be user error or intended.

BizHawk's interface is a "Load ROM" interface, there isn't going to be some "Install <x>" button added, such would just be shoehorned into "Load ROM", we're not a 3DS emulator, we're a multisystem emulator, this is the price you pay with a one size fits all system.
