### ISSUE TITLE
[F.Rq.] melonDS w/ Wi-Fi support

### ISSUE THREAD

**Issue by ag-advania** [TASEmulators/BizHawk#4106]
Hello, the [melonDS DS Libretro core](https://github.com/JesseTG/melonds-ds) is working, the wifi is Working, however the touchscreen isn't working and we are unable to configure the core options (blank configuration). Thanks !

edit: Changing to core update request i.e. adding Wi-Fi support to the existing melonDS core. It's not really worth improving compatibility with this particular Libretro core, and we're certainly not adding a separate core. --yoshi

**Comment by ag-advania** [comment]
Wifi support mainly, MelonDS doesn't support features like RAM Watch, editing, etc. Bizhawk is the only way to use these features with Wifi included.

**Comment by ag-advania** [comment]
> > Wifi support mainly
> 
> #4018 & #2450

I mean, wifi is working with this Core and Bizhawk, just the touchscreen isn't, so the work to adapt it could be minimal

**Comment by CasualPokePlayer** [comment]
Wifi support is something needing frontend integration. This was explicitly something not pursued with the BizHawk port (as it's problematic with waterboxing, which completely prevents the way upstream does wifi from working at all).

I don't know wtf you are talking about "touchscreen isn't working at all," the touchscreen works fine with this core and has for a long time. I would assume you have a really bad config here that has touch inputs unbound from the mouse somehow (which is user error if anything).

**Comment by ag-advania** [comment]
> Wifi support is something needing frontend integration. This was explicitly something not pursued with the BizHawk port (as it's problematic with waterboxing, which completely prevents the way upstream does wifi from working at all).
> 
> I don't know wtf you are talking about "touchscreen isn't working at all," the touchscreen works fine with this core and has since it was originally integrated. I would assume you have a really bad config here that has touch inputs unbound from the mouse somehow (which is user error if anything).

It looks like you may confusing "MelonDS core" and "MelonDS DS core" which is the updated version.
The MelonDS Core is working perfectly with no issues. However the "MelonDS DS core" has more features like wifi, and this is working ! :-) 
Only the touchscreen is not working correctly, that's why I've specified "MelonDS DS core" not the native one.

So Bizhawk is working perfectly on Wifi with this non-native module. IMO it would be awesome to replace the native module by this one which is the most updated one.

**Comment by CasualPokePlayer** [comment]
You are thinking our melonDS core port has any relationship with libretro melonDS' cores: it does not. melonDS as a name is from upstream, which is not libretro. Our melonDS core at the moment is slightly ahead of melonDS DS if anything (so it has the inverse relationship that you purport)

The libretro integration in BizHawk (if this is what you're referring to) is not something that is considered here. Our core port is waterboxed, which will prevent any kind of wifi from working on the native side on a fundamental level, including if you were to shove melonDS DS into our waterbox system.

**Comment by ag-advania** [comment]
Oh I see, thanks for the explanation. I'm now understanding why Wifi can't be added to the native Bizhawk core and also the limited support of libretro cores.
