### ISSUE TITLE
Mapping Analog to dpad gives too narrow diagonals when using XInput controllers.

### ISSUE THREAD

**Issue by zaphod77** [TASEmulators/BizHawk#4108]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
For games that don't support Analog, it's possible to map the analog as dpad in controller settings. This works as expected with DirectInput controllers, but when using XInput, the diagonals are very narrow, as verified by the input display.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Start Symphony of the Night (or any other game that doesn't use analog controls, but this is the game i found the bug with)
2. Using controller settings, map xinput stick up to dpad up, stick down to dpad down, etc.
3. Turn on Display Input in view menu, and move the analog stick in a circle.  The time that two directions are active is very small compared to the time one direction is active.  When using a DirectInput controller, this does not happen.  This causes diagonal inputs to be dropped during rapid circular motions.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1; Win11 23H2  1903; Intel/I5 8300. Logitech f310 controller, 8bitdo Pro 2 bluetooth controller.

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

Things work as expected in Duckstation, when using it's feature that lets you use analog for d pad in games that don't support analog.  Diagonals register reliably during rapid circles.

**Comment by CasualPokePlayer** [comment]
Please try 2.10 rc or a recent dev build: the XInput and DInput options do not exist anymore, they've been replaced by a singular SDL2 input backend.

**Comment by zaphod77** [comment]
I will try that and see if it's resolved.

**Comment by zaphod77** [comment]
Still says "X1 LStick Up" when i do the map.

![image](https://github.com/user-attachments/assets/bd71940c-ce84-4d57-9421-cce25af25460)

**Comment by CasualPokePlayer** [comment]
X# / J# do not mean "XInput vs DInput" under the newer scheme. It's rather an indication of whether SDL's Game Controller interface is being used (X) or whether SDL's Joystick interface is being used (J). Most controllers would be covered under SDL's Game Controller interface (not just Xbox like controllers), with really only a few really oddball controllers being covered under SDL's Joystick interface.

I suspect the issue is just due to the arbitrary numbers used to determine if an axis triggered a ""button"" press. The numbers seemed to be done differently between XInput and DInput and XInput numbers were used when integrating the SDL backend.

**Comment by CasualPokePlayer** [comment]
See if the latest dev build fixes this.

**Comment by zaphod77** [comment]
Yes, that change fixes it.  

The circle acts smoothly, and i can chain wingsmashes.

**Comment by zaphod77** [comment]
Well it's close. there really should be an option to adjust sensitivity for analog to dpad stuff, but the current one is a sensible default now.
