### ISSUE TITLE
M&L Bowser's Inside Story no longer beatable due to microphone regression (worked in 2.9.1)

### ISSUE THREAD

**Issue by blueYOSHI9000** [TASEmulators/BizHawk#4112]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"

### Summary
Mario & Luigi Bowser's Inside Story no longer detects the microphone input in the most recent 2.10-rc1 version (though oddly enough the "Mic Test" accessible on the title-screen works, more on this below). [Video here](https://youtu.be/tmGorNDSOLg), it shows off 1.9.1 & 1.9.2/2.10-rc1 side-by-side while setting the mic controls up and showing the issue off.

[Here's the SaveStates used](https://mega.nz/folder/j8cXhQCL#FKT9vNARQNoygvQPx29pMA), it also includes a third ('doctor') not shown in the video, but it is another point in the game that does not work anymore. Savefiles are also provided, the doctor one is recommended as you only have to walk into the clinic (~30s), the fire one needs a minigame first (~2min). All savestates & savefiles are for the EU version that's also linked to RetroAchievements.

Another interesting, maybe related, fact is that a similar thing happened in RetroArch where the original 'melonDS' core works perfectly fine but the newer 'melonDS DS' core only works on the Mic Test screen but *not* during actual gameplay (whether using fire or during the doctor segment), just like BizHawk 2.10-rc1.

### Repro
1. load the above linked SaveStates (either the 'fire' or 'doctor' one) - or play through the game until those points
2. use the microphone
3. it works in 2.9.1 but not in 2.10-rc1

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- [broken] BizHawk 2.9.2/2,10-rc1, Win10 HOME, AMD Ryzen, NVIDIA GTX
- [works] BizHawk 2.9.1, rest same
Both tested on fresh installs with nothing changed but the input settings.

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
This was already fixed in the latest dev build.
