### ISSUE TITLE
Solar Sensor Desync - Commit 89d76ef

### ISSUE THREAD

**Issue by Drakodan** [TASEmulators/BizHawk#4118]
Previously reported desync issues whilst working in TAStudio with the Boktai games as the solar sensor would read an incorrect value on rewinding and making changes.

This was identified as a GPIO issue which was fixed in a previous commit.

Now the same issue is present on the above commit, cause unclear if it's not GPIO-related.

*How to reproduce:*

- Open relevant ROM
- In TAStudio, open the attached TASPROJ file
- Project should open mid-desync, character should die directly after starting playback
- Manually rewind to frame 322900~ and resume playback, desync should not occur

[1585 - Zoku Bokura no Taiyou - Taiyou Shounen Django (J) (v1.0) Desync test.zip](https://github.com/user-attachments/files/17803639/1585.-.Zoku.Bokura.no.Taiyou.-.Taiyou.Shounen.Django.J.v1.0.Desync.test.zip)

Made with dev build 89d76ef6c.

**Comment by Morilli** [comment]
What is the difference between this and #4094?

**Comment by Drakodan** [comment]
It's the same issue (I assume so at least, I can't 100% confirm that the cause is directly the same), but this report is to confirm that the same behaviour is occurring on the latest dev build as I believe there was talk of a new release candidate. These can probably be merged if that's appropriate

**Comment by CasualPokePlayer** [comment]
I can reproduce it, but this doesn't seem particularly useful for figuring out what's desyncing. The desync point is frame 322996/322997, frame 322997 is a "bad" savestate within the tasproj, and frame frame 322996 (and before has a "good" savestate). The point where execution diverged would however just be before the "bad" frame 322997 state, i.e. not present in the tasproj since a that point the state is good.

Haven't checked the other movie yet, might be more useful in this case.

**Comment by Drakodan** [comment]
Hopefully this project file shows a better scenario for diagnosing:

- Open TASPROJ file (Should open at frame 322998
- Start normal playback, pause playback after passing 323100~
- Erase the L input at frame 323028
- Start normal playback, desync should occur almost immediately

Within reason, these sorts of desyncs can be created at basically any point in this fight by rewinding an already-played section and changing an input. If you want me to create a desync according to specific instructions, please let me know.

[1585 - Zoku Bokura no Taiyou - Taiyou Shounen Django (J) (v1.0) Desync test new.zip](https://github.com/user-attachments/files/17822621/1585.-.Zoku.Bokura.no.Taiyou.-.Taiyou.Shounen.Django.J.v1.0.Desync.test.new.zip)
