### ISSUE TITLE
Saturnus settings dialog shows no settings

### ISSUE THREAD

**Issue by Matheus-The-Razor** [TASEmulators/BizHawk#4122]
The Core of the Sega Saturn, Saturnus when you enter SAT - Sync Settings is blank, can fix it?
![Sync](https://github.com/user-attachments/assets/2002345f-fa0e-468d-9a03-f4be119f9148)

**Comment by CasualPokePlayer** [comment]
This issue was already fixed since https://github.com/TASEmulators/BizHawk/commit/7477aa335977d8800f42bdd8b50fe0d7e8df2c9b.
