### ISSUE TITLE
Display keys at the end of input OSD

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#4132]
![изображение](https://github.com/user-attachments/assets/273ed41f-78d7-4a7b-95e0-0a91b2536fb0)

Keys often occupy most of the input string, and actually useful controls (per-player ones) always go after it (because [keys are added as player 0](https://github.com/TASEmulators/BizHawk/blob/29b848d3367e231dee1a1f7d1e70478903d0196e/src/BizHawk.Emulation.Common/Base%20Implementations/ControllerDefinition.cs#L122)), so it becomes VERY annoying to always have to fullscreen the emu if you need to see input OSD.

While in tastudio you can see only the inputs you need (keys are hidden by default there), during traditional tasing or video dumping you won't be able to only see the useful inputs in a reasonably small window unless you reanchor the input string for all systems, and then you have to change it back every time you want it in the normal place.

I think adding ones starting with `"Key "` as the last player in `GenOrderedControls()` would be a much better idea. For other types of input strings this probably doesn't matter, like bk2 file itself.

**Comment by YoshiRulz** [comment]
Moving player 0 to the end might be easier.

**Comment by vadosnaprimer** [comment]
> Moving player 0 to the end might be easier.

That'd affect ordering in all places, right? Is everyone fine with that?

**Comment by YoshiRulz** [comment]
No, it's separate from movie mnemonics. `Bk2InputDisplayGenerator` vs `Bk2LogEntryGenerator`.

**Comment by vadosnaprimer** [comment]
Isn't `GenOrderedControls()` (that actually orders them) common for all of them?
