### ISSUE TITLE
Emuhawk unable to recognize Microsoft Visual C++ 2010 SP1 Runtime (x64) despite having downloaded prerequisites

### ISSUE THREAD

**Issue by Eberis-lol** [TASEmulators/BizHawk#4135]
Apologies in advance if this is against anything, but as per the title I am unable to load Emuhawk 2.9.1, and used the latest prerequisite installer (2.4.8_1), and can confirm they are on the same drive, and have restarted upon downloading the prerequisites.

![System apps](https://github.com/user-attachments/assets/c295c42d-1b30-4ed0-94d2-db0d25ede926)
![emuhawk](https://github.com/user-attachments/assets/abb39fbd-4091-4b5a-ad72-16bee36b75a7)
![image](https://github.com/user-attachments/assets/95d31876-09bb-42b7-be5a-619166c3645e)

**Comment by YoshiRulz** [comment]
Not sure if 2010 is the same as 2010 SP1, but either way that's [no longer a dependency](https://github.com/TASEmulators/BizHawk/commit/d9a93c474a3d95a9044049b13e52d3dd54756cd1) in 2.10. Try [2.10 RC2](https://github.com/TASEmulators/BizHawk/releases/2.10-rc2).

**Comment by Eberis-lol** [comment]
That seems to have worked, thank you greatly.
