### ISSUE TITLE
PUAE core - Bizhawk just closes while game is loading

### ISSUE THREAD

**Issue by ScHlAuChii** [TASEmulators/BizHawk#4137]
### Summary
Game closes the emu while loading!

### Repro
https://mcgeezer.itch.io/kung-fu-remaster
Run the game Devil´s Temple via a multidisk XML file.
Just let it run and after the title screen it will crash Bizhawk.

### Output
None, just closes

This is the build I used:
https://github.com/TASEmulators/BizHawk/commit/69b61b574d7dbad65785b57c6a7d17cf6cc59b38

**Comment by vadosnaprimer** [comment]
Dies in `CanPollInput()` with System.ExecutionEngineException. Raising initial mem sized doesn't help.

**Comment by CasualPokePlayer** [comment]
ExecutionEngineException indicates some kind of memory corruption within managed memory. `CanPollInput()` is likely a red herring here, the corruption is likely from unmanaged code doing some copy into managed memory (e.g. write too much data into the pinned video/sound buffers)

**Comment by vadosnaprimer** [comment]
Fixed in fc2b37cab78a130e06696b0ad6b0ecb48ea06182
