### ISSUE TITLE
PUAE core - Lack of Amiga drive info / Disk Switching Messages

### ISSUE THREAD

**Issue by ScHlAuChii** [TASEmulators/BizHawk#4138]
### Summary
It is currently completely unclear what disk is in what drive.
You dont know if a disk was actually inserted or if the disk you inserted is broken.

This is how it currently is:
![CurrentState](https://github.com/user-attachments/assets/3b0a6584-7304-41f5-9cdc-0aa6e750054a)

This is how I suggest it should be:
![FutureState](https://github.com/user-attachments/assets/f8f964dc-0bf3-40cb-b2f9-9aeece471469)

Additionally when you insert or eject a disk, Bizhawk should say something like:
Turrican2AGADisk1 inserted to FD0
Turrican2AGADisk1 ejected from FD0

**Comment by vadosnaprimer** [comment]
Do you really need to know which drive each slot is in? You can iterate through drives, and I made it print what file is inserted, and the max drive number is 4, so that's kinda quicker?

**Comment by ScHlAuChii** [comment]
Yep knowing which drive each slot is in is very useful information.
Currently Amigahawk only supports unclean ADF dumps which often were badly cracked.
So even if you inserted a slot it doesnt guarantee that it works. 
Also some Amiga games are picky in how they support those drive.
So any extra info to the user is useful.

**Comment by ScHlAuChii** [comment]
Is that in the current build?

**Comment by vadosnaprimer** [comment]
Yes.

**Comment by ScHlAuChii** [comment]
Yep its perfectly fine and works as intended - but:
If you set 4 drives and load in an XML with 3 slots, it crashes once you switch to the 4th drive.

-------------------------------------------------------------
System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index
   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei BizHawk.Emulation.Cores.Computers.Amiga.PUAE.FrameAdvancePrep(IController controller, Boolean render, Boolean rendersound) in /src/BizHawk.Emulation.Cores/Computers/Amiga/PUAE.cs:Zeile 139.
   bei BizHawk.Emulation.Cores.Waterbox.WaterboxCore.FrameAdvance(IController controller, Boolean render, Boolean rendersound) in /src/BizHawk.Emulation.Cores/Waterbox/WaterboxCore.cs:Zeile 207.
   bei BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force) in /src/BizHawk.Client.EmuHawk/MainForm.cs:Zeile 3052.
   bei BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() in /src/BizHawk.Client.EmuHawk/MainForm.cs:Zeile 885.
   bei BizHawk.Client.EmuHawk.Program.SubMain(String[] args) in /src/BizHawk.Client.EmuHawk/Program.cs:Zeile 351.

**Comment by vadosnaprimer** [comment]
Crash fixed in b8ec340c90ebe39bd1d2009aab9e0c54b40a1778
