### ISSUE TITLE
Auto-adjust input according to lag

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#734]
Right  now it's fully broken, one needs to copy taseditor logic.

**Comment by kamanabc123** [comment]
AGREED! COPY TAS EDITOR FROM FCEUX

**Comment by vadosnaprimer** [comment]
How about you test it.

**Comment by vadosnaprimer** [comment]
Somehow this mostly works, just pauses every time it removes a frame due to disappeared lag on it.

**Comment by vadosnaprimer** [comment]
See 8310e5420c7ede08f647b4c99893430766e5f3e8 for why this is completely screwed.

**Comment by RetroEdit** [comment]
I think this issue should be reopened.

Here's my rationale:
1) **Usefulness**: Allowing inputs and lag to interact more naturally turns impossible tasks into trivial ones. In a recent TAS I did with 30 FPS lag, this feature probably would have saved me hours of time. More broadly, from my automated GBA resync work, I've realized for *so many* games, this feature would allow making changes to earlier parts of a TAS without having to adjust later parts. Generally this could offer far higher quality of life when TASing laggy games. I strongly believe many users would discover and use this feature if it worked intuitively.
2) **Implementation difficulties**: from the pre-closure commit, implementing this "would involve touching that minefield of bools that control everything in insane ways". This seems more like a systemic problem with technical debt in BizHawk/TAStudio's codebase than a particularly good reason for closing this.
3) **Why bother keeping this open if no one will fix it?** Personally, I am greatly interested in implementing this, but it will probably be several years before I do. But I would also argue closing issues like this obscures future possible design directions, while keeping this issue open causes minimal harm. Closing issues as "won'tfix" is appropriate for feature requests that are logically incompatible or redundant to existing features, but I don't think this is such a case. This issue tracker currently allows feature requests, and this is hardly the most ambitious open feature request, with issues like #3061 remaining open.

**Comment by vadosnaprimer** [comment]
>1. **Usefulness**: Allowing inputs and lag to interact more naturally turns impossible tasks into trivial ones. In a recent TAS I did with 30 FPS lag, this feature probably would have saved me hours of time. More broadly, from my automated GBA resync work, I've realized for _so many_ games, this feature would allow making changes to earlier parts of a TAS without having to adjust later parts. Generally this could offer far higher quality of life when TASing laggy games. I strongly believe many users would discover and use this feature if it worked intuitively.

Absolutely. I know it's helpful, I just indicated nobody begged for it for all these years. I used it all the time in fceux in both Battletoads and DuckTales2, because those games lag very randomly.

>2. **Implementation difficulties**: from the pre-closure commit, implementing this "would involve touching that minefield of bools that control everything in insane ways". This seems more like a systemic problem with technical debt in BizHawk/TAStudio's codebase than a particularly good reason for closing this.

"Impossible to perfectly implement without a complete overhaul of all the logic" is a very solid reason in my books. Technical debt sure, but when it's literally everywhere, one would think remaking it from scratch is a better idea. Except when adding back all the logic one would still drown in all the behavior quirks.

Trying to make it work perfectly would be a nightmare because of all the logic that exists, not because some of that logic is broken or bad. Everything is intertwined by design because it's how the workflow is. So properly fixing this ticket is technically unfeasible, because it's impossible to keep in mind literally everything that can go wrong. I've spent years on this tool and fixing all its bugs, and I know the entirety of the workflow, but I tried and miserably failed to fix this issue correctly. Maybe I'm not smart and someone can do it better.

>3. **Why bother keeping this open if no one will fix it?** Personally, I am greatly interested in implementing this, but it will probably be several years before I do. But I would also argue closing issues like this obscures future possible design directions, while keeping this issue open causes minimal harm. Closing issues as "won'tfix" is appropriate for feature requests that are logically incompatible or redundant to existing features, but I don't think this is such a case. This issue tracker currently allows feature requests, and this is hardly the most ambitious open feature request, with issues like [Always be recording a movie #3061](https://github.com/TASEmulators/BizHawk/issues/3061) remaining open.

I agree there's no harm in endlessly keeping this open. #3061 feels much more optimistic to me, because it's a life saver for all the glitch hunters, so it has a ton of meta value in a much bigger scope than this one.

**Comment by RetroEdit** [comment]
If the codebase is so complicated where it's impossible to keep in mind everything that can go wrong, I still think that's a problem with both the design and test coverage. Complexity need not require overcomplication.

But I'll concede code speaks louder than words on issues like this.
