### ISSUE TITLE
hook/callback system needs memorydomain scope

### ISSUE THREAD

**Issue by zeromus** [TASEmulators/BizHawk#839]
Hooks need to be set on a memorydomain, not on the entire core (and implicity sysbus)

**Comment by YoshiRulz** [comment]
Isn't this implemented already? It's just that most (all?) cores only pass a single scope:
https://github.com/TASEmulators/BizHawk/blob/e23a2df7e097b3cc117b2ffd6cb5ade029cd792a/src/BizHawk.Emulation.Cores/Consoles/Nintendo/GBHawk/GBHawk.IDebuggable.cs#L15

**Comment by zeromus** [comment]
looks like adelikat did that 3 months later
is the memdomain parameter accessible to lua?

**Comment by YoshiRulz** [comment]
https://github.com/TASEmulators/BizHawk/blob/e23a2df7e097b3cc117b2ffd6cb5ade029cd792a/src/BizHawk.Client.Common/lua/LuaHelperLibs/EventsLuaLibrary.cs#L98-L125

**Comment by CasualPokePlayer** [comment]
I am fairly certain core core changes are going to be needed for every core to do something like this

**Comment by CasualPokePlayer** [comment]
Testing it out myself it does seem to function as intended, and this is documented(-ish) on the [lua page](http://tasvideos.org/Bizhawk/LuaFunctions.html).
