### ISSUE TITLE
Some games don't work with NesHawk

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#860]
They are:

Challenge of the Dragon (Asia) (PAL) (Unl) - Green Screen
Chuugoku Taitei (Asia) (Unl) - Black Screen
Dancing Blocks (Asia) (PAL) (Unl) - Green Screen
Gaiapolis (Asia) (Unl) - Green Screen
Mahjong World, The - Ma Que Shi Jie (Asia) (NTSC) (Unl)
Mahjong World, The - Ma Que Shi Jie (Asia) (PAL) (Unl)
Metal Fighter (Asia) (Sachen) (Unl)
Poker Mahjong - Pu Ke Mao Que (Asia) (Unl)
Popo Team (Asia) (Unl)
Pyramid II (Asia) (PAL) (Unl) - Green Screen
Qi Wang - Chinese Chess (Asia) (Unl)
Rockball (Asia) (Unl)
Sidewinder (Asia) (PAL) (Unl)
Silent Assault (Asia) (PAL) (Unl)
Silver Eagle (Asia) (PAL) (Unl) - Black Screen
Super Cartridge Ver 2 - 10 in 1 (Asia) (Unl)
Super Cartridge Ver 3 - 8 in 1 (Asia) (Unl)
Super Cartridge Ver 9 - 3 in 1 (Asia) (Unl)
Super Pang II (Asia) (Unl)
Taiwan Mahjong - Tai Wan Ma Que 16 (Asia) (Unl)
Othello (Australia) (Unl)
Pipemania (Australia) (HES) (Unl) - Crashes Bizhawk.
Sidewinder (Australia) (Unl)
Xing He Zhan Shi (China) (Unl) - Crashes Bizhawk
Xing Ji Zheng Ba (China) (Unl) - Green Screen
AV Super Real Pachinko (Japan) (Unl)
Mahjong Samit - Kabukicho Hen (Japan) (Unl)
Dooly Bravo Land (Korea) (Unl) - Green Screen
Korean Igo (Korea) (Unl) - Green Screen
BB Car (Unknown) (Unl)
Buzz & Waldog (USA) (Proto) (Unl) - Green Screen
Hard Drivin' (USA) (Proto) (Unl)
Tagin' Dragon (USA) (Unl) - Crashes 
Elite (Unknown) (NTSC Demo)
Block Out (USA) (Proto)
Family BASIC (Japan) (v2.0a) - Green Screen
Family BASIC (Japan) (v2.1a) - Green Screen
Batman - Return of the Joker (USA) (Beta) - Crashes Bizhawk
Bugs Bunny Birthday Bash (USA) (Beta) [b]
Dr. Mario (USA) (Beta) (Between 1990-02-02 & 1990-04-27, later) - Crashes Bizhawk
Virus (USA) (Beta) (1990-02-02) - Crashes Bizhawk

**Comment by hegyak** [comment]
Family BASIC and AV Super Real Pachinko should be fixed with the updated Developer Build.  The rest, I don't know about.  What Build are you testing these ROMs with?

**Comment by PinkLouie** [comment]
Latest stable build.

**Comment by alyosha-tas** [comment]
My goodness there always sems to be more NES games 0_0

I'll scratch games off the list as I fix them.

Challenge of the Dragon (Asia) (PAL) (Unl) - Green Screen
Chuugoku Taitei (Asia) (Unl) - Black Screen
Dancing Blocks (Asia) (PAL) (Unl) - Green Screen
Gaiapolis (Asia) (Unl) - Green Screen
Mahjong World, The - Ma Que Shi Jie (Asia) (NTSC) (Unl)
Mahjong World, The - Ma Que Shi Jie (Asia) (PAL) (Unl)
Metal Fighter (Asia) (Sachen) (Unl)
Poker Mahjong - Pu Ke Mao Que (Asia) (Unl)
Popo Team (Asia) (Unl)
Pyramid II (Asia) (PAL) (Unl) - Green Screen
Qi Wang - Chinese Chess (Asia) (Unl)
Rockball (Asia) (Unl)
Sidewinder (Asia) (PAL) (Unl)
Silent Assault (Asia) (PAL) (Unl)
Silver Eagle (Asia) (PAL) (Unl) - Black Screen
Super Cartridge Ver 2 - 10 in 1 (Asia) (Unl)
Super Cartridge Ver 3 - 8 in 1 (Asia) (Unl)
Super Cartridge Ver 9 - 3 in 1 (Asia) (Unl)
Super Pang II (Asia) (Unl)
Taiwan Mahjong - Tai Wan Ma Que 16 (Asia) (Unl)
Othello (Australia) (Unl)
Pipemania (Australia) (HES) (Unl) - Crashes Bizhawk.
Sidewinder (Australia) (Unl)
Xing He Zhan Shi (China) (Unl) - Crashes Bizhawk
Xing Ji Zheng Ba (China) (Unl) - Green Screen
AV Super Real Pachinko (Japan) (Unl)
Mahjong Samit - Kabukicho Hen (Japan) (Unl)
Dooly Bravo Land (Korea) (Unl) - Green Screen
Korean Igo (Korea) (Unl) - Green Screen
BB Car (Unknown) (Unl)
Buzz & Waldog (USA) (Proto) (Unl) - Green Screen
Hard Drivin' (USA) (Proto) (Unl)
Tagin' Dragon (USA) (Unl) - Crashes
Elite (Unknown) (NTSC Demo)
Block Out (USA) (Proto)
Family BASIC (Japan) (v2.0a) - Green Screen
Family BASIC (Japan) (v2.1a) - Green Screen
Batman - Return of the Joker (USA) (Beta) - Crashes Bizhawk
Bugs Bunny Birthday Bash (USA) (Beta) [b]
Dr. Mario (USA) (Beta) (Between 1990-02-02 & 1990-04-27, later) - Crashes Bizhawk
Virus (USA) (Beta) (1990-02-02) - Crashes Bizhawk

**Comment by alyosha-tas** [comment]
Metal Fighter (Asia) (Sachen) (Unl) works fine for me. What issue are you having with it?

**Comment by PinkLouie** [comment]
BB Car really has no problem, my bad. But Metal Fighter has. Look the screenshots.

![2017-05-26 5](https://cloud.githubusercontent.com/assets/24971871/26516342/2878cedc-425b-11e7-9172-e9c944e1dc96.png)
![2017-05-26 6](https://cloud.githubusercontent.com/assets/24971871/26516343/2879cc7e-425b-11e7-8d5d-5381e0a094c5.png)

**Comment by alyosha-tas** [comment]
Ah, ok you need to make sure you use NESHawk. 
Look at the bottom center of the window in your images and you will see 'QuickNES.'
This is the less accurate and less compatible (but for some reason the default) core.
To change cores, load a ROM, then go to NES->Core->NESHawk.
Then Go to Emulation-> Reboot Core.
Now you will see NESHawk instead of QuickNes at the bottom of the screen.
Metal Fighter will then play correctly.
Please make sure the games on your list are actually NESHawk, as QuickNES is not actively maintained.

**Comment by PinkLouie** [comment]
Sorry, but it happens with Neshawk too.

![2017-05-26 7](https://cloud.githubusercontent.com/assets/24971871/26516560/9692f0ca-425e-11e7-9590-f06233c9089e.png)

**Comment by alyosha-tas** [comment]
That's weird, maybe you have a different ROM, can you click on that little question block in the lower left of the screen and copy paste the info in it?

**Comment by PinkLouie** [comment]
------
BEGIN NES rom analysis:
Found iNES header:
pr=32,ch=32,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER000,sys=
Since this is iNES we can (somewhat) confidently parse PRG/CHR banks to hash.
headerless rom hash: sha1:CAAC1E829133851648BA7C7CD6EAA7D26A464999
headerless rom hash:  md5:3CA3304155228C01BDFD747BCB50E4B5
Could not locate game in bizhawk gamedb
Could not locate game in nescartdb
Attempting inference from iNES header
Chose board from iNES heuristics:
pr=32,ch=32,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER000,sys=
Final game detection results:
pr=32,ch=32,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER000,sys=
""
Implemented by: class NROM
END NES rom analysis
------

This is a No-Intro rom.

**Comment by alyosha-tas** [comment]
Same ROM, What version of BizHawk are you using? The game loads and runs correctly in the latest release 1.12.2

This is what I get:
------
BEGIN NES rom analysis:
Found UNIF header:
pr=32,ch=32,wr=0,vr=0,ba=0,pa=1|0,brd=UNIF_UNL-SA-016-1M,sys=
Since this is UNIF we can confidently parse PRG/CHR banks to hash.
headerless rom hash: sha1:CAAC1E829133851648BA7C7CD6EAA7D26A464999
Could not locate game in bizhawk gamedb
Could not locate game in nescartdb
Using information from UNIF header
Final game detection results:
pr=32,ch=32,wr=0,vr=0,ba=0,pa=1|0,brd=UNIF_UNL-SA-016-1M,sys=
""
Implemented by: class SachenSimple
END NES rom analysis
------

**Comment by PinkLouie** [comment]
I'm running 1.12.2 too. Weird? Surely.

**Comment by PinkLouie** [comment]
Note the problem do not happen in the game itself. It happen in the "movie", when you wait, and in the intro.

**Comment by alyosha-tas** [comment]
Well, it looks like your ROM must have a different (incorrect) header.
It should have a UNIF header, but has an incorrect iNES header specifying mapper 0.
I see similar behaviour with other ROMs like Korean Igo which plays fine.
Maybe NoIntro's ROMs are outdated?

Anyway I'll add it to the gamedb.

NES ROMs are so messy.

**Comment by adelikat** [comment]
I think it is worthwhile to mention games that dont' work on quicknes too.  If they work on neshawk and not quicknes, add them to the blacklist in the quicknes core

**Comment by alyosha-tas** [comment]
I've cleared up most of the list, but that Bugs Bunny  Birthday Bash seems not to work in any emulator, is it known to function somehow?

**Comment by PinkLouie** [comment]
Sorry, this is a bad dump.

**Comment by RetroGameIntros** [comment]
There is working dump in GoodNES 3.23b, but no sound only picture
![2](https://cloud.githubusercontent.com/assets/28905475/26766269/b8125580-4996-11e7-84cd-7556404f69b8.JPG)

**Comment by Sappharad** [comment]
Any working dumps are hacks. There are no valid dumps, per TCRF:
https://tcrf.net/Proto_talk:The_Bugs_Bunny_Birthday_Blowout

**Comment by PinkLouie** [comment]
Some games are not working in 1.13. They are:

3-D Block (Asia) (Hwang Shinwei) (Unl)
Chinese KungFu (Asia) (Unl)
Chuugoku Taitei (Asia) (Unl) - Black Screen
Fighting Hero III (Asia) (Unl)
Final Combat (Asia) (NTSC) (Unl)
Final Combat (Asia) (PAL) (Unl)
Great Wall, The (Asia) (PAL) (Unl)
Hell Fighter (Asia) (PAL) (Unl)
Jovial Race (Asia) (PAL) (Unl)
Super Pang (Asia) (PAL) (Unl)
Twin Eagle (Asia) (PAL) (Unl)
Little Red Hood (Australia) (Unl) - some artifacts
Sidewinder (Australia) (Unl) - Green Screen
Xing Ji Zheng Ba (China) (Unl) - Green Screen
Ying Xiong Yuan Yi Jing Chuan Qi (China) (Unl) - Green Screen
AV Soccer (Japan) (Unl)
AV Super Real Pachinko (Japan) (Unl)
Mahjong Samit - Kabukicho Hen (Japan) (Unl)
Dooly Bravo Land (Korea) (Unl)

**Comment by PinkLouie** [comment]
Some licensed games as well: 

Galaxian (Japan)
Galaxian (Japan) (Rev A)
Dragon Ball 3 - Gokuu Den (Japan) (Rev 1)
Super Mario Bros. 25 Shuunen Version (Japan) (En) (Promo, Virtual Console)
Banana (1986-09-08)(Victor Ongaku Sangyou)(JP) - Green Screen - Tosec rom
Pirates! (Germany)
Pirates! (Europe)
Snowboard Challenge (Europe)

**Comment by alyosha-tas** [comment]
PinkLouie how are you able to generate these lists so quickly? Do you have some kind of automated testing mechanism? If so I would be interested to know how it works.

**Comment by PinkLouie** [comment]
I just drag and drop one by one.

**Comment by RetroGameIntros** [comment]
Galaxian (Japan) (Rev A) not working, showing error (headered ROM from No-Intro)

Pirates! (Europe) and Pirates! (Germany) works, but they have graphical glitches
![pirates europe 2](https://cloud.githubusercontent.com/assets/28905475/26786280/c101d8dc-4a0e-11e7-94d3-66178754fade.JPG)
![pirates europe](https://cloud.githubusercontent.com/assets/28905475/26786279/c100f084-4a0e-11e7-8d9c-6f4f2a4d95ba.JPG)
![default](https://cloud.githubusercontent.com/assets/28905475/26786304/d48307f0-4a0e-11e7-99e1-97f4cdf92479.JPG)

**Comment by PinkLouie** [comment]
Pirates have problem because it's opened as NTSC but should be opened as Pal. I think BizHawk should read the filename to detect NTSC and PAL games. No-intro and GoodTools have naming conventions, as Tosec, so you can make it happen.

**Comment by hegyak** [comment]
We don't trust our users to actually name files correctly.  That's why we use Checksums of ROM files.

**Comment by alyosha-tas** [comment]
Several of those are actually fixed in master but didn't make it into 1.13. 
To my knowledge, here is the updated list:

3-D Block (Asia) (Hwang Shinwei) (Unl)
Chinese KungFu (Asia) (Unl)
Chuugoku Taitei (Asia) (Unl) - Black Screen
Fighting Hero III (Asia) (Unl)
Final Combat (Asia) (NTSC) (Unl)
Final Combat (Asia) (PAL) (Unl)
Great Wall, The (Asia) (PAL) (Unl)
Hell Fighter (Asia) (PAL) (Unl)
Jovial Race (Asia) (PAL) (Unl)
Super Pang (Asia) (PAL) (Unl)
Twin Eagle (Asia) (PAL) (Unl)
Little Red Hood (Australia) (Unl) - some artifacts
Ying Xiong Yuan Yi Jing Chuan Qi (China) (Unl) - Green Screen
AV Soccer (Japan) (Unl)
AV Super Real Pachinko (Japan) (Unl) ?? (works for me)
Hard Drivin' (USA) (Proto) (Unl)

Dragon Ball 3 - Gokuu Den (Japan) (Rev 1)
Super Mario Bros. 25 Shuunen Version (Japan) (En) (Promo, Virtual Console)
Banana (1986-09-08)(Victor Ongaku Sangyou)(JP) - Green Screen - Tosec rom
Pirates! (Germany)
Pirates! (Europe)
Snowboard Challenge (Europe)
Mahjong (Japan)
Pac-Man (Japan) (En) (Rev B)
Miracle Piano Teaching System, The (Germany)

**Comment by PinkLouie** [comment]
Today I tried some GoodNes roms. They ones not working are the following:

AV Soccer (Hacker)
Boogerman II (Rex-Soft) [!] - Green Screen
Boogerman II (Rex-Soft) [U][!]
Hell Fighter (Sachen) [!]
Hell Fighter (Sachen) [U][!]
Olympic IQ (Sachen) [U][!]
Poker II (Sachen) [U][!]
Strategist (With Intro) (Sachen) [U][!]
Tasac (Sachen) [U][!] - 1
Keyboard Transformer (R) [U][!] - 1
Subor V1.0 (R) - Black Screen
SuborWin 2000 (R) [!] - Blue Screen
Bio Hazard (No-Bug) (Unl) - Green Screen
City Fighter IV (Sound) (Unl) [U]
Dringle (Unl)
Famikan (Unl) - Green Screen
Mei Shao Nv Meng Gong Chang (Princess Maker) (Sachen) (Unl) [U][!]
Square Force (Unl) [!] - Green Screen

Dragon Quest II - Akuryou no Kamigami (J-VC)
Dragon Quest III - Soshite Densetsu e... (J-VC) (PRG1)
Gradius II (J) (VC) - Grey Screen
Kage no Densetsu (J) (VC)
Street Gangs (E) (VC)
Russkie Gonki (Highway Star) (R) [!]

I still want to try the chinese roms.

**Comment by PinkLouie** [comment]
I forgot to mention this two tosec roms:

Captain Skyhawk (1989)(Rare)(PlayChoice-10)
Mario's Open Golf (1991)(Nintendo)(PlayChoice-10)

**Comment by PinkLouie** [comment]
Here is the list of Chinese games:

Ba Bao Qi Zhu - Li Jian Ba Quan Zhuan (EverQuest) (ES-1067) (Ch)
Cheng Ji Si Han (ES-1110) (Ch) - Crashes Bizhawk
Feng Se Huan Xiang (ES-1138) (Ch) - Black Screen
Gui Mei Zhan Ji (ES-1125) (Ch) - Green Screen
Ji Dou Sheng Zhan Shi (ES-1117) (Ch)
Legend of Zelda - Three Force (Ch) [U] - 1 - Green Screen
Legend of Zelda - Tri Force (ES-1096) (Ch) [U][!] - Green Screen
Long Zhu Ying Xiong (Ch) - Black Screen
Ninja Ryukenden (Ch)
San Xia Wu Yi - Yu Mao Chuan Qi (ES-1071) (Ch) [U]
Shuang Zai Long 2 (Field Combat) (Ch) - Green Screen
Subor V3.0 (Ch)
Tin Choi Ma Li (Genius Merio Bros) (JMH MTV Corp) (Ch) [U]
Xing Ji Zheng Ba (Ch) - Green Screen
Yuu Yuu Hakusho 97 V (Eng) (Ch)
Zhan Guo Qun Xiong Chuan (Ch) - Gree Screen

**Comment by zeromus** [comment]
@ghost, it will take a full time programmer to even put in a respectable showing at trying and failing to keep up with the discovery of broken NES games. We ordinarily work on a "i need this to work" basis, not an "I tested 1000000000 games and here's 28931923 that didnt work" basis. Thank you for testing 1000000000 games, but please don't do that anymore. We need to prioritize by what people actually need.

**Comment by vgturtle127** [comment]
@zeromus Could you explain what you mean by "what people actually need"?

Do you mean bugs in games that aren't pirate carts, prototypes, etc.? Non-mapper stuff? I just want to understand so I know what should be done in regards to this core.

**Comment by zeromus** [comment]
You think I'm defining "what people actually need" in some kind of crafty way, where I can tell a person "aha! you don't actually need that" and then we don't have to do it.

That isn't the case.

It is meant literally. Nobody needs "Ninja Jajamaru - Ginga Daisakusen (J) (Beta)" to work. 

Not because of X reason or because of Y reason. Because ... nobody ... needs ... it.

**Comment by vgturtle127** [comment]
@zeromus Well, I think "needs to work" is relative, and people can use the other 100,000 NES emulators that are out there, but since it is your core, I just wanted to know what you wanted, since it is yours.

**Comment by zeromus** [comment]
What I want is for people to need something when they write a bug about it. If everyone searched for bugs and wrote up whatever they found, we would be fixing mostly things nobody needs, and stuff people need fixed would be buried in the noise of things nobody needs.

**Comment by vgturtle127** [comment]
@zeromus OK, I think I understand what you're saying.

**Comment by alyosha-tas** [comment]
Making an updated post that I can keep track of:

3-D Block (Asia) (Hwang Shinwei) (Unl)
Chinese KungFu (Asia) (Unl)
Chuugoku Taitei (Asia) (Unl) - Black Screen
Little Red Hood (Australia) (Unl) - some artifacts
AV Soccer (Japan) (Unl)
Hard Drivin' (USA) (Proto) (Unl)

Super Mario Bros. 25 Shuunen Version (Japan) (En) (Promo, Virtual Console)
Banana (1986-09-08)(Victor Ongaku Sangyou)(JP) - Green Screen - Tosec rom
Mahjong (Japan)
Miracle Piano Teaching System, The (Germany)

AV Soccer (Hacker)
Olympic IQ (Sachen) [U][!]
Poker II (Sachen) [U][!]
Strategist (With Intro) (Sachen) [U][!]
Tasac (Sachen) [U][!] - 1
Ultimate Air Combat (E) (Beta) (M3)
Dr. Mario (USA) (Beta) (Between 1990-02-02 & 1990-04-27, later)
Virus (USA) (Beta) (1990-02-02)
Ninja Jajamaru - Ginga Daisakusen (J) (Beta)
Crystalis (U) (Prototype) - not sure
Playbox BASIC (Prototype V0.0) [!]

Licensed ones:

Star Trek - 25th Anniversary (G)
Dragon Quest II - Akuryou no Kamigami (J-VC)
Dragon Quest III - Soshite Densetsu e... (J-VC) (PRG1)
Gradius II (J) (VC) - Grey Screen
Kage no Densetsu (J) (VC)
Street Gangs (E) (VC)
Captain Skyhawk (1989)(Rare)(PlayChoice-10) - Tosec
Mario's Open Golf (1991)(Nintendo)(PlayChoice-10) - Tosec

**Comment by alyosha-tas** [comment]
From Sonia-7

Jetsons, The - Cogswell's Caper (Japan)
sha1:127B2C71AB249ECC197F7F88CEFC1FDE2EC7F2CE
md5:16EE244AC9BA24651878FA9B835353AD

https://user-images.githubusercontent.com/24638400/134544572-c5097369-c6c7-4435-963e-3c4e6d88e2b2.png

**Comment by alyosha-tas** [comment]
This issue has become a unwieldy, closing in favor of #2999
