### ISSUE TITLE
Nes: Option to detect and use Zapper/accessories automatically when loading rom.

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#875]
Mesen does it, and it's very useful. You load a rom, and then, the zapper pointer is there.

**Comment by hegyak** [comment]
This would need to be a GameDB change, most likely.  Since not all games use the Zapper.

**Comment by zeromus** [comment]
📎 It looks like you're using software, would you like help with that?

**Comment by adelikat** [comment]
I don't like it when emulators do this.

**Comment by alyosha-tas** [comment]
I don't like this one, and won't be implementing it, no point leaving it open forever.
