### ISSUE TITLE
When applying aspect ratio correction, increase height if width is larger than needed

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/BizHawk#956]
Say I have a game that runs at 512x224. The current ARC method will shrink the width carelessly just because it forces width to be 4/3 of the height. That causes loss of info and reduces the quality of the picture.

The solution is, instead of basing 100% on height, check if width is originally more than 4/3 of height. If it is, increase height instead, to be 3/4 of width. (4:3 used here just as an example.)

**Comment by zeromus** [comment]
It sounds like a simpler solution is "never shrink"

**Comment by vadosnaprimer** [comment]
Here's how it should be done:

```C#
private void UpdateAspect(x, y)
{
	VirtualHeight = BufferWidth > BufferHeight * x / y
		? BufferWidth * y / x
		: BufferHeight;
	VirtualWidth = VirtualHeight * x / y;
}
```

I copied some existing implementation (it was surprising that cores do this on their own) and tried it for Arcade Battletoads (512x224), and got shrunk video. The above code is used in our encoding scripts and handles arbitrary aspect ratios perfectly, and it fixed the problem here too.

**Comment by CasualPokePlayer** [comment]
The frontend's aspect ratio correction is just fitting the video buffer with specified buffer width and height into an image with the specified virtual width and height. The frontend generally doesn't care about the aspect ratio per se, as it is assumed the virtual width and height have the correct aspect ratio for the system, and subsquently it does not force 4:3 or some other specific aspect ratio (unless the virtual width/height happen to have such an aspect ratio). If the core is not correctly using VirtualWidth/VirtualHeight, that's a problem for that core specifically, not the frontend itself.
