### ISSUE TITLE
Macro-Ticket: Bugs to fix only at major release

### ISSUE THREAD

**Issue by zeromus** [TASEmulators/BizHawk#971]
Due to backwards compatibility problems

* ~~"Nintento" #970~~ fixed in eb1d87933 + cc4b12b0a
* Lua library function names / normalizing
* Change hooks to combined namespace e.g. "sysbus" read/write/execute to "sysbus.read"/"sysbus.write" etc.

**Comment by YoshiRulz** [comment]
There's a few typos that are visible to users, the ones I've noticed are in errors.
* I'll list them here if I come across any.

**Comment by YoshiRulz** [comment]
https://github.com/TASVideos/BizHawk/blob/c19c7cd5c39087027475a6eff6268c8aea8ce2e5/BizHawk.Emulation.Cores/Consoles/Sony/PSX/Octoshock.cs#L221-L222

**Comment by YoshiRulz** [comment]
CLR target should be bumped to .NET Framework 4.8 - [the last version](https://github.com/TASVideos/BizHawk/pull/1422#issuecomment-490741652), compatible with [Win7+](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies).

see also #1485, where I list the direct benefits to us devs from use of C# 7.x (8.x was minor changes)

**Comment by YoshiRulz** [comment]
Potential bugs in disasm, copied from #1533.

Param 0 duplicated, 1 ignored:
https://github.com/TASVideos/BizHawk/blob/df96db1e2dff44951bc277992b28690db59edbd8/BizHawk.Emulation.Cores/CPUs/W65816/Disassembler.cs#L312

Params 1 and 12 ignored:
https://github.com/TASVideos/BizHawk/blob/b0095927b6e035833bb76a6fec45c3265d39b687/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.ITraceable.cs#L24-L40

**Comment by YoshiRulz** [comment]
Can we please have the prereq installer download ffMPEG? Even GitHub knows shipping a copy is dumb:
![](https://i.imgur.com/3kASCFN.png)

**Comment by zeromus** [comment]
no, because it would have to be “installed” and ffmpeg should not be installed.

**Comment by YoshiRulz** [comment]
I'm ashamed I forgot this until now, but we should be providing *at least* a checksum for each release, preferably signed.

---

On IRC I suggested to write the (most recent) release to config so later versions can warn the user about importing.

**Comment by YoshiRulz** [comment]
Is
> Change hooks to combined namespace e.g. "sysbus" read/write/execute to "sysbus.read"/"sysbus.write" etc.

distinct from #759? This looks like you wanted a `sysbus` library like `mainmemory`.
